### ISSUE TITLE
安卓10 edxposed 插件显示未启用

### ISSUE THREAD

**Issue by chengrui146** [yujincheng08/BiliRoaming#1]
目测运行正常，港澳台啥的都能看，就是插件里显示未启用

![_1701845028_Screenshot_2020-03-28-23-35-21-296_org meowcat edxposed manager_1585409721000_wifi_0](https://user-images.githubusercontent.com/40446636/77827055-733a4900-710b-11ea-89ab-e7d93ccf8d4c.jpg)
![_-1815633211_Screenshot_2020-03-28-23-35-28-495_me iacn biliroaming_1585409728000_wifi_0](https://user-images.githubusercontent.com/40446636/77827056-75040c80-710b-11ea-973c-fead2c483b46.jpg)
![_2040525281_Screenshot_2020-03-28-23-37-25-682_org meowcat edxposed manager_1585409845000_wifi_0](https://user-images.githubusercontent.com/40446636/77827058-759ca300-710b-11ea-81cc-48b001c4f86a.jpg)

**Comment by yujincheng08** [comment]
Confirmed.

原因在于java转kotlin时候把`isModuleActive`函数变成变量+getter了。
