### ISSUE TITLE
[BUG] 视频分享复制链接不正确

### ISSUE THREAD

**Issue by oOtroyOo** [yujincheng08/BiliRoaming#100]
**问题描述**
视频分享其中的复制链接所生成的短链接不正确
**复现步骤**
如何复现
1. 视频分享-复制链接，会生成如下地址
https://b23.tv/k2aTEM
但是在开启插件后为
https://b23.tv/av671737528/
2. 在任意浏览器访问不出来，会弹404消息
**截图**

![Screenshot_20210217-030926](https://user-images.githubusercontent.com/19978148/108110615-79903580-70ce-11eb-99e6-3987af60229e.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：一加
 - 哔哩漫游版本：0365809e69
 - 哔哩哔哩版本和版本号：6.5.0
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
关于这个问题，Edxposed里还真没日志

**Comment by duzhaokun123** [comment]
后面多了个`/`

**Comment by oOtroyOo** [comment]
> 后面多了个`/`

经过我再次测试。如果手动添加一个 p1 即
https://b23.tv/av671737528/p1
就可以访问。
是否问题在于p1这个复制丢了

**Comment by duzhaokun123** [comment]
看看代码
https://github.com/yujincheng08/BiliRoaming/blob/7e8397a33ff44f8cd5bb7cc387ead71b1e5e8943/app/src/main/java/me/iacn/biliroaming/hook/MiniProgramHook.kt#L36
应该是`query`为`""`导致
那么总是把结尾的`/`删掉就行了

**Comment by yujincheng08** [comment]
query 不应该为 `""` 的呀，它是返回 `p1` 什么的

**Comment by duzhaokun123** [comment]
@yujincheng08 估计是哔哩哔哩版本的问题，`6.18.2`没有问题

**Comment by duzhaokun123** [comment]
@yujincheng08 测试`6.5.0`没有问题，看来是随机出现的问题，只能总是去结尾`/`

**Comment by oOtroyOo** [comment]
更新了一下哔哩哔哩。6.18.2
确实可以访问。现在可以正确的添加`p1`，即
https://b23.tv/av671737528/p1
也就是说`query`应该就等于`p1`
这个问题就有点怪了。楼上说版本没问题。

**Comment by duzhaokun123** [comment]
@oOtroyOo 要不你把你的 6.5.0 发出来

**Comment by oOtroyOo** [comment]
https://file.troy-web.top/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9_6.5.0.apk

**Comment by duzhaokun123** [comment]
@oOtroyOo 用你的客户端也没问题，太神奇了，我开始怀疑是一加的问题了

**Comment by duzhaokun123** [comment]
算了 ~~不能重现的bug不是一个好bug~~ 我单方面宣布不再解决此问题

**Comment by yujincheng08** [comment]
我也宣布不解决（

**Comment by oOtroyOo** [comment]
我clone下来跑了一下

生成了以下链接
https://b23.tv/jGftfI
然后header Location转到的地址如下

https://www.bilibili.com/video/BV18U4y1W72R?share_medium=android&share_plat=android&share_source=COPY&share_tag=s_i&timestamp=1613556715&unique_k=jGftfI

其中并没有 p=1这个字段

在同视频P2进行测试结果如下

https://b23.tv/JsvBBP 

https://www.bilibili.com/video/BV18U4y1W72R?p=2&share_medium=android&share_plat=android&share_source=COPY&share_tag=s_i&timestamp=1613556902&unique_k=JsvBBP

此时就有p=2这个字段。

由于代码中会分割筛选
```
it.split("=")
it.size == 2
it[0] == "p"
```
此时没有字段当然筛选出空的。

结论：可以判断一下这个值，来取消多余的 `/`
```
bundle.putString("params_content", "https://b23.tv/av${av}" + if (!query.isNullOrEmpty()) "/${query}" else "");
```

**Comment by yujincheng08** [comment]
PR, 请 😆
