### ISSUE TITLE
[Feature] 希望增加下港澳台番剧繁体转简体字幕功能，谢谢大佬

### ISSUE THREAD

**Issue by TianYv233** [yujincheng08/BiliRoaming#1013]
### 原因

如题，哔哩哔哩自带的简体字幕却是繁体CC字幕，有点困扰
如以下，手机打开就只有繁体字幕:
https://www.bilibili.com/bangumi/play/ep713782

### 功能简述

希望增加下港澳台番剧繁体转简体字幕功能

### 功能逻辑

获取CC字幕，自动翻译成指定语言

### 实现参考

https://greasyfork.org/zh-CN/scripts/431021-bilibili-b%E7%AB%99-%E7%95%AA%E5%89%A7cc%E5%AD%97%E5%B9%95%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2-%E7%BF%BB%E8%AF%91-%E7%B9%81%E4%BD%93%E8%BD%AC%E7%AE%80%E4%BD%93
这个是油猴脚本

**Comment by yujincheng08** [comment]
有没有一种可能，已经有这个功能了
