### ISSUE TITLE
[Server] 修改服务器域名,原为api.lolicon.team

### ISSUE THREAD

**Issue by hanasaki-misaki** [yujincheng08/BiliRoaming#1019]
### 联系方式

https://t.me/lolicon1893

### 域名

bili.lolicon.team

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/miraipip

**Comment by yujincheng08** [comment]
好了。
