### ISSUE TITLE
[Bug] 所选upos时效时无法正常回退到mcdn

### ISSUE THREAD

**Issue by BigBadNeko** [yujincheng08/BiliRoaming#1021]
### 问题描述

如题 进度条卡00:00黑屏

### 复现步骤

如上

### 预期行为

正常播放

### 实际行为

如问题描述

### 截图或录屏

![Uploading Screenshot_20230406-115212.png…]()

### 安卓版本

10

### 哔哩漫游版本

27122a38ba

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.16.0

### 使用的框架和版本

LSPosed 1.8.6 (6712)

### 其他

选择有效upos时正常播放
P.S. upos列表一大半失效 默认upos也寄了 可以更新一下

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11165886/log.txt)

**Comment by zjns** [comment]
B站视频播放只会按顺序请求三个流地址，一个base_url，两个backup_url，所以其实backup_url塞再多也没用，遇到这种情况自己切换upos吧。
