### ISSUE TITLE
[BUG]主站登录状态对于泰区番剧不再通用，仅返回最高480P播放地址

### ISSUE THREAD

**Issue by Merlyx** [yujincheng08/BiliRoaming#103]
**问题描述**
泰区番剧主站登录状态不再通用，仅返回最高480P播放地址

**复现步骤**
如下

**截图**
1

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI
 - 哔哩漫游版本：BiliRoaming_0365809e69-signed.apk
 - 哔哩哔哩版本和版本号：1
 - 使用的框架和版本：edxposed
 - 其他：巨人

**日志**
{
	"code": 0,
	"message": "0",
	"ttl": 1,
	"data": {
		"video_info": {
			"quality": 32,
			"timelength": 1374960,
			"stream_list": [{
				"stream_info": {
					"quality": 112,
					"description": "  1080P+",
					"new_description": "1080P 高码率",
					"display_desc": "1080P",
					"need_vip": true,
					"need_login": true,
					"intact": false,
					"no_rexcode": false
				}
			}, {
				"stream_info": {
					"quality": 80,
					"description": "  1080P",
					"new_description": "1080P  ",
					"display_desc": "1080P",
					"need_vip": true,
					"need_login": true,
					"intact": true,
					"no_rexcode": false
				},
				"dash_video": {
					"base_url": "",
					"backup_url": [],
					"bandwidth": 1947497,
					"codecid": 7,
					"md5": "",
					"size": 0,
					"audio_id": 30216
				}
			}, {
				"stream_info": {
					"quality": 64,
					"description": "  720P",
					"new_description": "720P  ",
					"display_desc": "720P",
					"need_vip": false,
					"need_login": true,
					"intact": true,
					"no_rexcode": false
				},
				"dash_video": {
					"base_url": "",
					"backup_url": [],
					"bandwidth": 1459474,
					"codecid": 7,
					"md5": "",
					"size": 0,
					"audio_id": 30216
				}
			}, {
				"stream_info": {
					"quality": 32,
					"description": "  480P",
					"new_description": "480P  ",
					"display_desc": "480P",
					"need_vip": false,
					"need_login": false,
					"intact": true,
					"no_rexcode": false
				},
				"dash_video": {
					"base_url": "手动隐藏,
					"backup_url": null,
					"bandwidth": 503788,
					"codecid": 7,
					"md5": "",
					"size": 0,
					"audio_id": 30216
				}
			}, {
				"stream_info": {
					"quality": 16,
					"description": "  360P",
					"new_description": "360P  ",
					"display_desc": "360P",
					"need_vip": false,
					"need_login": false,
					"intact": true,
					"no_rexcode": false
				},
				"dash_video": {
					"base_url": "手动隐藏",
					"backup_url": null,
					"bandwidth": 346096,
					"codecid": 7,
					"md5": "",
					"size": 0,
					"audio_id": 30216
				}
			}],
			"dash_audio": [{
				"id": 30216,
				"base_url": "手动隐藏",
				"backup_url": null,
				"bandwidth": 68753,
				"codecid": 0,
				"md5": "",
				"size": 0
			}, {
				"id": 30232,
				"base_url": "手动隐藏",
				"backup_url": null,
				"bandwidth": 134244,
				"codecid": 0,
				"md5": "",
				"size": 0
			}, {
				"id": 30280,
				"base_url": "手动隐藏",
				"backup_url": null,
				"bandwidth": 246321,
				"codecid": 0,
				"md5": "",
				"size": 0
			}]
		}
	}
}

**Comment by yujincheng08** [comment]
我也没办法呀，我总不能给你整个 access_key 吧
