### ISSUE TITLE
屏蔽新版b站弹出的鼓励一下内容

### ISSUE THREAD

**Issue by Haocen2004** [yujincheng08/BiliRoaming#1039]
### 原因

![Screenshot_2023-04-13-21-39-08-199_tv danmaku bili](https://user-images.githubusercontent.com/25221696/231777069-4f30414b-a132-44db-bb40-a4684c3c0c2b.jpg)
如图 “发送评论 有点东西” 部分
没有意义还容易误触（

### 功能简述

提供一个选项关闭它

### 功能逻辑

阻止弹出或者自动点击x

### 实现参考

无

**Comment by yujincheng08** [comment]
已经有了
