### ISSUE TITLE
[Bug] 笔记图片保存在7.25.0失效

### ISSUE THREAD

**Issue by RimuruChan** [yujincheng08/BiliRoaming#1040]
### 问题描述

在b站7.25.0版本下无法正常长按保存笔记图片
其实前两个版本就不行了

### 复现步骤

1. 打开视频
2. 打开评论区
3. 找到一个笔记图片
4. 长按图片
5. 无反应

### 预期行为

正常保存笔记图片

### 实际行为

没有保存笔记图片

### 安卓版本

13

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.25.0

### 使用的框架和版本

LSPosed 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11228403/log.txt)

**Comment by zjns** [comment]
已经修复了，用最新CI版本。

**Comment by Kimaru-bili** [comment]
B站7.30版本下又失效了 其他功能都正常

**Comment by zjns** [comment]
> B站7.30版本下又失效了 其他功能都正常

用最新CI版，看选项说明。

**Comment by Kimaru-bili** [comment]
好的好的 没注意 感谢解答
