### ISSUE TITLE
[BUG] UPOS 服务测速失败以及开启模块无法进入大会员礼包专区

### ISSUE THREAD

**Issue by Alampdow** [yujincheng08/BiliRoaming#105]
**问题描述**
发生了什么情况？有什么现状？
1. 模块的 UPOS 测速无法使用，显示测速失败
2. 开启模块后，app 内打开年度会员游戏礼包页面一片空白，关闭模块后则可以正常显示

**复现步骤**
如何复现
1. 在我的界面打开我的大会员->卡券包->年度专享游戏礼包->去往礼包专区，页面显示一片空白

**截图**
![Screenshot_20210220-091603](https://user-images.githubusercontent.com/13143916/108577520-4fec3e00-735c-11eb-9927-9b4b664dd5eb.jpg)

**环境信息**
 - 安卓版本：Android 11
 - 系统版本：Oxygen OS 11.0.6.8
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号：6.18.2
 - 使用的框架和版本：EdXposed 5.2.2

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6013870/log.txt)

**Comment by yujincheng08** [comment]
1. UPOS 测速需要服务器支持，有些服务器不支持
2. 礼包专区我这里能打开。你的日志显示 `[main] Response Code: ERROR Flags: 0` 但是调用栈没有漫游
