### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mikazukizero** [yujincheng08/BiliRoaming#1051]
### 问题描述

启用模块后，bilibili（包名com.bilibili.app.in）的“记忆弹幕开关”功能失效

### 复现步骤

bug表现为启用模块时，在上一视频关闭弹幕后，点击下一视频并播放时无法记忆弹幕开关状态，停用模块后正常。

### 预期行为

记忆弹幕开关状态

### 实际行为

记忆弹幕开关功能失效

### 安卓版本

13

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.1.6.0

### 使用的框架和版本

LSPosed 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11261373/log.txt)

**Comment by yujincheng08** [comment]
所有功能都没开也会这样？

**Comment by mikazukizero** [comment]
> 所有功能都没开也会这样？

稍后我试一下

**Comment by mikazukizero** [comment]
> 所有功能都没开也会这样？

所有功能不开不会，开启“解锁番剧限制”就会，我现在复现不了功能失效了，但是现在进视频弹幕会在三秒左右关闭而正常是进入立刻关闭，也许是偶然事件吧
