### ISSUE TITLE
[Feature] 为番剧/视频强制指定 h264/h265

### ISSUE THREAD

**Issue by rhjdvsgsgks** [yujincheng08/BiliRoaming#106]
**原因**
1. 在老机型上 h265 解码能力不够，遇到高码率的视频会音画不同步，这时换成 h264 就正常了
2. 番剧码率低，即使 h265 也能流畅播放，但下载时默认 h264 ，占空间

**功能简述**
为番剧/视频强制指定 h264/h265

**功能逻辑**
playurl 返回的结果中同时包含了两种 codec 的链接，根据需求过滤一部分即可

**实现参考**
我在写，番剧和视频的播放部分已经搞好了，下载部分格式有点不一样还在搞

手机炸了，缓更

**Comment by rhjdvsgsgks** [comment]
@yujincheng08 
请教一下这个把 qn 的值给 fnval 是什么意思
https://github.com/yujincheng08/BiliRoaming/blob/7d7c860ff9fd7297212bd4740db1ba7c8d0ea28a/app/src/main/java/me/iacn/biliroaming/hook/BangumiPlayUrlHook.kt#L43
最近翻文档好像说 16 是 `优先返回DASH-H265视频的JSON内容` 所以在想这个 issue 提到的功能能否通过“自定义 fnval ”实现，然后就看到了这一行，所以来问问

**Comment by david082321** [comment]
@rhjdvsgsgks 

https://t.me/biliroaming_chat/316261

https://t.me/biliroaming_chat/316263

**Comment by rhjdvsgsgks** [comment]
> @rhjdvsgsgks
> 
> https://t.me/biliroaming_chat/316261
> 
> https://t.me/biliroaming_chat/316263
> 
> 例如：
> 
>     1. 要 DASH-H265 + HDR + 4K
>        = 16 + 64 + 128
>        = 208
> 
>     2. 要 DASH-H265 + 杜比音频 + 4K
>        = 16 + 256 + 128
>        = 400

这个我是知道的，只不过我在好奇为什么要把 qn 的值给 fnval ，难道两者的定义相同？🤔

**Comment by david082321** [comment]
> 
> 这个我是知道的，只不过我在好奇为什么要把 qn 的值给 fnval ，难道两者的定义相同？🤔

看起来不同，qn 写的是 清晰度
