### ISSUE TITLE
[Feature] 移除新版本开屏广告

### ISSUE THREAD

**Issue by cxw620** [yujincheng08/BiliRoaming#1064]
### 原因

新版本开屏广告拦截有缺如, 例如最近出现这种
![](https://i0.hdslb.com/bfs/sycp/creative_img/202304/0d1883975b130a0f2930a688a0ae32be.webp)

From: https://t.me/biliroaming_chat/1912356

### 功能简述

移除新版本启动页广告

### 功能逻辑

在原有的基础上修复

**Comment by yujincheng08** [comment]
f1d0cb6bc672c838ba35388a594655e9f3e9a86a
