### ISSUE TITLE
[BUG] 自定义主题色没有按钮

### ISSUE THREAD

**Issue by 2370177068** [yujincheng08/BiliRoaming#107]
**问题描述**
发生了什么情况？有什么现状？

本来好好的，我想不用解析服务器下载视频，就在太极里关了哔哩漫游，然后打开发现自定义主题色的按钮没了。

**复现步骤**
如何复现
1. 关闭模块
2. 重新打开b站
3. 发现自定义主题色的按钮没了
过程无需关闭自定义主题色的开关

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2021-02-24-19-30-07-072_哔哩哔哩](https://user-images.githubusercontent.com/51988982/108996013-dac09600-76d8-11eb-9092-d91117a77cac.png)
![涂鸦_Screenshot_2021-02-24-19-29-51-562_哔哩哔哩](https://user-images.githubusercontent.com/51988982/108996052-e449fe00-76d8-11eb-9754-e67a0b40465d.png)

**环境信息**
 - 安卓版本：10
 - 系统版本：smartisan OS 8.1.2.2
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号：正式版 6.18.2
 - 使用的框架和版本：太极 曳影·7.0.0.02111627
 - 其他：无

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

日志可能没啥用，我当时没开输出日志
手机版没找到上传文件按钮。

`--------- beginning of main
02-24 19:37:28.383 19749 19749 D BiliRoaming: BiliBili process launched ...
02-24 19:37:28.383 19749 19749 D BiliRoaming: BiliRoaming version: 1.4.2(42) from /data/app/me.iacn.biliroaming-DswhdetNfuGA0lwfXRO9Bw==/base.apk
02-24 19:37:28.383 19749 19749 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.384 19749 19749 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.384 19749 19749 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.384 19749 19749 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.384 19749 19749 D BiliRoaming: Bilibili version: tv.danmaku.bili@6.18.2(6182200) (32bit)
02-24 19:37:28.384 19749 19749 D BiliRoaming: SDK: 10(29); Phone: SMARTISAN DT2002C
02-24 19:37:28.384 19749 19749 D BiliRoaming: Config: {th_server=biligo.org, show_hint=false, hk_server=service-fi0gz11m-1252917345.hk.apigw.tencentcs.com, add_4k=false, hidden=false, teenagers_mode_dialog=true, follow_dark=false, enable_av=true, main_func=true, custom_theme=true, upos_host=$1, allow_download=true, fix_download=true, show_info=true, add_live=false, save_log=true, comment_floor=true, cn_server=bilibili.com, tw_server=mysr.ellpew.ml}
02-24 19:37:28.389 19749 19749 D BiliRoaming: Reading hook info: /data/user/0/tv.danmaku.bili/cache/hookinfo.dat
02-24 19:37:28.390 19749 19749 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.390 19749 19749 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.411 19749 19749 D BiliRoaming: {field_color_array=l, class_download_thread_listener=tv.danmaku.bili.ui.offline.o, method_fastjson_parse=parseObject, method_like=e, class_share_wrapper=com.bilibili.lib.sharewrapper.h, method_garb=c, class_notification_builder=androidx.core.app.i$d, class_gson_converter=null, method_open_drawer=H, class_drawer_layout_params=androidx.drawerlayout.widget.DrawerLayout$e, class_abs_music_service=tv.danmaku.bili.ui.player.notification.AbsMusicService, field_abs_music_service=a, class_theme_name=tv.danmaku.bili.ui.garb.d, field_gson=null, method_skin_list=w9, class_theme_list_click=tv.danmaku.bili.ui.theme.ThemeStoreActivity$h, field_req=a, field_video_detail=v, method_check_blue=null, class_report_download_thread=tv.danmaku.bili.ui.offline.api.c, class_check_blue=null, class_bangumi_params_map=com.bilibili.bangumi.data.page.detail.a$b, field_theme_name=a, class_garb_helper=com.bilibili.lib.ui.garb.a, class_column_helper=com.bilibili.column.helper.l, field_column_color_array=n, method_is_drawer_open=A, method_params_to_map=a, class_music_notification_helper=tv.danmaku.bili.ui.player.notification.a, method_share_wrapper=f, field_color_id=a, class_retrofit_response=retrofit2.l, class_theme_processor=tv.danmaku.bili.ui.theme.l, class_section=tv.danmaku.bili.ui.video.section.b, class_setting_router=tv.danmaku.bili.ui.main2.mine.e, methods_set_notification=v, method_media_session_token=o, class_drawer=null, class_theme_id_helper=tv.danmaku.bili.ui.theme.k, class_fastjson=com.alibaba.fastjson.JSON, field_download_thread=s, method_close_drawer=e, methods_theme_reset=b;c, method_add_setting=qs, method_report_download_thread=c, class_theme_helper=tv.danmaku.bili.ui.theme.i, method_sign_query=g}
02-24 19:37:28.411 19749 19749 D BiliRoaming: Check hook info completed: needUpdate = false
02-24 19:37:28.417 19749 19749 D BiliRoaming: startHook: BangumiSeason
02-24 19:37:28.421 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.421 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.422 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.422 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.423 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.423 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.425 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.425 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.426 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.426 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.427 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.427 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.430 19749 19749 D BiliRoaming: startHook: BangumiPlayUrl
02-24 19:37:28.431 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.431 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.433 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.433 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.434 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.434 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.435 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.435 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.437 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.437 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.439 19749 19749 D BiliRoaming: startHook: CustomTheme
02-24 19:37:28.466 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.466 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.468 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.468 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.470 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.470 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.471 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.471 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.471 19749 19749 D BiliRoaming: startHook: TeenagersMode
02-24 19:37:28.473 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.473 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.473 19749 19749 D BiliRoaming: startHook: Comment
02-24 19:37:28.474 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.474 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.475 19749 19749 D BiliRoaming: startHook: Json
02-24 19:37:28.480 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.480 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.482 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.482 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.483 19749 19749 D BiliRoaming: startHook: Setting
02-24 19:37:28.484 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.484 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.486 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.486 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.490 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.490 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.492 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.492 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.493 19749 19749 D BiliRoaming: startHook: Env
02-24 19:37:28.494 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.494 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.496 19749 19749 W tv.danmaku.bil: Unsupported class loader
02-24 19:37:28.496 19749 19749 W tv.danmaku.bil: Could not establish class loader context
02-24 19:37:28.501 19749 19749 I Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
02-24 19:37:28.501 19749 19749 D Tinker.DefaultAppLike: onCreate
02-24 19:37:28.501 19749 19749 I BaseBiliApplication: tv.danmaku.bili is main process
02-24 19:37:28.504 19749 19749 I moss.traceservice.app: Disable trace service for blog in tv.danmaku.bili.
02-24 19:37:28.506 19749 19790 D BLOG-EVENT-Network: network changed: 3=>2
02-24 19:37:28.510 19749 19749 D NetworkSecurityConfig: Using Network Security Config from resource a2 debugBuild: false
02-24 19:37:28.528 19749 19749 I cr_BiliCrLibraryLoader: BiliCr version: 81.0.4044.156, arch: armv8l
02-24 19:37:28.529 19749 19749 W chromium: [0224/193728.529072:WARNING:httpdns_adapter.cc(266)] HttpDns init
02-24 19:37:28.532 19749 19749 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.532 19749 19749 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.533 19749 19834 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.533 19749 19834 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.533 19749 19834 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.533 19749 19834 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.534 19749 19834 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.534 19749 19834 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.537 19749 19838 I chromium: [0224/193728.537365:INFO:httpdns.cc(135)] OnEffectiveConnectionTypeChanged called by httpdns context networks 5
02-24 19:37:28.539 19749 19749 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.539 19749 19749 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.650 19749 19790 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:37:28.650 19749 19790 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
02-24 19:37:28.651 19749 19790 E EXposed : XposedHookGetPackageInfo: 0
02-24 19:`

**Comment by duzhaokun123** [comment]
bilibili 缓存问题，杀了再开试试
按钮还在，只是没有图标

**Comment by 2370177068** [comment]
不，我朋友也出现了这个图标，原来的小调色板图标没了。新的这个点开会像点网页一样的感觉，点了之后突然闪个白屏，然后才是进入这个新的(个性化)界面。我感觉是热更新，应该过几天都有这个图标。
