### ISSUE TITLE
[Feature] 希望添加版权音乐的小窗播放/后台播放

### ISSUE THREAD

**Issue by anonymouscnuser** [yujincheng08/BiliRoaming#1070]
### 原因

bilibili听歌，不需要会员。

### 功能简述

如图
1. 解锁下面两个灰色的按钮
2. 按/回退至HOME或返回操作时，小窗/后台继续播放，就像其他普通的视频一样
![8aa0cfd503d9bb28e13a7744f39bbae](https://user-images.githubusercontent.com/68681806/235519704-de41b326-0dbe-4a06-835c-74cdcdccc717.jpg)

图例链接： https://www.bilibili.com/video/BV17h411u7sb  或是任何音乐相关的官方投稿

### 功能逻辑

如功能简述

### 实现参考

如功能简述

**Comment by zjns** [comment]
e8fc6ba ，已经有了，解除播放限制。
