### ISSUE TITLE
[Server] Add:api.mahiro-kawaii.me<麻烦下把这个与 cherry.icu.cnmobile.link 放在一起，然后把这俩服务器在列表的位置往上移下，谢谢了>

### ISSUE THREAD

**Issue by lhf277** [yujincheng08/BiliRoaming#1071]
### 联系方式

https://t.me/mahiro_kawaii

### 域名

api.mahiro-kawaii.me

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [x] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/LiangBurs

**Comment by yujincheng08** [comment]
好了。
