### ISSUE TITLE
[BUG] 自定义配色失效

### ISSUE THREAD

**Issue by duzhaokun123** [yujincheng08/BiliRoaming#108]
**问题描述**
自定义配色失效
可能与设置界面更新有关

**复现步骤**
如何复现
1. 点我的页面右上角的衣服 (已经不是调色板了)

**截图**
懒得截

**环境信息**
 - 安卓版本：Android 11
 - 系统版本：RQ1A.210205.004
PixelExperience_polaris-11.0-20210207-0205-BETA-OFFICIAL
 - 哔哩漫游版本：1.4.2 (4b85dce 自己 debug 构建)
 - 哔哩哔哩版本和版本号：6.18.2
 - 使用的框架和版本：edxp v4.6.2 (46200)

**日志**
https://del.dog/8k2k0wkKd.txt

**Comment by yujincheng08** [comment]
热更新了 😞

**Comment by yujincheng08** [comment]
Duplicate of #107

**Comment by duzhaokun123** [comment]
所以不解决了?

**Comment by yujincheng08** [comment]
只是 mark 重复而已啊。。。

现在那东西是个 webview。实际上我有 webview 的注入（xhook.js），所以搞一下也可以。~你来 PR 吧。~

**Comment by duzhaokun123** [comment]
> 只是 mark 重复而已啊。。。

那你关什么 issus 啊，
而且我说的是自定义配色失效，#107 说的是按钮变了，好像没什么关系

> 现在那东西是个 webview。实际上我有 webview 的注入（xhook.js），所以搞一下也可以。~你来 PR 吧。~

要补作业

**Comment by yujincheng08** [comment]
重复为什么不关？

**Comment by duzhaokun123** [comment]
> 重复为什么不关？

原来我的逻辑有问题
```
问题重复(即使判断错误) -> 关 issus
```
没有大问题
可我却认为问题重复不用关
小丑竟是我自己
