### ISSUE TITLE
[Server] 添加域名: melusine.moe (麻烦添加到melusinesuki.site的上边，谢谢:D)

### ISSUE THREAD

**Issue by kotoritan** [yujincheng08/BiliRoaming#1085]
### 联系方式

t.me/Reze_bomb

### 域名

melusine.moe

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/ktrtan

**Comment by yujincheng08** [comment]
Done
