### ISSUE TITLE
[Server] 新增 bili.rikko.moe 同时删除 bili.ayaka.ink

### ISSUE THREAD

**Issue by KanaMiao** [yujincheng08/BiliRoaming#1087]
### 联系方式

t.me/KanaMiao

### 域名

bili.rikko.moe

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/KanaMiao

**Comment by yujincheng08** [comment]
Done
