### ISSUE TITLE
求个热门标签页的视频筛选

### ISSUE THREAD

**Issue by RizukiJI** [yujincheng08/BiliRoaming#1089]
### 原因

首先我是想知道有什么大伙都在看的视频的
但是很多都是时长很短没有内容没有营养的垃圾视频
所以想看看能不能做出这个功能，按时长，播放量，up主等相关信息筛选掉我不想看的内容

### 功能简述

按时长，播放量，up主等相关信息，筛选掉“热门”标签页的内容

### 功能逻辑

设置一个“净化推荐内容”，选择标题关键词，up主，分区，播放量，视频时长那些相关信息，筛选掉不想看的内容

### 实现参考

“首页推送过滤器”里头已经很完备了，只是想让推荐页也多一个这东西，对于又想看热点又不想看垃圾视频的我真的很重要求求了

**Comment by yujincheng08** [comment]
Duplicate of #354
