### ISSUE TITLE
[Feature] 移除视频浮窗后会把视频章节跳转一并屏蔽

### ISSUE THREAD

**Issue by XIlIlIln** [yujincheng08/BiliRoaming#1093]
### 原因

开启此项“移除视频浮窗”后，会把部分视频存在的 视频章节进度跳转 一并屏蔽

### 功能简述

“移除视频浮窗”屏蔽范围调整

### 功能逻辑

可否把此项从此功能开关中摘出

**Comment by zjns** [comment]
@cxw620
