### ISSUE TITLE
[Bug] 我的页面自定义无法移除“发布”按钮

### ISSUE THREAD

**Issue by eve2ptp** [yujincheng08/BiliRoaming#1097]
### 问题描述

我的页面自定义无法移除“发布”按钮
截图如下：
![Screenshot_20230515-003603](https://github.com/yujincheng08/BiliRoaming/assets/42791572/0cf24741-f021-466a-bcb2-6448cbc06b23)

![Screenshot_20230515-003611__01](https://github.com/yujincheng08/BiliRoaming/assets/42791572/1ece7252-809f-4f15-8715-ff3c7549e5c9)

### 复现步骤

自定义我的页面
不勾选发布按钮

### 预期行为

正常显示其余项

### 实际行为

无显示

### 安卓版本

9

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.20

### 使用的框架和版本

无

### 日志

[no log.txt](https://github.com/yujincheng08/BiliRoaming/files/11472459/no.log.txt)

**Comment by yujincheng08** [comment]
不知所云

**Comment by eve2ptp** [comment]
> 不知所云

哪里描述不够清楚？

**Comment by yujincheng08** [comment]
你截图的我的页面哪里有发布按钮？

**Comment by eve2ptp** [comment]
> 你截图的我的页面哪里有发布按钮？
如果没有勾选发布按钮，整个创作中心及其子项就不显示了
![Screenshot_20230515-005921__01](https://github.com/yujincheng08/BiliRoaming/assets/42791572/cf36535f-627c-4a1d-aac4-d206b9650f96)

**Comment by JasonKhew96** [comment]
把 创作中心 去掉就可以了，但里面的几个项目也会跟着没了

**Comment by eve2ptp** [comment]
> 把 创作中心 去掉就可以了，但里面的几个项目也会跟着没了

https://github.com/yujincheng08/BiliRoaming/issues/174
这算是以前修了又重新复现的 bug 么

**Comment by david082321** [comment]
> > 把 创作中心 去掉就可以了，但里面的几个项目也会跟着没了
> 
> #174 这算是以前修了又重新复现的 bug 么

1. 应该是要重启两次生效。
2. 删除按钮会同时删除整个区块，是我代码写不好（只能看有没有大佬来改

**Comment by eve2ptp** [comment]
那 reopen 好一点吧，复现方式已经给出了直接 close issue 是不是不太妥

**Comment by yujincheng08** [comment]
这都什么跟什么。
标题说无法去除，然后截图一看能去除的。然后你说你的问题是多去了些东西，与你描述严重不符合。描述不对、没有日志的 issue 就不值得开着。
而且 #174 说的是底栏的+号，你这个是我的页面的发布按钮，都不是同一个东西，还疯狂那里引用回复。

**Comment by eve2ptp** [comment]
> 这都什么跟什么。 标题说无法去除，然后截图一看能去除的。然后你说你的问题是多去了些东西，与你描述严重不符合。描述不对、没有日志的 issue 就不值得开着。 而且 #174 说的是底栏的+号，你这个是我的页面的发布按钮，都不是同一个东西，还疯狂在那里引用回复。

https://github.com/yujincheng08/BiliRoaming/issues/1097#issuecomment-1547249961 已经明确描述了我该说明的问题了：“删除按钮会同时删除整个区块”，这个函数的正常逻辑应该是能去掉发布按钮的同时切保留整个分区及其子项。如果你认为这不是 bug 可以直说，那么这个 issue 到此为止。
还有，我最开始提 issue 是先搜过有没有类似问题才在之前的 issue 回复的。如果你觉得我这个描述不清晰，那我认为此前那个也一样。而你直接就回一句：“一年前的 issue 还回复，真牛逼”。
如果一个正常用户为了反馈一个问题专门跑到这里提 issue，且提供稳定复现方式能得到的就是这种答复，我只能说：“真牛逼”。

**Comment by yujincheng08** [comment]
乐，#174 都也不是描述清晰的 issue，也是直接关的。只是这个 issue 是 bug 修复之后提的，我好心回复一个 ref 而已。
而且回复一年前已经关掉的 issue 有什么用？难道给你重开老 issue？找不到开着的重复 issue 就开新的不就行？一句笼统的回复谁知道是什么问题？
另外，你都没仔细看 issue 就说同样的问题。重新开 issue 也没有描述好问题，截图也是乱来，日志也是直接 no log.txt，你这叫认真提 issue？提供复现方式又如何？我要你提供整个 issue template 都需要的东西。
这都做不到不被直接关还这么多人回复已经算仁慈了。免费开源项目不欠你的，没义务陪你当大爷。

**Comment by eve2ptp** [comment]
差不多得了，遇到bug，也知道bug是怎么回事还要扯有的没的。
针对非开发者能提供详细复现情况都算万幸了，在这点上的 issue template is shit
早点这么说我自己修完还不用浪费大家时间，再见

**Comment by yujincheng08** [comment]
乐，因为自己不遵守 issue template 就说 issue template is shit。
走好不送。
