### ISSUE TITLE
[Bug] 普通视频提示无法获取剧集信息

### ISSUE THREAD

**Issue by Steve-337** [yujincheng08/BiliRoaming#1098]
### 问题描述

平板上使用普通版哔哩哔哩，打开普通视频，在封面没加载出来的时候立马点击播放，漫游会提示“请求解析服务器发生错误：解析服务器错误：无法获取剧集信息”。此时视频会一直显示正在缓冲，退出重新进入等封面加载出来后即可正常播放。手机上相同版本B站，漫游和漫游配置则无此问题

### 复现步骤

1.平板上使用普通版B站打开任意普通视频
2.在封面未出现前点击播放视频
3.漫游提示“请求解析服务器发生错误：解析服务器错误：无法获取剧集信息”，此时视频会一直显示正在缓冲

### 预期行为

视频正常播放

### 实际行为

漫游提示“请求解析服务器发生错误：解析服务器错误：无法获取剧集信息”，视频一直显示正在缓冲无法播放

### 截图或录屏

![-6273704831902398516_119](https://github.com/yujincheng08/BiliRoaming/assets/48684035/bf927972-1e29-41ca-a178-eedb8def513e)

### 安卓版本

13

### 哔哩漫游版本

730a7edae3(1196)

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.29.0

### 使用的框架和版本

LSPosed 1.8.6(6712)

### 其他

任意一个普通视频，magisk26.1（26100）

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11478950/log.txt)

**Comment by Steve-337** [comment]
目前B站在平板上的播放ui与手机上不同（平板上竖屏状态下进度条是在暂停按钮下方且滑动快进有缩略图）不知是否与此有关

**Comment by zjns** [comment]
> 目前B站在平板上的播放ui与手机上不同（平板上竖屏状态下进度条是在暂停按钮下方且滑动快进有缩略图）不知是否与此有关

那应该是新版播放器，估计是点快了请求参数不对服务器返回了null，然后漫游误判这种情况应该处理，可以加个判断，那就是如果season_id和ep_id都为空也不处理。 @yujincheng08

**Comment by yujincheng08** [comment]
现在普通视频跟番剧走的是同一个接口了？

**Comment by zjns** [comment]
> 现在普通视频跟番剧走的是同一个接口了？

playViewUnite 是这样的。

**Comment by yujincheng08** [comment]
理论上老接口不会有这个问题。新接口有没有办法判断是不是请求番剧？比如说，存在 aid 之类的？

**Comment by zjns** [comment]
> 理论上老接口不会有这个问题。新接口有没有办法判断是不是请求番剧？比如说，存在 aid 之类的？

不确定他这种情况请求参数带没带aid，日志看不出来，看样子是啥参数都没有，不然服务器不会返回null，所以还是应该判断season_id和ep_id，本来两者必须至少要有一个代理服务器才能拿到season。

**Comment by zjns** [comment]
我明天PR吧，这一块我熟点。

**Comment by zjns** [comment]
> 那理论上老接口不会有这个问题。新接口有没有办法判断是不是请求番剧？比如说，存在 aid 之类的？

正常请求下可以判断，请求参数可以判断，返回supplement字段type_url也可以判断。但他这种明显不是正常情况，应该只有我说的办法了。

**Comment by zjns** [comment]
[app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/11483034/app-debug.apk.zip)
@Steve-337 装这个包复现一下试试，能获取到更详细的日志，然后分享到这。

**Comment by Steve-337** [comment]
> [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/11483034/app-debug.apk.zip) @Steve-337 装这个包复现一下试试，能获取到更详细的日志，然后分享到这。

[log.zip](https://github.com/yujincheng08/BiliRoaming/files/11483343/log.zip)

**Comment by zjns** [comment]
@Steve-337 log拿到了，可以把log删了，有敏感信息。

**Comment by Steve-337** [comment]
> @Steve-337 log拿到了，可以把log删了，有敏感信息。

删除那条评论就行了吧

**Comment by zjns** [comment]
[app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/11483597/app-debug.apk.zip)
@Steve-337 再试下这个包，看有没有问题。

**Comment by Steve-337** [comment]
> [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/11483597/app-debug.apk.zip)
> @Steve-337 再试下这个包，看有没有问题。

漫游没有提示了，但视频直接显示加载失败![Screenshot_2023-05-16-11-24-08-780_tv.danmaku.bili.jpg](https://github.com/yujincheng08/BiliRoaming/assets/48684035/182d9e52-3a4e-4c6b-afbc-21d51e49cabc)

**Comment by yujincheng08** [comment]
你不启用漫游时候，在封面没加载出来的时候立马点击播放，它能放出来吗？

**Comment by Steve-337** [comment]
> 你不启用漫游时候，在封面没加载出来的时候立马点击播放，它能放出来吗？

关了漫游后一切正常

**Comment by Steve-337** [comment]
> 你不启用漫游时候，在封面没加载出来的时候立马点击播放，它能放出来吗？

等一下，关了漫游后试了好几次，刚刚又触发这个问题了，直接显示加载失败，我看看是不是我其他模块影响

**Comment by zjns** [comment]
> > 你不启用漫游时候，在封面没加载出来的时候立马点击播放，它能放出来吗？
> 
> 等一下，关了漫游后试了好几次，刚刚又触发这个问题了，直接显示加载失败，我把所有模块关了看看是不是我其他模块影响

应该就是阿B的问题，没考虑到这种情况，建议给官方提BUG，但不要提及漫游。

**Comment by yujincheng08** [comment]
> 应该就是阿B的问题

同感

**Comment by Steve-337** [comment]
> 你不启用漫游时候，在封面没加载出来的时候立马点击播放，它能放出来吗？

已经把面具内所有模块关闭并重启，连续刷一些视频后（点开一个视频然后点下方推荐视频）必触发加载失败
