### ISSUE TITLE
[Bug] 自定义访问密钥后 无法完整解锁影视区和纪录片区的vip内容

### ISSUE THREAD

**Issue by paulzzh** [yujincheng08/BiliRoaming#1099]
### 问题描述

登录帐号没有会员
替换的key有会员
尝试播放任意需会员的纪录片或电影 只能观看6分钟 之后强制显示播放结束界面 但音频仍在正常播放
并且解除投屏限制失效 投屏按钮变灰按下提示需要会员 但是解除下载限制正常 能正常下载全片
番剧不受影响

### 复现步骤

自定义cn访问密钥
播放流浪2
到6分钟时画面被掐断 声音仍然在

### 预期行为

正常完整播放电影和纪录片 正常解锁投屏

### 实际行为

无法完整播放 无法投屏

### 截图或录屏

![77BEFE10A72B0B6CF7B4F3D9BFFD3800](https://github.com/yujincheng08/BiliRoaming/assets/28055560/f8c238c5-bbd2-4c8a-ac03-cf971dcfb968)

### 安卓版本

13

### 哔哩漫游版本

CI 730a7ed

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.18.0

### 使用的框架和版本

LSPosed 1.8.6

### 其他

本人通过抓包可以确定解析服务器返回了正确的timelength视频长度和视频url
主动下载可以获得完整长度的视频

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11481326/log.txt)

**Comment by zjns** [comment]
自定义访问密钥不针对无需解锁区域的剧集，只针对需要解锁从解析服务器获取的剧集。

**Comment by zjns** [comment]
自定义cn密钥后，会将会员状态hook强制设置为有效，所以才会有这奇怪的表现。 @vvb2060

**Comment by yujincheng08** [comment]
该功能只用于调试，不用于解锁 VIP。
