### ISSUE TITLE
[Feature] 做一个港澳台搜索

### ISSUE THREAD

**Issue by cmmdwl** [yujincheng08/BiliRoaming#110]
**原因**
为什么想要这个功能
官方搜索屏蔽了港澳台
**功能简述**
想要个怎样的功能
独立搜索下港澳台被隐藏的番剧
**功能逻辑**
如何互交、如何使用等
照泰区一样
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
泰区我记得可以搜出来港澳台的吧

**Comment by cmmdwl** [comment]
泰区现在搜索的只剩下泰区了

**Comment by cmmdwl** [comment]
![Screenshot_2021-02-26-22-57-53-138_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/21263352/109316011-1fd5fb00-7886-11eb-9c90-5f87cd0e18f5.jpg)![Screenshot_2021-02-26-22-57-57-937_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/21263352/109316018-219fbe80-7886-11eb-928d-89af85984f5f.jpg)
如图所示 只剩下泰区

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/109375173-9100c700-78f5-11eb-9ec3-b98b132f8229.png)

这一季港澳台新番都能搜到了
故意隐藏的番剧是搜不出来的，建议直接关注 `番剧出差`

**Comment by yujincheng08** [comment]
~好！那不加了~

**Comment by AustraliaLetter** [comment]
请问泰区搜索哪个版本的客户端支持？我的搜索页没有这一标签项

**Comment by david082321** [comment]
> 请问泰区搜索哪个版本的客户端支持？我的搜索页没有这一标签项

连点7次版本号
