### ISSUE TITLE
[Feature] 视频左右两侧双击快进快退5秒

### ISSUE THREAD

**Issue by SkeStars** [yujincheng08/BiliRoaming#1103]
### 原因

方便使用

### 功能简述

在视频全屏界面，右侧四分之一区域双击快进5秒，左侧双击快退5秒

### 功能逻辑

左右两侧的双击手势功能由暂停改为快进快退

### 实现参考

youtube reex 希望大佬能实现，太难就算了

**Comment by yujincheng08** [comment]
太难，并且影响正常逻辑。
