### ISSUE TITLE
[Bug] 无法移除互动弹窗，三连和投票等

### ISSUE THREAD

**Issue by lscsczl** [yujincheng08/BiliRoaming#1104]
### 问题描述

无法移除互动弹窗，三连和投票等，版本1.6.8-1.6.10都无法使用改功能

### 复现步骤

打开带有三连关注弹窗的视频例如：BV1Ts4y1M7y2，BV13T411h7VS，就会显示看见弹窗

### 预期行为

视频全程看不见任何三连弹窗或投票弹窗

### 实际行为

三连和投票弹窗正常显示

### 安卓版本

12

### 哔哩漫游版本

1.6.8、1.6.9、1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.10.0、7.14.1、7.18.0

### 使用的框架和版本

内置模块LSPatch

### 其他

BV1Ts4y1M7y2，BV13T411h7VS

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11484230/log.txt)

**Comment by yujincheng08** [comment]
#995
