### ISSUE TITLE
[Feature]能不能加入泰国版bilibili支持

### ISSUE THREAD

**Issue by prprinu** [yujincheng08/BiliRoaming#111]
**原因**
泰国版bilibili优势：
1. 拥有大陆版所有版权番及字幕
2. 拥有大陆版没有的或下架的版权番，包含许多爽翻肉番
3. 拥有的大陆版权番还是无剪辑的版本
4. 和大陆版的主程序应该是大体一致的，打开泰国版能看到bili漫游激活提示，但是没有设置选项

**功能简述**
如题，针对泰国版优化一下，应该不难

**功能逻辑**
不太清楚

**截图**
![Screenshot_20210228-191942](https://user-images.githubusercontent.com/72260150/109430693-93991480-79fa-11eb-9843-ef43da805bf2.png)
![Screenshot_2021-02-28-19-19-55-185_com bstar intl](https://user-images.githubusercontent.com/72260150/109430701-985dc880-79fa-11eb-84f2-3388fc15961b.jpg)

**实现参考**
目前我觉得最大的原因应该是语言和UI的差异，因为泰国版无中文支持，加之设置菜单与大陆版也不同，如图报错显示name=null，其他的应该不需要做太大改动。

**Comment by yujincheng08** [comment]
改动可大了，不会兼容
