### ISSUE TITLE
[Bug] 弹幕投票视频屏蔽功能失效

### ISSUE THREAD

**Issue by coburnsith** [yujincheng08/BiliRoaming#1111]
### 问题描述

弹幕投票视频屏蔽功能失效

### 复现步骤

打开有弹幕投票的视频

### 预期行为

不会出现投票投票选择框

### 实际行为

出现了投票投票选择框

### 截图或录屏

![1 `0~JT_X}DW ROX}`JG0DV](https://github.com/yujincheng08/BiliRoaming/assets/30407517/46243d4b-d5b2-475b-ae7e-de74265713b9)
![4$496)BBE1RU3AGZ_ {0D9Y](https://github.com/yujincheng08/BiliRoaming/assets/30407517/8afa853e-c9b1-4207-bba4-ad91a0aab27d)
![C@Y79F`D}0 $K D4VU`((FR](https://github.com/yujincheng08/BiliRoaming/assets/30407517/141b5d0f-242c-4e35-9e19-380dd2b9c217)

### 安卓版本

11

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

[LSPatch] [1.6.10] [7.18.0] 哔哩哔哩.apk

### 使用的框架和版本

[LSPatch] [1.6.10] [7.18.0] 哔哩哔哩.apk

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11514094/log.txt)

**Comment by yujincheng08** [comment]
#1100
