### ISSUE TITLE
[Bug] 强制使用旧版播放器功能无效

### ISSUE THREAD

**Issue by Raiden-1** [yujincheng08/BiliRoaming#1117]
### 问题描述

打开强制使用旧版播放器，重启应用好几次了，还是新版播放器

### 复现步骤

打开强制使用旧版播放器，确定并重启客户端

### 预期行为

旧版播放器 (半屏时进度条在框内）

### 实际行为

仍为新版播放器

### 截图或录屏

![Screenshot_2023-05-21-10-31-41-07_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/75219287/af7b1b29-fd08-43cf-8001-a4595fe87788)
![Screenshot_2023-05-21-10-32-02-80_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/75219287/167c29d2-f9aa-4e15-8c4e-2666fa8add3c)

### 安卓版本

13

### 哔哩漫游版本

1.6.11.r1324

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.30.0

### 使用的框架和版本

无lsp

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11523627/log.txt)

**Comment by zjns** [comment]
issue 提错地方了，官方漫游没有这选项的。
