### ISSUE TITLE
[Feature] 希望增加屏蔽评论功能

### ISSUE THREAD

**Issue by 2554814993** [yujincheng08/BiliRoaming#1118]
### 原因

爱看评论，看着看着很多时间就没了

### 功能简述

屏蔽评论，或者不添加评论按钮

### 功能逻辑

开启了屏蔽评论功能，视频下面就不出现评论按钮

### 实现参考

类似自定义底栏功能

**Comment by bilibili2233a** [comment]
上帝模式xposed模块 把评论区按钮删了
