### ISSUE TITLE
[Bug] 广告屏蔽不生效

### ISSUE THREAD

**Issue by huoyan1231** [yujincheng08/BiliRoaming#1119]
### 问题描述

开启屏蔽up主推荐广告后广告仍然存在

### 复现步骤

打开屏蔽up主广告
打开任意视频

### 预期行为

up主推荐广告不应显示

### 实际行为

广告仍然显示

### 截图或录屏

![Screenshot_2023-05-22-01-21-55-347_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/53113734/c1564903-3c13-4588-8ec8-e1b6c03a239f)
![Screenshot_2023-05-22-01-22-02-703_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/53113734/22ed821d-5e59-4013-abdd-669ed810cf17)

### 安卓版本

13

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.11.0

### 使用的框架和版本

1.8.9

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11525151/log.txt)

**Comment by yujincheng08** [comment]
那个不是 up 主推荐广告

**Comment by huoyan1231** [comment]
> 那个不是 up 主推荐广告

az，那这个广告有没有制作对应功能的安排
