### ISSUE TITLE
[BUG] 部分泰国番剧无法解除限制

### ISSUE THREAD

**Issue by david082321** [yujincheng08/BiliRoaming#112]
**问题描述**
发生了什么情况？有什么现状？
部分泰国番剧 (如 School days)，打开后仍然无法加载。

**复现步骤**
如何复现
1. 设置泰国解析服务器
2. 在泰区搜索 school
3. 点击 "School days" 这个番

**截图**
* 搜索的截图 [https://t.me/biliroaming_chat/207988](https://t.me/biliroaming_chat/207988)
* 点开的截图
![Screenshot_20210303-024031](https://user-images.githubusercontent.com/7046617/109698096-f7256c80-7bc9-11eb-8031-94c909ec6777.jpg)

**环境信息**
 - 安卓版本：9
 - 系统版本：Samsung OneUI 1.1
 - 哔哩漫游版本：3d34c0d147
 - 哔哩哔哩版本和版本号：原版6.19.0
 - 使用的框架和版本：LSPosed 1.1.0 (5368)
 - 其他：番剧：School days

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6071019/log.txt)

**其他**
需要请求新的api，而且必须要泰国解析服务器提供支持(因为需要代理ip)

详细内容请看群聊
* [https://t.me/biliroaming_chat/208061](https://t.me/biliroaming_chat/208061)
* [https://t.me/biliroaming_chat/208048](https://t.me/biliroaming_chat/208048)

**Comment by yujincheng08** [comment]
部分番已经下架了，你当然看不了。

**Comment by david082321** [comment]
但是泰国app仍然可以看

**Comment by david082321** [comment]
> 部分番已经下架了，你当然看不了。

但是泰国app仍然可以看
[https://t.me/biliroaming_chat/208058](https://t.me/biliroaming_chat/208058)

**Comment by yujincheng08** [comment]
但是你日志里面没有请求，你重新抓个日志把，另外把 just trust me 关了

**Comment by david082321** [comment]
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6071313/log.txt)
@yujincheng08

**Comment by yujincheng08** [comment]
emm，知道问题了， `https://bangumi.bilibili.com/view/web_api/season` 都不能用了，这样只能依赖代理服务器获取番剧信息了

**Comment by david082321** [comment]
> emm，知道问题了， `https://bangumi.bilibili.com/view/web_api/season` 都不能用了，这样只能依赖代理服务器获取番剧信息了

或者可以考虑原本的仍然使用，只有都没有结果的时候，才从代理服务器获取？
这样就算代理服务器没有代理新的api `api.global.bilibili.com/intl/gateway/v2/ogv/view/app/season`，原本的一样能用。

**Comment by yujincheng08** [comment]
是这么个打算。所以等一个有缘人 PR :)

**Comment by david082321** [comment]
部分番可以加载简介，但是集数无法加载
https://t.me/biliroaming_chat/209508

ss35908
https://bangumi.bilibili.com/view/web_api/season?season_id=35908

**Comment by david082321** [comment]
| ss_id | title |
| -- | -- |
|34583|为美好的世界献上祝福！ 第二季|
|34797|魔物娘的医生|
|34957|暗芝居 第五季|
|34975|盾之勇者成名录|
|35089|竞女!!!!!!!!|
|35122|斩！赤红之瞳|
|35129| Fate/kaleid liner 魔法少女☆伊莉雅 2wei Herz！|
|35279|Code Geass 反叛的鲁路修|
|35280|Code Geass 反叛的鲁路修 R2|
|35285|PSYCHO-PASS心灵判官|
|35305|终结的炽天使|
|35322|Fate/kaleid liner 魔法少女☆伊莉雅 2wei OVA|
|35394|七大罪|
|35431|独占我的英雄|
|35496|异世界居酒屋～古都阿伊特力亚的居酒屋阿信～|
|35583|School Days|
|35584|School Days Valentine Days|
|35585|School Days OVA 特别篇 魔法少女心|
|35589|尸骸派对 被诅咒的灵魂|
|35745|世界第一初恋|
|35746|世界第一初恋2|
|35748|世界第一初恋 OAD|
|35750|纯情罗曼史|
|35751|纯情罗曼史 第二季|
|35752|纯情罗曼史 第三季|
|35757|某科学的超电磁炮T|
|35908|3月的狮子|
|35932|刀剑神域|
|35986|超级恋人|
|36031|超级恋人 第二季|
|36032|LOVE STAGE!!|
|36294|约会大作战 第二季|
|36612|情色漫画老师|
|36687|小林家的龙女仆|
|36915|剧场版 妄想学生会|
|36935|回复术士的重来人生|
|37272|元气少女缘结神◎|
|37285|元气少女缘结神|
|37614|暗芝居 第六季|
|37615|暗芝居 第七季|
|37632|暗芝居 第四季|
|37942|暗杀教室 第二季 课外授课篇|
|37995| 中二病也要谈恋爱！SP|
