### ISSUE TITLE
[Bug] 1.6.11版本多个功能失效

### ISSUE THREAD

**Issue by Tyanyie** [yujincheng08/BiliRoaming#1122]
### 问题描述

"支持禁用图片评论时自动勾选转发到动态" 功能不好使   无论是本地图片或截图都不好使，还是会自动勾选转发动态

“视频评分的那种或者三连或投票的悬浮按钮屏蔽” 功能依旧不好使

### 复现步骤

模块里禁用上述功能禁用的按钮都开启了

### 预期行为

应该发生的是上述功能都好使

### 实际行为

也重启过应用2次以上
重启过手机

清理过b站应用缓存
都不好用

### 安卓版本

11

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.14.1

### 使用的框架和版本

LSposed 1.8.6 riru

### 其他

magisk XS-8aaa45c6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11530734/log.txt)

**Comment by yujincheng08** [comment]
> 哔哩哔哩版本号
7.14.1

严重怀疑是老版本问题。请观察新版本是不是也有同样问题。漫游兼容都是向新版看起，旧版坏掉或者不兼容是很正常的。
