### ISSUE TITLE
无法选择更高的清晰度

### ISSUE THREAD

**Issue by Zeb-5505** [yujincheng08/BiliRoaming#1123]
### 问题描述

无法观看/缓存高清晰度视频

### 复现步骤

任意视频选择高清晰度

### 预期行为

播放/缓存高清片源

### 实际行为

提示开通大会员

### 截图或录屏

![Screenshot_2023-05-23-17-58-27-126_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/89502452/5215e1a3-1d02-49e6-9360-8b6b4c3a98ff)
![Screenshot_2023-05-23-17-58-50-576_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/89502452/5dc0018b-12e9-47e0-a2dc-50f57a31780e)

### 安卓版本

13

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.30.0

### 使用的框架和版本

直接安装已经嵌入的app 下载地址：https://wwe.lanzoux.com/b015ll4sb 2333

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11543937/log.txt)

**Comment by Zeb-5505** [comment]
> 那你是大会员吗？

不是的

**Comment by david082321** [comment]
> > 那你是大会员吗？
> 
> 不是的

那就对了，没花钱还想白嫖？哪有这么好的事

B站直接给你拦下来了

**Comment by Zeb-5505** [comment]
> > > 那你是大会员吗？
> > 
> > 
> > 不是的
> 
> 那就对了，没花钱还想白嫖？哪有这么好的事
> 
> B站直接给你拦下来了

之前倒是可以😥😥
