### ISSUE TITLE
追番（港澳台）界面暗色背景[Feature] 

### ISSUE THREAD

**Issue by a3087814532** [yujincheng08/BiliRoaming#1125]
### 原因

晚上追番打开这个界面直接被闪瞎了眼睛。

![Screenshot_2023-05-22-22-29-53-81_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/77884486/5429a94d-ece7-4111-93fc-eaac3cad8d41)

### 功能简述

界面背景跟随手机暗色模式

### 功能逻辑

设置

**Comment by yujincheng08** [comment]
这不是我们的锅。。这个页面就是白的。
