### ISSUE TITLE
[Feature] 增强首页中“推广”的提示

### ISSUE THREAD

**Issue by xixiaxixi** [yujincheng08/BiliRoaming#1128]
### 原因

漫游block功能似乎对这一类别不生效

### 功能简述

以任何方式增强或隐藏带有这个恼人的小火箭的logo的推广

### 功能逻辑

大思路大家应该是一致的

### 实现参考

![微信图片编辑_20230526033102](https://github.com/yujincheng08/BiliRoaming/assets/24312323/a6a43b0e-cfd3-484b-bd66-24d1e7a80c8d)

**Comment by yujincheng08** [comment]
本来就支持。

**Comment by xixiaxixi** [comment]
> 本来就支持。

我使用的XPatch版本的，只要是推广都没有显示屏蔽选项。其它正常的视频下面是会显示的。

**Comment by yujincheng08** [comment]
在漫游设置里面设置。这个弹出选项是给内容过滤的，不是类型过滤。

**Comment by xixiaxixi** [comment]
> 在漫游设置里面设置。这个弹出选项是给内容过滤的，不是类型过滤。

那先不说通用性了。就我这个案例，我该如何配置？（最近全是这个卖卡的，点了不感兴趣还来

**Comment by yujincheng08** [comment]
漫游设置搜首页推送过滤器，其中一个选项就是，名字我忘了你自己试试。

**Comment by xixiaxixi** [comment]
就是针对这个特例很难干掉所以才提的issue。
它的第一个tag不是🚀。我并不想干掉“9千点赞”，这不通用；当然，干掉“数码”这个分区更不显示。

呵呵，只能干掉“5G”了

![9cc9873a7a69d33f02624a4cc484ca4](https://github.com/yujincheng08/BiliRoaming/assets/24312323/0c56868f-0d50-41ee-8991-9ae5bacc8966)
