### ISSUE TITLE
[Bug] 开屏页面弹出出现错误null提示框，无法使用搜索功能

### ISSUE THREAD

**Issue by DYC5152** [yujincheng08/BiliRoaming#1131]
### 问题描述

出现错误null 部分功能可能失效

### 复现步骤

打开bilibili app就会显示此信息，而且搜索时会自动重启
![Screenshot_2023-05-26-14-00-15-44_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/107192935/885801a4-f109-40a6-a5cf-411700c87bb9)

### 预期行为

应该显示bilibili漫游已启动

### 实际行为

显示出现错误null

### 截图或录屏

![Screenshot_2023-05-26-14-00-15-44_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/107192935/b10d8633-6971-408c-af34-4b752c4e99a2)

### 安卓版本

12

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.31.0

### 使用的框架和版本

1.8.6(6712)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11572055/log.txt)
日志文件如上

**Comment by yujincheng08** [comment]
#1116
