### ISSUE TITLE
[Bug] 搜索闪退以及多个未知功能失效

### ISSUE THREAD

**Issue by youruoxiao** [yujincheng08/BiliRoaming#1132]
### 问题描述

如题

### 复现步骤

打开软件即显示报错信息

### 预期行为

插件正常运行

### 实际行为

插件报错

### 截图或录屏

![Screenshot_2023-05-26-22-41-39-332_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/64008186/46d6a3ed-290a-4fdd-ba12-d7a7092a7701)

### 安卓版本

13

### 哔哩漫游版本

1.6.11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.31.0

### 使用的框架和版本

lsp1.8.6

### 其他

无

### 日志

[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/11576353/old_log.txt)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11576357/log.txt)

**Comment by yujincheng08** [comment]
#1116
