### ISSUE TITLE
下载分享

### ISSUE THREAD

**Issue by dofv** [yujincheng08/BiliRoaming#1139]
### 原因

直接分享的话只能通过小程序或者从小程序打开app，这样太麻烦了。b站虽然有个下载分享但是只下载了视频的一部分。下载原视频的话还要把音频和视频合成，这样也很麻烦。

### 功能简述

视频详情页右上角添加下载分享，把视频保存到本地

### 功能逻辑

视频详情页右上角添加下载分享，把视频保存到本地

**Comment by yujincheng08** [comment]
做出来我就要踩缝纫机了
