### ISSUE TITLE
[Server] 删除域名: melusinesuki.site 麻烦西大师了:D

### ISSUE THREAD

**Issue by kotoritan** [yujincheng08/BiliRoaming#1142]
### 联系方式

t.me/Reze_bomb

### 域名

删除域名melusinesuki.site，其余不变

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/ktrtan

**Comment by yujincheng08** [comment]
Done
