### ISSUE TITLE
[Feature] 希望可以添加一个移除所有渐变彩色的弹幕

### ISSUE THREAD

**Issue by HS7097** [yujincheng08/BiliRoaming#1147]
### 原因

这类弹幕质量很差，而且观感很恶心，希望作者可以考虑添加一个这个功能，谢谢作者

### 功能简述

移除渐变彩色弹幕或者移除彩色弹幕的颜色属性（不影响纯色弹幕）

### 功能逻辑

在隐藏功能中添加弹幕过滤器选项即可

### 实现参考

拦截整个视频的所有弹幕，并放行未带有弹幕渐变色信息的弹幕

**Comment by cxw620** [comment]
可以尝鲜一下, 测试几天: https://github.com/cxw620/BiliRoamingX/releases/tag/v1.6.10.test.hantong_8529370

**Comment by yujincheng08** [comment]
9dfcb6e91bb1321d660d33dca0bf251a3f6163ae
