### ISSUE TITLE
[Bug] getAccessKey 获取可能有问题

### ISSUE THREAD

**Issue by david082321** [yujincheng08/BiliRoaming#1150]
### 问题描述

[Screenshot](https://t.me/biliroaming_chat/2030370)

[可行的解决方法](https://t.me/biliroaming_chat/2030457) 

### 复现步骤

1. 打开需要解锁的番剧

### 预期行为

正确获取 access_key

### 实际行为

获取到的字串为 32位access_key 加 一串不明来源的token

### 安卓版本

13

### 哔哩漫游版本

832f153928 (1214)

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

tv.danmaku.bili@7.34.0(7340200) (64bit)

### 使用的框架和版本

LSPatch

### 日志

[Log](https://t.me/biliroaming_chat/2030441)

**Comment by yujincheng08** [comment]
经过检查没有问题，就是这样的。
