### ISSUE TITLE
[Server] 解析服务器停止解析，麻烦作者大大删除

### ISSUE THREAD

**Issue by InternetBugs** [yujincheng08/BiliRoaming#1153]
### 联系方式

无

### 域名

陈睿.我爱你 bilibili.com.co xn--3dz622b.xn--n4y597a0mfle743a.icu

### 支持地区

- [ ] 中国大陆
- [ ] 港澳
- [ ] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by yujincheng08** [comment]
done.
