### ISSUE TITLE
[Bug] 竖版视频替换失败

### ISSUE THREAD

**Issue by Webpage-gh** [yujincheng08/BiliRoaming#1160]
### 问题描述

在使用Bilibili打开b23.tv链接后，竖版视频没有被替换为正常样式

### 复现步骤

1. 默认打开允许b23.tv在Bilibili打开
2. 从其他软件点击b23.tv链接

### 预期行为

调转到Bilibili内浏览器后再次跳转到**正常**样式，即使是竖版视频

### 实际行为

调转到Bilibili内浏览器后再次跳转到*"竖版*"样式

### 截图或录屏

https://github.com/Webpage-gh/BiliRoaming/raw/temp/YouCut_20230629_135657234.mp4

### 安卓版本

12

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.17.0

### 使用的框架和版本

Lsposed 1.8.6

### 日志

我已经尽量缩减[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11902455/log.txt)的大小了（

**Comment by Webpage-gh** [comment]
> 你倒是给个示例链接啊

[给了啊](https://github.com/Webpage-gh/BiliRoaming/raw/temp/YouCut_20230629_135657234.mp4)

**Comment by yujincheng08** [comment]
还得我自己OCR是吧

**Comment by Webpage-gh** [comment]
稍等
