### ISSUE TITLE
[Feature] 能否有方法强制开启cc智能字幕

### ISSUE THREAD

**Issue by Bluky-BlueSkyDream** [yujincheng08/BiliRoaming#1163]
### 原因

有的视频不允许开启智能字幕，但是有时候个人又很需要这一功能

### 功能简述

强制开启cc智能字幕，并在播放操作界面强制唤出字幕设置按钮

### 功能逻辑

功能开启后在每个视频播放界面中都有字幕设置按钮，并且可以选择智能字幕

**Comment by yujincheng08** [comment]
开不了是因为啊b后台没给这个视频生成字母，强制开了你也拿不到字幕。

**Comment by Bluky-BlueSkyDream** [comment]
了解，感谢回复
