### ISSUE TITLE
[Bug] 视频弹幕大小先默认再变回默认大小

### ISSUE THREAD

**Issue by ColdLemonTea** [yujincheng08/BiliRoaming#1168]
### 问题描述

不知什么时候的CI版开始出现点进视频弹幕大小先默认再回到设置大小

### 复现步骤

1.打开b站*（废话）
2.随便点一个有弹幕的视频
3.静观其变
*注：为Play版最新Bilibili

### 预期行为

当然是不会随意大小变（设置大小）

### 实际行为

随意大小变（默认2设置）

### 截图或录屏

录屏有点大，发在7月8日tg群组的ci版本评论里了

### 安卓版本

13

### 哔哩漫游版本

37930662c

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.17.0

### 使用的框架和版本

LSPosed 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/11994413/log.txt)

**Comment by ColdLemonTea** [comment]
似乎是的

**Comment by ColdLemonTea** [comment]
> 无法复现，关闭漫游所有功能也会有问题？

似乎是的

**Comment by yujincheng08** [comment]
那亲测没问题

**Comment by ColdLemonTea** [comment]
> 那亲测没问题

wait，好像关了解锁番剧限制就好了

**Comment by ColdLemonTea** [comment]
把解锁番剧关了就好了（
