### ISSUE TITLE
[Bug] 官方版哔哩哔哩闪退

### ISSUE THREAD

**Issue by woker105** [yujincheng08/BiliRoaming#1169]
### 问题描述

播放部分视频必定会闪退，关闭漫游后恢复正常

### 复现步骤

例如av814225886，100%复现

### 预期行为

正常播放视频

### 实际行为

闪退

### 安卓版本

11

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.37

### 使用的框架和版本

LSPosed 1.8.6,zygisk

### 其他

面具版本26.1

### 日志

[log(1).txt](https://github.com/yujincheng08/BiliRoaming/files/12014759/log.1.txt)

**Comment by yujincheng08** [comment]
无法复现
