### ISSUE TITLE
港澳台番剧无字幕

### ISSUE THREAD

**Issue by zst-z** [yujincheng08/BiliRoaming#1172]
### 问题描述

漫游看港澳台番剧没字幕，已经尝试过更换解析服务器以及回退漫游版本，旧版字幕设置只有关闭选项，有人知道怎么解决吗？

### 复现步骤

1.打开bilibili
2.选择港澳台番剧分区
3.随机打开一部番剧均无字幕

### 预期行为

显示繁体转换为简体的字幕(已开启相关繁体转简体功能)

### 实际行为

无字幕

### 截图或录屏

![Screenshot_20230716-171537_bilibili](https://github.com/yujincheng08/BiliRoaming/assets/64670945/aa8857e6-7e62-4444-b045-87a2c495b8d5)
![Screenshot_20230716-171533_bilibili](https://github.com/yujincheng08/BiliRoaming/assets/64670945/88fdac39-406d-4451-8450-5727454d4824)

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

3.17.0

### 使用的框架和版本

LSP 1.8.6

### 其他

任意港澳台番剧
mgaisk 26.1
系统为 A13 EVO

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12063643/log.txt)

**Comment by zst-z** [comment]
bilibili为 play版，抱歉，上传时是选择了play版，但是我目前实际看到的是粉版。

**Comment by yujincheng08** [comment]
亲测没问题

![Screenshot_2023-07-16-17-29-20-229_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/5022927/7cf2c823-127e-45b5-9a33-5fefedb878cf)

另外漫游并不负责港澳台字幕的加载。

**Comment by zst-z** [comment]
OK，那应该是我的问题，我看看能否自己解决。

**Comment by zst-z** [comment]
OK，已解决。只需重装bilibili。
但是还不知道为什么会触发这个问题
