### ISSUE TITLE
[Bug] 7.39.0番剧解锁失效

### ISSUE THREAD

**Issue by clevercjl** [yujincheng08/BiliRoaming#1174]
### 问题描述

更新到7.39.0后泰区番剧无法播放，港澳台番剧切集后才能播放

### 复现步骤

1.打开7.39.0版本B站
2.打开泰区或港澳台番剧
3.出现上述问题

### 预期行为

都正常播放

### 实际行为

泰区番剧显示“视频不见了”
港澳台番剧切集前无法解锁，切集后正常播放，选集上显示“受限”

### 截图或录屏

![Screenshot_20230719_095615](https://github.com/yujincheng08/BiliRoaming/assets/81756592/6d2e58b3-7854-4b59-9080-0adcdb42f5c4)
![Screenshot_20230719_095631](https://github.com/yujincheng08/BiliRoaming/assets/81756592/5f33a305-7181-4d02-805e-ece5603fce3c)
![Screenshot_20230719_095646](https://github.com/yujincheng08/BiliRoaming/assets/81756592/4f82a0cd-5218-4877-8846-21e459e83d90)

### 安卓版本

13

### 哔哩漫游版本

c9214c6fef

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.39.0

### 使用的框架和版本

lspatch

### 其他

无职转生第二季 泰区
鬼灭之刃 刀匠村篇 港澳台

### 日志

[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/12090415/old_log.txt)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12090417/log.txt)

**Comment by yujincheng08** [comment]
经过测试没问题。

**Comment by clevercjl** [comment]
现在好了，今天早上还不行呢，不知道B站抽什么风
