### ISSUE TITLE
[Bug] 底栏净化 “节目” 失效

### ISSUE THREAD

**Issue by ColdLemonTea** [yujincheng08/BiliRoaming#1176]
### 问题描述

底栏净化功能中净化失效，只有在刚开启后重启的一次生效，再重启一次就失效了

### 复现步骤

1.打开底栏净化，选择“节目”并重启
2.观察底栏
3.再次重启
4.观察底栏

### 预期行为

净化后 “节目” 项目不出现

### 实际行为

能净化，但只能净化一次

### 截图或录屏

发在ci 0b0d7e42ed (1227) 版本的tg评论区

### 安卓版本

13

### 哔哩漫游版本

0b0d7e42ed (1227)

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.17.0

### 使用的框架和版本

LSPosed 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12119507/log.txt)

**Comment by yujincheng08** [comment]
无法复现

https://github.com/yujincheng08/BiliRoaming/assets/5022927/804b22ba-832e-4c1d-bfda-ac3d67c333d5
