### ISSUE TITLE
[Bug] 哔哩哔哩7.39版本似乎不能使用

### ISSUE THREAD

**Issue by TaoRone** [yujincheng08/BiliRoaming#1178]
### 问题描述

LSP框架融合，发现自建和公共服务器均失效，测试PC 网页版脚本解锁正常
因此反馈

### 复现步骤

LSP框架融合哔哩漫游1.6.12版和哔哩哔哩7.39版
融合后服务器不能正常解锁，自建服务器中亦无任何显示

### 预期行为

RT

### 实际行为

LSP框架融合哔哩漫游1.6.12版和小米商店下载的哔哩哔哩7.39版

### 安卓版本

14

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.39

### 使用的框架和版本

LSPatch 0.5.1(368)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12130944/log.txt)

**Comment by yujincheng08** [comment]
能用。
