### ISSUE TITLE
[Bug] 太极阴，Play版3.17.0无法使用

### ISSUE THREAD

**Issue by SSpinachZ** [yujincheng08/BiliRoaming#1181]
### 问题描述

太极阴，Play版3.17.0无法使用

### 复现步骤

paly版bilibili 3.17.0，使用太极阴加载漫游模块。

### 预期行为

paly版3.16.0可以正常使用

### 实际行为

打开play版bilibili立即闪退。

### 安卓版本

12

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.17.1

### 使用的框架和版本

太极阴内核129

### 日志

[logcat.log](https://github.com/yujincheng08/BiliRoaming/files/12136566/logcat.log)

**Comment by yujincheng08** [comment]
太极问题，看日志没有任何漫游相关的，所以即使没有漫游也会闪退。
