### ISSUE TITLE
[LSPatch]版本WIN11的安卓子系统安装后打不开闪退[Bug] 

### ISSUE THREAD

**Issue by 1ocean1** [yujincheng08/BiliRoaming#1183]
### 问题描述

[LSPatch]版本WIN11的安卓子系统安装后打不开闪退

### 复现步骤

打不开闪退

### 预期行为

正常使用

### 实际行为

应用闪退

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.31.0

### 使用的框架和版本

[LSPatch]

### 日志

打不开无法提供日志

[log.1.txt](https://github.com/yujincheng08/BiliRoaming/files/12138285/log.1.txt)

**Comment by yujincheng08** [comment]
跟漫游无关
