### ISSUE TITLE
[Bug] 哔哩哔哩客户端加载失败

### ISSUE THREAD

**Issue by leotoe7** [yujincheng08/BiliRoaming#1184]
### 问题描述

模块是1.6.12版本，lsp是1.8.6，哔哩哔哩是7.38.0，最新也试过，激活模块后进入哔哩哔哩加载失败。
![Screenshot_20230724-144657](https://github.com/yujincheng08/BiliRoaming/assets/42823055/fe5d4257-ea72-47e2-95c5-6bca1e712894)

### 复现步骤

同上

### 预期行为

正常情况应该正常加载出首页

### 实际行为

无法加载

### 截图或录屏

![Screenshot_20230724-144706](https://github.com/yujincheng08/BiliRoaming/assets/42823055/f6e9da49-5509-4273-8926-4d4d5771564b)
![Screenshot_20230724-144749](https://github.com/yujincheng08/BiliRoaming/assets/42823055/2dbb0d9e-3f52-49dc-9915-2569f235498c)

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.38.0

### 使用的框架和版本

1.8.6

### 其他

面具是26100

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12142650/log.txt)

**Comment by yujincheng08** [comment]
关掉模块就能加载了？

**Comment by leotoe7** [comment]
发现是justtrustme这个模块在作怪，禁用解决问题

**Comment by yujincheng08** [comment]
看到证书不被信任了，那是你网络问题。
