### ISSUE TITLE
[Bug] 长按自由复制简介失效

### ISSUE THREAD

**Issue by Kangnakamuyii** [yujincheng08/BiliRoaming#1190]
### 问题描述

长按自由复制简介失效

### 复现步骤

打开漫游设置的自由复制后，展开并长按视频简介

### 预期行为

会出现自由复制的窗口

### 实际行为

没有出现自由复制的窗口

### 安卓版本

13

### 哔哩漫游版本

最新 CI 版

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.40.0

### 使用的框架和版本

LSPosed 1.8.6(6941)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12169624/log.txt)

**Comment by cxw620** [comment]
实测 7.39.0(7390300) 不可用, 7.40.0(7400300) 可以用. 你尝试卸载哔哩哔哩重新安装, 或者进 Manager 重新优化. 
我个人是测试的时候从 7.39.0 降级安装到 7.37.0, 再安装 7.40.0, 发现居然能用(我是 LSPatch)
