### ISSUE TITLE
[Bug] 倍速预览消失

### ISSUE THREAD

**Issue by iduee** [yujincheng08/BiliRoaming#1194]
### 问题描述

全屏倍速预览变成0.0了

### 复现步骤

打开任意视频发生

### 预期行为

正常显示倍速

### 实际行为

不显示倍速

### 截图或录屏

![Screenshot_2023-07-28-16-09-08-839_tv danmaku bili-edit](https://github.com/yujincheng08/BiliRoaming/assets/110977176/b02d8bd5-82ce-455d-be1c-45e5d1ba268e)

### 安卓版本

13

### 哔哩漫游版本

1.6.12.r1362版本

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.40.0

### 使用的框架和版本

1.6.12.r1362版本

### 其他

1.6.12.r1362版本

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12192075/log.txt)

**Comment by yujincheng08** [comment]
无法复现。
