### ISSUE TITLE
可以加一个调节字号的功能吗

### ISSUE THREAD

**Issue by 1753851153** [yujincheng08/BiliRoaming#1196]
### 原因

b站正文标题和评论区的字号实在太小了，而且不能调节

### 功能简述

希望加一个调节字体大小的按钮

### 功能逻辑

怎样都行

**Comment by yujincheng08** [comment]
这种功能请求应该提给官方

**Comment by 1753851153** [comment]
好吧，不好意思打扰了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月30日(周日) 晚上7:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yujincheng08/BiliRoaming] 可以加一个调节字号的功能吗 (Issue #1196)




 
Closed #1196 as not planned.
