### ISSUE TITLE
[Feature] 请求添加恢复评论区按热度排序以赞数为准

### ISSUE THREAD

**Issue by DestoryG** [yujincheng08/BiliRoaming#1197]
### 原因

B站更新评论区机制，现在按热度排序是一些零赞评论跟一些高赞评论混杂起来，非常混乱

### 功能简述

恢复以前的评论区按赞数排序评论

### 功能逻辑

加一个恢复按赞数排序的开关，打开后就是按赞数排序

**Comment by yujincheng08** [comment]
这是接口行为决定，漫游没法做。
