### ISSUE TITLE
[Bug] 7.41.0 系列问题

### ISSUE THREAD

**Issue by cxw620** [yujincheng08/BiliRoaming#1199]
### 问题描述

由于 7.41.0 看起来有大量重构, 目前发现相当一部分功能受到影响. 目前修复了大部分失效功能, 正在测试.

详情见 #1205

~~电脑也不知道为什么, 昨天还好好的, 今天想测试, 编译老是失败, ninja 报错了一串乱码, 也不知道哪出问题, 挂个 issue 等别人来修了 :(~~

### 复现步骤

7.41.0 百分百复现

### 预期行为

功能正常

### 实际行为

功能异常

### 截图或录屏

![image](https://github.com/yujincheng08/BiliRoaming/assets/70561268/1c5646ed-4ed2-4c7b-85cf-1c1f36b34519)

### 安卓版本

12

### 哔哩漫游版本

最新ci

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.41.0(7410300)

### 使用的框架和版本

LSPatch

### 日志

无

**Comment by yujincheng08** [comment]
解锁我没发现问题呀，海外解锁大陆的

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/assets/5022927/28854c40-04be-4a9d-b443-ddc6f30e15a1

**Comment by yujincheng08** [comment]
有可能是灰测，需要账号

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/assets/5022927/b0ff9e48-133c-4ec5-a6ca-0ee3e4d988a6

评论复制

**Comment by cxw620** [comment]
> 有可能是灰测，需要账号

群里有说失效我才去看看的, 结果我也中招了. 等我修好编译环境再去抓 log 看看, 麻了()

**Comment by cxw620** [comment]
看到你的评论区和我的布局确实不太一样, 颜色还有那个等级的标识可以看出来
![image](https://github.com/yujincheng08/BiliRoaming/assets/70561268/a59a6a45-1fe5-4bc8-8695-0121b1e16b60)

**Comment by yujincheng08** [comment]
你的子评论区还有条纹

**Comment by yujincheng08** [comment]
😡

**Comment by cxw620** [comment]
我先 log 看看能不能找到灰度配置的 blconfig key (还以为是所有人都这样)

**Comment by yujincheng08** [comment]
你 ninja 报啥错？

**Comment by cxw620** [comment]
> 你 ninja 报啥错？

```text
> Task :app:buildCMakeDebug[arm64-v8a][biliroaming] FAILED

> Task :app:compileDebugKotlin
w: Language version 2.0 is experimental, there are no backwards compatibility guarantees for new language and library features

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a][biliroaming]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\.cxx\Debug\2z5y23gw\arm64-v8a'
  [1/1] Linking CXX shared library D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build\intermediates\cxx\Debug\2z5y23gw\obj\arm64-v8a\libbiliroaming.so
  FAILED: D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so
  cmd.exe /C "cd . && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --sysroot=D:/DevelopEnv/Android/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -nostdinc++ -std=c++2b -Wall -Qunused-arguments -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -fno-stack-protector 
-fomit-frame-pointer -Wno-builtin-macro-redefined -Wno-unused-value -D__FILE__=__FILE_NAME__ -Wno-c++2b-extensions -fno-limit-debug-info -Og  -nostdlib++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libbiliroaming.so -o D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build\intermediates\cxx\Debug\2z5y23gw\obj\arm64-v8a\libbiliroaming.so @CMakeFiles\biliroaming.rsp  && cmd.exe /C "cd /D D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\.cxx\Debug\2z5y23gw\arm64-v8a && D:\DevelopEnv\Android\cmake\3.22.1\bin\cmake.exe -E make_directory D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe --only-keep-debug D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a/biliroaming && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe 
--strip-all D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so""
  'cmd.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
  ���������ļ���
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "D:\\DevelopEnv\\Android\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\LocalDevelop\\LocalRepo\\Project\\BiliRoamingX\\app\\.cxx\\Debug\\2z5y23gw\\arm64-v8a" ^
        biliroaming
    from D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app

**Comment by duzhaokun123** [comment]
https://github.com/yujincheng08/BiliRoaming/assets/39830683/bccef355-f791-4173-988c-f7920c7e78a8

评论复制 🤔

**Comment by yujincheng08** [comment]
试试手动运行 `cmd.exe /C "cd . && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --sysroot=D:/DevelopEnv/Android/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -nostdinc++ -std=c++2b -Wall -Qunused-arguments -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -fno-stack-protector 
-fomit-frame-pointer -Wno-builtin-macro-redefined -Wno-unused-value -D__FILE__=__FILE_NAME__ -Wno-c++2b-extensions -fno-limit-debug-info -Og  -nostdlib++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libbiliroaming.so -o D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build\intermediates\cxx\Debug\2z5y23gw\obj\arm64-v8a\libbiliroaming.so @CMakeFiles\biliroaming.rsp  && cmd.exe /C "cd /D D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\.cxx\Debug\2z5y23gw\arm64-v8a && D:\DevelopEnv\Android\cmake\3.22.1\bin\cmake.exe -E make_directory D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe --only-keep-debug D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a/biliroaming && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe 
--strip-all D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so""`

**Comment by cxw620** [comment]
> 试试手动运行 `cmd.exe /C "cd . && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --sysroot=D:/DevelopEnv/Android/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -nostdinc++ -std=c++2b -Wall -Qunused-arguments -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -fno-stack-protector -fomit-frame-pointer -Wno-builtin-macro-redefined -Wno-unused-value -D__FILE__=__FILE_NAME__ -Wno-c++2b-extensions -fno-limit-debug-info -Og -nostdlib++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libbiliroaming.so -o D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build\intermediates\cxx\Debug\2z5y23gw\obj\arm64-v8a\libbiliroaming.so @CMakeFiles\biliroaming.rsp && cmd.exe /C "cd /D D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\.cxx\Debug\2z5y23gw\arm64-v8a && D:\DevelopEnv\Android\cmake\3.22.1\bin\cmake.exe -E make_directory D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-objcopy.exe --only-keep-debug D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so D:\LocalDevelop\LocalRepo\Project\BiliRoamingX\app\build/symbols/debug/arm64-v8a/biliroaming && D:\DevelopEnv\Android\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe --strip-all D:/LocalDevelop/LocalRepo/Project/BiliRoamingX/app/build/intermediates/cxx/Debug/2z5y23gw/obj/arm64-v8a/libbiliroaming.so""`

重做系统了， 反正也有一年清空一次的习惯 😀 晚上再看看



> free_copy.mp4 
> 评论复制 🤔

就是这样的情况

**Comment by zjns** [comment]
ab实验 key: ff_unite_detail2，官方是想统一UGC和PGC视频的播放，一方面是降低维护成本吧，番剧信息现在也走grpc View接口返回了。

**Comment by Chenyigit** [comment]
“净化搜索页面”失效了

**Comment by cxw620** [comment]
> “净化搜索页面”失效了

另外提 issue, 提供相应信息. 我暂时没发现这个问题没办法复现
