### ISSUE TITLE
[Feature] 添加自定义泰区弹幕功能

### ISSUE THREAD

**Issue by cmy2008** [yujincheng08/BiliRoaming#1200]
### 原因

泰区弹幕会串到其他视频里

### 功能简述

在弹幕设置中添加自定义弹幕按钮或在解析番剧时自动从官区或港澳台区替换弹幕

### 功能逻辑

获取弹幕时将原来串进去的cid替换为从官区或港澳台区获取到的对应剧集cid，顺便禁用弹幕防止大聪明在弹幕中宣传漫游

### 实现参考

弹弹play的弹幕装载功能

**Comment by yujincheng08** [comment]
> 泰区弹幕会串到其他视频里

修过了啊
