### ISSUE TITLE
[Feature] 支持净化评论内容

### ISSUE THREAD

**Issue by CuteLittleSky** [yujincheng08/BiliRoaming#1206]
### 原因

某些人喜欢在评论区@AI视频小助手 和听歌识曲的工具人,看视频评论是看有价值的东西而不是看这无聊的东西的..即使屏蔽这两个账号仍然会显示别人@他们的内容

#1154 下面似乎的回复似乎只是关闭整个评论区

### 功能简述

类似净化动态屏蔽指定关键词,屏蔽指定评论内容

### 功能逻辑

参考净化主页内容与动态内容

**Comment by 5ec1cff** [comment]
https://github.com/yujincheng08/BiliRoaming/pull/1211
