### ISSUE TITLE
[Feature] QQ小程序的哔哩哔哩竖屏视频替换为正常视频

### ISSUE THREAD

**Issue by CoreyLu1104** [yujincheng08/BiliRoaming#1213]
### 原因

他人通过QQ分享的小程序哔哩哔哩竖屏视频，跳转到B站之后仍是竖屏样式，希望可以替换为正常视频。

### 功能简述

他人通过QQ分享的小程序哔哩哔哩竖屏视频，跳转到B站之后仍是竖屏样式，希望可以替换为正常视频。

### 功能逻辑

点击小程序的打开App，跳转到哔哩哔哩之后是正常视频。

**Comment by cxw620** [comment]
试一下[这里的版本](https://github.com/cxw620/BiliRoamingH/releases/tag/H_Debug_0a4e9dd)可不可以, 可以我就 PR.

**Comment by CoreyLu1104** [comment]
小米12 Pro, MIUI 14, Android 13, LSPosed 1.8.6(6975)
测试通过,可以使用,非常感谢!
