### ISSUE TITLE
[Feature] 能否将发评反诈功能集成进来？

### ISSUE THREAD

**Issue by cmmdwl** [yujincheng08/BiliRoaming#1222]
### 原因

原版本作者有一段时间不更新了，换了新版app没法知道自己的评论是否发出去了

### 功能简述

将 biliSendCommAntifraud 直接加入到模块里面

### 功能逻辑

https://github.com/freedom-introvert/biliSendCommAntifraud

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/pull/516

不打算加。
