### ISSUE TITLE
[Bug] 主页刷新后哔哩漫游失效

### ISSUE THREAD

**Issue by 839565735hu** [yujincheng08/BiliRoaming#1224]
### 问题描述

主页刷新后哔哩漫游部分功能失效

我所已知的是:
自动点赞视频失效,
去除长按复制失效,
长按自由复制失效,
无法分享视频(点击复制链接没反应,QQ之类的显示分享失败)

可能原因：Magisk Delta，存在应用分身（小米自带双开，但是出问题的不是分身，分身根本就不能使用哔哩漫游）

### 复现步骤

在哔哩漫游设置后点重启客户端，然后到首页，是可以正常运行的（例如点赞，复制），
但是在首页刷新一次后就没有了效果,失去部分功能。

### 预期行为

正常运行

### 实际行为

异常状态

### 安卓版本

12

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.43.0

### 使用的框架和版本

1.8.6（6712）-Zygisk

### 其他

Magisk Delta：d2a66567-delta（26105）
手机信息：红米k50，MIUI 13.0.24

### 日志

[1692598117194log.txt](https://github.com/yujincheng08/BiliRoaming/files/12392766/1692598117194log.txt)

**Comment by yujincheng08** [comment]
#1199
