### ISSUE TITLE
[Bug] 743版本港澳台无法正确显示评论

### ISSUE THREAD

**Issue by cmmdwl** [yujincheng08/BiliRoaming#1225]
### 问题描述

7.43版本下官方似乎重构了番剧解析页面

### 复现步骤

打开港澳台, 没有正确提示解锁,切换视频选集后出现漫游提示获取到地址,但弹幕和评论依旧被禁用

### 预期行为

![221505201244367482](https://github.com/yujincheng08/BiliRoaming/assets/21263352/ab1b9a64-ee6e-4e2b-b7c3-bfa272eabb5f)

### 实际行为

![237849213507188102](https://github.com/yujincheng08/BiliRoaming/assets/21263352/76cb8566-0931-4c39-a347-1d1e7d3abe7b)

### 安卓版本

13

### 哔哩漫游版本

1.612

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.43.0

### 使用的框架和版本

1.86 6712

### 日志

无

**Comment by cxw620** [comment]
升级最新 ci
