### ISSUE TITLE
长按自由复制不生效

### ISSUE THREAD

**Issue by david4958606** [yujincheng08/BiliRoaming#1227]
### 问题描述

如题，现在长按评论不会出现复制选择弹窗，会直接复制所以内容到剪贴板

### 复现步骤

1. 开启长按自由复制和去除长按复制功能
2. 打开任意视频评论区
3. 长按评论

### 预期行为

出现弹窗让人自由选择

### 实际行为

复制评论全文到剪贴板

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.43.0

### 使用的框架和版本

LSPOSED 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12407390/log.txt)

**Comment by yujincheng08** [comment]
修过了。
