### ISSUE TITLE
[Feature] 首页推荐支持净化 推广🚀, 最好支持自定义 card_type

### ISSUE THREAD

**Issue by My-Responsitories** [yujincheng08/BiliRoaming#1229]
### 原因

首页多了不少推广🚀, 视频内容几乎都是卖卡, 抓包发现该推广的`card_type`为`cm_v2`, 漫游不能净化该类型 https://github.com/yujincheng08/BiliRoaming/blob/7c97d1c26c185c017aa437689c7660023a583fd4/app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt#L54#L68

### 功能简述

屏蔽推广🚀, 最好能够添加自定义`card_type`屏蔽

### 功能逻辑

在`净化首页推荐内容`中添加`推广🚀`选项, 添加`自定义card_type`选项

**Comment by cxw620** [comment]
这个 `card_type` 既然有 `cm_v2`, 那应该有 `cm` 吧, 都是推广()

自定义的话设置复杂, 我觉得没啥必要, 及时更新版本就是.
