### ISSUE TITLE
[BUG]泰区棍勇解析失败

### ISSUE THREAD

**Issue by Merlyx** [yujincheng08/BiliRoaming#123]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 泰区搜索回复术士的重来人生
2. 打开
3. 提示系统错误 解析失败

**截图**
![Screenshot_2021-03-14-08-57-13-897_tv danmaku bili](https://user-images.githubusercontent.com/7742683/111054108-c59f8180-84a4-11eb-85f9-36580531a34d.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：miui12
 - 哔哩漫游版本：ff615b09f3
 - 哔哩哔哩版本和版本号：6.18.0
 - 使用的框架和版本：lsposed
 - 其他：回复术士的重启人生

**日志**

<details>
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6135897/log.txt)

</details>

**Comment by yujincheng08** [comment]
早就修过了

**Comment by Merlyx** [comment]
> 早就修过了

不太懂唉...看了一下用的也是最新ci

**Comment by Merlyx** [comment]
> 早就修过了

查明原因了，这些都是走泰国api的番剧
最后能正常解析的版本是
https://github.com/yujincheng08/BiliRoaming/commit/14c0abfbaff8cad30e669a4f4002601b32df622d

然后这个版本的改动似乎导致出了点问题
https://github.com/yujincheng08/BiliRoaming/commit/9e5822a0a5442d9eb4e8e61f3c0ba2d1185ab5eb

**Comment by yujincheng08** [comment]
@Merlyx 你的问题，我的正常。

**Comment by Merlyx** [comment]
![Screenshot_2021-03-15-01-34-27-928_com guoshi httpcanary premium](https://user-images.githubusercontent.com/7742683/111078042-a6e5cd00-852e-11eb-9ae4-270e3fa39f11.jpg)
出问题的版本看抓包的番剧信息也是正常返回 但是显示页面还是加载出错

**Comment by Merlyx** [comment]
> @Merlyx 你的问题，我的正常。

抱歉打扰大佬了，确实问题在我这边
这种问题是真的玄学...
具体研究了一下 是因为白嫖华为云的缘故
然后他们提供的域名中含有横杠之类导致的转义问题
这是我的解析地址b1a8064d31c64eaaac10e7fb720d2f65.apig.ap-southeast-2.huaweicloudapis.com/bilithaiapi
