### ISSUE TITLE
[Bug] 打开漫游设置中的“显示 AV 号”和“净化分享”后，分享链接中的 BV 号无法转换为 AV 号

### ISSUE THREAD

**Issue by Kangnakamuyii** [yujincheng08/BiliRoaming#1232]
### 问题描述

打开漫游设置中的“显示 AV 号”和“净化分享”后，分享链接中的 BV 号无法转换为 AV 号

### 复现步骤

1.打开漫游设置中的“显示 AV 号”和“净化分享”
2.重启客户端，打开视频，点击分享
3.点击“复制链接”

### 预期行为

触发复制链接后，分享链接中的 BV 号转换为 AV 号

### 实际行为

触发复制链接后，分享链接中的 BV 号无法转换为 AV 号

### 安卓版本

13

### 哔哩漫游版本

最新 CI 版

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.44.0

### 使用的框架和版本

LSPosed 1.8.6 (6958)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12419694/log.txt)

**Comment by yujincheng08** [comment]
#1216

**Comment by cxw620** [comment]
> #1216

看了看日志用的 86b30b455e 是修过的版本, 可能是 7.44 又改东西了?

**Comment by cxw620** [comment]
我今天试了试, 无法复现(7440300, LSPatch). 建议重新安装哔哩哔哩后, LSPosed 重新启用模块, 重启然后看看这个问题是否依然存在.
