### ISSUE TITLE
[Bug] 泰区非官方字幕加载失败

### ISSUE THREAD

**Issue by clevercjl** [yujincheng08/BiliRoaming#1234]
### 问题描述

泰区番剧非官方字幕加载失败

### 复现步骤

1.打开有上传非官方字幕的泰区番剧
2.点击非官方字幕
3.显示字幕加载失败

### 预期行为

正常加载并显示字幕

### 实际行为

显示字幕加载失败

### 截图或录屏

https://github.com/yujincheng08/BiliRoaming/assets/81756592/99a45ed5-41f2-4b88-b3a4-ec2b82ad0d7e

### 安卓版本

13

### 哔哩漫游版本

29a067e570

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.44.0

### 使用的框架和版本

LSPatch

### 其他

莱莎的炼金工房
谎言游戏第8集
无职转生第二季第7集

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12425462/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/12425463/old_log.txt)

**Comment by yujincheng08** [comment]
这是网络问题，跟漫游没有关系。
