### ISSUE TITLE
[Bug] 清理缓存后加载不了任何内容

### ISSUE THREAD

**Issue by xming521** [yujincheng08/BiliRoaming#1235]
### 问题描述

清理缓存后加载不了任何内容 文字 视频

### 复现步骤

1.启用插件
2.清除哔哩哔哩软件缓存
3.打开

### 预期行为

正常加载

### 实际行为

清理缓存后加载不了任何内容 文字 视频

### 截图或录屏

![553faada89d61ca30e6137cafc036ff](https://github.com/yujincheng08/BiliRoaming/assets/32786500/929fffe3-6c9e-4f92-9d1c-564dc559174a)
![image](https://github.com/yujincheng08/BiliRoaming/assets/32786500/69e79ebb-12d5-4e27-bf6c-4a0afab8f091)

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.44.0

### 使用的框架和版本

LSP 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12428998/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/12428999/old_log.txt)

**Comment by cxw620** [comment]
升级最新 ci / 重新优化并重启手机 / 切换网络环境 / 关闭模块做对照, 依次执行, 还有问题另外再说
