### ISSUE TITLE
[Bug] 无法进入"我的"页面 (Mine Page)

### ISSUE THREAD

**Issue by DiracKeeko** [yujincheng08/BiliRoaming#1237]
### 问题描述

哔哩漫游 app版本 7.44.0(7440300) X_1.6.12.r1366

设置如下：
1、隐藏设置里，设置了点击头像跳转"我的"页面。（设置点击头像跳转个人主页）
2、未设置滑动进入"我的"页面。
3、关闭主界面下方"我的" 入口。

无法通过点击头像打开"我的"页面了。

### 复现步骤

设置如下：
1、隐藏设置里，设置了点击头像跳转"我的"页面。（设置点击头像跳转个人主页）
2、未设置滑动进入"我的"页面。
3、关闭主界面下方"我的" 入口。

无法通过点击头像打开"我的"页面了。

### 预期行为

点击头像，跳转"我的"页面

### 实际行为

点击头像，没有任何反应，也无法通过任何入口，进入我的页面(Mine Page)。(无法进入Mine Page也就无法进入设置 - 无法修改配置)

### 截图或录屏

![Snipaste_2023-08-25_14-31-04](https://github.com/yujincheng08/BiliRoaming/assets/48583643/d778de4c-a0e8-45b6-b73a-7ee4f0ba781d)

### 安卓版本

12

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

unknown

### 使用的框架和版本

unknown

### 日志

无法进入设置界面了 T T.

**Comment by cxw620** [comment]
X 版不归这儿管. 实在不行就清除数据.

**Comment by DiracKeeko** [comment]
OK
