### ISSUE TITLE
[Server] 新增解析服务器

### ISSUE THREAD

**Issue by SakuraAkino** [yujincheng08/BiliRoaming#1243]
### 联系方式

https://t.me/SakuraAkino

### 域名

api.xn--3bs5b681glo2bpsat27a.com

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [X] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/ SakuraAkino

**Comment by SakuraAkino** [comment]
与`api.qiu.moe`的区别在于其依托全球(含中国大陆)加速CDN，可能拥有更快更稳定的体验，可以避免某些地区日益加强的网络阻断。

**Comment by yujincheng08** [comment]
好了
