### ISSUE TITLE
[Feature] 可否屏蔽掉带货动态?

### ISSUE THREAD

**Issue by cmmdwl** [yujincheng08/BiliRoaming#1245]
### 原因

![image](https://github.com/yujincheng08/BiliRoaming/assets/21263352/1751ca3c-a50b-43ac-a622-f950bea6af54)
有些up主会一次性发很多带货链接,但是由于b站不会折叠带货链接,会比较污染动态页面,又不想直接取关up主

### 功能简述

能否针对性对准带货蓝链接做动态折叠或直接隐藏?

### 功能逻辑

直接移除

**Comment by cxw620** [comment]
给个 UP 名字瞅瞅, 没关注过会发这种广告的测试不了

**Comment by cmmdwl** [comment]
> 给个 UP 名字瞅瞅, 没关注过会发这种广告的测试不了

https://t.bilibili.com/834145780616921144
还有
