### ISSUE TITLE
[Bug] 无法屏蔽三连浮窗

### ISSUE THREAD

**Issue by coke9960** [yujincheng08/BiliRoaming#1247]
### 问题描述

华为p40，鸿蒙4.0系统
安装的是最新的7.42包
但是无法屏蔽三连浮窗，我确定我打开了屏蔽按钮

### 复现步骤

1.打开屏蔽三连浮窗的功能
2.打开任意一个有三连浮窗的视频

### 预期行为

一直播放到视频结束，不弹出任何三连浮窗

### 实际行为

弹出了浮窗

### 安卓版本

鸿蒙4.0

### 哔哩漫游版本

1.6.12r1366

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.42.0

### 使用的框架和版本

无

### 其他

没有使用面具，任意有三连浮窗的视频均会触发

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12459702/log.txt)

**Comment by cxw620** [comment]
r1366 是 X 版的, 不归这管

**Comment by qinxs** [comment]
> r1366 是 X 版的, 不归这管

这个版本能否支持 屏蔽一键三连提示框？
