### ISSUE TITLE
[Bug] 三连浮窗屏蔽失效

### ISSUE THREAD

**Issue by coke9960** [yujincheng08/BiliRoaming#1248]
### 问题描述

非常抱歉，刚才版本错了……不过换了这个版本问题依然存在
华为p40，鸿蒙4.0，三连浮窗屏蔽失效

### 复现步骤

1.打开屏蔽三连浮窗功能
2.打开任意有三连浮窗的视频

### 预期行为

屏蔽三连浮窗

### 实际行为

未屏蔽

### 截图或录屏

https://github.com/yujincheng08/BiliRoaming/assets/129470497/750c1283-3068-491b-a866-f9af2268ea0f

### 安卓版本

鸿蒙4.0

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.45.0

### 使用的框架和版本

无

### 其他

未使用框架和面具

### 日志

[log(1).txt](https://github.com/yujincheng08/BiliRoaming/files/12461151/log.1.txt)

**Comment by cxw620** [comment]
1.6.12? 更新最新 ci

**Comment by coke9960** [comment]
> 1.6.12? 更新最新 ci

不好意思，请问怎么更新啊？我看了latest是1.6.12啊？

**Comment by cxw620** [comment]
你应该用的是 lspatch 吧, 自己加 tg 频道, 找最新的下载 https://t.me/biliroaming_lspatch2

**Comment by cmmdwl** [comment]
> > 1.6.12? 更新最新 ci
> 
> 不好意思，请问怎么更新啊？我看了latest是1.6.12啊？
 
![1693298117](https://github.com/yujincheng08/BiliRoaming/assets/21263352/4d612529-1258-4368-969b-048559865868)
![1693298128(1)](https://github.com/yujincheng08/BiliRoaming/assets/21263352/42139328-318b-4bd0-b592-fd5616641efe)
如图所示

**Comment by coke9960** [comment]
> 你应该用的是 lspatch 吧, 自己加 tg 频道, 找最新的下载 https://t.me/biliroaming_lspatch2

更新至最新版已解决，感谢

**Comment by coke9960** [comment]
> > > 1.6.12? 更新最新 ci
> > 
> > 
> > 不好意思，请问怎么更新啊？我看了latest是1.6.12啊？
> 
> ![1693298117](https://user-images.githubusercontent.com/21263352/263954663-4d612529-1258-4368-969b-048559865868.png) ![1693298128(1)](https://user-images.githubusercontent.com/21263352/263954679-42139328-318b-4bd0-b592-fd5616641efe.png) 如图所示 请注意,本方法下载下来的是模块 打包需要lspatch

已解决，感谢
