### ISSUE TITLE
[Bug] 7.45.0 若干功能失效

### ISSUE THREAD

**Issue by CatOverrun** [yujincheng08/BiliRoaming#1251]
### 问题描述

包括但不限于：视频默认倍速功能，竖屏视频替换功能，失效。

### 复现步骤

播放视频

### 预期行为

1，当设置了默认视频播放速度不为100%的情况下，进入视频播放页后应自动切换至150%或设定速度，同时屏幕下方提示已设置倍速为150%（设置数值）
2，当进入竖屏视频（不仅仅是视频尺寸小于1那种，是会占满全屏的格式）时，会自动替换为普通竖着播放视频的方式播放。

### 实际行为

虽然屏幕下方，有倍速自动切换的提示，但并未实际生效。竖屏也并未替换成功。

### 安卓版本

12

### 哔哩漫游版本

e949868c8b

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.45.0

### 使用的框架和版本

LSPosed 1.9.1(6990)

### 日志

未收集到日志，我更新7.45.0进去发现两个功能失效后，认为是还未支持该版本，即刻退回7.44.0了。

后续重新安装7.45.0，获取了日志。
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12496376/log.txt)

**Comment by cxw620** [comment]
已经确认问题存在, 正在修复

**Comment by cxw620** [comment]
第一个问题无法复现, 我自己的版本自动倍速似乎是正常的, hook 的地方也是一致的. 还是请提供一下日志.

**Comment by CatOverrun** [comment]
> 第一个问题无法复现, 我自己的版本自动倍速似乎是正常的, hook 的地方也是一致的. 还是请提供一下日志.

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12496376/log.txt)

**Comment by cxw620** [comment]
无法复现, 实测正常, 日志也没看出啥问题, 除非又内测什么玩意了. 

安装这个版本, 然后手机打开 adb, 连接电脑, 运行 `adb logcat | select-string "BiliRoaming" | select-string "E BiliRoaming:|TestHook|PlayerCoreServiceV2" `, 随便看几个视频, 自己看看有没有 `BiliPlayerV2 | PlayerCoreServiceV2-[player] player speed type=1.20` 的记录(假设你设定的是默认120%, 即 1.2 倍速).

[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/12498439/app-debug.zip)
