### ISSUE TITLE
净化动态-首选视频标签不生效

### ISSUE THREAD

**Issue by A-JiuA** [yujincheng08/BiliRoaming#1252]
### 问题描述

开启首选视频标签后，进入动态依然是全部标签

### 复现步骤

打开首选视频标签
重启
打开动态

### 预期行为

默认选择视频标签

### 实际行为

默认选择全部标签

### 截图或录屏

![Screenshot_2023-08-31-20-15-27-824_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/34974508/949682bb-a57d-45e4-9261-1ce5585783e6)
![Screenshot_2023-08-31-20-25-26-029_tv danmaku bili-edit](https://github.com/yujincheng08/BiliRoaming/assets/34974508/d3f776e1-83f0-4eda-9517-ba07c33c399a)

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.44.0

### 使用的框架和版本

LSPosed 1.8.6

### 其他

Magisk Alpha 26105

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12486032/log.txt)

**Comment by cxw620** [comment]
已知问题, 等待修复.
