### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ZzzzYyyyO** [yujincheng08/BiliRoaming#1254]
### 问题描述

海外番剧无法生成字幕

### 复现步骤

海外番剧没有字幕选项

### 预期行为

显示字幕开关

### 实际行为

无字幕开关

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.0

### 使用的框架和版本

LSPosed 1.9.1

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12497137/log.txt)

**Comment by cxw620** [comment]
请升级到最新 ci 观察问题是否解决
