### ISSUE TITLE
[Feature] 希望能够提供关闭启动时的浮窗提示的选项

### ISSUE THREAD

**Issue by Giresharu** [yujincheng08/BiliRoaming#1258]
### 原因

是否已启动模块功能可以从个人页面下面是否有漫游的设置看出来，不是很需要这个浮窗提示。尤其是如果用户不需要用解析，只需要其他功能的情况下，每次都弹出来一个大黑块告之解析没有设置好，观感不是很好。所以希望能够添加关闭提示的功能。

### 功能简述

添加一个选项来选择是否弹出模块启动时的提示浮窗

### 功能逻辑

我觉得可以将浮窗提示分为三个选项状态，1.完全关闭，什么提示都不显示 2.仅在解析功能启动，但地址填写无效时提示 3.通常情况仅提示模块启动成功，若解析功能启用但地址无效时也在同一浮窗换行作提示

**Comment by yujincheng08** [comment]
明明有啊
