### ISSUE TITLE
B站方向逻辑反人类

### ISSUE THREAD

**Issue by DargonStar** [yujincheng08/BiliRoaming#1261]
### 原因

当关闭自动旋转后，全屏只能向左转，无法向右转

<img width="540" alt="17ddf6773051cfb03cac74b7e716fb5" src="https://github.com/yujincheng08/BiliRoaming/assets/127091329/b2f3a130-329a-415d-b2ad-9d911d7508b4">

![20a87b0f8ff7fde8253a4f7810544d2](https://github.com/yujincheng08/BiliRoaming/assets/127091329/b13483f9-5786-49d2-a513-fa77d53c34f5)

![706f451335304d6f843300561e79acb](https://github.com/yujincheng08/BiliRoaming/assets/127091329/4e625a43-1d1d-4240-a6db-720b9cfe35db)

### 功能简述

全屏时根据传感器方向确定

### 功能逻辑

求求了

**Comment by JasonKhew96** [comment]
这是不是应该让官方修，模块为什么要修复官方 bug
