### ISSUE TITLE
[Bug] 软件失效，看不了港澳台

### ISSUE THREAD

**Issue by fenglipop29** [yujincheng08/BiliRoaming#1263]
### 问题描述

之前还能看。最近不知道是不是b站改了什么东西，b站app在打开港澳台番剧后直接就显示根据版权无法播放，之前还会在屏幕下方有一行字大概是尝试用服务器获取视频，现在这行字都没有了

### 复现步骤

1

### 预期行为

1

### 实际行为

1

### 安卓版本

13

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.43.0

### 使用的框架和版本

Lsposed 1.9.1

### 日志

--------- beginning of main
09-10 15:38:39.778 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.780 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.781 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.781 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.784 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.784 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.784 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:39.786 13401 13401 I HandWritingStubImpl: isKeyboardTypeChanged: false
09-10 15:38:43.644 13401 13401 W BiliRoaming: 没有保存过日志
09-10 15:38:43.692 13401 19598 W Parcel  : Expecting binder but got null!
09-10 15:38:45.989 13401 13401 I tv.danmaku.bili: System.exit called, status: 0
09-10 15:38:45.989 13401 13401 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
09-10 15:38:46.155 25109 25109 E tv.danmaku.bili: Not starting debugger since process cannot load the jdwp agent.
09-10 15:38:46.172 25109 25109 I LSPosed : Loading xposed for tv.danmaku.bili/10222
09-10 15:38:46.176 25109 25109 I LSPosed-Bridge: Loading legacy module me.iacn.biliroaming from /data/app/~~hBbGs9wobarGO3kprMtMGQ==/me.iacn.biliroaming-Fi8yyVPc5cF_sg1PaSbK6g==/base.apk
09-10 15:38:46.180 25109 25109 W tv.danmaku.bili: Unsupported class loader
09-10 15:38:46.181 25109 25109 I LSPosed-Bridge:   Loading class me.iacn.biliroaming.XposedInit
09-10 15:38:46.184 25109 25109 I LSPosed-Bridge: Loading legacy module icu.freedomIntrovert.biliSendCommAntifraud from /data/app/~~Oyc_q-U2u_MSycQh2X0pfg==/icu.freedomIntrovert.biliSendCommAntifraud-dXkrOd8U3wecOu5Qaeo4KQ==/base.apk
09-10 15:38:46.222 25109 25109 W tv.danmaku.bili: Unsupported class loader
09-10 15:38:46.223 25109 25109 I LSPosed-Bridge:   Loading class icu.freedomIntrovert.biliSendCommAntifraud.xposed.PostCommentHook
09-10 15:38:46.227 25109 25109 I MessageMonitor: Load libmiui_runtime
09-10 15:38:46.234 25109 25109 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10222; state: ENABLED
09-10 15:38:46.239 25109 31103 D AppScoutStateMachine: 25109-ScoutStateMachinecreated
09-10 15:38:46.242 25109 25109 W ziparchive: Unable to open '/data/app/~~xaJJOj29k1TBjIWlX0FZ3g==/tv.danmaku.bili-zamZxueqFtqPRfrFXJflRQ==/base.dm': No such file or directory
09-10 15:38:46.242 25109 25109 W ziparchive: Unable to open '/data/app/~~xaJJOj29k1TBjIWlX0FZ3g==/tv.danmaku.bili-zamZxueqFtqPRfrFXJflRQ==/base.dm': No such file or directory
09-10 15:38:47.101 25109 25109 W System  : ClassLoader referenced unknown path: 
09-10 15:38:47.101 25109 25109 W tv.danmaku.bili: Unsupported class loader
09-10 15:38:47.113 25109 25109 I LSPosed-Bridge: bilibili version code:7430300
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge: java.lang.NoSuchMethodError: com.bilibili.app.comm.comment2.model.b#z(com.bilibili.app.comm.comment2.CommentContext,java.lang.String,long,long,long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean)#exact
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.XposedHelpers.h(Unknown Source:0)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.c.get(Unknown Source:13)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at java.util.Optional.orElseThrow(Optional.java:404)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.XposedHelpers.findMethodExact(SourceFile:1)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.XposedHelpers.findAndHookMethod(SourceFile:1)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at NBUEyB.WWVacTmOJXdJiSj.XposedHelpers.findAndHookMethod(SourceFile:2)
09-10 15:38:47.115 25109 25109 E LSPosed-Bridge:     at icu.freedomIntrovert.biliSendCommAntifraud.xposed.PostComm

**Comment by yujincheng08** [comment]
1
