### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by blessingsoftwareneverdone** [yujincheng08/BiliRoaming#1265]
### 问题描述

打开软件后显示的是漫游正常启动但是看港澳台番剧显示账号未登录，但是已经是登陆状态且重新登陆过，同时尝试过卸载重下以及更换解析服务器，但是仍然没有效果，一周之前还可以正常观看，且这周内没有进行漫游设置的更改

### 复现步骤

1.打开B站
2.点开任意港澳台番剧的任意一集
3.显示账号未登录

### 预期行为

正常是可以正常观看的

### 实际行为

显示账号未登录

### 截图或录屏

![Screenshot_20230911_235206_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/144710882/c4f79663-7af9-400e-8268-61f7cb7ed139)

### 安卓版本

鸿蒙3.0

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.31.0

### 使用的框架和版本

[LSPatch] [1.6.12] [7.31.0] 

### 其他

任意港澳台番剧任意一集

### 日志

--------- beginning of main
09-11 23:37:13.420 29829 29829 E neuron.client: [main] startService with throwable t=[Ljava.lang.StackTraceElement;@d568115
09-11 23:37:13.422 29829 29829 E neuron.client: [main] doFireEvent start service intent=161a4361-55e4-4553-95c0-060dea0c42ac failed, handle lost event
09-11 23:37:43.518 29829 29829 E neuron.client: [main] startService with throwable t=[Ljava.lang.StackTraceElement;@f47aa1b
09-11 23:37:43.520 29829 29829 E neuron.client: [main] doFireEvent start service intent=d92bb333-7e8c-44e2-9709-744c11cf2c8f failed, handle lost event
09-11 23:37:53.976 29829 29829 E neuron.client: [main] startService with throwable t=[Ljava.lang.StackTraceElement;@d90b764
09-11 23:37:53.977 29829 29829 E neuron.client: [main] doFireEvent start service intent=2454d998-f65e-4f9a-b946-2eb02543c0c2 failed, handle lost event
09-11 23:38:27.726 29829 29996 E moss.brdcst.reactor: [MossBroadcast] Handle error Exception in BidirectionalStream: net::ERR_CONNECTION_ABORTED, ErrorCode=11, InternalErrorCode=-103, Retryable=false.
09-11 23:38:27.727 29829 29996 E moss.brdcst.client: [MossBroadcast] Reactor error UNAVAILABLE.
09-11 23:38:27.732 29829 29996 E moss.brdcst.laser: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:38:27.732 29829 29996 E infra.initLaser: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:38:27.733 29829 29996 E moss.brdcst.apppush: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:38:27.733 29829 29996 E im-brdcst: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:38:27.736 29829 29996 E PushStreamRpc: [MossBroadcast] appEventStream onError
09-11 23:38:27.736 29829 29996 E PushStreamRpc: com.bilibili.lib.moss.api.NetworkException: UNAVAILABLE
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.common.exception.a.c(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.grpc.exception.a.c(BL:2)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.grpc.exception.a.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.b.A(BL:3)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.b.g(BL:4)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.r(BL:3)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1$onError$1$1.invoke(BL:2)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1$onError$1$1.invoke(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.L(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.l(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1.g(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1.e(Unknown Source:0)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.k.run(Unknown Source:4)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at android.os.Handler.handleCallback(Handler.java:966)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at android.os.Looper.loopOnce(Looper.java:205)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at android.os.Looper.loop(Looper.java:293)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.Status.d(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.stub.ClientCalls$f.a(BL:3)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m.r(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m.l(BL:1)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m$d$c.b(BL:7)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m$d$c.a(BL:3)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.t.run(BL:2)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at io.grpc.internal.r1.run(BL:2)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at java.lang.Thread.run(Thread.java:930)
09-11 23:38:27.736 29829 29996 E PushStreamRpc: Caused by: org.chromium.net.impl.BidirectionalStreamNetworkException: Exception in BidirectionalStream: net::ERR_CONNECTION_ABORTED, ErrorCode=11, InternalErrorCode=-103, Retryable=false
09-11 23:38:27.736 29829 29996 E PushStreamRpc: 	at org.chromium.net.impl.CronetBidirectionalStream.onError(BL:3)
09-11 23:38:27.736 29829 29996 E GameMossManager: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:38:27.738 29829 29996 E moss.brdcst.room: [MossBroadcast] Moss room service on error UNAVAILABLE.
09-11 23:38:27.739 29829 29996 E UpperArchiveWatcher: onError com.bilibili.lib.moss.api.NetworkException: UNAVAILABLE
09-11 23:38:28.225 29829 29829 E GameCenterEntryManager: [main] newList = [GameCenterEntrance(id=874, title=我的游戏, icon=null, url=bilibili://game_center/list?fragment_name=played&game_page=new_mine_game&sourceFrom=100012, red_dot=0, type=1, default=false), GameCenterEntrance(id=880, title=游戏更新, icon=null, url=bilibili://game_center/game_update?sourceFrom=100012, red_dot=1, type=3, default=false), GameCenterEntrance(id=877, title=找游戏, icon=null, url=bilibili://game_center/game_category?sourceFrom=100012, red_dot=0, type=7, default=false), GameCenterEntrance(id=914, title=游戏排行榜, icon=null, url=bilibili://game_center/rank_list?sourceFrom=100012, red_dot=0, type=6, default=false)]
09-11 23:38:28.225 29829 29829 E GameCenterEntryManager: [main] nothing changed, just return!
09-11 23:38:28.332 29829 29922 E PUSH_LG_BPushReportHelper: [thread_back_io] default, type: huawei, push_sdk: 3, mobile_version: 12, device_token: -1, extra: {"app_channel":"master","switch_type":"{\"status\":[{\"系统默认通道\":1,\"哔哩哔哩\":1},{\"系统默认通道\":2,\"哔哩哔哩\":2}],\"switch_name\":[\"横幅\",\"锁屏\"]}","lessons_mode":"0","teenagers_mode":"0"}, notify_switch: 1, time_zone: 8, type: 7, mobile_brand: HUAWEI, mobile_model: CET-AL00
09-11 23:38:28.506 29829 29829 E NewGoodsDetailAbUtils: [main] writeConfigToCache() start
09-11 23:38:28.700 29829 30020 E okhttp.bilow.biz.tracker: [OkHttpExecutor #5] Miss RpcExtra in bilow biz tracker, new one.
09-11 23:38:28.700 29829 29926 E okhttp.bilow.biz.tracker: [rx-pool-1-thread-1] Miss RpcExtra in bilow biz tracker, new one.
09-11 23:38:29.138 29829 29928 E okhttp.bilow.biz.tracker: [rx-pool-1-thread-2] Miss RpcExtra in bilow biz tracker, new one.
09-11 23:38:29.426 29829 29829 E GameCenterEntryManager: [main] newList = [GameCenterEntrance(id=874, title=我的游戏, icon=null, url=bilibili://game_center/list?fragment_name=played&game_page=new_mine_game&sourceFrom=100012, red_dot=0, type=1, default=false), GameCenterEntrance(id=880, title=游戏更新, icon=null, url=bilibili://game_center/game_update?sourceFrom=100012, red_dot=1, type=3, default=false), GameCenterEntrance(id=877, title=找游戏, icon=null, url=bilibili://game_center/game_category?sourceFrom=100012, red_dot=0, type=7, default=false), GameCenterEntrance(id=914, title=游戏排行榜, icon=null, url=bilibili://game_center/rank_list?sourceFrom=100012, red_dot=0, type=6, default=false)]
09-11 23:38:29.426 29829 29829 E GameCenterEntryManager: [main] nothing changed, just return!
09-11 23:38:32.775 29829 29996 E moss.brdcst.prefs: [MossBroadcast] Error update last service message id from 146 to 135.
09-11 23:40:30.818 29829 29996 E moss.brdcst.reactor: [MossBroadcast] Handle error Exception in BidirectionalStream: net::ERR_CONNECTION_ABORTED, ErrorCode=11, InternalErrorCode=-103, Retryable=false.
09-11 23:40:30.819 29829 29996 E moss.brdcst.client: [MossBroadcast] Reactor error UNAVAILABLE.
09-11 23:40:30.825 29829 29996 E moss.brdcst.laser: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:40:30.826 29829 29996 E infra.initLaser: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:40:30.826 29829 29996 E moss.brdcst.apppush: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:40:30.827 29829 29996 E im-brdcst: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:40:30.828 29829 29996 E PushStreamRpc: [MossBroadcast] appEventStream onError
09-11 23:40:30.828 29829 29996 E PushStreamRpc: com.bilibili.lib.moss.api.NetworkException: UNAVAILABLE
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.common.exception.a.c(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.grpc.exception.a.c(BL:2)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.impl.grpc.exception.a.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.b.A(BL:3)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.b.g(BL:4)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.r(BL:3)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1$onError$1$1.invoke(BL:2)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1$onError$1$1.invoke(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.L(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor.l(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1.g(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.StreamReactor$respObserver$1.e(Unknown Source:0)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at com.bilibili.lib.moss.internal.stream.internal.protocol.k.run(Unknown Source:4)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at android.os.Handler.handleCallback(Handler.java:966)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at android.os.Handler.dispatchMessage(Handler.java:110)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at android.os.Looper.loopOnce(Looper.java:205)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at android.os.Looper.loop(Looper.java:293)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at android.os.HandlerThread.run(HandlerThread.java:67)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.Status.d(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.stub.ClientCalls$f.a(BL:3)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.s0.a(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m.r(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m.l(BL:1)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m$d$c.b(BL:7)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.m$d$c.a(BL:3)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.t.run(BL:2)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at io.grpc.internal.r1.run(BL:2)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at java.lang.Thread.run(Thread.java:930)
09-11 23:40:30.828 29829 29996 E PushStreamRpc: Caused by: org.chromium.net.impl.BidirectionalStreamNetworkException: Exception in BidirectionalStream: net::ERR_CONNECTION_ABORTED, ErrorCode=11, InternalErrorCode=-103, Retryable=false
09-11 23:40:30.828 29829 29996 E PushStreamRpc: 	at org.chromium.net.impl.CronetBidirectionalStream.onError(BL:3)
09-11 23:40:30.829 29829 29996 E GameMossManager: [MossBroadcast] class com.bilibili.lib.moss.api.NetworkException, UNAVAILABLE
09-11 23:40:30.830 29829 29996 E moss.brdcst.room: [MossBroadcast] Moss room service on error UNAVAILABLE.
09-11 23:40:30.831 29829 29996 E UpperArchiveWatcher: onError com.bilibili.lib.moss.api.NetworkException: UNAVAILABLE
09-11 23:40:30.992 29829 29829 E GameCenterEntryManager: [main] newList = [GameCenterEntrance(id=874, title=我的游戏, icon=null, url=bilibili://game_center/list?fragment_name=played&game_page=new_mine_game&sourceFrom=100012, red_dot=0, type=1, default=false), GameCenterEntrance(id=880, title=游戏更新, icon=null, url=bilibili://game_center/game_update?sourceFrom=100012, red_dot=1, type=3, default=false), GameCenterEntrance(id=877, title=找游戏, icon=null, url=bilibili://game_center/game_category?sourceFrom=100012, red_dot=0, type=7, default=false), GameCenterEntrance(id=914, title=游戏排行榜, icon=null, url=bilibili://game_center/rank_list?sourceFrom=100012, red_dot=0, type=6, default=false)]
09-11 23:40:30.992 29829 29829 E GameCenterEntryManager: [main] nothing changed, just return!
09-11 23:40:31.094 29829 29922 E PUSH_LG_BPushReportHelper: [thread_back_io] default, type: huawei, push_sdk: 3, mobile_version: 12, device_token: -1, extra: {"app_channel":"master","switch_type":"{\"status\":[{\"系统默认通道\":1,\"哔哩哔哩\":1},{\"系统默认通道\":2,\"哔哩哔哩\":2}],\"switch_nam``

**Comment by JasonKhew96** [comment]
解析服务器问题
