### ISSUE TITLE
[Feature] 增加默认播放速度调整功能

### ISSUE THREAD

**Issue by Sev73n** [yujincheng08/BiliRoaming#1266]
### 原因

b站的视频都太墨迹了 默认1.5可以设置 有需要的视频 可以 手动调回1倍

### 功能简述

b站的视频都太墨迹了 默认1.5可以设置 有需要的视频 可以 手动调回1倍

### 功能逻辑

b站的视频都太墨迹了 默认1.5可以设置 有需要的视频 可以 手动调回1倍

### 实现参考

有一个单独的模块 就是bilibili调速 可是封装进去就没法设置了 希望能合并这两个项目

**Comment by cxw620** [comment]
默认倍速这功能不是有吗? 看不懂你这是啥意思

**Comment by Sev73n** [comment]
![Screenshot_20230913_015956_tv.danmaku.bili.jpg](https://github.com/yujincheng08/BiliRoaming/assets/16495885/b4308ccd-bbd0-498d-a83c-b9f60d33c19d)

没有这个功能吧
