### ISSUE TITLE
[Feature]解除地域限制后授权大会员

### ISSUE THREAD

**Issue by e-onion** [yujincheng08/BiliRoaming#127]
**原因**
为什么想要这个功能
解除地域限制后不能授权大会员，无法观看高码率的1080p60帧
**功能简述**
想要个怎样的功能
开放大会员的授权
**功能逻辑**
如何互交、如何使用等
使观看境外番剧时仍能使用大会员权限
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by JasonKhew96** [comment]
除了 东南亚区（新加坡/泰国）的番都会自动授权大会员

东南亚 区的番本来就不属于这应用，账号不通

**Comment by SakuraAkino** [comment]
该功能已实现。大陆大会员与港澳台大会员互通，但东南亚大会员与前两者不互通。在使用大陆或港澳台账号请求东南亚番剧时，会被判定为未登录用户，即最高仅支持480p（部分公共解析服务器已为用户替换为东南亚登录用户key，可正常观看720p）。
