### ISSUE TITLE
移除“用云视听打开”弹窗

### ISSUE THREAD

**Issue by Fiz-Victor** [yujincheng08/BiliRoaming#1270]
### 原因

发现最近有些视频开头出现了“用云视听打开”的弹窗，并未发现关闭入口，极度影响观感

### 功能简述

去除弹窗

### 功能逻辑

开关

**Comment by cxw620** [comment]
升级最新 CI, 问题依然存在请提供哔哩哔哩的版本号, 你正在使用的漫游版本号以及漫游 log.

**Comment by Fiz-Victor** [comment]
BV1AN411H76p
7.31.0
ci测试中

**Comment by cxw620** [comment]
> BV1AN411H76p 7.31.0 ci经检查，未发现任何功能可以去除“云视听”弹窗

那个 "移除视频浮窗" 就是

**Comment by Fiz-Victor** [comment]
经过搜索，发现并未找到类似功能，但发现代码存在相关字符串，请问是刻意隐藏了吗
