### ISSUE TITLE
[Bug] 7.48.0自定义主题色失效

### ISSUE THREAD

**Issue by clevercjl** [yujincheng08/BiliRoaming#1271]
### 问题描述

更新7.48.0后自定义主题色失效

### 复现步骤

1.打开7.48.0普通版B站
2.页面为默认主题色，并且“我的”页面右上方调色盘点不开

### 预期行为

页面为自定义的主题色，调色盘可以点开

### 实际行为

页面为默认主题色，调色盘点不开

### 安卓版本

13

### 哔哩漫游版本

bb5284d445

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.48.0

### 使用的框架和版本

LSPatch 1.9.1

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12648798/log.txt)

**Comment by cxw620** [comment]
确认问题在 7.48.0 存在, 排除了 themeNameClass 找错的问题还是不行. 不知道咋修了(一下子没咋看懂原理, 特别是那个调色盘的入口咋弄出来的, 我只知道从个性装扮可以进去设置颜色) @yujincheng08 有时间你看看?

**Comment by zifeiyu1999** [comment]
一样的问题，看着就很难受，我的还不是默认的颜色，而是白色
