### ISSUE TITLE
[Bug] CI版本的净化分享在Play版本上坏掉了

### ISSUE THREAD

**Issue by HinataKato** [yujincheng08/BiliRoaming#1272]
### 问题描述

因为要用封面比例所以下了CI版本的漫游，下载后发现链接净化坏掉了

### 复现步骤

1. 打开一个视频
2. 分享-复制链接

### 预期行为

净化后的链接

### 实际行为

粘贴后发现输出的是b23.tv

### 安卓版本

13

### 哔哩漫游版本

2bb5b25865

### 哔哩哔哩版本

Play版

### 哔哩哔哩版本号

3.16.0

### 使用的框架和版本

Lsposed 1.9.1 (6990)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12705497/log.txt)

**Comment by cxw620** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/12706204/app-debug.zip)
你看看这个版本解决了没, 没有就发日志, 解决了我就 PR.

**Comment by HinataKato** [comment]
> [app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/12706204/app-debug.zip) 你看看这个版本解决了没, 没有就发日志, 解决了我就 PR.

还是坏的
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12707201/log.txt)

**Comment by cxw620** [comment]
> > [app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/12706204/app-debug.zip) 你看看这个版本解决了没, 没有就发日志, 解决了我就 PR.
> 
> 还是坏的 [log.txt](https://github.com/yujincheng08/BiliRoaming/files/12707201/log.txt)

[app-debug-0924.zip](https://github.com/yujincheng08/BiliRoaming/files/12707858/app-debug-0924.zip)

看看这个

**Comment by HinataKato** [comment]
> [app-debug-0924.zip](https://github.com/yujincheng08/BiliRoaming/files/12707858/app-debug-0924.zip)
> 
> 看看这个
依旧
[log (1).txt](https://github.com/yujincheng08/BiliRoaming/files/12745577/log.1.txt)
