### ISSUE TITLE
[Feature] 还原原生音乐通知的功能

### ISSUE THREAD

**Issue by HinataKato** [yujincheng08/BiliRoaming#1279]
### 原因

#1277 把音乐通知给删掉了，但是对于Play版跟老版本来说还是需要的

### 功能简述

-

### 功能逻辑

-

**Comment by yujincheng08** [comment]
那你选择一个不要更新

**Comment by HinataKato** [comment]
> 那你选择一个不要更新

Play版3.18确实没把通知改回原生的音乐通知，按Play版这个更新频率估计得下辈子

**Comment by yokinanya** [comment]
> 那你选择一个不要更新

现在视频是原生音乐通知没错，但是直播不是

**Comment by PianCat** [comment]
> 那你选择一个不要更新

要不做个版本号分辨吧

**Comment by tehcneko** [comment]
7.50.0 正式版和 7.51.0 内测版都没见到有原生通知
