### ISSUE TITLE
[BUG]自定义主题色无法用，调色板出现一瞬间就变成T恤图标

### ISSUE THREAD

**Issue by robinbz** [yujincheng08/BiliRoaming#128]
**问题描述**
发生了什么情况？有什么现状？
自定义主题色没法用，一点开（我的），调色板出现一瞬间就变成T恤图标
**复现步骤**
如何复现
1. 打开...哔哩哔哩
2. 点击...【我的】
3. 出现...状况
调色板图标出现一瞬间，然后变成T恤图标
**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：10
 - 系统版本：氧OS
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号：6.21.0 release-b5106613（如概念版6.2.3）
 - 使用的框架和版本：LSPosed1.3.4（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
不太懂怎么上传文件

> 点击文本框下面小长条可以上传文件
# #`
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6222479/log.txt)
![log txt](https://user-images.githubusercontent.com/26329535/112853605-9b260900-90df-11eb-872d-89bb0059650a.png)

`

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/985a5130ed0505247d1f67b7beef8a2c4d5cbf4d

**Comment by robinbz** [comment]
没有解决
