### ISSUE TITLE
[Feature] 关于 #1277 中对于原生音乐通知的移除的建议

### ISSUE THREAD

**Issue by PianCat** [yujincheng08/BiliRoaming#1285]
### 原因

#1277 中的变更：MusicNotification 的移除过于激进

经测试，目前新版本 7.48.0 以及 7.49.0 均无法触发由B站提供的原生音乐通知。

具体测试如下图：

7.48.0：
![Stitch_20231003_203901](https://github.com/yujincheng08/BiliRoaming/assets/50688679/10dac445-5ff0-4917-a002-c65083de1351)
7.49.0：
![Stitch_20231003_204236](https://github.com/yujincheng08/BiliRoaming/assets/50688679/db51cdc9-bf5f-471b-ac66-1d210f89d027)

希望提议出移除的能够给出对应的App版本以及对应的设备及其系统，以方便其他用户进行复现。

### 功能简述

*

### 功能逻辑

*

### 实现参考

如果确认已经存在该组件/调用的情况下，能否考虑强制启用该组件/调用？

**Comment by sakarie9** [comment]
play 版本 3.18.0 也无原生通知，请求重新加入 MusicNotification

**Comment by Akizon77** [comment]
MIUI 14.0.19 
bilibili 7.49
![IMG_20231013_153344_388](https://github.com/yujincheng08/BiliRoaming/assets/64686663/9c39c030-fec4-4d5a-9db8-393c93903a7e)
![IMG_20231013_153341_333](https://github.com/yujincheng08/BiliRoaming/assets/64686663/fdd8ca6e-7e19-49b9-bd22-bb396c81406d)
![Screenshot_2023-10-13-15-28-30-025_com miui securitycenter](https://github.com/yujincheng08/BiliRoaming/assets/64686663/0cff5756-73a5-4014-9f22-68260e043b5c)

**Comment by mio-19** [comment]
play 版本 3.18.0 无原生通知，请求重新加入

**Comment by tehcneko** [comment]
7.50.0 正式版和 7.51.0 内测版都没见到有原生通知

**Comment by tehcneko** [comment]
反编译之后找到原生音乐通知需要满足以下条件之一：
- VIVO 手机
- 千分之一的概率
