### ISSUE TITLE
[Bug] “净化分享”功能致B站分享视频失败

### ISSUE THREAD

**Issue by Hinghuai** [yujincheng08/BiliRoaming#1287]
### 问题描述

在开启净化分享状态下，哔哩哔哩无法对外分享视频，包括微信QQ复制链接方式均提示“分享失败”，在关闭“净化分享”功能后分享正常

### 复现步骤

1.启用“净化分享功能”
2.根据提示确认设置并重启客户端
3.随机点进视频并分享至微信或QQ（在多次尝试过程中，最多在第二次分享时就能发生）
3.哔哩哔哩提示“分享失败”

### 预期行为

正常跳转至QQ或微信发送界面

### 实际行为

哔哩哔哩提示分享失败，无其他反馈

### 截图或录屏

![Screenshot_2023-10-07-23-07-05-708_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/63064333/b5afa40a-179a-4c42-b1ff-561efaf54476)
![Screenshot_2023-10-07-23-06-46-350_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/63064333/167b9988-b886-4c4c-b1fc-e66ed2d06cf5)

### 安卓版本

12

### 哔哩漫游版本

1.6.12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.48.0

### 使用的框架和版本

LSPosed 1.91(6990)

### 其他

Magisk 82903582-alpha (26105)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/12838155/log.txt)

**Comment by yujincheng08** [comment]
没法修，只能说 expected 了。
