### ISSUE TITLE
[Bug] 1.7.0打开视频时有几率闪退

### ISSUE THREAD

**Issue by dunxuan** [yujincheng08/BiliRoaming#1290]
### 问题描述

有时候视频还能继续播放，但是报错了，有时候软件直接重启，而且历史记录里没有闪退的视频。
经验证是1.7.0的问题，1.6.12没问题。
麻烦了大佬∗︎˚(* ˃̤൬˂̤ *)˚∗︎

### 复现步骤

1.打开一个视频
2.感觉来了

### 预期行为

正常播放视频

### 实际行为

闪退报错

### 截图或录屏

![Screenshot_2023-10-13-08-19-59-223_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/33661049/221ee70c-87b5-48f9-9cc7-042d4b34c53b)

### 安卓版本

MIUI14 安卓13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50 7.49

### 使用的框架和版本

LSPosed 1.9.2

### 其他

magisk 26.3

### 日志

[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/12888554/old_log.txt)
应该是这个日志

**Comment by yujincheng08** [comment]
二分看看是哪个功能引起的？

**Comment by cxw620** [comment]
是不是同时给哔哩哔哩上了几个模块互相干扰了?

**Comment by dunxuan** [comment]
卸载重装后好了，之前对模块和B站降级和更新操作了好几次都会稳定出现bug。
![0089jzyPgy1gqdh3ul9eej30e80e8myq jpg (512×512)](https://github.com/yujincheng08/BiliRoaming/assets/33661049/2de0e4c0-1707-4183-94c4-5e85dcee7c46)

**Comment by whzdl** [comment]
我的v20鸿蒙3也有这个bug，看着一半软件重启，或者是直接就到闪退到桌面，不知道啥原因，我寻思着我这手机性能够啊，高强度刷视频和画质调高后比较容易出现这种情况
