### ISSUE TITLE
[BUG]泰区解析出现问题

### ISSUE THREAD

**Issue by AustraliaLetter** [yujincheng08/BiliRoaming#130]
**问题描述**
发生了什么情况？有什么现状？
无法解析[转生史莱姆日记](https://bangumi.bilibili.com/anime/1002302) 

**复现步骤**
如何复现
1. 在任何评论区发布上述网址
2. 点击发布后的链接
3. 正确进入页面，番剧信息正常显示，但是播放器始终处于全黑状态。点击“追番”后提示正在解析，随即提示出错。

-或者-

1. 浏览器访问https://bangumi.bilibili.com/anime/1002302
2. 点击页面中的“使用APP打开”按钮
3. 同上

**截图**
点击文本框下面小长条可以上传文件
![IMG_20210407_091917](https://user-images.githubusercontent.com/82068485/113796666-5d318080-9782-11eb-99ec-b2f123e5e24c.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.0.6
 - 哔哩漫游版本：1.4.3
 - 哔哩哔哩版本和版本号：原版6.21.5
 - 使用的框架和版本：EdXposed v0.5.2.2_4683
 - 其他：泰国版转生史莱姆日记

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[logs.txt](https://github.com/yujincheng08/BiliRoaming/files/6268259/logs.txt)

**Comment by JasonKhew96** [comment]
初步怀疑是 upos 问题

**Comment by AustraliaLetter** [comment]
> 初步怀疑是 upos 问题

但是看其它的番剧没有问题
我觉得可能是链接的问题？我用泰国APP搜的，拿到的链接是https://m.global.bilibili.com/play/1002302/10064269，不符合 @miyouzi 提供的可转换链接的格式

**Comment by miyouzi** [comment]
通过最上面提供的链接，能够打开播放
![Screenshot_20210407_122230_tv danmaku bili](https://user-images.githubusercontent.com/24269465/113810183-4009ab80-979c-11eb-95f0-4eb102969d70.jpg)

**Comment by JasonKhew96** [comment]
> > 初步怀疑是 upos 问题
> 
> 但是看其它的番剧没有问题
> 我觉得可能是链接的问题？我用泰国APP搜的，拿到的链接是[https://m.global.bilibili.com/play/1002302/10064269](https://m.global.bilibili.com/play/1002302/10064269)，不符合 @miyouzi 提供的可转换链接的格式

你那链接我能加载出来，都说了是 upos 问题，日志里显示正常解析

泰区的就简单的换一下就行
ss ID: 1002302
ep ID: 10064269
https://www.bilibili.com/bangumi/play/ss1002302
https://www.bilibili.com/bangumi/play/ep10064269

**Comment by AustraliaLetter** [comment]
感谢
