### ISSUE TITLE
[Server] 添加新服务器

### ISSUE THREAD

**Issue by heinu123** [yujincheng08/BiliRoaming#1301]
### 联系方式

https://t.me/yinlangd

### 域名

https://api.mihoyo.buzz

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/heinu

**Comment by yujincheng08** [comment]
Done
