### ISSUE TITLE
[Feature] 请求添加一个屏蔽指定表情的功能

### ISSUE THREAD

**Issue by parano11d** [yujincheng08/BiliRoaming#1307]
### 原因

被评论区满屏的狗头弄得生理不适了，请求添加一个屏蔽指定表情的功能

### 功能简述

屏蔽指定表情，尤其是狗头

### 功能逻辑

能够屏蔽评论区的指定表情，无论是单独屏蔽这个表情，还是把整句话全部屏蔽了都行

**Comment by cxw620** [comment]
你试试在评论筛选里面加一个 `[doge]` (或者`(\[doge\])` 正则模式)

**Comment by parano11d** [comment]
x

> 你试试在评论筛选里面加一个 `[doge]` (或者`(\[doge\])` 正则模式)

谢谢你：）
