### ISSUE TITLE
[Feature] 请求移除开屏广告

### ISSUE THREAD

**Issue by Oscar0901** [yujincheng08/BiliRoaming#1308]
### 原因

恶心人的扭一扭广告

### 功能简述

去除开屏广告，比如自动跳过，或删除广告提供应商，或删除对应区域

### 功能逻辑

去除开屏广告，比如自动跳过，或删除广告提供应商，或删除对应区域

**Comment by JasonKhew96** [comment]
已经有了，“净化开屏页面”

**Comment by Oscar0901** [comment]
> 已经有了，“净化开屏页面”

那个是净化开屏的推广，不是开屏广告啊(
