### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wang2650** [yujincheng08/BiliRoaming#1309]
### 问题描述

10月22号之后，突然不能用移动网络显示内容。首页打开一片空白项，没有内容。从6.4升级到7.5后，还是如此。 在wifi下正常使用。我在有问题之前没有做其他设置。

### 复现步骤

1打开应用
2首页空白
3切换为wifi网络
4一切恢复正常

### 预期行为

正常使用

### 实际行为

没有内容。

### 截图或录屏

![54e7e200da1a3843caa676eac683052](https://github.com/yujincheng08/BiliRoaming/assets/3048544/487c76cc-b182-4dbd-9035-866f6a547cff)
![330958a878987fc20dbde5f2f32e63b](https://github.com/yujincheng08/BiliRoaming/assets/3048544/d0f71bb4-e52f-4eb6-af82-272be3fb5b3c)

### 安卓版本

小米9

### 哔哩漫游版本

7.50.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

lsposed 1.82

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13156442/log.txt)

**Comment by yujincheng08** [comment]
网络问题。

**Comment by wang2650** [comment]
问题已解决。  我有两张卡，一张没问题，一张有问题，怎么换版本都不行（只能用wifi，用流量就用不了b站，但是用快手没问题）。  最后我从网上看到答案，切换了下飞行模式，就解决了。  原因是什么不知道。感谢回复。
