### ISSUE TITLE
太极版1.7无法使用去小程序分享[Bug] 

### ISSUE THREAD

**Issue by lvye-asia** [yujincheng08/BiliRoaming#1311]
### 问题描述

 分享至微信和QQ的都是小程序

### 复现步骤

正常分享过程

### 预期行为

分享出去为链接

### 实际行为

小程序分享

### 截图或录屏

![Screenshot_20231027_215902](https://github.com/yujincheng08/BiliRoaming/assets/105652758/6d558e9b-43e8-4fb8-ae52-59fc147f8ed1)
![Screenshot_20231027_215851_com tencent mobileqq](https://github.com/yujincheng08/BiliRoaming/assets/105652758/e7cf16c5-83fa-4434-b99c-cfccd698eb2d)

### 安卓版本

鸿蒙 4.0

### 哔哩漫游版本

1.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.52

### 使用的框架和版本

太极 14.0.5.10151817-10092

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13189744/log.txt)

**Comment by lvye-asia** [comment]
系统版本是Harmony os 4.0.0.116[C00E116R1P4log)

**Comment by yujincheng08** [comment]
尝试重新安装或者重新优化，这是太极问题

**Comment by lvye-asia** [comment]
> 尝试重新安装或者重新优化，这是太极问题

重新安装了还是没有用
