### ISSUE TITLE
[Bug]lsp版，其他地区番剧搜索出错

### ISSUE THREAD

**Issue by olkamz** [yujincheng08/BiliRoaming#1313]
### 问题描述

已添加可以使用的解析服务器，但在使用搜索功能搜索其他地区番剧时，出错搜索不出来，显示加载失败。应该是在lsp7.38.0往后就一直有这个bug了

### 复现步骤

1添加完访问正常的解析服务器
2开启其他地区搜索功能
3搜索番剧，其他地区加载失败（但首页旁边的其他地区页面能正常使用）

### 预期行为

正常搜索出结果

### 实际行为

加载失败

### 截图或录屏

![Screenshot_20231029_092949](https://github.com/yujincheng08/BiliRoaming/assets/45625524/e60830e6-b898-4808-b95e-19467a746173)

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

lspatch（release里下载的）

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13197017/log.txt)

**Comment by JasonKhew96** [comment]
日志都没有相关内容（
日志应该要抓出问题时候的

**Comment by cxw620** [comment]
> @cxw620 不如帮海外用户弄弄 never gonna give you up（

可是现在是 playurl 都没有了, 看了眼返回 -403 咱也不知道为什么, 估计是没版权()

👇 大陆
![image](https://github.com/yujincheng08/BiliRoaming/assets/70561268/ef7916c2-a407-45cb-bd79-256a0e7f7ece)
👇 海外
![image](https://github.com/yujincheng08/BiliRoaming/assets/70561268/ec60ac1f-7c33-4a04-9593-8a1efaa9d6fa)

**Comment by yujincheng08** [comment]
@cxw620 试了一下，国内 ip 打开视频，然后国外 ip 过去缓存下载链接似乎没问题，不知道走的是不是同一个接口。

**Comment by cxw620** [comment]
> @cxw620 试了一下，国内 ip 打开视频，然后海外 ip 获取缓存下载链接似乎没问题，不知道走的是不是同一个接口。

测了一下, 老接口 `bilibili.app.playurl.v1.PlayURL` 还是可以正常拿到的(真的要为了这个适配吗, 那就是 PlayerUniteReply 返回 null 然后得再请求一次老接口, 还拿不到再请求漫游服务器, 这样就很慢了())

**Comment by yujincheng08** [comment]
可以适配一下。这种视频其实挺多的。有些番剧国创番剧甚至是这种形式的我记得。

**Comment by cxw620** [comment]
周末看看有没有空吧, 在 PR #1291 的基础上弄. ~~工作日摸鱼禁止()~~
