### ISSUE TITLE
[Bug] 自定义底栏是空的

### ISSUE THREAD

**Issue by IIIlllIIllIIIll** [yujincheng08/BiliRoaming#1317]
### 问题描述

自定义底栏是空的

### 复现步骤

1. 打开模块设置
2. 打开自定义底栏

### 预期行为

自定义底栏有选项

### 实际行为

自定义底栏是空的

### 截图或录屏

![Screenshot_20231103_174038](https://github.com/yujincheng08/BiliRoaming/assets/35266436/df194839-ca61-4b36-a1eb-fa63ebee57b3)

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.51.0

### 使用的框架和版本

TaiChi 14.0.5.10151817-10092

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13246810/log.txt)

**Comment by IIIlllIIllIIIll** [comment]
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13246822/log.txt)

**Comment by yujincheng08** [comment]
太极的问题，尝试重新优化

**Comment by IIIlllIIllIIIll** [comment]
谢谢, 重装哔哩哔哩后正常了
