### ISSUE TITLE
[Feature] 是否可以解决于QQ和微信中以小程序的状态“分享失败”的问题？

### ISSUE THREAD

**Issue by Fitzgerald-Porthmouth-Koenigsegg** [yujincheng08/BiliRoaming#1318]
### 原因

此问题出现在将视频、直播间、番剧等以小程序的状态分享至QQ和微信中所出现的情况。

分享至QQ则提示：非官方应用，appid=100951776（错误码：25201）
分享至微信则提示：签署金钥有误，请确认签署金钥是否与开放平台上填写的相同。

在旧版本中，这个问题可以通过反复重启应用的情况得以豁免，而在新版本中，此方法不奏效。

尽管我可以々短链接的形式进行分享，但我遭遇了多次被误判成广告、传销等发布者的情况，遂不啻如此。

### 功能简述

可正常将视频以小程序的状态分享至QQ和微信中，且长期不会出现报错提醒。

### 功能逻辑

可正常将视频以小程序的状态分享至QQ和微信中，且长期不会出现报错提醒。

**Comment by yujincheng08** [comment]
非 root 下无解。

**Comment by wangxiaolong1234555** [comment]
ji

> root非下无解。

我手机有root，如何解决这个问题？

**Comment by yujincheng08** [comment]
有 root 用 lsposed

**Comment by wangxiaolong1234555** [comment]
lsposed咋用？安卓变量

> 有 root 用 lsposed

**Comment by david082321** [comment]
> lsposed咋用？

在Magisk里面安装LSPosed
重启手机
打开LSPosed，确认安装成功
卸载修改版B站
安装漫游
安装原版B站
在LSPosed里面选择漫游，指定作用于B站
重启B站APP
如果没有在B站看到漫游设置，那么重启手机
