### ISSUE TITLE
[Feature] 请求添加关闭合集自动播放功能

### ISSUE THREAD

**Issue by xiaoqingyxq** [yujincheng08/BiliRoaming#1319]
### 原因

很多短视频的up主都喜欢把自己的视频搞一个合集，导致偶尔点进去看一个视频没反应过来自动放下一个，很烦。现在的合集自动播放下一集和多p视频是同一个，为了不自动播放只能设置视频播放方式为播完当前自动暂停(如图)
![S31105-17013612_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/103957202/b73531c4-5d9c-4ccd-94de-ed56e105e25c)
，这又导致了看一些多p长视频或者番剧还要手动播放下一集，继续烦。记得以前b站是可以设置关闭合集连放的，后来没有了，希望大大可以把合集的自动联播按钮和视频的分开，跪谢。

### 功能简述

合集是否自动播放单独设一个开关

### 功能逻辑

点击选择打开关闭

**Comment by yujincheng08** [comment]
合集和多 p 视频是一样的了。
