### ISSUE TITLE
能不能添加一个所有消息一键已读功能

### ISSUE THREAD

**Issue by 205687875** [yujincheng08/BiliRoaming#132]
**原因**
为什么想要这个功能

强迫症表示每次上b站都要点一下右上角信封
**功能简述**
想要个怎样的功能
所有消息一键已读
**功能逻辑**
如何互交、如何使用等
点击特定按钮所有消息一键已读
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
类似于微x的一键已读功能

**Comment by ketal178** [comment]
直接把红点删了得了

**Comment by david082321** [comment]
官方 6.59.0 以上，提供该功能
