### ISSUE TITLE
[Bug] BiliRoaming 1.7.0版不兼容 bilibili play 3.11.0版

### ISSUE THREAD

**Issue by pesh178** [yujincheng08/BiliRoaming#1320]
### 问题描述

使用BiliRoamin 1.6.12版可以正常hook bilibili 3.11.0 play 版，升级为BiliRoamin 1.7.0后失效

### 复现步骤

1.升级BiliRoamin到1.7.0

### 预期行为

哔哩哔哩客户端设置出现哔哩漫游设置

### 实际行为

没有置出现哔哩漫游设置

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.11.0

### 使用的框架和版本

LSPosed 1.9.2(7024)-Zygisk

### 日志

没有设置入口无法使用漫游自带的日志功能

**Comment by yujincheng08** [comment]
play 都 3.18 了
