### ISSUE TITLE
[Server] 新增解析服务器(顺便改改联系方式 +赞助地址)

### ISSUE THREAD

**Issue by heinu123** [yujincheng08/BiliRoaming#1324]
### 联系方式

https://t.me/wtdnwbzda

### 域名

api.rnmmihoyo.cc

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://www.heinu.cc/donate

**Comment by 0JsJ0** [comment]
感谢开通的服务器
