### ISSUE TITLE
[Feature]添加cc字幕设置

### ISSUE THREAD

**Issue by L245T** [yujincheng08/BiliRoaming#133]
**原因**
B站自带的cc字幕没有走安卓规范使用系统设置，而是自己搞了一套用弹幕实现，但是字幕不能调大小、阴影、透明度等等

**功能简述**
能够调整cc字幕的字体、大小、阴影、字体边缘颜色、字体边缘大小、字体边缘透明度、背景不透明度、字幕窗口颜色

**功能逻辑**
建议在模块设置的杂项中的弹幕设置下方添加入口，调整可调整参数

**Comment by yujincheng08** [comment]
B 站 CC 字幕本身就有很多配置参数的。但是 B 站客户端根本不理会这些参数，而是写死的显示效果，导致根本无法实现。
