### ISSUE TITLE
[Bug] 开启闪退

### ISSUE THREAD

**Issue by urusaia** [yujincheng08/BiliRoaming#1332]
### 问题描述

一打开总是要闪退几次才加载出来
报错：
11-24 23:46:54.168  5502  5502 E ili:pushservic: Not starting debugger since process cannot load the jdwp agent.

### 复现步骤

1.点击图标
2.等待几秒
3.闪退

### 预期行为

打开直接进主页

### 实际行为

闪退

### 安卓版本

鸿蒙2.0 安卓10

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

lsposed

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13460783/log.txt)

**Comment by yujincheng08** [comment]
因为缺乏设备，不会对鸿蒙进行特殊兼容。
