### ISSUE TITLE
[Bug]7.55+ 默认播放速度功能失效

### ISSUE THREAD

**Issue by CatOverrun** [yujincheng08/BiliRoaming#1335]
### 问题描述

无法以设置的默认倍速播放视频。测试最后功能正常的版本，7.54。后面的7.55 56 57均有此问题。

### 复现步骤

设置如图后，点击任意视频，不会以1.5倍速播放。

### 预期行为

以设置的倍速播放视频

### 实际行为

没有倍速，以1.0原速播放视频

### 截图或录屏

![Screenshot_20231130-163644](https://github.com/yujincheng08/BiliRoaming/assets/18223125/645f085a-337b-45f0-9673-766834df8740)

### 安卓版本

12

### 哔哩漫游版本

b18e86474a

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.57

### 使用的框架和版本

LSPosed 1.9.2(7024)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13510492/log.txt)

**Comment by cxw620** [comment]
试一下这个版本看看可不可以.
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/13522282/app-debug.zip)

**Comment by CatOverrun** [comment]
> 试一下这个版本看看可不可以. [app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/13522282/app-debug.zip)

使用此版本，更新7.57.1的哔哩哔哩，重启手机。
状态是进入视频后，下面会弹出提示“哔哩漫游：已设置1.5倍速”（这是之前好的时候也会弹，但更新到7.55+之后不弹了）但实际上视频没有倍速，还是1.0速。

**Comment by cxw620** [comment]
不应该啊, 奇怪, 我测试能正常倍速啊()

**Comment by cxw620** [comment]
你再试试我自己分支的版本, 还是用三星商店那个哔哩哔哩, 重新设置一下默认倍速, 点进去个视频看看, 然后发日志
[app-debug-h.zip](https://github.com/yujincheng08/BiliRoaming/files/13522513/app-debug-h.zip)

这块我也没改东西, 跟原版表现应该一样的, 奇怪了...

**Comment by CatOverrun** [comment]
> 你再试试我自己分支的版本, 还是用三星商店那个哔哩哔哩, 重新设置一下默认倍速, 点进去个视频看看, 然后发日志 [app-debug-h.zip](https://github.com/yujincheng08/BiliRoaming/files/13522513/app-debug-h.zip)
> 
> 这块我也没改东西, 跟原版表现应该一样的, 奇怪了...

全测试了一次
之前那个app-debug，重启，配合三星商店的7.57.1或者tg里的7.57.2，均是推送消息提示修改倍速，实际没修改。
app-debug-h，重启，7.57.1，.2，结果一样。我这先临时解决就是退回7.54就可以用，我再等等吧。

**Comment by CatOverrun** [comment]
直至哔哩哔哩版本7.61，哔哩漫游版本8dfab0c8f4，情况依旧。底部显示调整播放速度，实际没有。
找到个临时解决办法，用了个别人的组件，[bili调速](https://github.com/V-E-O/biliSpeed/)，它不是调整的播放器里那个倍速，那里还显示1.0，但视频确实以1.5倍速播放了。

**Comment by yujincheng08** [comment]
我这边 7.62 成功复现。一开始速度是快的，但是过一下下他就变回原速了。
