### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cakesa** [yujincheng08/BiliRoaming#1336]
### 问题描述

我用的google chrome浏览器在PC网页上看的
之前清了一次cookie发现现在一直授权不了，取消授权也报错。
点授权的话就跳转一个新页面然后一直卡在：正在获取授权，请稍候……
然后完全不动
点取消授权的时候是：感谢使用，正在为您清除登录cookie
访问key删除失败，错误：[403]undefined

不知道是我的问题还是bug，有没有人和我一样

### 复现步骤

点授权的话就跳转一个新页面然后一直卡在：正在获取授权，请稍候……
然后完全不动
点取消授权的时候是：感谢使用，正在为您清除登录cookie
访问key删除失败，错误：[403]undefined

### 预期行为

1

### 实际行为

1

### 截图或录屏

![1](https://github.com/yujincheng08/BiliRoaming/assets/75235868/48a3b117-d47a-46ec-b34a-3334d2ca327e)
![2](https://github.com/yujincheng08/BiliRoaming/assets/75235868/d2fe66f1-d5af-4301-a6e7-41895a9996ea)

### 安卓版本

12

### 哔哩漫游版本

1.6.2

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

LSPosed 1.8.2

### 日志

[1.txt](https://github.com/yujincheng08/BiliRoaming/files/13512608/1.txt)

**Comment by skytianle666** [comment]
油猴脚本与本应用（哔哩漫游）无关
