### ISSUE TITLE
[Server] 移除解析

### ISSUE THREAD

**Issue by CodePwn2021** [yujincheng08/BiliRoaming#1340]
大势（天官赐福事件）目前已去，暂时不提供解析服务了

### 联系方式

null

### 域名

bili.ox19.top

### 支持地区

- [ ] 中国大陆
- [ ] 港澳
- [ ] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by yujincheng08** [comment]
Done
