### ISSUE TITLE
观看港澳台番剧时不停弹出“已获取播放地址”提示

### ISSUE THREAD

**Issue by Tommy12pl** [yujincheng08/BiliRoaming#1342]
### 问题描述

观看区域外版权番剧时一直弹出“已获取播放地址”提示，更换解析服务器和UPOS服务器以及换用蓝奏云网盘内提供的LSPatch版客户端都无法解决。

### 复现步骤

在设置好解析服务器和UPOS后播放区域外版权番剧即可复现

### 预期行为

每一集只在播放之前弹出一次提示

### 实际行为

每一秒左右就会弹出一次提示，无论哪一集

### 截图或录屏

![IMG_20231210_234653](https://github.com/yujincheng08/BiliRoaming/assets/67495124/9d3d1cad-f96f-424a-a0c2-2c5253079f08)

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.58.0

### 使用的框架和版本

LSPatch 0.5.1

### 其他

未root，是使用LSPatch嵌入补丁，重新打包后安装的

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13631111/log.txt)

**Comment by yujincheng08** [comment]
你的网络问题。

**Comment by Tommy12pl** [comment]
> 你的网络问题。

已经试过从Wi-Fi切换到数据网络、更换解析服务器、更换UPOS、重新打包安装包和使用不同的VPN节点等方式，情况仍旧。

**Comment by david082321** [comment]
> 已经试过从Wi-Fi切换到数据网络、更换解析服务器、更换UPOS、重新打包安装包和使用不同的VPN节点等方式，情况仍旧。

漫游设置里面关闭模块提示信息，眼不见为净
