### ISSUE TITLE
请问可以添加新的lsp版本的客户端下载方式吗

### ISSUE THREAD

**Issue by hak5ya** [yujincheng08/BiliRoaming#1343]
### 问题描述

今天更新移动端，lsp版本客户端时，发现使用手机下载最新安装包时提示需要付费，不过目前可以通过切换手机浏览器UA为电脑实现免费下载

### 复现步骤

使用手机浏览器下载lsp版本客户端，提示蓝奏云下载需要付费

### 预期行为

免费使用手机浏览器更新lsp版客户端

### 实际行为

无法直接使用手机浏览器下载蓝奏云盘文件

### 截图或录屏

![Screenshot_2023-12-12-01-23-21-843_com tencent mtt](https://github.com/yujincheng08/BiliRoaming/assets/116129694/e359b0ec-f402-465c-ba5d-6a306b1f619d)

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

[LSPatch] [1.7.0] [7.50.0]

### 日志

抱歉，这并不是一个软件的BUG，但是我也不知道这个问题应该发在哪个分类下

**Comment by xzlosats111** [comment]
浏览器ua改成电脑就可以下了，不过这个便携版的太久没更新了，小问题挺多，建议自己折腾一下，原版客户端然后lsposed或lspacth注入模块

**Comment by xzlosats111** [comment]
> 感谢解答，我已经重新安装了原版客户端，不过现在又有了一个新的问题，移除最常访问（视频）这个功能失效了开启后在动态的最常访问中仍然有视频选项卡 ![Screenshot_2023-12-14-02-04-00-341_tv danmaku bili](https://private-user-images.githubusercontent.com/116129694/290286431-577fc8cd-2d30-46f4-81a7-d587eebba13e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzIxNjgsIm5iZiI6MTcwMjYzMTg2OCwicGF0aCI6Ii8xMTYxMjk2OTQvMjkwMjg2NDMxLTU3N2ZjOGNkLTJkMzAtNDZmNC04MWE3LWQ1ODdlZWJiYTEzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwOTE3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDNlZmVkMWY5ZmFjNzI1ZDY4MjQ4M2JmNTlmZGE2OTNiZDQ1N2I5YTFmZTYwY2RlMmFjMTJlYTIwNjU2ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YGiUvW90pswdmPyLAuv4AEYJaAS8p_JomMRCOhDyysM) ![Screenshot_2023-12-14-02-04-08-710_tv danmaku bili](https://private-user-images.githubusercontent.com/116129694/290286459-875565cd-0fa3-424e-b26c-4515c1254e90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzIxNjgsIm5iZiI6MTcwMjYzMTg2OCwicGF0aCI6Ii8xMTYxMjk2OTQvMjkwMjg2NDU5LTg3NTU2NWNkLTBmYTMtNDI0ZS1iMjZjLTQ1MTVjMTI1NGU5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwOTE3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWEwZTg2ZGMzM2JkMTM3OThlZmNmN2M2NzIyODAxMzAzMDk4MWZjY2M0MzcxN2EyN2QzNzJkZTEwMGMwNDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T9WaOoUbrHPoDqynOyt-0z-9pDiWrMOFENYrossckKQ)

你回错人了，我不是作者，就路过多了一嘴，你要么再重新写个bug反馈？反正我就开了个屏蔽广告，其他基本没动，目前没发现问题

**Comment by yujincheng08** [comment]
浏览器ua改成电脑就可以下了
