### ISSUE TITLE
[Feature] 禁用视频播放器左侧滑动调整亮度

### ISSUE THREAD

**Issue by xzlosats111** [yujincheng08/BiliRoaming#1344]
### 原因

B站视频播放器左侧上下滑动，可以快速调节当前视频亮度，右侧可以调节音量大小，但是很容易误触，而且一旦是误触就是变成最亮或最暗，很讨厌，希望关掉，因为我是习惯左手抓手机所以误触的是亮度，如果右手估计就是音量了

### 功能简述

增加一个设置项，可以关闭这两个滑动调节或者加一个亮度跟随系统设置开关
目前在B站自带的设置项以及编辑播放器设置项里面，我都没找到这个开关，应该就是没有

### 功能逻辑

同上

### 实现参考

miui13，已经把B站修改系统设置的权限给关了，亮度调的是当前页面亮度，音量调的是我的系统音量，具体怎么做到的我不知道
关于亮度找到了一个这样的模块，
https://modules.lsposed.org/module/com.fankes.refusebrightness
不过不想应用整个app，就想把那个功能删掉而已

**Comment by yujincheng08** [comment]
播放器有个小锁，点开就行。
