### ISSUE TITLE
[Bug] 番剧出差失效

### ISSUE THREAD

**Issue by moyusumiu** [yujincheng08/BiliRoaming#1347]
### 问题描述

番剧出差无法查看港澳台以及东南亚区番剧，疑似接口又被更改了？

### 复现步骤

1.打开b站
2.点击港澳台番剧

### 预期行为

可选集数，能够播放番剧

### 实际行为

集数没有显示，无法播放

### 截图或录屏

![Screenshot_20231222_012121_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/148297038/70ae6654-941a-4c63-8c6c-61d2b546e46d)

### 安卓版本

12

### 哔哩漫游版本

1.6.2

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

LSPosed 1.8.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13744699/log.txt)

**Comment by moyusumiu** [comment]
补充:根据运行提示各位大佬提供的服务器有在正常运行，但就是如上图情况
使用加速器全局模式，港澳台番剧则正常

**Comment by moyusumiu** [comment]
再订正:全局模式下集数可选，评论区恢复可看，但是番剧依旧无法播放

**Comment by yujincheng08** [comment]
6.74.0 太老了。

**Comment by rhwong** [comment]
同样的问题，哔哩哔哩版本7.59.0

**Comment by cxw620** [comment]
> 同样的问题，哔哩哔哩版本7.59.0

NO LOG NO FIX
