### ISSUE TITLE
[Bug] 泰区番剧加载异常

### ISSUE THREAD

**Issue by NaNaChiSama** [yujincheng08/BiliRoaming#1349]
### 问题描述

泰区番剧加载错误

### 复现步骤

1.打开哔哩哔哩
2.搜索番剧
3.切换泰区搜索
4.进入搜索出来的泰区番剧

### 预期行为

能正常加载出泰区番剧，并且匹配解析服务器所支持的最高画质(如4K)

### 实际行为

加载泰区番剧会出错，偶尔加载出来了画质也最高只有480P

### 截图或录屏

![IMG_20231223_064634](https://github.com/yujincheng08/BiliRoaming/assets/97809275/0fc8174b-b44f-49db-982c-0b35e7b4af41)
![Screenshot_2023-12-23-06-56-48-02_e615dcad39387724f53efab3bb596b18](https://github.com/yujincheng08/BiliRoaming/assets/97809275/95eec3f1-2099-4c98-a6f9-a990a9547002)

### 安卓版本

13

### 哔哩漫游版本

1.7.0 (3999e618d3)

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.60.0

### 使用的框架和版本

LSPatch 0.6

### 其他

所有番都加载不出来(第一份log)，能加载出番剧的情况在我记录了十多次的log里面就只出现了一次，并且就算加载出来了也只有最高480P的画质(第二份log)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13757143/log.txt)
[log (1).txt](https://github.com/yujincheng08/BiliRoaming/files/13757146/log.1.txt)

**Comment by cxw620** [comment]
已经确认问题是哔哩哔哩关停了漫游依赖的获取剧集信息的 API, 目前暂时没办法修复. 考虑解析服务器改代码提供剧集信息, 但是这需要时间以及维护者精力.
