### ISSUE TITLE
［B U G］设置自定义速度不起作用

### ISSUE THREAD

**Issue by weijia99** [yujincheng08/BiliRoaming#135]
问题描述
发生了什么情况？有什么现状？

模块的设置播放速度不起作用

复现步骤
如何复现

漫游设置-自定义播放速度列表-填写数字隔开，加不加x都不起作用

截图

![Screenshot_20210411-135648.jpg](https://i.loli.net/2021/04/12/iwU3dZ12lDrTsQ7.jpg)
![Screenshot_20210412-085400.jpg](https://i.loli.net/2021/04/12/bcaznxfJ1lwYKR3.jpg)
环境信息

安卓版本：Android 11
系统版本：氢 OS 11.0.6.8
哔哩漫游版本：1.4.3
哔哩哔哩版本和版本号：6.18.2
使用的框架和版本：xpatch-latest
日志
log.txt

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/issues/134#issuecomment-817414625
