### ISSUE TITLE
[Bug] play版 3.18.1 无法观看港澳台番剧和泰区番剧，提示提示无法获取剧集信息

### ISSUE THREAD

**Issue by niu164** [yujincheng08/BiliRoaming#1351]
### 问题描述

play版 3.18.1 无法观看港澳台番剧和泰区番剧，提示
无法获取剧集信息

### 复现步骤

打开3.18.1 play版b站
搜索港澳台分区
点开任意一个港澳台番剧

### 预期行为

正常播放

### 实际行为

提示无法获取剧集信息

### 截图或录屏

![Screenshot_2023-12-24-14-10-39-635_com bilibili app in](https://github.com/yujincheng08/BiliRoaming/assets/76257039/51742de8-9e32-417a-885b-1268ae24a1ee)
![Screenshot_2023-12-24-14-10-58-216_com bilibili app in](https://github.com/yujincheng08/BiliRoaming/assets/76257039/6339a078-1e76-4b82-aa53-78221cfc24eb)

### 安卓版本

13

### 哔哩漫游版本

3999e618d3

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.1

### 使用的框架和版本

1.9.2 (7024) - Zygisk

### 其他

magisk delta

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13761029/log.txt)

**Comment by niu164** [comment]
补充:与clash无关，我关了也是一样的

**Comment by cxw620** [comment]
换个解析服务器看看

**Comment by niu164** [comment]
> 换个解析服务器看看

换了一个还是一样的问题，一模一样的服务器国内版能正常使用，play版就提示无法获取剧集信息

**Comment by cxw620** [comment]
国内版估计也不能用, 有缓存罢了. 你换个没看过的番试试看看.

**Comment by niu164** [comment]
> 国内版估计也不能用, 有缓存罢了. 你换个没看过的番试试看看.

试了几个也都能看，没提示异常

**Comment by yujincheng08** [comment]
我这边国内版没问题，难道又是灰测？

**Comment by niu164** [comment]
> 我这边国内版没问题，难道又是灰测？

国内版是没问题啊，我说的是play版😂

**Comment by yujincheng08** [comment]
> > 我这边国内版没问题，难道又是灰测？
> 
> 国内版是没问题啊，我说的是play版😂

我没跟你说

**Comment by niu164** [comment]
> > > 我这边国内版没问题，难道又是灰测？
> > 
> > 
> > 国内版是没问题啊，我说的是play版😂
> 
> 我没跟你说

🌝好的

**Comment by cxw620** [comment]
到时候再看看吧, `bangumi.bilibili.com/view/web_api/season` 这个接口确认是寄了, 处理 season_id 这块的逻辑我忘了

**Comment by cxw620** [comment]
> 
> ### 日志
> [log.txt](https://github.com/yujincheng08/BiliRoaming/files/13761029/log.txt)

这日志跟没有一样, 看看还有没有别人反馈这问题吧, 能确定的是东南亚的肯定是寄, 港澳台走 united 接口的没问题.

**Comment by xy97** [comment]
> > ### 日志
> > [log.txt](https://github.com/yujincheng08/BiliRoaming/files/13761029/log.txt)
> 
> 这日志跟没有一样, 看看还有没有别人反馈这问题吧, 能确定的是东南亚的肯定是寄, 港澳台走 united 接口的没问题.

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13763371/log.txt)
我也遇到了这个问题，已经好几天了

**Comment by JasonKhew96** [comment]
看了一眼，走 `com.bapis.bilibili.pgc.gateway.player.v2.PlayViewReply` `getThaiSeason` 拉出了错误
~~怎么变成泰区了，这部分谁写的？（~~

**Comment by zjns** [comment]
`bangumi.bilibili.com/view/web_api/season` api 已经无了
https://github.com/yujincheng08/BiliRoaming/blob/3999e618d373d0cd1e66017b264bd868d79f75d1/app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt#L79-L120
建议直接把这段代码删了
泰区直接走解析服务器拿 season，港澳台无需再次请求接口拿 season 信息，针对老版播放器，season 信息会通过 https://api.bilibili.com/pgc/view/v2/app/season 完整下发，针对新版播放器，season 信息会完整通过 Unite ViewReply 完整下发，只需要修改其中的字段信息即可解除限制。

**Comment by cxw620** [comment]
> `bangumi.bilibili.com/view/web_api/season` api 已经无了
> 
> https://github.com/yujincheng08/BiliRoaming/blob/3999e618d373d0cd1e66017b264bd868d79f75d1/app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt#L79-L120
> 
> 
> 建议直接把这段代码删了
> 泰区直接走解析服务器拿 season，港澳台无需再次请求接口拿 season 信息，针对老版播放器，season 信息会通过 https://api.bilibili.com/pgc/view/v2/app/season 完整下发，针对新版播放器，season 信息会通过 Unite ViewReply 完整下发，只需要修改其中的字段信息即可解除限制。

看看最近谁有空 commit 一下？我最近两周都忙😇

**Comment by muzirinai** [comment]
请问怎么看泰区，服务器是支持泰区的

**Comment by niu164** [comment]
> > `bangumi.bilibili.com/view/web_api/season` api 已经无了
> > https://github.com/yujincheng08/BiliRoaming/blob/3999e618d373d0cd1e66017b264bd868d79f75d1/app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt#L79-L120
> > 
> > 建议直接把这段代码删了
> > 泰区直接走解析服务器拿 season，港澳台无需再次请求接口拿 season 信息，针对老版播放器，season 信息会通过 https://api.bilibili.com/pgc/view/v2/app/season 完整下发，针对新版播放器，season 信息会通过 Unite ViewReply 完整下发，只需要修改其中的字段信息即可解除限制。
> 
> 看看最近谁有空 commit 一下？我最近两周都忙😇

悲，还没人修，😭

**Comment by ZerOri** [comment]
同样的问题，看来只有play版有

**Comment by sqksws** [comment]
有没有天使救救😭

**Comment by kljjh** [comment]
play版3.18.1 用了最新ci版还是不行啊 跟之前一样的问题
日志：
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13904750/log.txt)

**Comment by chouex** [comment]
play版 3.18.2 無法解鎖國內番剧, `v1.7.0`  與`master`都不可以, 換國內版沒有問題
master 的錯誤信息
![image](https://github.com/yujincheng08/BiliRoaming/assets/767140/c4e265e9-d4bf-4273-be5c-e4bf843bec92)
