### ISSUE TITLE
在哔哩哔哩我的里面点击哔哩漫游设置没反应打不开模块菜单[Bug] 

### ISSUE THREAD

**Issue by ABLB1** [yujincheng08/BiliRoaming#1355]
### 问题描述

在哔哩哔哩我的里面点哔哩漫游设置没反应，打不开模块菜单，只能从桌面哔哩漫游app内选择启动客户端并打开模块设置才能打开模块设置菜单，但是关了以后点哔哩漫游设置还是没反应

### 复现步骤

打开哔哩哔哩，点击我的，点击哔哩漫游设置没反应

### 预期行为

应该打开哔哩漫游模块设置菜单

### 实际行为

点了以后什么都没发生，没反应

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.60

### 使用的框架和版本

lsposed1. 9. 2

### 其他

面具版本26.4

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13779928/log.txt)

**Comment by yujincheng08** [comment]
在 lsposed 里面重新优化哔哩哔哩

**Comment by SHIERQICI** [comment]
重新优化没有解决，最后打开的方式是在哔哩漫游app里点击“打开模块设置”强制打开的，如此更改好了设置。但其他方式尝试打开其设置页面依然失败。
