### ISSUE TITLE
[Bug] 搜索内容过滤正则匹配反直觉

### ISSUE THREAD

**Issue by duzhaokun123** [yujincheng08/BiliRoaming#1356]
### 问题描述

搜索内容过滤正则匹配反直觉

### 复现步骤

1. 搜索内容过滤使用正则模式
2. 添加匹配项`.`

### 预期行为

过滤掉所有结果

### 实际行为

仅过滤了包含一个字符的结果

### 安卓版本

13

### 哔哩漫游版本

1.6.13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.61.0

### 使用的框架和版本

LSPatch 0.6 (398)

### 其他

https://github.com/yujincheng08/BiliRoaming/blob/8dfab0c8f4a7167d8ae99815e5f138ed98465e15/app/src/main/java/me/iacn/biliroaming/hook/ProtoBufHook.kt#L309
这里用的 matches 但 matches 要求完整匹配
<img width="598" alt="image" src="https://github.com/yujincheng08/BiliRoaming/assets/39830683/a3c460a9-07a2-4787-bdb6-ca6038f22168">
应该用 contains
<img width="601" alt="image" src="https://github.com/yujincheng08/BiliRoaming/assets/39830683/851cfc9b-197b-4205-b40f-ed57f2001b8f">

### 日志

no

**Comment by cxw620** [comment]
或许你可以直接改了 PR, 问题明确()
