### ISSUE TITLE
[Bug] PC端 解除B站区域限制8.4.6导致视频无法加载

### ISSUE THREAD

**Issue by Frank-Z-Chen** [yujincheng08/BiliRoaming#1358]
### 问题描述

![image](https://github.com/yujincheng08/BiliRoaming/assets/79745119/0c25e62a-1e79-45a3-89b2-dee124fc0fd1)

更新到8.4.6之后视频无法加载，降级到8.4.5解决问题。

### 复现步骤

1. 更新到8.4.6
2. 打开任意番剧，等大概10秒页面会刷新
3. 拉取视频失败

### 预期行为

视频成功加载

### 实际行为

除视频以外的元素都成功加载，如评论。但是视频无法加载。

### 安卓版本

X

### 哔哩漫游版本

X

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

X

### 使用的框架和版本

X

### 日志

X

**Comment by yujincheng08** [comment]
X

**Comment by Frank-Z-Chen** [comment]
> X

为啥给关了

**Comment by david082321** [comment]
> 为啥给关了

因为你跑错地方了 https://github.com/ipcjs/bilibili-helper/issues
