### ISSUE TITLE
[Bug] hd版无法加载港澳台地区的评论，弹幕能加载但无法发送弹幕，泰区无法加载，经clash日志表明是地址更改了

### ISSUE THREAD

**Issue by laoqijun1** [yujincheng08/BiliRoaming#1361]
### 问题描述

如题

### 复现步骤

1.用lspatch改包（把哔哩漫游整合进hd版的安装包里）
2.安装
3.登入，并设置解析服务器
4.搜索番剧出差，随便点一个港澳台番剧，播放

### 预期行为

能发弹幕，评论和看评论（网页版脚本就能做到）

### 实际行为

能看弹幕，无法看评论，发弹幕

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.44.2

### 使用的框架和版本

lspatch 0.5.1(360) 框架版本1.8.5(6649)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13835193/log.txt)

**Comment by yujincheng08** [comment]
似乎已经修复。
