### ISSUE TITLE
[Server] Request server deletion

### ISSUE THREAD

**Issue by CielNeko** [yujincheng08/BiliRoaming#1363]
### 联系方式

https://t.me/ciel_pm_bot

### 域名

bili.rikko.moe

### 支持地区

- [ ] 中国大陆
- [ ] 港澳
- [ ] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

此服务器不再维护

**Comment by yujincheng08** [comment]
done
