### ISSUE TITLE
缓存视频转格式 

### ISSUE THREAD

**Issue by 632225259** [yujincheng08/BiliRoaming#1364]
### 原因

有时候需要把缓存视频导入到别的地方观看。

### 功能简述

有没有考虑过加个功能，缓存的视频批量转成mp4之类的视频格式，还能自动命名

### 功能逻辑

勾选自动转换缓存格式，能指定转换后存储位置就更好了

**Comment by yujincheng08** [comment]
这个设计版权问题不会实现。
