### ISSUE TITLE
[Bug] play版或概念版依旧无法观看港澳台番剧和泰区番剧，提示 无法获取剧集信息

### ISSUE THREAD

**Issue by q1351022** [yujincheng08/BiliRoaming#1366]
### 问题描述

play版无法观看港澳台番剧和泰区番剧，提示
无法获取剧集信息，己下载电报最新版本。

### 复现步骤

打开play版b站
搜索港澳台分区
点开任意一个港澳台

### 预期行为

正常播放

### 实际行为

无法获取剧集信息

### 安卓版本

11

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.1

### 使用的框架和版本

1.9.2

### 其他

面具版本26.1

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13924093/log.txt)

**Comment by yujincheng08** [comment]
不想支持 play 了，好麻烦。用粉版吧。

**Comment by q1351022** [comment]
> 不想支持 play 了，好麻烦。用粉版吧。

刚刚看到更新了，谢谢大佬。₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by moleoxa** [comment]
> 不想支持 play 了，好麻烦。用粉版吧。

请问粉版的包名是哪个？
