### ISSUE TITLE
[Bug] 泰区番剧切集后只有第一集显示字幕

### ISSUE THREAD

**Issue by clevercjl** [yujincheng08/BiliRoaming#1367]
### 问题描述

泰区番剧切集前不显示字幕，切集后只有第一集显示字幕，后面的集数都不显示字幕，所有泰区番剧都一样，不是偶发问题

### 复现步骤

1.打开一部泰区番剧
2.首集不显示字幕
3.切集后的集数不显示字幕
4.切回第一集显示字幕
5.切到其他集还是不显示字幕

### 预期行为

正常显示字幕

### 实际行为

不显示字幕

### 截图或录屏

https://github.com/yujincheng08/BiliRoaming/assets/81756592/9830ef58-989c-4e68-bfd6-e6e366e4dc12

### 安卓版本

13

### 哔哩漫游版本

1573deb52e

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63.0

### 使用的框架和版本

LSPatch 1.9.2

### 其他

测试的番：葬送的芙莉莲、狩龙人拉格纳、间谍过家家、欢迎来到实力至上主义的教室、僵尸百分百等

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13926323/log.txt)

**Comment by yujincheng08** [comment]
无法复现。
