### ISSUE TITLE
解锁番剧限制功能失效，UPOS服务器测速失败

### ISSUE THREAD

**Issue by china-luoyu** [yujincheng08/BiliRoaming#1369]
### 问题描述

1. 观看港澳台限制番剧提示:请求解析服务器发生错误(点此查看更多)解析服务器错误:无法获取聚集信息
2. UPOS服务器测试失败

### 复现步骤

1. 打开bilibili
2. 点击搜索并搜索哔哩哔哩番剧出差，在投稿页面随意点击一个番剧
3. 播放小窗出现提示[观看港澳台限制番剧提示:请求解析服务器发生错误(点此查看更多)解析服务器错误:无法获取聚集信息]并且伴随相同的弹窗提示。  不出现剧集，评论界面提示:抱歉，暂无聚集可供评论
4. 点开番剧的瞬间，评论后出现了评论数数字，随后消失

### 预期行为

港澳台限制视频正常播放，且评论区可以正常查看。
UPOS服务器测速正常出现各个服务器的速度

### 实际行为

港澳台限制视频无法播放，评论区无法查看。
 UPOS服务器测速失败

### 截图或录屏

![Screenshot_20240114_122240](https://github.com/yujincheng08/BiliRoaming/assets/104239672/5d3214cf-892d-498d-a087-6a75d0045468)
![IMG_20240114_122231](https://github.com/yujincheng08/BiliRoaming/assets/104239672/a5d8f0b6-7d90-4987-9a9a-735ec0136ba8)
![Screenshot_20240114_121809](https://github.com/yujincheng08/BiliRoaming/assets/104239672/b976033a-e55a-4be3-8285-ba61d72f94b4)
![Screenshot_20240114_121758](https://github.com/yujincheng08/BiliRoaming/assets/104239672/2d80295c-fbda-4baa-9f9d-05ff506fcb2f)

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.1

### 使用的框架和版本

API 版本 93  LSPatch 版本 0.6 (398)  框架版本 1.9.2 (7024)  系统版本 13 (API 33)  设备 Vivo V2302A   系统架构 arm64-v8a

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13930329/log.txt)

**Comment by yujincheng08** [comment]
修过了
