### ISSUE TITLE
[Feature] 能否将修复港澳台和泰区观看做成新版本更新

### ISSUE THREAD

**Issue by moyusumiu** [yujincheng08/BiliRoaming#1370]
### 原因

翻看bug请求列表发现问题已经修复但是网盘貌似还停留在1.7.0，没有电报从网页这边看到电报群有更新但是因为没有账号无法下载

### 功能简述

能够正常观看泰区番剧

### 功能逻辑

无

### 实现参考

无

**Comment by duzhaokun123** [comment]
那既然能在这说话为什么不从 GitHub 下载

**Comment by moyusumiu** [comment]
> 那既然能在这说话为什么不从 GitHub 下载

你好，谢谢回复，我算是个小白并不是很懂怎么从github下载，平时都是直接下载整合好的APP，且昨天尝试用太极和漫游发现反而会启动闪退。。。只能使用整合好的APP

**Comment by moyusumiu** [comment]
> 那既然能在这说话为什么不从 GitHub 下载

你好，谢谢回复，我算是个小白并不是很懂怎么从github下载源码打包成apk，平时都是直接下载整合好的APP，且今天拜托朋友下载电报群的文件之后发现太极阴只支持发布的正式版（1.7.0这样的编号）。。。

**Comment by yujincheng08** [comment]
等 bug 修完再说。
