### ISSUE TITLE
原生音乐通知在Coloros失效

### ISSUE THREAD

**Issue by Enmmma** [yujincheng08/BiliRoaming#1371]
### 问题描述

开启后不显示通知

### 复现步骤

在漫游设置内打开选项

### 预期行为

通知可以正常显示

### 实际行为

通知不显示，但通过通知滤盒可以查看到该通知

### 安卓版本

14

### 哔哩漫游版本

a0a6187c3b (1322)

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.63.0

### 使用的框架和版本

Lsposed

### 其他

可能是OPPO魔改了系统的API,但是通过xposed的应该也可以实现吧

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13961454/log.txt)

**Comment by yujincheng08** [comment]
这个只是开启哔哩哔哩的原生音乐通知。通知本身已经不是漫游生成的了。所以不打算修。
