### ISSUE TITLE
[Bug] 7.64.0搜索其他地区番剧失效

### ISSUE THREAD

**Issue by calpa2007** [yujincheng08/BiliRoaming#1372]
### 问题描述

搜索其他地区番剧在7.64.0失效

### 复现步骤

1.搜索番剧
2.点击其他地区番剧栏
3.结果为空白

### 预期行为

显示搜索结果

### 实际行为

一片空白

### 截图或录屏

https://github.com/yujincheng08/BiliRoaming/assets/140033044/6e69c2bd-60f4-40ae-9751-48ee7306dabe

### 安卓版本

13

### 哔哩漫游版本

a0a6187c3b

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.64.0

### 使用的框架和版本

LSPatch 0.6(402)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/13962803/log.txt)

**Comment by no-10032** [comment]
b站压根没买这番在其他地区的版权怎么可能有结果

**Comment by calpa2007** [comment]
没有的话应该会显示“什么都没有找到”才对，不是完全空白，而且泰区是有这部番的
