### ISSUE TITLE
哔哩哔哩官方7.64.0版本使用免root方式后直播标签页空白

### ISSUE THREAD

**Issue by gumiling** [yujincheng08/BiliRoaming#1376]
### 问题描述

哔哩哔哩官方7.64.0版本使用免root方式后直播标签页空白，经核查7.50.0之后的版本，发现此情况仅于7.64.0版本开始出现

### 复现步骤

1. 使用lspatch集成模式嵌入模块，整合哔哩哔哩官方7.64.0和哔哩漫游
2. 启动后点击直播，点击推荐一栏最后的图标进入全部标签
3. 可以发现是一片空白
4. 环境为miui14.0.5，miui14.0.17和miui14.0.25，安卓12和安卓13
5. 哔哩漫游版本测试了1.7.0版本到提交的最新版本ff79035031，都有这种问题

### 预期行为

正常情况下应该有所有的直播标签

### 实际行为

实际上一片空白

### 安卓版本

13

### 哔哩漫游版本

BiliRoaming_ff79035031

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.64.0

### 使用的框架和版本

lspatch0.6

### 日志

[1_5004020762542080972.txt](https://github.com/yujincheng08/BiliRoaming/files/14011025/1_5004020762542080972.txt)

**Comment by zjns** [comment]
official bug, fixed by 7.65.0
