### ISSUE TITLE
[Bug] 启动bilibili时弹出错误

### ISSUE THREAD

**Issue by HeJinDing-aipiao** [yujincheng08/BiliRoaming#1377]
### 问题描述

启动bilibili时报错

### 复现步骤

1.打开

### 预期行为

正常弹出插件提示

### 实际行为

弹出出现错误

### 截图或录屏

![Screenshot_2024-01-23-20-47-58-591_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/72332681/1998c358-4ad8-4e7a-9a03-b841b280387f)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.64.0

### 使用的框架和版本

lsposed 1.9.2(7024)

### 其他

magisk版本65207f96 (26404)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14024172/log.txt)

**Comment by yujincheng08** [comment]
已修复。

**Comment by HeJinDing-aipiao** [comment]
等待插件后续更新吗？还是有其他解决办法

**Comment by yujincheng08** [comment]
等更新，或者用 CI
