### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ADKadk0** [yujincheng08/BiliRoaming#1378]
### 问题描述

安卓14运行时偶尔会出现崩溃，然后应用自动重启，看了一半的视频也没有记录

### 复现步骤

暂时没有能稳定导致崩溃的方法

### 预期行为

正常情况应该是视频正常播放

### 实际行为

实际上应用自动重启，当时播放的视频没有记录

### 安卓版本

14

### 哔哩漫游版本

目前公开的最新版

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

xspatch版（记不太清了，拼写差不多

### 其他

任何视频都有可能出现

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14024967/log.txt)

**Comment by yujincheng08** [comment]
日志没发现异常。
