### ISSUE TITLE
[BUG]泰国解析又出问题了。。

### ISSUE THREAD

**Issue by AustraliaLetter** [yujincheng08/BiliRoaming#138]
**问题描述**
发生了什么情况？有什么现状？
无法观看[致不灭的你](https://bangumi.bilibili.com/anime/1002225/) 
昨天还能看的。。

**复现步骤**
如何复现
1. 动态或评论发布链接
2. 点击链接
3. 提示加载失败

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.0.6
 - 哔哩漫游版本：1.4.3
 - 哔哩哔哩版本和版本号：6.22.0
 - 使用的框架和版本：EdXposed v0.5.2.2_4683
 - 其他：致不灭的你

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6308386/log.txt)

另外，新上的番（100开头的）好像不能显示在历史记录中，也不能点赞、弹幕、追番

**Comment by JasonKhew96** [comment]
![Screenshot_20210414-161013.jpg](https://user-images.githubusercontent.com/29531167/114676561-ff7dd500-9d3b-11eb-9d3a-3eb5331792f2.jpg)

同一个解析服务器，我这没问题

**Comment by JasonKhew96** [comment]
> 另外，新上的番（100开头的）好像不能显示在历史记录中，也不能点赞、弹幕、追番

新上的番 id 完全不通用了，而且会串评论弹幕

还有，不登录是没法用泰区解析服务器，部分解析服务器强制登录了

**Comment by AustraliaLetter** [comment]
> 同一个解析服务器，我这没问题
我现在也没问题了。。所以是什么问题。。网络波动么。。
