### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by VanityOfWall** [yujincheng08/BiliRoaming#1381]
### 问题描述

打开时会弹出一段错误日志

### 复现步骤

打开就会

### 预期行为

不弹出错误

### 实际行为

弹出错误

### 截图或录屏

![Screenshot_2024-01-25-10-35-45-651_tv danmaku bil](https://github.com/yujincheng08/BiliRoaming/assets/48897610/eaf6a0c2-36e1-4d31-a97e-dd92b5c04754)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.65.0

### 使用的框架和版本

太极14.0.6

### 日志

[log(1).txt](https://github.com/yujincheng08/BiliRoaming/files/14046099/log.1.txt)

**Comment by yujincheng08** [comment]
已修
