### ISSUE TITLE
[Bug] 泰区番剧字幕不显示

### ISSUE THREAD

**Issue by xifeng0** [yujincheng08/BiliRoaming#1382]
### 问题描述

泰区番剧正常播放，但是字幕不显示，选择任意字幕均不显示。

### 复现步骤

播放任意泰区番剧，然后选择字幕，出现任意字幕均不显示情况。

### 预期行为

正常情况会显示对应语言字幕

### 实际行为

实际什么都没显示

### 安卓版本

11

### 哔哩漫游版本

ff79035031

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.65.0-b13987783

### 使用的框架和版本

@biliroaming_lspatch2频道发布的内置版

### 日志

[583309715_log.txt](https://github.com/yujincheng08/BiliRoaming/files/14046776/583309715_log.txt)

**Comment by JasonKhew96** [comment]
盲猜 `.ass` 字幕

**Comment by xifeng0** [comment]
> 盲猜 `.ass` 字幕

我也测试了以前正常的老番，也不显示，难道现在全面替换为ass了嘛

**Comment by zjns** [comment]
https://github.com/zjns/BiliRoamingX-integrations/commit/cecdd2a887bd6b718afaa5e3b110c8e3fafa3847 episode 对象加上 duration 字段就行了。
