### ISSUE TITLE
[Server] 请求添加服务器

### ISSUE THREAD

**Issue by CielNeko** [yujincheng08/BiliRoaming#1384]
### 联系方式

https://t.me/ciel_pm_bot

### 域名

bili.ayo.moe

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://bili.ayo.moe/donate

**Comment by yujincheng08** [comment]
不加了吗🧐

**Comment by CielNeko** [comment]
> 不加了吗🧐

可以加了 刚刚服务器出了点问题

**Comment by yujincheng08** [comment]
还在外面，回去就加

**Comment by yujincheng08** [comment]
Done.
