### ISSUE TITLE
[Feature] 希望能支持一下安卓老版本

### ISSUE THREAD

**Issue by QLJ9152** [yujincheng08/BiliRoaming#1385]
### 原因

有些老手机空间不够安装B站，就算是老版本占用的空间都很大，突然发现这个哔哩漫游才几百K，就想要装。可是哔哩漫游至少要安卓7.0以上，所以希望能够支持一下安卓老版本

### 功能简述

空间占用少，能正常看些视频就好了

### 功能逻辑

只希望能正常使用

**Comment by CJYKK** [comment]
啊，这是个Xposed模块，相当于B站的插件啦……
本身不提供功能的……

**Comment by QLJ9152** [comment]
我是傻逼

**Comment by CJYKK** [comment]
> 我是傻逼

不至于不至于

**Comment by CJYKK** [comment]
> 我是傻逼

要不要考虑下[https://github.com/10miaomiao/bilimiao2](bilimiao)？

**Comment by QLJ9152** [comment]
φ(゜▽゜*)♪，感谢
