### ISSUE TITLE
[Feature] 屏蔽未来版本中直播出现的计数弹幕

### ISSUE THREAD

**Issue by moyusumiu** [yujincheng08/BiliRoaming#1386]
### 原因

从7.65版本往后的粉红b站确定出现了和网页端同样的当弹幕池出现同样的弹幕时会提供复读按钮并在屏幕上将此弹幕居中置顶并计数，持续时间长极度影响观感

### 功能简述

能够将这个计数效果以及出现的“大家都在说”屏蔽，网页端那边的插件以及旧版本（7.50往前）会将这个复读弹幕按正常弹幕飘过只在后面显示“×n”

### 功能逻辑

将特殊弹幕(应该是直播间版的高级弹幕？）强制转化为正常弹幕

**Comment by yujincheng08** [comment]
减少遮挡，我觉得是好事。

**Comment by moyusumiu** [comment]
> 减少遮挡，我觉得是好事。

见仁见智吧，至少这个功能出现之后大伙更加乐意按复读动态效果停不下来，就会一直存在(计数是动态的，直到999没人按之前不会停下)

至于遮挡问题，我看直播和视频都是常态让弹幕只显示1/4的屏幕

**Comment by moyusumiu** [comment]
> > 减少遮挡，我觉得是好事。
> 
> 见仁见智吧，至少这个功能出现之后大伙更加乐意按复读动态效果停不下来，就会一直存在(计数是动态的，直到999没人按之前不会停下)
> 
> 至于遮挡问题，我看直播和视频都是常态让弹幕只显示1/4的屏幕

这功能就是视频那边的投票弹幕的移植(应该？效果一样的)
