### ISSUE TITLE
[Feature] 自定义access_key 仅对泰区api生效

### ISSUE THREAD

**Issue by BraveSail** [yujincheng08/BiliRoaming#139]
**原因**
泰区和国区/港澳台区的access_key不通用，目前在自定义选项里填写了泰区key则国区/港澳台区无法播放，鉴于目前泰区api风控加强，公共解析服务器被ban风险加大，如用户有观看泰区720p+的需求，则用户自己填写access_key相对安全。

**功能简述**
~~分别设置泰区、国区/港澳台区的access_key~~
自定义 access_key 仅对泰区api生效

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by skdy520** [comment]
h

**Comment by vvb2060** [comment]
我认为，应该先找到一个不强制替换access_key的东南亚区解析服务器。

**Comment by BraveSail** [comment]
> 我认为，应该先找到一个不强制替换access_key的东南亚区解析服务器。

[BiliRoaming-PHP-Server](https://github.com/david082321/BiliRoaming-PHP-Server)默认是不替换的，替换是可选选项，~~[我已经搭建了个不替换的](https://api.10ms.net)~~

现在的设置自定义key好像是全局的？ ~~如果能改成仅对泰区api生效也可以~~ 我还是改下标题吧
