### ISSUE TITLE
[Bug] 没有哔哩漫游设置

### ISSUE THREAD

**Issue by 526awd** [yujincheng08/BiliRoaming#1393]
### 问题描述

“我的”页面没有哔哩哔漫游设置

### 复现步骤

1.打开哔哩哔哩
2.点击我的

### 预期行为

有哔哩漫游设置按钮

### 实际行为

没有有哔哩漫游设置按钮

### 截图或录屏

https://github.com/yujincheng08/BiliRoaming/assets/62787078/b52fb5f4-97b1-4d7c-a3d4-8ddad2870e4d

### 安卓版本

7

### 哔哩漫游版本

1.70.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0

### 使用的框架和版本

原生xposed 89

### 其他

magisk 20.4

### 日志

[log_020840.txt](https://github.com/yujincheng08/BiliRoaming/files/14143763/log_020840.txt)

**Comment by yujincheng08** [comment]
不支持原版的 xposed 了
