### ISSUE TITLE
[Server] 请求从公共服务器列表中删除 @LiangBurs 的所有服务器

### ISSUE THREAD

**Issue by lhf277** [yujincheng08/BiliRoaming#1394]
### 联系方式

telegram: @YukinaHisazumi 

### 域名

cherry.icu.cnmobile.link , api.mahiro-kawaii.me

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by yujincheng08** [comment]
done
