### ISSUE TITLE
[Bug] 应用启动时报错

### ISSUE THREAD

**Issue by lsxuan12138** [yujincheng08/BiliRoaming#1395]
### 问题描述

如图
![Screenshot_20240204_012927_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/74349318/8d712897-c8fe-4d4a-a865-00f033bec498)
，在应用启动时显示错误信息

### 复现步骤

1. 打开哔哩哔哩

### 预期行为

正常启动

### 实际行为

出现错误信息

### 截图或录屏

![Screenshot_20240204_012927_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/74349318/f2315600-c81e-4c6c-a06f-f922590b9467)

### 安卓版本

鸿蒙4

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0（目前最新版，但是前面两三个版本就有这个问题了）

### 使用的框架和版本

太极14.0.6.11231507-10411

### 其他

目前只是显示错误信息，但是对实际功能貌似影响不大

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14152348/log.txt)
这里我看了下貌似是classnotfound导致的，但是具体原因应该还得作者大大看下

**Comment by lsxuan12138** [comment]
另外，这个问题在手机和平板上都有，（mate60pro和matepad pro12.6 2021）都是鸿蒙4，不过日志只抓了手机上的。

**Comment by yujincheng08** [comment]
修过了

**Comment by lsxuan12138** [comment]
所以这个修复会在新版本发布吗？新版本啥时候发布啊？
