### ISSUE TITLE
[Bug] AV号疑似溢出

### ISSUE THREAD

**Issue by AliasQli** [yujincheng08/BiliRoaming#1396]
### 问题描述

分享链接中出现负的AV号

### 复现步骤

1. 打开显示AV号和净化分享
2. 打开[AV1650249150](https://www.bilibili.com/video/av1650249150)
3. 选择分享->复制链接

### 预期行为

分享链接为 https://www.bilibili.com/video/av1650249150?p=1&unique_k=114514

### 实际行为

分享链接为 https://www.bilibili.com/video/av-497234498?p=1&unique_k=114514 ，1650249150 + 497234498 = 2147483648

（PS: 参数p和unique_k的实际意义是什么？）

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.2

### 使用的框架和版本

LSPosed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14152534/log.txt)

**Comment by yujincheng08** [comment]
修过了。
