### ISSUE TITLE
[Bug] 1.7.0 分享链接时产生出错误的AV号

### ISSUE THREAD

**Issue by AmazingRise** [yujincheng08/BiliRoaming#1399]
### 问题描述

AV1550075496
该视频的链接分享功能不正常

### 复现步骤

1. 打开该视频 AV1550075496
2. 点击分享链接
3. 生成出的链接的AV号为-597408152，为1550075496的相反数。
4. 【别不开心，我来带你一起蹦超欢乐的UK piano house消除烦恼-哔哩哔哩】 https://www.bilibili.com/video/av-597408152?p=1&unique_k=114514
5. 视频详情页面的AV号展示是正常的，只有分享链接时会产生错误的av号

### 预期行为

生成的链接应该包含正确的AV号
https://www.bilibili.com/video/av1550075496?p=1&unique_k=114514
1550075496

### 实际行为

实际生产出的链接中的AV号是正确AV号的相反数
https://www.bilibili.com/video/av-597408152?p=1&unique_k=114514
且链接无法正常访问

### 安卓版本

11

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.61.0

### 使用的框架和版本

Lsposed 1.8.6

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14174932/log.txt)

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/issues/1396
