### ISSUE TITLE
是否支持海外国内番

### ISSUE THREAD

**Issue by nightmare30** [yujincheng08/BiliRoaming#14]
你好 这个插件是否支持国外看国内番，我记得前段时间可以 现在又不行了 不知道是不是软件更新到最新版本没有兼容

**Comment by yujincheng08** [comment]
现在都只是。6.0最新版。

**Comment by yujincheng08** [comment]
现在都支持。6.0最新版。

**Comment by yujincheng08** [comment]
确实用户反映加载不出来。其实是UPOS的问题，看来我得研究一下怎么添加一个upos的设置。

**Comment by yujincheng08** [comment]
今天看了一下并不是UPOS的问题。问题出在b站后端不再识别`platform`这个字段，请求时候是请求PC的`playurl`，这时候国内的CDN会返回`403`（但是海外CDN不区分）。目前只能看@esterTion 能否给biliplus修复这个问题，或者看看kghost/bilibili-area-limit#16 能不能加入兼容了。

**Comment by nightmare30** [comment]
十分感谢作者 今天看了一下 好了

**Comment by nightmare30** [comment]
貌似又失效了，显示解析失败.
这是log 
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5222225/log.txt)

**Comment by nightmare30** [comment]
不好意思 我才看到群里的通知 打扰了

**Comment by yujincheng08** [comment]
@nightmare30 Biliplus炸了

**Comment by nightmare30** [comment]
感谢作者添加备用服务器 可以正常使用了
