### ISSUE TITLE
[BUG]泰区4月新番拿不到第二集的地址

### ISSUE THREAD

**Issue by AustraliaLetter** [yujincheng08/BiliRoaming#140]
**问题描述**
尝试观看[致不灭的你](https://bangumi.bilibili.com/anime/1002225/) 第二集的时候发现界面没有第二集，而泰国APP有第二集，如图。
从泰国APP拿到的地址是https://m.global.bilibili.com/play/1002225/10087791 ，按照 #130 中 @JasonKhew96 所说转换为 https://www.bilibili.com/bangumi/ep10087791/ 后访问，提示解析失败，资源不存在。

**复现步骤**
如何复现
1. 在评论区分别发布 https://bangumi.bilibili.com/anime/1002225/ 和 https://www.bilibili.com/bangumi/ep10087791 
2. 分别点击上述两链接
3. 前者的解析结果中没有第二集，后者解析失败

**截图**
点击文本框下面小长条可以上传文件
![IMG_20210420_115625](https://user-images.githubusercontent.com/82068485/115335765-71d53600-a1d0-11eb-92a3-9b92f3655398.jpg)
![IMG_20210420_120200](https://user-images.githubusercontent.com/82068485/115335777-7699ea00-a1d0-11eb-9f10-e5e8e3068f02.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.0.6
 - 哔哩漫游版本：1.4.3
 - 哔哩哔哩版本和版本号：6.22.5
 - 使用的框架和版本：EdXposed v0.5.2.2_4683
 - 其他：致不灭的你

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6340579/log.txt)

**Comment by JasonKhew96** [comment]
@AustraliaLetter 柒默 服务器不支持解析 ep，请用 ss

**Comment by AustraliaLetter** [comment]
> @AustraliaLetter 柒默 服务器不支持解析 ep，请用 ss
> 
> EDIT: 诶，缓存好像有点问题，我问问
> EDIT2: 你可以换另一个代理服务器。。。

@JasonKhew96 我这里只有 https://哔哩.ink 可以解析，https://api.qiu.moe 和 https://biligo.org 解析都会失败。。

**Comment by JasonKhew96** [comment]
> > @AustraliaLetter 柒默 服务器不支持解析 ep，请用 ss
> > 
> > EDIT: 诶，缓存好像有点问题，我问问
> > EDIT2: 你可以换另一个代理服务器。。。
> 
> @JasonKhew96 我这里只有 https://哔哩.ink 可以解析，https://api.qiu.moe 和 https://biligo.org 解析都会失败。。

@AustraliaLetter 那等 柒默 修 🙃，不然直接用东南亚原版 APP 看

**Comment by AustraliaLetter** [comment]
@JasonKhew96 现在第二集突然有了，是因为服务器修好了么？

**Comment by JasonKhew96** [comment]
> @JasonKhew96 现在第二集突然有了，是因为服务器修好了么？

缓存刷新了，因为服务器不会一直请求，缓存减低被风控的风险（~~白嫖怪太多~~）
