### ISSUE TITLE
[Bug] bv转av号连接出现错误产生负数

### ISSUE THREAD

**Issue by RimuruChan** [yujincheng08/BiliRoaming#1401]
### 问题描述

尝试分享连接时出现了负数

### 复现步骤

BV1FU421Z7Ff的视频
打开分享选择连接分享
复制出来的链接是负数
【当黍黍上岛后，怪物就像：-哔哩哔哩】 https://www.bilibili.com/video/av-647462574?p=1&unique_k=114514

### 预期行为

应该是正常的av号

### 实际行为

av号出现了负数

### 安卓版本

14

### 哔哩漫游版本

62ff4b9cfb(1304)

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.62.0

### 使用的框架和版本

LSPosed 1.9.0

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14203499/log.txt)

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/issues/1396

**Comment by RimuruChan** [comment]
#1388
