### ISSUE TITLE
哔哩哔哩7.66.0版本未开启任何功能便在启动时出现报错[Bug] 

### ISSUE THREAD

**Issue by M100816** [yujincheng08/BiliRoaming#1410]
### 问题描述

哔哩哔哩7.66.0版本未开启任何功能便在启动时出现报错
哔哩漫游：出现错误
java.Lang,CLassNotFoundException:
Com,bilibiLi,search.api.SearchRank
部分功能可能失效。falG.bzfHPmCJ.unY cW.tf.XposedHelpers.findCLass(Unknown Sokrce:l2)
biliroaming.69.b(SourdeFile:344)
me,iacn,biliroaming.XposedInit.a(SourceFi
le:9)
biliroaming.sj.beforeHookedMethod(Sourc
eFile:625)：
falG,bzfHPmCJ.unYcW.tf.XpoSedBrdge$L egacyApiSupport.handleBefore(Unknown Source:24)
J,callback(Unknown Source:179)
LSPHooker_.callAppLica
tionOnCreate(Unknown
Source:|l)
android.app.ActivityThread.handleBindAp
plication(ActivityThread.java:7363)
android.app.ActivityThread.-$
$Nest$mhandleBindAppLication(Unknown
Source:0)
android.app.ActivityThread$H.handleMes
sage(ActivityThread.java:2393)
androidl.os.Handler,dispatchMessage(Han
dLer.java:106)
android,os.Looper.LoopOnce(Looper.java:2
22)
android.os.Loopet.toop(Loopehajapa:314)android.app.ActivityThread,main(Activit yThread.java:8587)
jara.Lang.reflect.Method,invoke(Native
Method)
Com,android,internal.os.RuntimeInit$Met hodAndArgsCaller.run(RuntimeInit.java.5 65)
Com,android.internaL.os.ZygoteInit.maìn(
ZygoteInit.java:1081)

### 复现步骤

打开B站7.66.0版本
首页出现报错

### 预期行为

正常运行

### 实际行为

哔哩漫游：出现错误
java.Lang,CLassNotFoundException:
Com,bilibiLi,search.api.SearchRank
部分功能可能失效。falG.bzfHPmCJ.unY cW.tf.XposedHelpers.findCLass(Unknown Sokrce:l2)
biliroaming.69.b(SourdeFile:344)
me,iacn,biliroaming.XposedInit.a(SourceFi
le:9)
biliroaming.sj.beforeHookedMethod(Sourc
eFile:625)：
falG,bzfHPmCJ.unYcW.tf.XpoSedBrdge$L egacyApiSupport.handleBefore(Unknown Source:24)
J,callback(Unknown Source:179)
LSPHooker_.callAppLica
tionOnCreate(Unknown
Source:|l)
android.app.ActivityThread.handleBindAp
plication(ActivityThread.java:7363)
android.app.ActivityThread.-$
$Nest$mhandleBindAppLication(Unknown
Source:0)
android.app.ActivityThread$H.handleMes
sage(ActivityThread.java:2393)
androidl.os.Handler,dispatchMessage(Han
dLer.java:106)
android,os.Looper.LoopOnce(Looper.java:2
22)
android.os.Loopet.toop(Loopehajapa:314)android.app.ActivityThread,main(Activit yThread.java:8587)
jara.Lang.reflect.Method,invoke(Native
Method)
Com,android,internal.os.RuntimeInit$Met hodAndArgsCaller.run(RuntimeInit.java.5 65)
Com,android.internaL.os.ZygoteInit.maìn(
ZygoteInit.java:1081)
跳

### 截图或录屏

![1000020169](https://github.com/yujincheng08/BiliRoaming/assets/138355736/7a8a3d56-0437-4fb8-b191-9d11a46d62ce)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.66.0

### 使用的框架和版本

lsp1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14325612/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/14325613/old_log.txt)

**Comment by yujincheng08** [comment]
修过的了
