### ISSUE TITLE
[Feature] 移除直播间某些分区的马赛克遮盖

### ISSUE THREAD

**Issue by mon030** [yujincheng08/BiliRoaming#1411]
### 原因

例如minecraft分区，屏幕的左下角会有马赛克模糊遮盖（非主播自行添加）。
![IMG_20240224_192223](https://github.com/yujincheng08/BiliRoaming/assets/42599449/656670fb-d001-4fee-a4b8-21f941739b0d)
![IMG_20240224_192238](https://github.com/yujincheng08/BiliRoaming/assets/42599449/22b97144-f014-4531-85c0-74c2a45c8951)
所使用的b站客户端版本 安卓7.67.0

### 功能简述

移除直播间一些分区的马赛克遮盖

### 功能逻辑

马赛克似乎是在用户端添加的，见实现参考的视频。

### 实现参考

【我的世界直播强制模糊？网页端还能看到无码直播吗【半滴故事会】-哔哩哔哩】 https://www.bilibili.com/video/av1100306895?p=1

**Comment by Kal-tsit63** [comment]
实测，7.65版本以上会添加马赛克模糊，不包括7.65版本本身
