### ISSUE TITLE
最新1.7.0版本依旧报错java.lang.ClassNotFoundException:com.bilibili.search.api.SearchRank[Bug] 

### ISSUE THREAD

**Issue by Herobetrine** [yujincheng08/BiliRoaming#1412]
### 问题描述

打开7.67.0版本哔哩哔哩稳定出现java.lang.ClassNotFoundException:com.bilibili.search.api.SearchRank

### 复现步骤

打开哔哩哔哩稳定触发

### 预期行为

正常进入首页

### 实际行为

出现报错java.lang.ClassNotFoundException:com.bilibili.search.api.SearchRank

### 截图或录屏

![Screenshot_2024-02-25-09-17-02-130_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/91196386/59827ea4-9363-4ba3-b545-c87ea91bac81)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.67.0

### 使用的框架和版本

1.9.2(7024)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14394960/log.txt)

**Comment by yujincheng08** [comment]
已修复
