### ISSUE TITLE
[Bug]去你大爷的小程序功能出现错误 

### ISSUE THREAD

**Issue by rain-0** [yujincheng08/BiliRoaming#1415]
### 问题描述

观察到开启时分享链接中的bv号转av号错误，关闭该功能后分享链接正常
例如https://www.bilibili.com/video/BV1bv421r7Jb 分享链接为https://www.bilibili.com/video/av-696411775?p=1&unique_k=114514 指向出错页面，去除av号中-与？后字符后会指向另一个视频

### 复现步骤

打开任意视频，点击右上角三点，复制链接

### 预期行为

复制出指向正确视频的链接

### 实际行为

复制出指向错误页面的链接

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.18.2

### 使用的框架和版本

Lsposed1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14459239/log.txt)

**Comment by yujincheng08** [comment]
修过啦
