### ISSUE TITLE
使用官方“暂停记录历史”api实现选择性保存历史

### ISSUE THREAD

**Issue by boxjohn** [yujincheng08/BiliRoaming#1416]
### 原因

有一些不那么健康的视频，不想留下历史记录，看过就好了，也不会再回去看（防止女友查手机）

### 功能简述

使用官方“暂停记录”历史api实现根据自定义筛选条件决定要不要保存该视频历史

### 功能逻辑

使用官方“暂停记录历史”api实现：根据自定义的筛选条件决定要不要保存该视频历史，离开该视频后再重新打开历史记录功能

### 实现参考

开源项目pilipala[https://github.com/guozhigq/pilipala](url)的历史记录中有暂停/开始历史记录的功能，估计是抓的网页端哔哩哔哩的接口

**Comment by david082321** [comment]
app其实有个手动删除指定历史记录的功能。

进入历史记录后，右上角管理，然后多选不要的视频，删除。

另外，新版本B站内置帐号切换功能，可以多个号使用。
