### ISSUE TITLE
[Bug] 看视频会出现闪退到上个界面的bug！

### ISSUE THREAD

**Issue by qwe6781331** [yujincheng08/BiliRoaming#1422]
### 问题描述

偶尔看视频会突然卡了一下，大概1秒后闪退到上个界面，然后视频历史记录也没有

### 复现步骤

观看视频
出现卡顿不到两秒
闪退到上个界面

### 预期行为

正常情况视频卡顿

### 实际行为

突然出现卡顿，然后闪退到上个界面

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

[LSPatch] [1.7.0] [7.50.0] 

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14588332/log.txt)

**Comment by yujincheng08** [comment]
这个是b站自己的问题。等下个版本发新的内置版。
