### ISSUE TITLE
[Bug] 每次启动bilibili必然出现一下情况

### ISSUE THREAD

**Issue by yangtong2011** [yujincheng08/BiliRoaming#1426]
### 问题描述

每次启动bilibili必然出弹窗

### 复现步骤

启动bilibili

### 预期行为

进入b站首页

### 实际行为

出现弹窗

### 截图或录屏

![Screenshot_2024-03-15-21-37-01-921_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/88962048/52a7d524-cada-4cdd-aa53-2f4a678dc886)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.69.0

### 使用的框架和版本

LSPosed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14616190/log.txt)

**Comment by yujincheng08** [comment]
修过了。
