### ISSUE TITLE
[Bug] 净化连接BV转换AV异常

### ISSUE THREAD

**Issue by XiaoYangTech** [yujincheng08/BiliRoaming#1429]
### 问题描述

BV1W2421M7pV 这个视频
在模块开启净化链接以后分享，转的AV号有问题，会带一个“-”，然后点开链接404

### 复现步骤

BV1W2421M7pV 这个视频，在模块开启净化链接以后分享，复制链接，然后打开链接

### 预期行为

转的AV号打开以后直接就是视频

### 实际行为

转的AV号有问题，会带一个“-”，然后用链接打开报错404

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 使用的框架和版本

LSPosed 1.9.2 Zygisk

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14623340/log.txt)

**Comment by yujincheng08** [comment]
修过了，等下个版本
