### ISSUE TITLE
[Bug] 勾选提示模块运行信息会导致报错

### ISSUE THREAD

**Issue by CxZMoE** [yujincheng08/BiliRoaming#1432]
### 问题描述

勾选提示模块运行信息会导致报错

### 复现步骤

1. 勾选
![微信图片_20240319162912](https://github.com/yujincheng08/BiliRoaming/assets/39299424/3dd6f568-b7e4-4057-8179-dda3466d5ed5)

2. 重启报错
![微信图片_20240319162931](https://github.com/yujincheng08/BiliRoaming/assets/39299424/da50e46f-1bbb-4653-a857-8282d1b0cd18)

### 预期行为

不报错

### 实际行为

报错了

### 安卓版本

Android 14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.69.0

### 使用的框架和版本

LSPosed 1.9.2

### 其他

Magisk 27000

### 日志

[1_log.txt](https://github.com/yujincheng08/BiliRoaming/files/14647722/1_log.txt)

**Comment by yujincheng08** [comment]
修过了

**Comment by skytianle666** [comment]
用ci版。
