### ISSUE TITLE
[Bug] 分享链接时av号为负,疑似int数值溢出

### ISSUE THREAD

**Issue by AcdeAsdff** [yujincheng08/BiliRoaming#1433]
### 问题描述

在试图分享某一视频链接时得到如下信息

【电影《雪豹》定档4月3日，万玛才旦作品展人豹矛盾冲突-哔哩哔哩】 https://www.bilibili.com/video/av-195560374?p=1&unique_k=114514

显然打不开,因为有av-195560374
但注意到简介内av号为正(AV1951923274)
使用该av号替换,得到相应视频
(注意到 1951923274 - (-195560374) == 2147483648)

### 复现步骤

1.打开b站手机端点击视频(av号可能需要足够大,如AV1951923274)
2.点击右上角三个点分享,选择复制链接

### 预期行为

得到如下信息:

【电影《雪豹》定档4月3日，万玛才旦作品展人豹矛盾冲突-哔哩哔哩】 https://www.bilibili.com/video/av1951923274?p=1&unique_k=114514

### 实际行为

得到如下信息:

【电影《雪豹》定档4月3日，万玛才旦作品展人豹矛盾冲突-哔哩哔哩】 https://www.bilibili.com/video/av-195560374?p=1&unique_k=114514

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.13.0

### 使用的框架和版本

LSPosed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14721501/log.txt)

**Comment by AcdeAsdff** [comment]
没看源码，也许可以换一波biginteger？
干脆把简介那个数值拿来好了，那个是对的

**Comment by yujincheng08** [comment]
修过啦，等发布新版
