### ISSUE TITLE
[BUG]现在换成港澳台有问题了。。

### ISSUE THREAD

**Issue by AustraliaLetter** [yujincheng08/BiliRoaming#144]
**问题描述**
发生了什么情况？有什么现状？
打开港澳台的番剧一直是加载中的状态
我试了好几个了，都这样。泰国番剧反而没问题。。
换过upos服务器，换过解析服务器。同样的解析服务器在脚本中就可以正常使用。

**复现步骤**
如何复现
1. 打开任意港澳台番剧

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.0.6
 - 哔哩漫游版本：1.4.3
 - 哔哩哔哩版本和版本号：6.23.0
 - 使用的框架和版本：EdXposed v0.5.2.2_4683
 - 其他：影宅

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6370976/log.txt)

话说为什么出问题的总是我啊。。是我有问题么。。
不好意思打扰大家了……

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/61d0addc4e9356c47a0d46eac2d0988676c177a2

这能怪谁呢？更新客户端不留意模块更新。还不是怪你自己。

**Comment by AustraliaLetter** [comment]
> [61d0add](https://github.com/yujincheng08/BiliRoaming/commit/61d0addc4e9356c47a0d46eac2d0988676c177a2)
> 
> 这能怪谁呢？更新客户端不留意模块更新。还不是怪你自己。

@yujincheng08 代码的更改没有体现在Releases中。
我以为模块更新地址是 https://github.com/yujincheng08/BiliRoaming/releases/latest 中，更新地址中的最新版本是 v1.4.3，更新于4月3日。修复了影响正常使用的问题后不发布更新，这是谁的问题？
其实我很好奇，更新了代码后为什么不发布呢？是因为更新日志不好写吗？

**Comment by yujincheng08** [comment]
> > [61d0add](https://github.com/yujincheng08/BiliRoaming/commit/61d0addc4e9356c47a0d46eac2d0988676c177a2)
> > 这能怪谁呢？更新客户端不留意模块更新。还不是怪你自己。
> 
> @yujincheng08 代码的更改没有体现在Releases中。
> 我以为模块更新地址是 https://github.com/yujincheng08/BiliRoaming/releases/latest 中，更新地址中的最新版本是 v1.4.3，更新于4月3日。修复了影响正常使用的问题后不发布更新，这是谁的问题？
> 其实我很好奇，更新了代码后为什么不发布呢？是因为更新日志不好写吗？

:) 我不发就不发，还成我问题了？升级出问题了赖我？爱用用不用滚好吧。
