### ISSUE TITLE
[Bug] 长按简介自由复制失效

### ISSUE THREAD

**Issue by huoyan1231** [yujincheng08/BiliRoaming#1442]
### 问题描述

长按简介无任何反应

### 复现步骤

长按任意视频简介

### 预期行为

弹出复制框

### 实际行为

无复制框弹出

### 安卓版本

14

### 哔哩漫游版本

b55430ead6

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.40.0

### 使用的框架和版本

lsposed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14895677/log.txt)

**Comment by yujincheng08** [comment]
7.40 版本太低了

**Comment by huoyan1231** [comment]
> 7.40 版本太低了

我更新到7.60也不行。。
最低要求版本是多少

**Comment by huoyan1231** [comment]
7.70版本也不行
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/14903835/log.txt)

**Comment by yujincheng08** [comment]
7.70 亲测没问题呀

**Comment by huoyan1231** [comment]
> 7.70 亲测没问题呀

重新安装了模块，还是不行
