### ISSUE TITLE
［BUG］最新版本提示部分功能失效

### ISSUE THREAD

**Issue by LINKlang** [yujincheng08/BiliRoaming#1447]
### 问题描述

如题，更新完后，每次打开b站都会提示
![Screenshot_2024-04-21-01-10-57-99_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/116951234/e1343de1-6595-4a4e-9d19-9bec72eb1f08)

### 复现步骤

更新
打开b站

### 预期行为

提示正常运行

### 实际行为

提示部分功能失效

### 截图或录屏

![Screenshot_2024-04-21-01-10-57-99_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/116951234/0c8479da-d549-4fa6-8d73-b9204c067983)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.75.0

### 使用的框架和版本

LSP 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15048720/log.txt)

**Comment by yujincheng08** [comment]
修过了

**Comment by LINKlang** [comment]
> 修过了

请问如何解决，是需要更新哔哩漫游吗，但是我看到release页面最新版本也是1.7.0

**Comment by yujincheng08** [comment]
先用 CI 版吧，最近有点忙有些 bug 还没修
