### ISSUE TITLE
[Feature] 希望增加调整b站文字大小的选项

### ISSUE THREAD

**Issue by Dome-World** [yujincheng08/BiliRoaming#1448]
### 原因

在很多的设备上(如小米)，b站文字太小，且自身不带调整大小，用起来很难受，所以有大量的人都在使用放大ui版7.2.0，但是该版本没有漫游，所以希望漫游本身增加这个功能

### 功能简述

可以有一个设置项，设置字号

### 功能逻辑

点击设置字号

### 实现参考

有个放大ui版7.2.0，长按我的放大，酷安评论区有

**Comment by yujincheng08** [comment]
这种应该让叔叔亲自弄关怀模式
