### ISSUE TITLE
[Server] bili.ayo.moe 全区域解析已修复

### ISSUE THREAD

**Issue by CielNeko** [yujincheng08/BiliRoaming#1449]
### 联系方式

t.me/CielZero

### 域名

bili.ayo.moe

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

afdian.net/a/CielNeko

**Comment by yujincheng08** [comment]
Done
