### ISSUE TITLE
[Bug] bilibili国际版最新版3.19.0“哔哩漫游：出现错误”

### ISSUE THREAD

**Issue by BitsAstro** [yujincheng08/BiliRoaming#1450]
### 问题描述

启动时发生了错误

### 复现步骤

打开软件时报错

### 预期行为

应该正常运行

### 实际行为

错误

### 截图或录屏

![Screenshot_2024-04-29-21-50-18-254_com bilibili app in](https://github.com/yujincheng08/BiliRoaming/assets/138313793/4df3c27e-4887-450d-8b61-47c37ead6fec)

### 安卓版本

11

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.19.0

### 使用的框架和版本

lsposed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15150199/log.txt)

**Comment by yujincheng08** [comment]
修过了，等下一个版本或者用 CI 版。
