### ISSUE TITLE
[Bug] 在play3.19.0版本启动时报错，卡顿。疑似需适配最新的play3.19.0版本

### ISSUE THREAD

**Issue by dustxn** [yujincheng08/BiliRoaming#1451]
### 问题描述

启动时报告出现错误，部分功能可能失效。错误代码很长（满屏幕）
app使用疑似卡顿，具体失效功能有待确认。

### 复现步骤

打开B站app（3.19.0版本），触发率100%

### 预期行为

不报错，无卡顿。

### 实际行为

报错，卡顿。

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.19.0

### 使用的框架和版本

LSPosed 1.9.2

### 日志

日志：
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15150543/log.txt)

**Comment by yujincheng08** [comment]
启动时的错误已经修复，可以尝试 CI 版，或者等下个版本。

**Comment by dustxn** [comment]
> 启动时的错误已经修复，可以尝试 CI 版，或者等下个版本。

你好，请问如何获得CI 版
我不会把源代码变成apk文件

**Comment by yujincheng08** [comment]
https://t.me/biliroaming
