### ISSUE TITLE
[Feature] 去除广告

### ISSUE THREAD

**Issue by aaa-qwq-123** [yujincheng08/BiliRoaming#1455]
### 原因

广告真的很烦

### 功能简述

去除开屏广告
去除青少年弹窗
去除首页顶部搜索栏旁边的广告
去除 我的 页面大会员横幅广告
谢谢😊

### 功能逻辑

嗯，直接把广告扣掉就行了不需要交互的吧？

### 实现参考

。这我怎么知道

**Comment by aaa-qwq-123** [comment]
啊，去青少年弹窗已经有了，不好意思

**Comment by david082321** [comment]
你说的全都有了

**Comment by Eric-lHHI** [comment]
> 你说的全都有了

国际版 我的 大会员横幅 和 我的NFT 可以去掉吗，怎么没找到这个功能
