### ISSUE TITLE
[Server] 只开放泰国，但有购买BG会员，能看4K画质

### ISSUE THREAD

**Issue by david082321** [yujincheng08/BiliRoaming#1456]
### 联系方式

Github @david082321

### 域名

bilibili.page

### 支持地区

- [ ] 中国大陆
- [ ] 港澳
- [ ] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by yujincheng08** [comment]
Done
