### ISSUE TITLE
[Bug] 评论区自由复制失效

### ISSUE THREAD

**Issue by Qing-Novel** [yujincheng08/BiliRoaming#1460]
### 问题描述

最新版本下视频评论区无法自由复制了，视频简介依旧可以

### 复现步骤

1、打开去除长按复制和长按自由复制
2、随便打开一个视频并打开评论区
3、长按即可
![Screenshot_20240506_214554_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/136884931/6d43659a-56a8-40fc-ba59-f6de90da3fc6)
![Screenshot_20240506_214640_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/136884931/3d38a85e-f8a6-4b82-9c09-cdeb5b2f14c9)
![Screenshot_20240506_214704_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/136884931/cbef7a0e-fad2-4a65-b759-24fa5161b01c)

https://github.com/yujincheng08/BiliRoaming/assets/136884931/e60d2980-1ddb-4016-a451-bbfa8194c023

### 预期行为

评论区长按弹出自由复制对话框

### 实际行为

评论区长按弹出软件默认复制栏
![Screenshot_20240506_214704_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/136884931/c2a6ac9e-6ba1-486e-bd99-14e057b6618f)

### 安卓版本

10和12

### 哔哩漫游版本

e3c23ff23

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 使用的框架和版本

LSPosed 1.8.2

### 日志

已上传相关日志
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15221519/log.txt)

**Comment by mczph** [comment]
实测国际版最新版也出现相同问题，需退回至3.18.2版本

**Comment by MengNianxiaoyao** [comment]
> 实测国际版最新版也出现相同问题，需退回至3.18.2版本

3.19.0没这个问题，就是最新版有

**Comment by Bluky-BlueSky** [comment]
目前粉版b站最新版8.4.0依然存在这个问题（漫游版本：8e963f3acf)，评论区长按自由复制失效（长按唤起b站自带评论区菜单），视频简介区长按自由复制依然有效
