### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiaoye1028** [yujincheng08/BiliRoaming#1467]
### 问题描述

今天重启手机，打开比站首页突然弹报错，卸载重装也没用

### 复现步骤

打开比站报错

### 预期行为

正常没有报错

### 实际行为

实际报错

### 截图或录屏

![Screenshot_2024-05-18-00-07-48-629_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/66059004/9c0666eb-9f75-439a-96a7-3f65bce6a9f2)
![Screenshot_2024-05-18-00-26-38-522_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/66059004/3646564f-f2b4-4758-928d-d9bfa34c4d70)

### 安卓版本

14

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0 

### 使用的框架和版本

LSPosed 1.9.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15354435/log.txt)
[1_log.txt](https://github.com/yujincheng08/BiliRoaming/files/15354436/1_log.txt)

**Comment by skytianle666** [comment]
新版哔哩哔哩APP更改了一些东西导致模块找不到了，CI版早已修复，请使用CI版而不是正式版
