### ISSUE TITLE
[Bug] 搜索非大陆地区番剧功能不可用

### ISSUE THREAD

**Issue by EmptyDreams** [yujincheng08/BiliRoaming#1475]
### 问题描述

如图所示，搜索港澳台和泰区番剧时不显示搜索结果（b站泰区是买了这个番剧的）

我更换了好几个解析服务器到均无法解决问题，同时我从主页港澳台入口点番剧看是能够正常播放、加载评论和弹幕的。

### 复现步骤

1. 打开其它地区番剧解析并设置解析服务器
2. 打开其它地区番剧搜索功能
3. 随便搜索一个番剧

### 预期行为

应该显示搜索结果

### 实际行为

无论搜索什么都什么都不显示

### 截图或录屏

![Screenshot_20240526_092542_tv danmaku bili](https://github.com/yujincheng08/BiliRoaming/assets/44894906/5322634b-e25b-47ce-a57d-21440d6e3f29)

### 安卓版本

12

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 使用的框架和版本

LSPatch 0.6(框架版本 1.9.2)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/15445729/log.txt)

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/7a2ace204b97e6efd49910b91adef64d417ea1e4

**Comment by EmptyDreams** [comment]
> [7a2ace2](https://github.com/yujincheng08/BiliRoaming/commit/7a2ace204b97e6efd49910b91adef64d417ea1e4)

就是说这个问题已经修复了但是暂未发版是吗？

**Comment by yujincheng08** [comment]
对
