### ISSUE TITLE
[Feature] 希望能够在首页推荐中自定义屏蔽时长小于xx分钟的视频

### ISSUE THREAD

**Issue by NianBroken** [yujincheng08/BiliRoaming#1476]
### 原因

我不想看低质量短视频

### 功能简述

例如屏蔽总时长小于2分钟的视频

### 功能逻辑

none

**Comment by yujincheng08** [comment]
早就有了

**Comment by NianBroken** [comment]
> 早就有了

@yujincheng08 我好像并没有在设置中找到相对于的入口，该如何开启这个功能呢？
