### ISSUE TITLE
无法搜索到港澳台番剧[BUG]

### ISSUE THREAD

**Issue by piexian** [yujincheng08/BiliRoaming#148]
**问题描述**
发生了什么情况？有什么现状？
港澳台番剧搜索不到但是已经追番的还能看到也能播放

**复现步骤**
如何复现
1. 打开...哔哩哔哩
2. 点击...搜索港澳台
3. 出现...状况番剧为空

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2021-05-03-02-31-33-193_tv danmaku bili](https://user-images.githubusercontent.com/64474352/116823672-56ace380-ab4b-11eb-89d2-21d1acf0d871.jpg)
![Screenshot_2021-05-03-02-32-45-809_tv danmaku bili](https://user-images.githubusercontent.com/64474352/116823677-59a7d400-ab4b-11eb-825c-2764219b77c2.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI12.5
 - 哔哩漫游版本：1.4.3
 - 哔哩哔哩版本和版本号：6.23.5（如概念版6.2.3）
 - 使用的框架和版本：lsp1.3.5（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
b 站屏蔽了

**Comment by lrhtony** [comment]
建议关注哔哩哔哩番剧出差官号，在稿件里搜
