### ISSUE TITLE
[Bug] 打开哔哩哔哩报错

### ISSUE THREAD

**Issue by litianyuhehe** [yujincheng08/BiliRoaming#1483]
### 问题描述

开屏报错误代码

### 复现步骤

打开哔哩哔哩 出现错误代码

### 预期行为

开屏不报错误代码

### 实际行为

开屏报错误代码

### 截图或录屏

![Screenshot_2024-06-12-11-22-13-94_149003a2d400f6adb210d7e357a3a646](https://github.com/yujincheng08/BiliRoaming/assets/29541117/cee94dd3-3ab1-4cb0-b3ef-d56717904b8c)

### 安卓版本

14

### 哔哩漫游版本

tg最新测试版 eb78fe4e18

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0

### 使用的框架和版本

1.9.3 mod 7295

### 其他

magisk alpha 27002

### 日志

[log.txt](https://github.com/user-attachments/files/15797986/log.txt)

**Comment by yujincheng08** [comment]
修过了，等发版
