### ISSUE TITLE
[Server] 请求更改hk.xifeng.cf服务域名,原服务不可用了

### ISSUE THREAD

**Issue by xifeng0** [yujincheng08/BiliRoaming#1486]
### 联系方式

tg:https://t.me/xifeng040

### 域名

bili.xifeng.cf

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

	https://afdian.net/a/xifeng04

**Comment by yujincheng08** [comment]
Done
