### ISSUE TITLE
强迫症来提个意见吧，望采纳。

### ISSUE THREAD

**Issue by 742903746** [yujincheng08/BiliRoaming#15]
希望自定义启动图片能选择不隐藏“bilibili”图标还有自定义主题颜色能保留当前装扮的主题。

**Comment by yujincheng08** [comment]
启动图片自己P个“bilibili”图标就好，不想弄太多开关。当前装扮的主题是啥？这个自定义主题颜色相当于弄了一个和其他主题独立的新主题。
