### ISSUE TITLE
[Bug] 无法加载“稍后再看”

### ISSUE THREAD

**Issue by Drangleic71** [yujincheng08/BiliRoaming#1500]
### 问题描述

[LSPatch] [1.7.0] [7.50.0] 哔哩哔哩.apk无法加载“稍后再看”，提示加载出错，请稍后再试
根据B站网友的反馈，该BUG可能跟APP客户端版本有关系
https://www.bilibili.com/read/cv35315056/?jump_opus=1

### 复现步骤

点击“稍后再看”，提示加载出错，请稍后再试

### 预期行为

加载“稍后再看”中的视频

### 实际行为

点击“稍后再看”，提示加载出错，请稍后再试

### 截图或录屏

![Screenshot_2024-07-14-14-17-50-250_tv danmaku bili](https://github.com/user-attachments/assets/201a0575-6ad9-4d3a-b31b-addb3f889186)

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

无

### 日志

[log.txt](https://github.com/user-attachments/files/16215830/log.txt)

**Comment by B1aK2** [comment]
B站改了“稍后再看”视频上限，以前是100个，现在把100个的上限移除了， 如果你“稍后再看”的视频数量超过了100个，就不能正常加载出来了，网页端上面删到100个以下就行了。

**Comment by zwr1036989059** [comment]
这边也在测试，添加特定视频后就会出现稍后再看的功能无法使用，这边测试的版本为1.6.4（6.74.0）及1.6.11（7.30.0），均会出现此问题，测试视频包括BV1KzaUeWEaQ，BV1abaUecEyp，BV1UqaDeaEdJ，BV1xyaDeZEjX
暂时没有特定出添加后会导致出现问题的视频的共同点
解决方案为将出现问题的视频从稍后再看中移除即可

**Comment by B1aK2** [comment]
> 这边也在测试，添加特定视频后就会出现稍后再看的功能无法使用，这边测试的版本为1.6.4（6.74.0）及1.6.11（7.30.0），均会出现此问题，测试视频包括BV1KzaUeWEaQ，BV1abaUecEyp，BV1UqaDeaEdJ，BV1xyaDeZEjX 暂时没有特定出添加后会导致出现问题的视频的共同点 解决方案为将出现问题的视频从稍后再看中移除即可
> 
> 根据主楼中问题描述的说法，想彻底解决此问题可能需要将漫游使用的哔哩哔哩版本进行升级？

需要自己打包最新版本的LSPatch版的哔哩哔哩客户端，这个就B站对旧版本客户端不兼容的问题。

**Comment by Remtg** [comment]
是稍后再看中某个视频有问题，移除问题视频之后就可以正常使用了，问题视频没有特征，找不到可以先给稍后在看中的视频做个备份，全部删除，然后重启即可

**Comment by JXing233** [comment]
B站改了AV号的逻辑 现在是15位的 如果你把15位av号的视频添加在稍后再看 就会出现这个情况

**Comment by CodePwn2021** [comment]
使用的哔哩哔哩版本过于最旧最冷

**Comment by CodePwn2021** [comment]
> > 使用的哔哩哔哩版本过于最旧最冷
> 
> LSPatch还有计划继续更新吗，目前链接里最新的LSPatch版哔哩哔哩客户端还是7.50.0

模块和第三方出的打包版有什么关系？

**Comment by CodePwn2021** [comment]
没注意到。。。抱歉
但这个包使用的LSPatch版本确实不支持Android 15
