### ISSUE TITLE
[Feature] 大会员每日领取10经验

### ISSUE THREAD

**Issue by TaiMiao** [yujincheng08/BiliRoaming#1502]
### 原因

建议添加大会员每日领取10经验的功能，因为明天都领比较麻烦，而且容易忘
![image](https://github.com/user-attachments/assets/08609690-fb84-4306-9261-3734cae06912)

### 功能简述

同上

### 功能逻辑

同上

**Comment by yujincheng08** [comment]
#1425

不打算做
