### ISSUE TITLE
[Bug] 评论区图片无法点开全屏显示

### ISSUE THREAD

**Issue by MA-KURO** [yujincheng08/BiliRoaming#1504]
### 问题描述

使用哔哩漫游时，评论区图片无法点开全屏显示

### 复现步骤

打开评论区，点击评论区图片

### 预期行为

图片展开为全屏显示

### 实际行为

无反应

### 安卓版本

12

### 哔哩漫游版本

652d6dce61

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.20

### 使用的框架和版本

1.9.2(7024)

### 日志

[log (1).txt](https://github.com/user-attachments/files/16436450/log.1.txt)

**Comment by WHATHBER** [comment]
我也遇到了，感觉得回退版本了，但是新版b站UI还挺好用的

**Comment by yinzhefuyun** [comment]
关闭【笔记图片长按预览保存】看看会不会会不会缓解

**Comment by CodePwn2021** [comment]
fixed in #1566
