### ISSUE TITLE
[Bug] 分享链接转为av号出现错误，av号成了负的

### ISSUE THREAD

**Issue by XEpicLi** [yujincheng08/BiliRoaming#1508]
### 问题描述

视频原始bv：BV1QT421Y78p，简介内转为的av号为AV1705552411，且能正常搜到。分享链接中内容为：
“【啊？逆天！11本平16本！【全网首发】-哔哩哔哩】 https://www.bilibili.com/video/av-441931237?p=1&unique_k=114514”，不能正常打开，且可看到av号为负。av-441931237显然无法识别，av441931237（去掉负号）为一东南亚地区节目。见图片。
![Screenshot_2024-08-07-09-03-37-543_tv danmaku bili](https://github.com/user-attachments/assets/fb17570c-9100-4155-85fd-b297fa736789)
![Screenshot_2024-08-07-09-03-50-613_tv danmaku bili](https://github.com/user-attachments/assets/779690e6-8191-4df5-b1fb-a44da62d3876)
![Screenshot_2024-08-07-09-04-13-879_tv danmaku bili](https://github.com/user-attachments/assets/595463a8-48a9-4849-9c80-0cfd48114cda)
![Screenshot_2024-08-07-09-04-32-735_tv danmaku bili](https://github.com/user-attachments/assets/66bd85a9-fc92-4c8f-89b6-512531a0d019)

### 复现步骤

根据上述描述打开该视频。
漫游设置：“去你xx的小程序”设为开启（会将分享链接转为av）
分享，选择复制链接。

### 预期行为

点开发现为正常视频内容。复制链接时链接av号应匹配简介中av号，至少不能是负的（（（

### 实际行为

点开链接，发现点不开。链接av号为负。

### 截图或录屏

见简介描述。图1：视频简介界面。图2：搜索简介中的av号，正常。图3：搜索分享链接中的av号（负的），搜不到。图4：搜索去除负号的av号，显示为一东南亚节目。

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0 (release-b13150977)

### 使用的框架和版本

LSPatch 1.7.0 7.50.0

### 日志

[1_log.txt](https://github.com/user-attachments/files/16517116/1_log.txt)

**Comment by XEpicLi** [comment]
没写标题🤣🤣🤣

**Comment by yujincheng08** [comment]
CI 修过了
