### ISSUE TITLE
[Feature]想问一下这个仓库应该还在更新适配吧（我看最近还有提交）。

### ISSUE THREAD

**Issue by qxFly** [yujincheng08/BiliRoaming#1511]
### 原因

 想问一下这个仓库应该还在更新适配吧（我看最近还有提交）。刚刚自己用源码构建了一下，版本号好像比最后一版公开的要低就是了。如果还有更新，以后就自己用源码构建了。

### 功能简述

无

### 功能逻辑

无

**Comment by yujincheng08** [comment]
有。
