### ISSUE TITLE
[Bug] “允许下载版权番剧”开启后无法下载任何视频

### ISSUE THREAD

**Issue by KaguYuuki** [yujincheng08/BiliRoaming#1514]
### 问题描述

开启模块内“允许下载版权番剧”后无法下载任何视频

### 复现步骤

1. 打开“哔哩漫游”模块内的“允许下载版权番剧”
2. 尝试下载任何有无版权的视频

### 预期行为

任何视频均正常下载，包括版权番剧

### 实际行为

任何视频均无法下载，包括版权番剧

### 开启“允许下载版权番剧”前
![Screenshot_2024-08-21-18-29-24-034_tv danmaku bili-edit](https://github.com/user-attachments/assets/c0c17345-94e7-4290-bfa5-f5c024ffd462)

### 开启“允许下载版权番剧”后
![Screenshot_2024-08-21-18-28-57-036_tv danmaku bili-edit](https://github.com/user-attachments/assets/72570f1f-bfb2-4d20-acb6-fee6861edb64)

### 安卓版本

14

### 哔哩漫游版本

652d6dce61

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 使用的框架和版本

LSPosed 1.9.3_mod

### 日志

[log.txt](https://github.com/user-attachments/files/16690311/log.txt)

**Comment by yujincheng08** [comment]
Duplicate of #1499
