### ISSUE TITLE
[Feature] 兼容新版B站的AVID

### ISSUE THREAD

**Issue by 0XPYEX0** [yujincheng08/BiliRoaming#1516]
### 原因

部分视频的AVID长度超过 `int` 甚至 `long` 的限制，例如
https://bilibili.com/video/av112881236443877
这条视频

### 功能简述

正常解析

### 功能逻辑

无

### 实现参考

应当使用 `BigInteger` 等进行解析，避免出现超限的问题

**Comment by JasonKhew96** [comment]
没有问题

https://github.com/yujincheng08/BiliRoaming/blob/652d6dce6149b746ca96a7be22b6e37797dc4d2d/app/src/main/java/me/iacn/biliroaming/utils/Utils.kt#L54-L64

![image](https://github.com/user-attachments/assets/9b9239ff-5817-4ff1-8f1f-ba7f1699cc54)

**Comment by 0XPYEX0** [comment]
合理
