### ISSUE TITLE
[Feature] 什么时候可以更新B站的版本？

### ISSUE THREAD

**Issue by LLL151** [yujincheng08/BiliRoaming#1522]
### 原因

7.50太老了，很多新功能已经不支持

### 功能简述

更新LSP版本

### 功能逻辑

上次更新已经是去年

**Comment by q35654046** [comment]
感觉大佬弃坑了

**Comment by NiYukk** [comment]
自己打包新版本就好了

**Comment by LLL151** [comment]
> 自己打包新版本就好了

如何打包，有打包的工具链接或者教程吗？

**Comment by buhaoye** [comment]
去下个lspatch，shizuku，照着教程你就知道怎么打包了，但老实说，新版那几个不是很稳定，有一堆bug，最好还是用7.75加上1.70的版本
