### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NGWT1** [yujincheng08/BiliRoaming#1530]
### 问题描述

开屏有错误显示

### 复现步骤

1.用lspatch刷入模块安装
2打开软件
3有错误显示
![Screenshot_20240929_003319](https://github.com/user-attachments/assets/20b0cc12-f44b-411c-8ea1-b8bb4223fccc)

### 预期行为

直接进入软件主页

### 实际行为

错误提醒

### 截图或录屏

![Screenshot_20240929_003319](https://github.com/user-attachments/assets/c56b7346-609a-4ea2-9e90-1856fd32f7ad)

### 安卓版本

14

### 哔哩漫游版本

1.6.15

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.15.0

### 使用的框架和版本

lspatch1.92

### 日志

[old_log.txt](https://github.com/user-attachments/files/17175639/old_log.txt)
[log.txt](https://github.com/user-attachments/files/17175640/log.txt)

**Comment by NGWT1** [comment]
手机为iQOOz9t，正式版最新系统

**Comment by NGWT1** [comment]
手机为iQOOZ9T，正式版最新系统orangOS

**Comment by CodePwn2021** [comment]
貌似是BiliRoamingX的问题，并且其中包含的信息过少，无法定位
