### ISSUE TITLE
[Bug] 闪退

### ISSUE THREAD

**Issue by yuanyunzhe** [yujincheng08/BiliRoaming#1533]
### 问题描述

三星S24+，之前一切正常，在一次重启后再打开发生闪退，另一台红米K60则可以正常运行

### 复现步骤

使用以下组合均发生闪退
- 发布的最新LSPatch打包普通版本（1.7.0+7.50.0）
- 发布的最新LSPatch打包HD版（1.7.0+1.44.1）
- 自行用LSPatch打包
  - 最新发布版模块（1.7.0）+最新发布版B站（8.14.0）
  - 最新发布版模块（1.7.0）+最新Play版B站（8.14.0）
  - 最新push模块（9926eef1f1）+最新发布版B站（8.14.0）
  - 以上组合均经过电脑（Win11）与手机（S24+）两种方式打包

### 预期行为

正常进入APP

### 实际行为

闪退

### 截图或录屏

https://github.com/user-attachments/assets/742f5db9-e422-477a-953d-cf05ee1a1b54

### 安卓版本

14（One UI 6.1）

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.50.0

### 使用的框架和版本

LSPosed 1.9.2

### 日志

[logs.txt](https://github.com/user-attachments/files/17264008/logs.txt)

**Comment by CodePwn2021** [comment]
使用的LSPatch不兼容Google Play系统更新带来的ART变更。这是LSPatch的问题。
可以尝试这个（Android 10 QPR1及以下版本）：
`adb uninstall com.google.android.art`
或者更换其他方案
