### ISSUE TITLE
[Bug] 开启速度慢

### ISSUE THREAD

**Issue by alan42521** [yujincheng08/BiliRoaming#1541]
### 问题描述

使用模块后，在启动图前会有一段白屏只显示bilibili logo，拖慢启动时间

### 复现步骤

1.打开b站app

### 预期行为

能像没开启模块前快速地打开到主页

### 实际行为

启动时间变慢

### 安卓版本

11

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.7.0

### 使用的框架和版本

8.18.0

### 日志

[log.txt](https://github.com/user-attachments/files/17540935/log.txt)

**Comment by CodePwn2021** [comment]
fixed in #1553 and #1555
