### ISSUE TITLE
哔哩哔哩更新后启动速度变慢

### ISSUE THREAD

**Issue by Hua159** [yujincheng08/BiliRoaming#1547]
### 问题描述

将哔哩哔哩app更新到版本8.19.0(经过测试，8.18.0也有这个问题)，在启用漫游模块的情况下，使得冷启动哔哩哔哩，第一屏动画所消耗时间过多，致使整体启动流程变长

### 复现步骤

1.哔哩哔哩应用更新至8.19.0
2.点击应用图标进行冷启动

### 预期行为

点击应用图标进行冷启动，去除开屏推广的情况下应是3s~4s

### 实际行为

点击应用图标进行冷启动， 去除开屏推广的情况下约6s

### 截图或录屏

https://github.com/user-attachments/assets/608c21e0-1756-4715-b8ff-1f53b2f03783

### 安卓版本

14

### 哔哩漫游版本

9926eef1f1

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.19.0

### 使用的框架和版本

lsposed框架 1.9.2-it (7240)

### 其他

KSU11928
Zygisk Next 1.2.3-441-6843192-release

### 日志

[log.txt](https://github.com/user-attachments/files/17588085/log.txt)

**Comment by CodePwn2021** [comment]
fixed in #1553
