### ISSUE TITLE
[Bug] Play 3.19.1 启动报错，然后显示封禁账号

### ISSUE THREAD

**Issue by lon91ong** [yujincheng08/BiliRoaming#1548]
### 问题描述

启动有报错，一段日子没理会，前天开始提示账号封禁

### 复现步骤

打开就弹出提示

### 预期行为

正常启动

### 实际行为

前阵子改玩Play版的哔哩哔哩安卓客户端，模块导入了以前的设置，启动时有报错信息，没管
前天开始提示账号封禁

### 截图或录屏

![启动报错](https://github.com/user-attachments/assets/f3630a0d-10f8-417a-b916-e7bb2a0ae8ab)

![账号封禁](https://github.com/user-attachments/assets/8dc678d2-b9fd-4417-8c93-0a04b2fd2a56)

### 安卓版本

13

### 哔哩漫游版本

1.7.0

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.19.1

### 使用的框架和版本

太极-阴 129

### 其他

手机是红米Note 10 Pro MIUI14.0.7 (Android 13)

### 日志

无日志

**Comment by skytianle666** [comment]
第一，封禁提示是来自哔哩漫游X的，而哔哩漫游X是基于revanced改包的，并不是Xposed模块与我们无关系，第二你蛮天才的这是将哔哩漫游模块注入漫游X的包了，叠BUFF呢？第三目前解析服务器确实将所有用户拉入黑名单了，原因我不做解释，请自行找寻。

**Comment by jueduilingdu08** [comment]
BiliRoamingX 跑路了，有一个镜像的，去掉了解析服务器的，叫BiliRoamingM，你可以试试。

**Comment by BDD282** [comment]
我也遇到了，前两天还能正常用今天就显示被封禁了，不知道什么原因，代理服务器的问题？

**Comment by BDD282** [comment]
> 第一，封禁提示是来自哔哩漫游X的，而哔哩漫游X是基于revanced改包的，并不是Xposed模块与我们无关系，第二你蛮天才的这是将哔哩漫游模块注入漫游X的包了，叠BUFF呢？第三目前解析服务器确实将所有用户拉入黑名单了，原因我不做解释，请自行找寻。

@skytianle666 所以是什么原因呢

**Comment by BDD282** [comment]
> 第一，封禁提示是来自哔哩漫游X的，而哔哩漫游X是基于revanced改包的，并不是Xposed模块与我们无关系，第二你蛮天才的这是将哔哩漫游模块注入漫游X的包了，叠BUFF呢？第三目前解析服务器确实将所有用户拉入黑名单了，原因我不做解释，请自行找寻。

@skytianle666 查到了，因为大规模传播直接被删除归档了，唉

**Comment by skytianle666** [comment]
@lon91ong 请自行关闭此议题
