### ISSUE TITLE
[BUG] 首页 竖屏视频 净化失效

### ISSUE THREAD

**Issue by david082321** [yujincheng08/BiliRoaming#155]
**问题描述**
这个[https://github.com/yujincheng08/BiliRoaming/commit/7c52bfc4d79b0c617763ebf0f93a3b0766378a2e](https://github.com/yujincheng08/BiliRoaming/commit/7c52bfc4d79b0c617763ebf0f93a3b0766378a2e)修改后，屏蔽失效(vertical)。

前一个版本(1f72f4d46b)可正确屏蔽。

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：
 - 哔哩漫游版本：495e9efc45
 - 哔哩哔哩版本和版本号：原版6.23.5（如概念版6.2.3）
 - 使用的框架和版本：应用转生（如太极6.3.0）
 - 其他：首页（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
一个 goto 一个 cardgoto

**Comment by david082321** [comment]
> 一个 goto 一个 cardgoto

可是 cardType 却能生效
