### ISSUE TITLE
大佬，蓝奏云链接挂了[BUG]

### ISSUE THREAD

**Issue by 1cylh** [yujincheng08/BiliRoaming#158]
**问题描述**
蓝奏云链接挂了

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by JasonKhew96** [comment]
@1cylh 
![image](https://user-images.githubusercontent.com/29531167/118273159-33444a00-b4f6-11eb-8b6c-897041488cfc.png)

**Comment by 1cylh** [comment]
> @1cylh
> ![image](https://user-images.githubusercontent.com/29531167/118273159-33444a00-b4f6-11eb-8b6c-897041488cfc.png)

多谢多谢了
