### ISSUE TITLE
[BUG]获取视频封面与新版播放器长按倍速播放冲突

### ISSUE THREAD

**Issue by BoBppy** [yujincheng08/BiliRoaming#163]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
国内版6.25.0后吧，加入长按倍速播放后的版本，播放的同时会触发漫游的保存封面

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：11
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
啊这，这大概不必吧

也许应该投功能建议，可否改一下保存视频封面的触发方式以解决问题

**Comment by yujincheng08** [comment]
下个版本会移除这个功能

**Comment by Steve-cn** [comment]
> 下个版本会移除这个功能

这功能挺好用的，倒是建议修改触发方式，如长按指定按钮，添加保存封面按钮，长按指定范围等

**Comment by yujincheng08** [comment]
已在 8b4e048bf06fb19a570f02937f8bfaee3c8be5b5 中移除该功能。
