### ISSUE TITLE
自定义底栏中无法去除发布按钮

### ISSUE THREAD

**Issue by zhejiushiguazi** [yujincheng08/BiliRoaming#174]
**问题描述**
自定义底栏中无法去除发布按钮
**复现步骤**
如何复现
打开哔哩漫游设置
自定义底栏后，取消发布选项
确定并重启客户端后依旧存在

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：10
 - 系统版本：
 - 哔哩漫游版本：1.4.4
 - 哔哩哔哩版本和版本号：6.29.0   release-b5668413
 - 使用的框架和版本：太极7.0.3.05282148-6316
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
#171

**Comment by eve2ptp** [comment]
> #171

最新版【[LSPatch] [1.6.10] [7.18.0] 哔哩哔哩.apk】仍然有这个问题

**Comment by yujincheng08** [comment]
一年前的 issue 还回复真牛逼👍
