### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by piexian** [yujincheng08/BiliRoaming#176]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 打开...哔哩哔哩
2. 点击...头像
3. 出现...状况 没有反应侧边栏不出来
![Screenshot_2021-06-24-14-46-27-399_tv danmaku bili](https://user-images.githubusercontent.com/64474352/123215426-0b012100-d48e-11eb-8986-f51a8cc5bfe7.jpg)

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI12.5
 - 哔哩漫游版本：1.4.4
 - 哔哩哔哩版本和版本号：6.30.0（如概念版6.2.3）
 - 使用的框架和版本：lsp1.4.5（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
2a4b343eb8c2fc91bdd4618e2ea4576e4b19c550
