### ISSUE TITLE
[BUG]现在无法自动点赞视频了

### ISSUE THREAD

**Issue by anby01** [yujincheng08/BiliRoaming#177]
**问题描述**
现在无法自动点赞视频了，也不记得是从那一版开始，反正某一次B站更新后至今一直无法自动点赞了

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/d0fa7a0b90f2ac6186c15481569ca42faac8524f
