### ISSUE TITLE
[BUG]现在无法自动点赞视频了，求修复更新

### ISSUE THREAD

**Issue by anby01** [yujincheng08/BiliRoaming#178]
**问题描述**
现在无法自动点赞视频了，也不记得是从哪一版开始，反正某一次B站更新后至今一直无法自动点赞了

**复现步骤**
如何复现
1. 打开漫游设置，勾选自动点赞视频
2. 随便点击一个视频...
3. 无法触发自动点赞

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 12.5
 - 哔哩漫游版本：1.4.4
 - 哔哩哔哩版本和版本号：官方版本6.30.0
 - 使用的框架和版本：lsp 1.4.5
 - 其他：

**日志**
求更新修复

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/issues/177

早修了

**Comment by anby01** [comment]
> #177
> 
> 早修了

我这边测试用最新B站 最新漫游 最新框架，是不会自动点赞的，不过早很多版本就已经这样了，反正是某次B站更新后就这样了，具体忘记哪个版本更新后了，以前都没问题的

**Comment by JasonKhew96** [comment]
> > #177
> > 早修了
> 
> 我这边测试用最新B站 最新漫游 最新框架，是不会自动点赞的，不过早很多版本就已经这样了，反正是某次B站更新后就这样了，具体忘记哪个版本更新后了，以前都没问题的

请：
https://github.com/yujincheng08/BiliRoaming/actions

不然自己编译

**Comment by yujincheng08** [comment]
> > #177
> > 早修了
> 
> 我这边测试用最新B站 最新漫游 最新框架，是不会自动点赞的，不过早很多版本就已经这样了，反正是某次B站更新后就这样了，具体忘记哪个版本更新后了，以前都没问题的

你说这些有用吗？先不说你日志都没有，我们都已经告诉你修好了，你还在这里重重复复这几句话，你想怎样？
