### ISSUE TITLE
[BUG]打开哔哩漫游设置崩溃

### ISSUE THREAD

**Issue by RainbowFunny826** [yujincheng08/BiliRoaming#182]
**问题描述**
打开哔哩漫游设置没有响应 并且多次点击后崩溃

**复现步骤**
如何复现
1. 打开我的
2. 点击哔哩漫游设置
3. 出现java.lang.NullPointerException状况

**截图**
![Screenshot_2021_0703_023335](https://user-images.githubusercontent.com/53068513/124317548-ef8ec800-dba9-11eb-9c5f-acc5f07278b8.png)

**环境信息**
 - 安卓版本：Android 8.1.0
 - 系统版本：vivo rev 8.20.15
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：官版 6.31.0
 - 使用的框架和版本：太极 7.0.3 阴内核 128

**日志**
--------- beginning of main
07-03 02:40:00.671 22601 22601 E EXposed : XposedHookGetPackageInfo: 0
07-03 02:40:00.671 22601 22601 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0
07-03 02:40:00.673 22601 22601 E EXposed : XposedHookGetPackageInfo: 0
07-03 02:40:00.675 22601 22601 E EXposed : isGetSigningDetails: 0, isGetSignatures: 0, flag: 0

**Comment by yujincheng08** [comment]
叫你用 7.10 的太极你不听是吧？
