### ISSUE TITLE
6.2.0+1.2.7 部分功能失效求解

### ISSUE THREAD

**Issue by 21inbottle** [yujincheng08/BiliRoaming#19]
b站客户端6.2.0，插件1.2.7，太极阳6.3.0，miui12 20.6.18
缓存番剧、区域限制解除、评论显示楼层的功能失效，求解
其他换主题颜色、去青少年提示、去会员购、显示楼层等功能都正常

**Comment by yujincheng08** [comment]
请提供log

**Comment by 21inbottle** [comment]
隔了一天突然正常了。感谢。
