### ISSUE TITLE
[BUG]1.4.5版模块闪退

### ISSUE THREAD

**Issue by HikkiFans** [yujincheng08/BiliRoaming#192]
**问题描述**
发生了什么情况？有什么现状？
1.4.5版本模块，通过太极加载到6.32版本b站客户端，功能正常，但无法打开模块设置窗口，会提示闪退。1.4.4版本无此问题。

**复现步骤**
如何复现
1. 打开b站客户端-我的-更多服务
2. 点击哔哩漫游设置
3. 出现太极已阻止b站客户端闪退的提示，无法打开哔哩漫游设置。

**截图**
点击文本框下面小长条可以上传文件
![IMG_20210707_215837](https://user-images.githubusercontent.com/87079640/124773050-32ca9d00-df02-11eb-8170-314c13e2ee09.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI12.5 
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：6.32.0
 - 使用的框架和版本：太极7.0.3
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by likecoly** [comment]
用7.10以上啊。。。橘黄色的标签很适合你
