### ISSUE TITLE
[Feature]能否添加直播间弹幕关键字屏蔽功能

### ISSUE THREAD

**Issue by Decwar** [yujincheng08/BiliRoaming#194]
**原因**
经常能看到烂梗、广告、钓鱼类的弹幕，但b站手机端的直播间始终不出关键字屏蔽功能

**功能简述**
直播间弹幕关键字屏蔽，可以的话加多UL等级屏蔽以及小心心礼物赠送屏蔽

**功能逻辑**
如已存在的首页关键字屏蔽功能

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
太难。
