### ISSUE TITLE
安卓10 Edxposed 功能生效玄学问题

### ISSUE THREAD

**Issue by jzl2163** [yujincheng08/BiliRoaming#2]
在我的设备（米9 Android10）上，有的时候点进Bilibili应用后，模块模块功能不会生效；有时点开应用会导致手机自动软重启，软重启后模块才能生效。

**Comment by dv3lood** [comment]
在k20pro 最新开发版上同样出现此问题

**Comment by yujincheng08** [comment]
我也是安卓10，用edxposed没有复现成功。有没有log？

**Comment by lsgbx** [comment]
刚下，bilibili5.56.1版本，只看见站官方反馈群公告找来的
安装后重启，edxposed sandhook稳定版最新，功能部分生效，净化类生效，但是版权下载和地区解锁不生效，软件内显示插件没有激活
不知道是不是因为这个模块是太极的原因（公告里写着支持太极，没写edxp）

**Comment by yujincheng08** [comment]
@lsgbx 我现在用edxposed的，功能都有生效。没生效的话要提供log我看看

**Comment by lsgbx** [comment]
emmm 重启了下
 清楚cache dalvik
 #`这回国内可以下载版权了，但是地区依旧不行，挂的洛杉矶代理，哔哩漫游内依旧显示未激活```
话说怎么附txt文件在github。。。
也不知道这份模块日志对不对，详细日志没开
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: chiron
Product: chiron
Model: Mi MIX 2
Fingerprint: Xiaomi/chiron/chiron:8.0.0/OPR1.170623.027/V9.5.4.0.ODEMIFA:user/release-keys
ROM description: chiron-user 8.0.0 OPR1.170623.027 V9.5.4.0.ODEMIFA release-keys
Architecture: arm64-v8a
Android build: QQ2A.200305.003
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.2 (4529) (SandHook)
EdXposed api: 91.0
Riru version: v19.7 (29)
Riru api: 4
Magisk: 20.4 (20400)
--------- beginning of main
--------- beginning of system
07-22 22:24:39.023   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.fkzhang.qqxposed-gsA0fBr-EX8WOPeJw-W3Jw==/base.apk
07-22 22:24:39.096   922   922 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
07-22 22:24:39.097   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.xloger.exlink.app-WM-e3uioLonRZoF4I3crKA==/base.apk
07-22 22:24:39.206   922   922 I EdXposed-Bridge:   Loading class com.xloger.exlink.app.HookMain
07-22 22:24:39.208   922   922 I EdXposed-Bridge:   Loading class com.xloger.exlink.app.HookSelf
07-22 22:24:39.209   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.ext.star.wars-vEWDo7WCgnJP2gyBMFpm8w==/base.apk
07-22 22:24:39.671   922   922 I EdXposed-Bridge:   Loading class com.ext.star.wars.x.AdHook
07-22 22:24:39.673   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedgepro-OwU8HC6R5XjVSQJ1RsxgaQ==/base.apk
07-22 22:24:39.698   922   922 I EdXposed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
07-22 22:24:39.701   922   922 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-Cw88a9iQBBvhXKdnuUsdHw==/base.apk
07-22 22:24:40.059   922   922 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
07-22 22:24:40.060   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.sollyu.xposed.hook.model-0u8qu7u1q8nU6rK6SnbSvw==/base.apk
07-22 22:24:40.267   922   922 I EdXposed-Bridge:   Loading class com.sollyu.kotlin.appenv.xposed.XposedEntry
07-22 22:24:40.272   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.jy.taofanfan-cu6ORiluWgz1qsoG8uMEBg==/base.apk
07-22 22:24:40.458   922   922 I EdXposed-Bridge:   Loading class com.jy.xposed.Main
07-22 22:24:40.461   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.surcumference.fingerprintpay-Gwtd0fkPRKSwKMuYpc--Dg==/base.apk
07-22 22:24:40.539   922   922 I EdXposed-Bridge:   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
07-22 22:24:40.540   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.omarea.vtools-6rRrkQNM91DlXlu7DmjOZA==/base.apk
07-22 22:24:40.635   922   922 I EdXposed-Bridge:   Loading class com.omarea.xposed.XposedInterface
07-22 22:24:40.636   922   922 I EdXposed-Bridge: Loading modules from /data/app/me.iacn.biliroaming-buLdhrkdeg1Wq-Fvad4ELw==/base.apk
07-22 22:24:40.646   922   922 I EdXposed-Bridge:   Loading class me.iacn.biliroaming.XposedInit
07-22 22:24:40.648   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.hentaibear.volumecontroller-qWiFFyI2Ns252W-TXnAGwQ==/base.apk
07-22 22:24:40.753   922   922 I EdXposed-Bridge:   Loading class com.hentaibear.volumecontroller.XposedHook.MainHook
07-22 22:24:40.754   922   922 I EdXposed-Bridge: Loading modules from /data/app/com.sudocode.sudohide-oCoUIhCqVxyNyAkyMbVEWg==/base.apk
07-22 22:24:40.816   922   922 I EdXposed-Bridge:   Loading class com.sudocode.sudoHideModule.XposedMain
07-22 22:24:40.819   922   922 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.xposedmoduletest-bhNvDTFfBpEfK_5A_R8uug==/base.apk
07-22 22:24:40.991   922   922 I EdXposed-Bridge:   Loading class github.tornaco.xposedmoduletest.xposed.XModuleDelegate
07-22 22:24:41.051   922   922 I EdXposed-Bridge: Loading modules from /data/app/fi.veetipaananen.android.disableflagsecure-k3DIKq8_sfgM1TPIbyNRzg==/base.apk
07-22 22:24:41.058   922   922 I EdXposed-Bridge:   Loading class fi.veetipaananen.android.disableflagsecure.DisableFlagSecureModule
07-22 22:24:41.059   922   922 I EdXposed-Bridge: Loading modules from /data/app/ru.wHgVDhPg.yYjJowhiS-RaUamz_MQk9_KCrXOhZwGQ==/base.apk
07-22 22:24:41.138   922   922 I EdXposed-Bridge:   Loading class com.xposed.XSupport
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/WindowManagerPolicy$WindowManagerFuncs;
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at github.tornaco.xposedmoduletest.xposed.submodules.PWMInterceptKeySubModule$2.afterHookedMethod(Unknown Source:22)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:388)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at SandHookerNew_1kaqrpqagufhjdooo1fjtr4bav.hook(Unknown Source:61)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at com.android.server.wm.WindowManagerService$5.run(WindowManagerService.java:999)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at android.os.Handler$BlockingRunnable.run(Handler.java:906)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at com.android.server.UiThread.run(UiThread.java:43)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.WindowManagerPolicy$WindowManagerFuncs" on path: DexPathList[[zip file "/data/app/github.tornaco.xposedmoduletest-bhNvDTFfBpEfK_5A_R8uug==/base.apk"],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, /vendor/lib64]]
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-18 20:10:16.067  1875  2072 E EdXposed-Bridge: 	... 12 more
04-04 12:01:41.185   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.fkzhang.qqxposed-gsA0fBr-EX8WOPeJw-W3Jw==/base.apk
04-04 12:01:41.473   923   923 I EdXposed-Bridge:   Loading class com.fkzhang.qqxposed.XposedInit
04-04 12:01:41.474   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.xloger.exlink.app-WM-e3uioLonRZoF4I3crKA==/base.apk
04-04 12:01:41.878   923   923 I EdXposed-Bridge:   Loading class com.xloger.exlink.app.HookMain
04-04 12:01:41.887   923   923 I EdXposed-Bridge:   Loading class com.xloger.exlink.app.HookSelf
04-04 12:01:41.888   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.ext.star.wars-vEWDo7WCgnJP2gyBMFpm8w==/base.apk
04-04 12:01:42.933   923   923 I EdXposed-Bridge:   Loading class com.ext.star.wars.x.AdHook
04-04 12:01:42.938   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedgepro-OwU8HC6R5XjVSQJ1RsxgaQ==/base.apk
04-04 12:01:43.003   923   923 I EdXposed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
04-04 12:01:43.012   923   923 I EdXposed-Bridge: Loading modules from /data/app/org.meowcat.edxposed.manager-Cw88a9iQBBvhXKdnuUsdHw==/base.apk
04-04 12:01:43.911   923   923 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
04-04 12:01:43.913   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.sollyu.xposed.hook.model-0u8qu7u1q8nU6rK6SnbSvw==/base.apk
04-04 12:01:44.542   923   923 I EdXposed-Bridge:   Loading class com.sollyu.kotlin.appenv.xposed.XposedEntry
04-04 12:01:44.543   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.jy.taofanfan-cu6ORiluWgz1qsoG8uMEBg==/base.apk
04-04 12:01:44.921   923   923 I EdXposed-Bridge:   Loading class com.jy.xposed.Main
04-04 12:01:44.922   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.surcumference.fingerprintpay-Gwtd0fkPRKSwKMuYpc--Dg==/base.apk
04-04 12:01:45.067   923   923 I EdXposed-Bridge:   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
04-04 12:01:45.068   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.omarea.vtools-6rRrkQNM91DlXlu7DmjOZA==/base.apk
04-04 12:01:45.162   923   923 I EdXposed-Bridge:   Loading class com.omarea.xposed.XposedInterface
04-04 12:01:45.163   923   923 I EdXposed-Bridge: Loading modules from /data/app/me.iacn.biliroaming-buLdhrkdeg1Wq-Fvad4ELw==/base.apk
04-04 12:01:45.166   923   923 I EdXposed-Bridge:   Loading class me.iacn.biliroaming.XposedInit
04-04 12:01:45.168   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.hentaibear.volumecontroller-qWiFFyI2Ns252W-TXnAGwQ==/base.apk
04-04 12:01:45.277   923   923 I EdXposed-Bridge:   Loading class com.hentaibear.volumecontroller.XposedHook.MainHook
04-04 12:01:45.279   923   923 I EdXposed-Bridge: Loading modules from /data/app/com.sudocode.sudohide-oCoUIhCqVxyNyAkyMbVEWg==/base.apk
04-04 12:01:45.393   923   923 I EdXposed-Bridge:   Loading class com.sudocode.sudoHideModule.XposedMain
04-04 12:01:45.394   923   923 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.xposedmoduletest-bhNvDTFfBpEfK_5A_R8uug==/base.apk
04-04 12:01:45.765

**Comment by yujincheng08** [comment]
@lsgbx 传日志可以点下方的上传栏（Attach files by...）上传文件。
另外这个日志没有有用的信息（

**Comment by lsgbx** [comment]
换了yahfa问题依旧，功能部分生效，净化类生效，但是版权下载和地区解锁不生效，软件内显示插件没有激活
下面是重启后启用的详细日志
[EdXposed_log.txt](https://github.com/yujincheng08/BiliRoaming/files/4430809/EdXposed_log.txt)

**Comment by yujincheng08** [comment]
@lsgbx 依然没有需要的信息，电脑端可以使用 adb 命令 ·adb logcat BiliRoaming:D·。
手机端可以使用 MatLog 这个应用，然后 Filter 设置 Log Tag 为 BiliRoaming。

**Comment by yujincheng08** [comment]
我自己用从sandhook向yahfa切换了一下，没啥问题

**Comment by lsgbx** [comment]
> @lsgbx 依然没有需要的信息，电脑端可以使用 adb 命令 ·adb logcat BiliRoaming:D·。
> 手机端可以使用 MatLog 这个应用，然后 Filter 设置 Log Tag 为 BiliRoaming。

![Screenshot_20200404-173659](https://user-images.githubusercontent.com/36256836/78423728-0985e600-769b-11ea-8c10-c63f1f32fe5a.jpg)
也有可能是我的环境太玄学了，mix2刷的安卓10 havoc 3.3
麻烦大佬了，实在找不出问题或者我还是没能送出关键信息就算了

**Comment by lsgbx** [comment]
![Screenshot_20200404-173646](https://user-images.githubusercontent.com/36256836/78423762-4225bf80-769b-11ea-8b7b-86cf049e9b3e.jpg)

**Comment by yujincheng08** [comment]
@lsgbx  你这是回国吗？？

**Comment by lsgbx** [comment]
emmm我这个是出国，在国内用全局代理，hk或者los的节点

**Comment by yujincheng08** [comment]
@lsgbx 全局代理不就是回国吗。打开biliplus试试吧

**Comment by lsgbx** [comment]
平时有蹭ipv6免费流量的需求（这么一说都懂了哈233）原先是没有打开biliplus接口的，刚才打开了，杀掉全部后台，启动b站问题依旧
这样就可以了，可以缓存版权番，可以使用净化
挂代理看b站我有油猴的解除b站区域限制的脚本，挂代理看b站用电脑得了，手机代理贼热
：）

**Comment by yujincheng08** [comment]
@lsgbx 杀一次不行就多杀次后台。不用biliplus的接口是解析不了大陆版权的番剧的。

**Comment by lsgbx** [comment]
打开了，强行停止b站和插件，打开问题依旧，开代理地区受限，插件提示未激活
可能真的就是我的问题，selinux状态也是宽容（magisk插件）
大部分人用着没问题就好

**Comment by lsgbx** [comment]
（放弃治疗，不再回复了）
thanks

**Comment by yujincheng08** [comment]
可以试一下最新commit的这个
[test.zip](https://github.com/yujincheng08/BiliRoaming/files/4438830/test.zip)

**Comment by jzl2163** [comment]
> 可以试一下最新commit的这个
> [test.zip](https://github.com/yujincheng08/BiliRoaming/files/4438830/test.zip)
> @dv3lood @jzl2163

其实在我这边，1.1.14版本开始除了港澳台番剧以外所有功能都可以正常使用了。（尽管软件内还是提示模块未生效）
考虑到该issus中描述的问题已解决，我将关闭此issue。同时，感谢开发者的及时跟进。

**Comment by yujincheng08** [comment]
@jzl2163 那就好
