### ISSUE TITLE
哔哩漫游导致卡米

### ISSUE THREAD

**Issue by KarlcxChina** [yujincheng08/BiliRoaming#20]
1.2.7导致卡米，疑似与qn冲突……?

**Comment by KarlcxChina** [comment]
同时启用任意模块都会导致卡开机动画（qn，对话框取消）或者无限重启（edxp manager）。

**Comment by KarlcxChina** [comment]
系统为MIUI12，andriod10，magisk版本19.3，edxp版本0.4.6.2（4529）YAHFA

**Comment by yujincheng08** [comment]
No log, no fix.
