### ISSUE TITLE
[BUG]会员购定金支付无法唤起微信支付

### ISSUE THREAD

**Issue by DuskShadows** [yujincheng08/BiliRoaming#212]
**问题描述**
会员购使用微信支付定金时无法唤起，支付宝正常

**复现步骤**
如何复现
1. 打开会员购预售商品
2. 点击支付定金
3. 选择微信支付并点击支付
3. 出现支付失败字样，微信支付未被唤起，微信支付方面未出现相关订单

**截图**
无

**环境信息**
 - 安卓版本：10
 - 系统版本：EMUI 10.0.0
 - 哔哩漫游版本：1.4.4
 - 哔哩哔哩版本和版本号：6.23.5
 - 使用的框架和版本：Xpatch版本
 - 其他：会员购定金支付-微信支付

**日志**
并未出现相应报错或异常，只是无法唤起微信支付，支付宝正常

**Comment by yujincheng08** [comment]
所有非 root 实现都改了签名，所以没办法。
