### ISSUE TITLE
希望能把下边的加号屏蔽掉，最好是还原成老版本没有加号的状态[Feature]

### ISSUE THREAD

**Issue by DeliciousLiMiao** [yujincheng08/BiliRoaming#215]
**原因**
为什么想要这个功能
新版本加号完全没有用，买了个装扮还少个图标
**功能简述**
想要个怎样的功能
加号屏蔽或者最好还原成老版本五个图标的
**功能逻辑**
如何互交、如何使用等
希望大佬可以添加一个此功能😘
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
无

**Comment by yujincheng08** [comment]
早就有了。

**Comment by dunxuan** [comment]
> 早就有了。

在哪里，没找到啊？😭
