### ISSUE TITLE
遇到“出现错误xxxxxxx,部分功能可能失效”的弹窗[BUG]

### ISSUE THREAD

**Issue by fly-pigeon** [yujincheng08/BiliRoaming#217]
**问题描述**
同标题
出现错误xxxxxxx,部分功能可能失效”的弹窗
**复现步骤**
如何复现
1.打开就有

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：harmonyOS2.0
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号   原版6.34
 - 使用的框架和版本：太极8.03
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by fly-pigeon** [comment]
无法上传图片还有日志

**Comment by david082321** [comment]
两个方法
1. 降级哔哩到6.33.0以下 (包含6.33.0)
2. 用最新ci版漫游 (但是你用太极，不支持ci版)

**Comment by fly-pigeon** [comment]
好的，谢谢大佬发自我的华为手机-------- 原始邮件 --------发件人： david082321 ***@***.***>日期： 2021年7月23日周五 16:59收件人： yujincheng08/BiliRoaming ***@***.***>抄送： fly-pigeon ***@***.***>, State change ***@***.***>主    题： Re: [yujincheng08/BiliRoaming] 遇到“出现错误xxxxxxx,部分功能可能失效”的弹窗[BUG] (#217)

两个方法

降级哔哩到6.33.0以下 (包含6.33.0)用最新ci版漫游 (但是你用太极，不支持ci版)
