### ISSUE TITLE
模块激活后b站客户端并未显示哔哩哔哩漫游设置选项

### ISSUE THREAD

**Issue by Benjamin23333** [yujincheng08/BiliRoaming#22]
![Screenshot_2020-07-16-17-13-19-001_me iacn biliroaming](https://user-images.githubusercontent.com/54323063/87653319-f3062500-c787-11ea-89bd-878599756ef9.jpg)
![IMG_20200716_171358](https://user-images.githubusercontent.com/54323063/87653337-f8fc0600-c787-11ea-9455-075b767f812f.jpg)

**Comment by yujincheng08** [comment]
log呢？
