### ISSUE TITLE
添加适配软件版本，可以在关于里面加一个适配什么版本

### ISSUE THREAD

**Issue by hmw886** [yujincheng08/BiliRoaming#224]
**原因**
为什么想要这个功能

**功能简述**
想要个怎样的功能

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by qi-mooo** [comment]
如果你是非root用户请使用lspatch内置模块版本(因为内置的版本能保证适配)，如果是root用户一般来说ci适配很快，几乎哔哩哔哩更新都是当天修复，所以大部分情况下并不需要写这个说明，而且最好没事不要更新哔哩哔哩app本体，保持哔哩漫游在最新版一般都不用考虑适配问题。
