### ISSUE TITLE
[Feature]东南亚区番剧应禁用评论、弹幕

### ISSUE THREAD

**Issue by zhongfly** [yujincheng08/BiliRoaming#225]
**原因**
会干扰到主站无关视频的评论 弹幕

**功能简述**
东南亚区番剧应该禁用评论区或禁用评论功能，使得用户无法发送评论

**功能逻辑**
显示评论区不可用（例如这样的视频https://www.bilibili.com/video/BV1tB4y1w7f1）

**实现参考**
无

**Comment by xt1234567788** [comment]
哇，你这个视频我能进去，但泰区的番剧我看不了
