### ISSUE TITLE
[BUG] Play 版 2.10.1 设置解析服务器页面空白

### ISSUE THREAD

**Issue by Lehmaning** [yujincheng08/BiliRoaming#227]
**问题描述**

**复现步骤**
1. 打开 bilibili 客户端的漫游设置
2. 选择设置解析服务器
3. 页面一片空白 无法设置

**截图**
![Screenshot_2021-08-03-16-01-50-81](https://user-images.githubusercontent.com/60032845/127980653-34509c13-9601-4b8c-8d3a-f000affb73fb.png)

**环境信息**
 - 安卓版本：Android 5.0
&emsp;（另外用 Android Q 打开 Xpatch 版会直接闪退）
 - 系统版本：
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：Play 版 2.10.1
 - 使用的框架和版本：Xposed 3.10.5

**日志**
Xposed 也是日志为空，没办法……

**Comment by yujincheng08** [comment]
5.0 过于老旧，无法兼容。。。

**Comment by Lehmaning** [comment]
> 5.0 过于老旧，无法兼容。。。

@yujincheng08 那我下的 Android Q 的 Xpatch 版完全无法打开，没root看不了日志，怎么办……

**Comment by Lehmaning** [comment]
> @yujincheng08 那在 Android Q 上安装的 Xpatch 版 bilibili 客户端完全无法打开，会直接闪退，没 root 看不了日志，怎么办……

找到原因了，是Play服务的安全检测的问题，在工作应用里冻结Play服务就好了。
