### ISSUE TITLE
[Bug]闪退

### ISSUE THREAD

**Issue by 8yoldkid** [yujincheng08/BiliRoaming#228]
**问题描述**`

点击哔哩漫游设置出现通知太极已阻止哔哩哔哩闪退，多次点击后哔哩哔哩闪退

**复现步骤**
如何复现
1. 打开哔哩哔哩
2. 点击哔哩漫游设置
3. 出现通知太极已阻止哔哩哔哩闪退，多次点击后哔哩哔哩闪退

**截图**
![Screenshot_20210804_090040](https://user-images.githubusercontent.com/88411503/128105945-d0ec28af-3f8e-476b-9588-eeb38c33717d.jpg)
![Screenshot_20210804_090059](https://user-images.githubusercontent.com/88411503/128105947-72f7fe33-dd70-474e-8975-dd9d47665f49.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：EMUI10.1.0
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：普通版6.35.0
 - 使用的框架和版本：太极7.0.3.05282148—6505
 - 其他：（如哪部番、哪个专栏等）

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6927899/log.txt)

**Comment by yujincheng08** [comment]
更新日志不会看？

**Comment by david082321** [comment]
在应用的关于里，去官方网站下载 (选网盘下载、不要选Github下载)
