### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KDreamelf** [yujincheng08/BiliRoaming#229]
**问题描述**
1. 自动点赞功能失效
2. 若开启拉取封面功能，进入APP时出现报错
3. 启动页广告去除失败（使用自定义启动页但不选择文件的模式，日志的前半部分，启动页广告被另一个LSP，联壁模块去除了，后面关闭该模块重新复现了一遍
）

**复现步骤**
开启对应功能发现并未生效
其中若开启拉去取封面功能将导致进入APP时直接报错（但仍然能进入APP）

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 12.5 21.8.2
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）：普通版6.35.0
 - 使用的框架和版本：（如太极6.3.0）面具LSP1.3.3（5475）
 - 其他：（如哪部番、哪个专栏等）

**日志**
[log(1).txt](https://github.com/yujincheng08/BiliRoaming/files/6935425/log.1.txt)

**Comment by yujincheng08** [comment]
请测试 CI 版：https://github.com/yujincheng08/BiliRoaming/actions

**Comment by david082321** [comment]
1. 请更新最新ci版 https://t.me/biliroaming
2. 不支持 哔哩6.34.0 以上了，所以最新ci版已删除该功能
3. 不选文件当然会报错，可以改用「净化开屏页面」功能

**Comment by KDreamelf** [comment]
[log(2).txt](https://github.com/yujincheng08/BiliRoaming/files/6935515/log.2.txt)
现在，自动点赞仍未生效，不管是刚进视频还是看完了视频（当然我个人认为看完视频自动点赞更符合逻辑）
