### ISSUE TITLE
对于通过修改包名后的bilibili的支持

### ISSUE THREAD

**Issue by rhjdvsgsgks** [yujincheng08/BiliRoaming#23]
rt，希望能像微x一样添加手动指定bilibili包名的功能，现在该模块无法在修改包名后的bilibili上生效

**Comment by yujincheng08** [comment]
b站有3个版本而且都能共存，没必要改包名吧

**Comment by rhjdvsgsgks** [comment]
是因为某些系统只对某些包名的应用中的视频有优化效果，为了体验这些优化只能通过修改包名

**Comment by yujincheng08** [comment]
实现不难，但是目前我SDK已经到了29，很难访问再模块的`SharedPreferece`了，有空再看看吧。或者你提个PR。

**Comment by rhjdvsgsgks** [comment]
我姿势水平太低了，不怎么了解怎么写这类东西，只能期待各位大佬了

**Comment by aorosora** [comment]
要不你考虑一下直接改源码里面的包名？

**Comment by rhjdvsgsgks** [comment]
我现在装了两个 bilibili ，一个没改包名用插件用来下载，一个改了包名没用插件用来看🤣

**Comment by aorosora** [comment]
不是，我意思是你用AndroidStudio把里面的tv.danmuku.bili/com.bilibili.app.in全部替换成你的包名，然后自己编译一份出来。这种需求应该挺小众的（感觉）

**Comment by aorosora** [comment]
不是，我意思是你用AndroidStudio把里面的tv.danmuku.bili或者com.bilibili.app.in其中一个全部替换成你的版本对应的新包名，然后自己编译一份出来。这种需求应该挺小众的（感觉）

**Comment by rhjdvsgsgks** [comment]
我知道你是这个意思，但我 gradle 环境坏了，只好这样将就下

**Comment by GTRxa** [comment]
港澳台又无法看了

**Comment by yujincheng08** [comment]
技术上似乎没办法实现了。
我是在`handleLoadPackage` 之后， `callApplicationOnCreate`之前判断包名的。这个阶段不能访问其他app的`ContentProvider`。并且在新的安卓版本上，访问其他app的文件和preference都被禁了。也就是说，没办法把自定义的包名在hook之前告诉b站客户端。

**Comment by GTRxa** [comment]
那，小米手机使用修改后的B站APP闪退怎么解决？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yujincheng08/BiliRoaming"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 晚上6:30
收件人:&nbsp;"yujincheng08/BiliRoaming"<BiliRoaming@noreply.github.com&gt;;
抄送:&nbsp;"云计算1608WSH 高斌彬"<1275785931@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yujincheng08/BiliRoaming] 对于通过修改包名后的bilibili的支持 (#23)





 
技术上似乎没办法实现了。
 我是在handleLoadPackage 之后， callApplicationOnCreate之前判断包名的。这个阶段不能访问其他app的ContentProvider。并且在新的安卓版本上，访问其他app的文件和preference都被禁了。也就是说，没办法把自定义的包名在hook之前告诉b站客户端。

**Comment by yujincheng08** [comment]
@GTRxa Won't response due to off topic.

**Comment by rhjdvsgsgks** [comment]
如果“把自定义包名配置的位置放到放到 `/data/local/tmp` ”或“把自定义包名的配置放到模块这个应用的配置文件里但设置权限使所有应用都有权访问”也不行吗

**Comment by GTRxa** [comment]
不太好使




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rhjdvsgsgks"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 晚上7:29
收件人: "yujincheng08/BiliRoaming"<BiliRoaming@noreply.github.com&gt;; 
抄送: "云计算1608WSH 高斌彬"<1275785931@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yujincheng08/BiliRoaming] 对于通过修改包名后的bilibili的支持 (#23)





 
如果“把自定义包名配置的位置放到放到 /data/local/tmp ”或“把自定义包名的配置放到模块这个应用的配置文件里但设置权限使所有应用都有权访问”也不行吗

**Comment by yujincheng08** [comment]
@rhjdvsgsgks `/data/local/tmp` 不是persistent的。后者就是 `XSharePreference` 的似乎，早在N时代就已经不能用了。而R时代更是完全禁止其他应用访问任何文件。

**Comment by rhjdvsgsgks** [comment]
原来是这样，感谢指点。XSharePreference 再 chown 一下后我试了至少在 Android 9 上是能用的，至于在 r 上用不了我是现在才知道，之前一直没用过 r

**Comment by GTRxa** [comment]
那怎么解决?
------&nbsp;原始邮件&nbsp;------
发件人:&quot;rhjdvsgsgks&quot;<notifications@github.com&gt;;
发送时间:2020年10月28日(星期三)&nbsp;晚上11:54
收件人:&quot;yujincheng08/BiliRoaming&quot;<BiliRoaming@noreply.github.com&gt;;
抄送人:&quot;GTRxa&quot;<1275785931@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:Re:&nbsp;[yujincheng08/BiliRoaming]&nbsp;对于通过修改包名后的bilibili的支持&nbsp;(#23)



 
原来是这样，感谢指点。XSharePreference 再 chown 一下后我试了至少在 Android 9 上是能用的，至于在 r 上用不了我是现在才知道，之前一直没用过 r
 
&mdash;

**Comment by yujincheng08** [comment]
@rhjdvsgsgks 把模块的target SDK改大就不行了。

**Comment by yujincheng08** [comment]
我把 @GTRxa 的评论都删了，全都是没有营养的。

**Comment by GTRxa** [comment]
主要现在不是安卓9以上系统还是其他，但是大概率还是小米方面以及魅族都有对原生安卓的修改?导致对修改类型软件兼容不太友好，导致频繁闪退。
------&nbsp;原始邮件&nbsp;------
发件人:&quot;LoveSy&quot;<notifications@github.com&gt;;
发送时间:2020年10月29日(星期四)&nbsp;凌晨0:04
收件人:&quot;yujincheng08/BiliRoaming&quot;<BiliRoaming@noreply.github.com&gt;;
抄送人:&quot;GTRxa&quot;<1275785931@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:Re:&nbsp;[yujincheng08/BiliRoaming]&nbsp;对于通过修改包名后的bilibili的支持&nbsp;(#23)



 
@rhjdvsgsgks 把模块的target SDK改大就不行了。
 
&mdash;

**Comment by GTRxa** [comment]
我也没评论啊～怎么删除我评论了～吃瓜群众感觉莫名其妙
------&nbsp;原始邮件&nbsp;------
发件人:&quot;LoveSy&quot;<notifications@github.com&gt;;
发送时间:2020年10月29日(星期四)&nbsp;凌晨0:05
收件人:&quot;yujincheng08/BiliRoaming&quot;<BiliRoaming@noreply.github.com&gt;;
抄送人:&quot;GTRxa&quot;<1275785931@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:Re:&nbsp;[yujincheng08/BiliRoaming]&nbsp;对于通过修改包名后的bilibili的支持&nbsp;(#23)



 
我把 @GTRxa 的评论都删了，全都是没有营养的。
 
&mdash;

**Comment by yujincheng08** [comment]
@GTRxa  你的回复全是和话题无关的没有营养的*垃圾*。

**Comment by yujincheng08** [comment]
@rhjdvsgsgks 好了，搞定了，可以试试 https://github.com/yujincheng08/BiliRoaming/commit/6e08feff2180e1562f64d4946286e08dc425a218

**Comment by rhjdvsgsgks** [comment]
好的，我试试

**Comment by yujincheng08** [comment]
@rhjdvsgsgks 我这边即使改成777也不行（

**Comment by rhjdvsgsgks** [comment]
还有上层的文件夹也要改权限
https://github.com/rhjdvsgsgks/VideoEnhancementPlus/blob/e66328fcfa2011bc4cc532dd01f7e85c439fca85/app/src/main/java/com/example/videoenhancementplus/SettingsActivity.kt#L34
另外，我在这个模块中用到了您的部分代码 (KotlinXposedHelper.kt 和 Log.kt) ，不知道这符不符合 license ，如果您介意的话我可以删掉这部分自己重写

**Comment by yujincheng08** [comment]
@rhjdvsgsgks 那可能是上层目录的权限问题。用是可以用，开源了就行，但是得写一下出处。

**Comment by rhjdvsgsgks** [comment]
在设置了权限后我这边的权限是这样的
```
. [drwx--x--x]
└── [drwxrwx--x]  shared_prefs
    └── [-rw-rw-r--]  pkgname_preferences.xml
```

我 readme 里标了，需要在应用里也加上吗？

**Comment by yujincheng08** [comment]
@rhjdvsgsgks 源文件写一下哪里来的就行啦

**Comment by rhjdvsgsgks** [comment]
好的，我回去就加上

**Comment by rhjdvsgsgks** [comment]
试过了，可以成功 hook 修改包名后的 bilibili 。
另外我在那两个文件里也加上了来源，直接 force push 上去的，不知道为什么网页版看起来还没有变化(用 git 是能看到的)，可能是还要等一会

**Comment by yujincheng08** [comment]
还是删掉这个功能了，很多人投诉会被其他应用唤醒（ContentProvider的缺陷）。目前是判断有没有 `tv.danmaku.bili.MainActivityV2` 这个类。如果有就也会hook。所以改包名不把这个类名改掉就也能hook了。

**Comment by Android1500** [comment]
> 还是删掉这个功能了，很多人投诉会被其他应用唤醒（ContentProvider的缺陷）。目前是判断有没有 `tv.danmaku.bili.MainActivityV2` 这个类。如果有就也会hook。所以改包名不把这个类名改掉就也能hook了。

Any idea how to make preference readable coz of selinux security on above sdk 25 i cant read my parameters through preference file I appreciate if you could help

**Comment by duzhaokun123** [comment]
@Android1500 https://github.com/apsun/RemotePreferences

**Comment by Android1500** [comment]
> @Android1500 https://github.com/apsun/RemotePreferences

I don't wanna use remotepreference any alternative solution sir?

**Comment by yujincheng08** [comment]
> > @Android1500 https://github.com/apsun/RemotePreferences
> 
> I don't wanna use remotepreference any alternative solution sir?

https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences

**Comment by Android1500** [comment]
> > > @Android1500 https://github.com/apsun/RemotePreferences
> 
> > 
> 
> > I don't wanna use remotepreference any alternative solution sir?
> 
> 
> 
> https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences

Yah i tried this one and its really working but it will not works if user don't install edxposed in this case app cant access preference Sir

**Comment by yujincheng08** [comment]
> Yah i tried this one and its really working but it will not works if user don't install edxposed in this case app cant access preference Sir

LSPosed also supports this.

**Comment by Android1500** [comment]
> > Yah i tried this one and its really working but it will not works if user don't install edxposed in this case app cant access preference Sir
> 
> 
> 
> LSPosed also supports this.

Thanks Sir i address the issue its coz of selinux permission when i change selinux permission to permissive then its works so any solution for read preference file without change selinux permission

**Comment by yujincheng08** [comment]
> Thanks Sir i address the issue its coz of selinux permission when i change selinux permission to permissive then its works so any solution for read preference file without change selinux permission

NEVER EVER TRUN OFF SELINUX: https://twitter.com/topjohnwu/status/1359054106019565571?s=20, https://twitter.com/topjohnwu/status/1318839675180625921?s=20
