### ISSUE TITLE
[BUG]专栏无法评论

### ISSUE THREAD

**Issue by zangxx66** [yujincheng08/BiliRoaming#230]
**问题描述**
专栏界面无法点赞，评论，转发

**复现步骤**
如何复现
1. 打开up主动态
2. 点击专栏
3. 无法获取up粉丝数，点赞，评论以及转发数量，点击评论输入框无法评论

**截图**
![Screenshot_20210805-104941196](https://user-images.githubusercontent.com/14540861/128283169-854a0db7-c84d-4b4e-93bc-472a7178e2b7.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：11
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：普通版6.26.2
 - 使用的框架和版本：lsposed， 1.4.5
 - 其他：https://b23.tv/PBoIoJ

**日志**

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6935615/log.txt)

**Comment by david082321** [comment]
请更新最新ci版 https://t.me/biliroaming

**Comment by zangxx66** [comment]
> 请更新最新ci版 https://t.me/biliroaming

谢谢，ci版已解决，请问如果之后要更新正式版，是不是也是要先卸载ci版
