### ISSUE TITLE
[BUG]番剧列表加载不出

### ISSUE THREAD

**Issue by manyiluogu** [yujincheng08/BiliRoaming#231]
**问题描述**
追番（港澳台）的七月新番和七月国创栏目会显示黑屏但内容都能点都能正常跳转或其他类似内容都会出现此情况

**复现步骤**
如何复现
1. 打开追番(港澳台)
2. 点击七月新番或者七月国创栏目
3. 出现内容显示黑屏但点击黑屏区域依旧可以跳转状况

**截图**
![Screenshot_2021-08-05-21-59-36-494_tv danmaku bil](https://user-images.githubusercontent.com/70379530/128362961-32cbcf7a-e5a8-49aa-ad8d-3f48915b7709.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI12.5 21.7.28
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：[LSPatch] [6.31.0]
 - 使用的框架和版本：[LSPatch] [6.31.0]
 - 其他：https://b23.tv/Obw5zy

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6939236/log.txt)

**Comment by yujincheng08** [comment]
ci 版没问题，请测试 ci 版

**Comment by manyiluogu** [comment]
要怎样加入ci版测试

**Comment by yujincheng08** [comment]
在 action 直接下，或者去 tg 频道下
