### ISSUE TITLE
[BUG]专栏内容加载错误

### ISSUE THREAD

**Issue by manyiluogu** [yujincheng08/BiliRoaming#232]
**问题描述**
打开专栏会出现专栏内的番剧加载失败和专栏内的内容加载失败的情况以及专栏内投票加载失败，投票个数选择两个以上会出现显示错乱

**复现步骤**
如何复现
1. 打开一个专栏
2. 直接出现内容加载不出来投票异常状况

**截图**
![Screenshot_2021-08-05-22-09-21-567_tv danmaku bil](https://user-images.githubusercontent.com/70379530/128364866-c4a31a5e-0a44-43d1-8934-4134e2b48138.jpg)
![Screenshot_2021-08-05-22-09-29-060_tv danmaku bil](https://user-images.githubusercontent.com/70379530/128364886-ac774709-9338-4df9-9118-54116d6022d6.jpg)
![Screenshot_2021-08-05-22-09-36-389_tv danmaku bil](https://user-images.githubusercontent.com/70379530/128364912-425da28a-d8d1-45d8-80e5-c86d62a1eba9.jpg)
![Screenshot_2021-08-05-22-09-52-598_tv danmaku bil](https://user-images.githubusercontent.com/70379530/128364940-3452b5c3-b608-4277-8ba2-813149f2fbbc.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI12.5 21.7.28
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：正式版6.31.0
 - 使用的框架和版本：[LSPatch] [6.31.0]
 - 其他：https://b23.tv/dmllmW
 - https://b23.tv/7yvpHE
 - https://b23.tv/33XB45

**日志**
[log(2).txt](https://github.com/yujincheng08/BiliRoaming/files/6939315/log.2.txt)

**Comment by yujincheng08** [comment]
CI 版已修复。
