### ISSUE TITLE
希望能支持哔哩哔哩番剧出差这个账号

### ISSUE THREAD

**Issue by YURICORN** [yujincheng08/BiliRoaming#233]
![Screenshot_2021-08-09-17-17-23-418_com.bilibili.app.in.jpg](https://user-images.githubusercontent.com/43528141/128684474-ca2c2fb0-0a7d-4977-99fd-546ae9c00af0.jpg)

**Comment by david082321** [comment]
ci版已修复
https://github.com/yujincheng08/BiliRoaming/actions/runs/1015799453

如果你是用把B站加进太极阴里面，那么不要更新，慢慢等正式版。
