### ISSUE TITLE
[BUG] java.lang.ClassNotFoundException: tv.danmaku.bili.ui.video.playerv2.UgcPlayerFragment

### ISSUE THREAD

**Issue by H4M5TER** [yujincheng08/BiliRoaming#235]
**问题描述**
报错 `java.lang.ClassNotFoundException: tv.danmaku.bili.ui.video.playerv2.UgcPlayerFragment`
使用了不长的一段时间，没有感觉出错误导致了什么后果。

**复现步骤**

1. 打开哔哩哔哩
2. 等待一段时间或等待开屏启动图关闭
3. 出现错误弹窗

**截图**

![Screenshot_2021-08-12-04-33-27-151](https://user-images.githubusercontent.com/21092951/129105876-0e4351a2-a0d7-4144-b662-f8d605bf8191.jpeg)

**环境信息**

 - 安卓版本：10
 - 系统版本：TB-J706F_S243005_210601_ROW
 - 哔哩漫游版本：1.4.5
 - 哔哩哔哩版本和版本号：普通版 6.36.0
 - 使用的框架和版本：LSPosed 1.4.7
 - 其他：（如哪部番、哪个专栏等）

我不确定系统版本是指什么，系统是小新 Pad Pro 的海外版，大概是添加了一些功能的 Stock Android。

**日志**

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6971546/log.txt)

**Comment by david082321** [comment]
漫游版本过低，ci版已经修复了
t.me/biliroaming

**Comment by H4M5TER** [comment]
感谢！
我有看其他 Issue 提到 CI 版，说 LSPosed 的源是 nightly 的，但是我看了一下没找到，这个链接要不要放进 README 呢？

**Comment by david082321** [comment]
> 感谢！
> 我有看其他 Issue 提到 CI 版，说 LSPosed 的源是 nightly 的，但是我看了一下没找到，这个链接要不要放进 README 呢？

模块的关于里面就有TG链接。
Github 的 Action 也能下载。
