### ISSUE TITLE
[Feature] 希望将已删除的功能添加回来

### ISSUE THREAD

**Issue by ajdgsu** [yujincheng08/BiliRoaming#239]
**原因**
我知道有许多选项因为各种各样的原因被移除了，但这并不代表这些选项就一定不好用/不能用。比如说之前的视频倍速功能，虽然自定义播放速度列表不能工作，但是默认播放速度还是可以正常工作的，然而1.4.6版将这个功能移除了，导致我没法升级到最新版(默认倍速对我来说是刚需功能)

**功能简述**
完全可以添加一个不稳定/已废弃的选项区域，将这些不能完美工作的选项都放进去，没准哪个客户端就能正常工作呢?

**功能逻辑**
可以继续在设置栏下面放置，如果嫌太长可以单独做进一个选项里(像手机上的开发者模式那样)

**Comment by david082321** [comment]
其实自定义播放速度，从播放器右上角三点使用，而且显示上有问题，实际上点击是生效的。

但是老是有人来群里说不生效。

**Comment by BoBppy** [comment]
可以考虑自己维护一个仓库，revert掉那条commit，然后用bot来upstream
