### ISSUE TITLE
关于android4.x支持问题

### ISSUE THREAD

**Issue by vocaloidchina** [yujincheng08/BiliRoaming#24]
开发者您好
我有一台闲置已久的安卓平板，系统为android4.3，已root，已装xposed。
然而在从release下载apk包安装时，提示“无法解析的安装包”，猜测由于安卓版本过低无法安装。而xpatch版本一直闪退。
由于平板过老无法再升级系统，因此是否有其他方法在android4.x上使用该插件？
谢谢。

**Comment by yujincheng08** [comment]
改了`minSdkVersion`到14，你试试吧，不保证能用。
[BiliRoaming_1.2.9.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/4944036/BiliRoaming_1.2.9.apk.zip)
