### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yaxuan97** [yujincheng08/BiliRoaming#240]
**问题描述**
发生了什么情况？有什么现状？
使用自定义底栏功能隐藏“我的”后，无法找到设置入口，点击左上角头像也无效。
**复现步骤**
如何复现
1. 打开设置界面，
2. 点击“自定义底栏”，取消勾选“我的”
3. 无法再找到设置入口：“我的”按钮消失，左上角头像点击无效，直接从“哔哩漫游”app点击“打开设置页面”也无效，必须清除数据。

**截图**
![Screenshot_2021-08-16-10-42-17-805_tv danmaku bili](https://user-images.githubusercontent.com/11773871/129505819-0915a04e-0099-42cf-a7a1-5964a4ae9375.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 12.5.3.0（RJNCNXM）
 - 哔哩漫游版本：1.4.6
 - 哔哩哔哩版本和版本号：普通版6.37.1和6.34.0都已测试存在问题
 - 使用的框架和版本：LSPosed 1.5.0（5880）
 - 其他：

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/6989533/log.txt)

**Comment by yujincheng08** [comment]
不是 bug
