### ISSUE TITLE
[BUG]东南亚app测试哔哩漫游出错

### ISSUE THREAD

**Issue by YFTX2015** [yujincheng08/BiliRoaming#243]
**问题描述**
发生了什么情况？有什么现状？
如下图所示
**复现步骤**
如何复现
1. 打开LSPosed，太极阳
2. 点击bilibili
3. 出现如图所示状况

**截图**
点击文本框下面小长条可以上传文件
![1629346271095](https://user-images.githubusercontent.com/12757305/130007385-ecd2dd19-5399-4c57-a41d-5cc205e9aef5.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：miui12.5.5（global）
 - 哔哩漫游版本：1.4.6

 - 哔哩哔哩版本和版本号：东南亚版1.12.1
 - 使用的框架和版本：LSPosed1.5.1(5898) ，太极阳8.0.3，两个都试过
 - 其他：蓝叠国际版上试过太极阴，同样出错
**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[LSPosed_Modules_2021-08-19T12_20_44.068.log](https://github.com/yujincheng08/BiliRoaming/files/7011662/LSPosed_Modules_2021-08-19T12_20_44.068.log)

**Comment by JasonKhew96** [comment]
不支持东南亚版

**Comment by qi-mooo** [comment]
本身哔哩漫游就不支持东南亚。。。。

**Comment by YFTX2015** [comment]
顺便问下，东南亚版是不是国际版？

**Comment by JasonKhew96** [comment]
> 顺便问下，东南亚版是不是国际版？

不太清楚，不过大多数版权都在东南亚地区，提供的字幕也是东南亚的语言（中文只有简体而已

**Comment by YFTX2015** [comment]
我一直以为东南亚版就是国际版，而且我看这边的介绍是支持国际版的，所以才过来的。

**Comment by david082321** [comment]
> 我一直以为东南亚版就是国际版，而且我看这边的介绍是支持国际版的，所以才过来的。

https://play.google.com/store/apps/details?id=com.bilibili.app.in

**Comment by YFTX2015** [comment]
看起来play版就是国际版

**Comment by YFTX2015** [comment]
还有个问题，我看到自建代理解析服务器里面有个泰区的反向代理，不晓得那个能不能够解析出东南亚app里面番剧的音视频地址?

**Comment by david082321** [comment]
> 还有个问题，我看到自建代理解析服务器里面有个泰区的反向代理，不晓得那个能不能够解析出东南亚app里面番剧的音视频地址?

东南亚的解析服务器，就是让你能在原版或play版或概念版，模拟东南亚app的请求。

**Comment by YFTX2015** [comment]
原来如此，那么看来暂时找不到能够捕获app里面音视频地址的脚本了。
