### ISSUE TITLE
[BUG] 所有图片，视频无法加载

### ISSUE THREAD

**Issue by SpaceThing** [yujincheng08/BiliRoaming#244]
**问题描述**
所有图片无法加载，视频间断可播放
文字内容，收藏正常
自己翻墙到新加坡节点反而可以访问（登录github时意外发现）

**复现步骤**
正常使用
关闭漫游和upos也一样无法加载

**截图**
![Screenshot_2021-08-19-21-23-37-548_tv danmaku bili](https://user-images.githubusercontent.com/61451659/130077149-5225a36a-0eab-42d8-ba51-34853bfb7b90.jpg)
![Screenshot_2021-08-19-21-23-45-720_tv danmaku bili](https://user-images.githubusercontent.com/61451659/130077155-87734286-4912-4516-85cc-84aa181742f1.jpg)
![Screenshot_2021-08-19-21-23-51-816_tv danmaku bili](https://user-images.githubusercontent.com/61451659/130077158-181a90f5-c283-499e-a2e2-325bba194bce.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.5 21.6.2
 - 哔哩漫游版本：1.4.6
 - 哔哩哔哩版本和版本号：lspatch版 6.37.1
 - 使用的框架和版本：lspatch
 - 其他：所有

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7014744/log.txt)

**Comment by yujincheng08** [comment]
看起来和漫游没有关系。

**Comment by david082321** [comment]
关闭去广告的软件(例如AdGuard，或是其他使用VPN的)

**Comment by SpaceThing** [comment]
没有用vpn，手机也没有刷magisk
反而用了vpn可以播放，wifi下也可以
log可能有误因为我是后来才存的
