### ISSUE TITLE
能不能加个搜索地区限制番剧的功能

### ISSUE THREAD

**Issue by dofv** [yujincheng08/BiliRoaming#246]
**原因**
加上之后方便，在浏览器用脚本太麻烦

**功能简述**
想要个怎样的功能

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by JasonKhew96** [comment]
为代理服务器增加更多压力？NO
建议去 哔哩哔哩出差 搜 港澳台 番剧
东南亚/泰区 的 已实现

**Comment by david082321** [comment]
1. 搜索UP「哔哩哔哩番剧出差」
2. 在UP空间搜索视频

**Comment by hiahia1234** [comment]
> 为代理服务器增加更多压力？NO 建议去 哔哩哔哩出差 搜 港澳台 番剧 东南亚/泰区 的 已实现

泰区的搜不到啊，schooldays   yosuga no sora都搜不到
