### ISSUE TITLE
能不能有办法看哔哩哔哩出差的主页

### ISSUE THREAD

**Issue by xt1234567788** [yujincheng08/BiliRoaming#250]
**原因**
好找番剧
**功能简述**
想要个怎样的功能

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by JasonKhew96** [comment]
早有了 https://github.com/yujincheng08/BiliRoaming/commit/6033bd17c903e3757b4526fe7c920da269db090d
