### ISSUE TITLE
[Feature]在隐藏功能里添加一个强制显示“按时间顺序”的开关

### ISSUE THREAD

**Issue by YuukoShiori** [yujincheng08/BiliRoaming#251]
**原因**
某官媒的大部分其他非时政视频已经不能按时间顺序查看评论，而且“按时间顺序”总是显示了几秒就很快消失

**功能简述**
在评论区的右上角强制添加“按时间顺序”（如果没有的话）

**功能逻辑**
开启隐藏功能并且开启强制显示“按时间顺序”之后，没有“按时间顺序”的视频评论区会显示这个按钮。

![IMG_20210823_165049](https://user-images.githubusercontent.com/47733293/130418852-941e2dce-c771-43c0-9d4c-2b465cfa8ec2.jpg)

**Comment by duzhaokun123** [comment]
api限制 做不到
