### ISSUE TITLE
[BUG]无法分享视频至微信

### ISSUE THREAD

**Issue by ChristianZly** [yujincheng08/BiliRoaming#254]
**问题描述**
发生了什么情况？有什么现状？
无法分享视频至微信和微信朋友圈
**复现步骤**
如何复现
1. 打开一个视频
2. 点击分享至微信或朋友圈
3. 出现“签名不对，请检查签名是否与开放平台上填写的一致”状况

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2021-08-24-15-42-04-922_tv danmaku bil](https://user-images.githubusercontent.com/88143739/130577830-90ab0bce-75a9-44ad-94ed-ca52931969dc.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 12.5 21.8.20
 - 哔哩漫游版本：1.46
 - 哔哩哔哩版本和版本号：正式版6.37.1（如概念版6.2.3）
 - 使用的框架和版本：LSPatch（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7037507/log.txt)

**Comment by yujincheng08** [comment]
无解。请 root 手机。
