### ISSUE TITLE
[BUG]漫游1.4.6搭配5.58.0 视频详情页没有推荐视频

### ISSUE THREAD

**Issue by MCFreeGod** [yujincheng08/BiliRoaming#256]
**问题描述**

**复现步骤**
如何复现
1. 打开B站客户端
2. 点击随便一个视频
3. 视频下方的推荐视频消失不见，但1.4.4版本没有这个问题

**截图**
![Screenshot_2021-08-25-16-07-08-832_tv danmaku bili](https://user-images.githubusercontent.com/76932277/130753674-c00820ba-58a2-4d0d-804e-613a7504ac87.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 21.8.23
 - 哔哩漫游版本：1.4.6
 - 哔哩哔哩版本和版本号：官方版5.58.0
 - 使用的框架和版本：LSP 1.3.1
 - 其他：所有视频

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7045122/log.txt)

**Comment by yujincheng08** [comment]
旧版本不再提供支持
