### ISSUE TITLE
[Feature] 建议净化动态页的“创作推广”广告

### ISSUE THREAD

**Issue by Samachurl** [yujincheng08/BiliRoaming#260]
**原因**
动态页出现了“创作推广”这种新形式的广告
![EB0YCTMSZ0F2E6U~K%4YQ4P](https://user-images.githubusercontent.com/48409650/131111798-585a60bc-a4a8-4151-8816-27c7f7f9e51c.jpg)

**功能简述**
建议净化动态页的“创作推广”广告

**功能逻辑**
建议默认净化

**Comment by yujincheng08** [comment]
Duplicate of #190
