### ISSUE TITLE
用最新版的自动点赞功能，他点了然后自动取消[BUG]

### ISSUE THREAD

**Issue by aekcool** [yujincheng08/BiliRoaming#267]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 打开...自动点赞
2. 点击...默认功能
3. 出现...状况自动取消点赞

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2021-09-10-10-30-29-420_tv danmaku bili](https://user-images.githubusercontent.com/68363567/132789711-73f2abcd-2f25-46e7-96bd-ac90c4e94a8f.jpg)
![Screenshot_2021-09-10-10-30-27-574_tv danmaku bili](https://user-images.githubusercontent.com/68363567/132789719-f26dbe4d-c739-4f97-a275-a72d3db0edcf.jpg)
**环境信息**
 - 安卓版本：安卓11
 - 系统版本：小米11ultra miui 开发版9.1

 - 哔哩漫游版本：1.4.6
 - 哔哩哔哩版本和版本号：6.37.1
 - 使用的框架和版本lsposed
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by aekcool** [comment]
不知道怎么上传日志

**Comment by yujincheng08** [comment]
无法复现。

**Comment by aekcool** [comment]
https://wwe.lanzoui.com/i5gcDttpd4f 日志文件
