### ISSUE TITLE
[BUG]关闭运行信息提醒后仍然显示

### ISSUE THREAD

**Issue by kcn3388** [yujincheng08/BiliRoaming#28]
新版本1.2.9取消了提示模块运行信息后仅会不提示启动时的运行信息，进入番剧或电影页面仍会提示已允许下载信息。
另外，设置页的哔哩漫游设置图标是灰色的，希望改成与主题色一致。
![S00724-05285080](https://user-images.githubusercontent.com/25716090/88340579-a5cd1900-cd6e-11ea-91b6-30507121f87e.png)

 - 安卓版本：Android 10
 - 系统版本：Flyme 8.20.7.21 daily
 - 哔哩漫游版本：1.29
 - 哔哩哔哩版本和版本号：6.5.0
 - 使用的框架和版本：edxposed v0.4.6.2(4529)(SandHook)

log在此
[Jul 24, 2020 05:22:24.log](https://github.com/yujincheng08/BiliRoaming/files/4968899/Jul.24.2020.05.22.24.log)

**Comment by yujincheng08** [comment]
早在https://github.com/yujincheng08/BiliRoaming/commit/822326352848f6daa789d8b4c459e0c2d144a156 中修了

**Comment by yujincheng08** [comment]
> 另外，设置页的哔哩漫游设置图标是灰色的，希望改成与主题色一致。

这是故意的。
