### ISSUE TITLE
[Feature]解除手机端1080P投屏限制

### ISSUE THREAD

**Issue by SpeedPartner** [yujincheng08/BiliRoaming#284]
**原因**
由于B站开始推广TV版的云视听小电视,手机端新版本投屏功能不再支持直接投屏1080P视频,看下是否可以取消这个限制

**功能简述**
解除手机端1080P投屏限制

**功能逻辑**
修改为之前版本的投屏逻辑,重新支持直接投屏1080P视频

**实现参考**

**Comment by amlkiller** [comment]
希望可以更进一步，恢复6.41最后一个版本的4K、杜比视界投屏。

**Comment by duzhaokun123** [comment]
一个想法是
获取单文件的视频流 通过 DLNA 投屏

**Comment by amlkiller** [comment]
> 一个想法是 获取单文件的视频流 通过 DLNA 投屏 这会替代 b站 自己的投屏实现

这就是 DLNA 的原理，将视频地址发给电视播放，手机和电视同步播放状态。
实现可以调用回旧的投屏或者直接改现有的，在投屏画质那做修改，使得能获取1080p的视频流来推送，这样支持会好些，功能也完整。
如果是单获取在视频流，然后在漫游里集成投屏扩展来通过它投屏也可以，但是会麻烦的多，不如单独做个xp模块，另外播放控制也要自己来。

**Comment by amlkiller** [comment]
本质上现在投屏画质限制还是在前端实现的，应该容易解决，就是没学过这个方面的，没法自己造轮子。(ノ｀⊿´)ノ

**Comment by yujincheng08** [comment]
似乎已经获取不了适合透明的 1080P 流地址了，只能用小电视了。

**Comment by david082321** [comment]
> 似乎已经获取不了适合透明的 1080P 流地址了，只能用小电视了。

貌似可以用 `mobi_app=android_pad_bot` 取得 1080p，甚至 1080p+
https://api.bilibili.com/pgc/player/api/playurl?access_key=■&aid=426119051&appkey=1d8b6e7d45233436&build=101718&buvid=■&cid=587731665&device=android&expire=1677260321&fnval=0&fnver=0&fourk=1&mid=23682052&mobi_app=android_pad_bot&module=bangumi&npcybs=0&otype=json&platform=android&qn=112&season_type=4&session=■&ts=1661708353&sign=■

**Comment by yandujun363** [comment]
所以这个不打算实现了吗
