### ISSUE TITLE
[Feature]长按动态复制相关

### ISSUE THREAD

**Issue by sunfkny** [yujincheng08/BiliRoaming#285]
**原因**
除了评论，动态也有长按复制，可以考虑给动态也加上 #282 的功能，使长按的效果统一

**功能简述**
长按动态时弹出一个对话框显示动态内容以便选择复制

**功能逻辑**
长按动态弹出动态内容对话框

**实现参考**
#282

**Comment by Henry-ZHR** [comment]
突然发现好像可以直接截胡 Clipboard，不用跟 `onLongClick` 斗智斗勇，就是 Toast 可能有点怪🤔
