### ISSUE TITLE
[Feature]Play版准许个性装扮使用

### ISSUE THREAD

**Issue by bwmgd** [yujincheng08/BiliRoaming#286]
**原因**
之前一直用原版的修改版，但是没有长按加速，而原版的标签太冗余而且有智障的+号，因此改用了play版，但只有颜色的主题有点不习惯

**功能简述**
可以实现个性装扮的加载

**功能逻辑**
添加个性装扮的按钮，实现可以更换到以购买的个性装扮

**实现参考**
在评论区点进去个性装扮的详情页，提示该服务在当前地区暂不服务，或许可以通过dns解析来实现个性装扮吗

**Comment by yujincheng08** [comment]
一个猜想，不一定对，原版的 + 号是不是可以去掉？

**Comment by dselegant** [comment]
> 一个猜想，不一定对，原版的 + 号是不是可以去掉？

不清楚，好像都是通过安装旧版去+号

**Comment by yujincheng08** [comment]
> > 一个猜想，不一定对，原版的 + 号是不是可以去掉？
> 
> 不清楚，好像都是通过安装旧版去+号

有没有可能漫游本身就支持去+号

**Comment by david082321** [comment]
原版的标签和+号，都用漫游能去掉
