### ISSUE TITLE
[BUG]评论区显示楼层功能失效

### ISSUE THREAD

**Issue by 1411484730** [yujincheng08/BiliRoaming#30]
哔哩哔哩版本6.6.0
哔哩漫游版本1.2.9
![Screenshot_2020-08-04-01-08-14-246_tv danmaku bili](https://user-images.githubusercontent.com/69163070/89208613-4208e280-d5ef-11ea-9b7c-62e6a0c4936e.jpg)
![Screenshot_2020-08-04-01-10-54-871_tv danmaku bili](https://user-images.githubusercontent.com/69163070/89208668-5f3db100-d5ef-11ea-866f-b082d358741e.jpg)

**Comment by yujincheng08** [comment]
Fixed in bdc4bc525b2917ade10f10ff324b4e923e016477
