### ISSUE TITLE
[BUG]1.5.0版，底栏添加频道功能消失 

### ISSUE THREAD

**Issue by jatalins** [yujincheng08/BiliRoaming#307]
**问题描述**
1.4.9版还有这个功能，1.5.0版里没有相关设置了，请问是取消了这个功能还是bug了

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：10
 - 系统版本：10
 - 哔哩漫游版本：1.5.0
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7461131/log.txt)

点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
取消了 https://github.com/yujincheng08/BiliRoaming/pull/305#issuecomment-955664006
