### ISSUE TITLE
[Feature]屏蔽哔哩哔哩动态上方的频道与话题

### ISSUE THREAD

**Issue by sche11** [yujincheng08/BiliRoaming#314]
**原因**
占据面积太大，打扰体验，可以看作是广告。

**功能简述**
类似首页屏蔽广告，屏蔽这一块

**功能逻辑**
**实现参考**
我使用了godmode，但用一段时间后，经常丢失视频，指up发布动态视频，只能看见up头像，视频也一并屏蔽了，体验很糟糕。

**Comment by wdxfy** [comment]
+1

**Comment by david082321** [comment]
#555

**Comment by zjns** [comment]
This issue should be closed now. @yujincheng08
