### ISSUE TITLE
[BUG]加速CDN设置测速一直失败  应用版本： bilibiliHD 1.60  

### ISSUE THREAD

**Issue by GaoJaJnn** [yujincheng08/BiliRoaming#317]
**问题描述**
bilibiliHD应用，UPOS测速一直失败导致港澳番剧解锁不了，已配置 
**复现步骤**
如何复现
1. 打开 哔漫设置
2. 点击 UPOS加速
3. 出现...状况 加速失败

**截图**
![Screenshot_2021-11-17-23-42-55-434_tv danmaku bilibilihd](https://user-images.githubusercontent.com/38997906/142232910-77daac78-a696-4137-ad54-1a046ce95938.jpg)
![Screenshot_2021-11-17-23-42-49-215_tv danmaku bilibilihd](https://user-images.githubusercontent.com/38997906/142232938-dcca0921-80fa-4c03-9fe8-c730f716238c.jpg)

点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：小米平板5Pro 开发版21.11.10
 - 哔哩漫游版本：1.51
 - 哔哩哔哩版本和版本号：HD版1.6
 - 使用的框架和版本：Magick 23.0 lsposed 1.6.3
 - 其他：港澳番剧

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7556000/log.txt)

无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by Juveline2000** [comment]
求大佬们解决 开了VPN和不开VPN测速我都试过了

**Comment by yujincheng08** [comment]
11-17 23:48:30.923 25152 25433 E BiliRoaming: getContent error: java.net.SocketTimeoutException: Read timed out with url https://anye.257053.xyz/pgc/player/api/playurl

明显网络问题
