### ISSUE TITLE
[BUG]安卓12闪退

### ISSUE THREAD

**Issue by tachikoma233** [yujincheng08/BiliRoaming#319]
**问题描述**
发生了什么情况？有什么现状？
app闪退，无法打开
**复现步骤**
如何复现
1. 打开哔哩哔哩app
2. 出现闪退状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：安卓12
 - 系统版本：MIUI12.5 21.11.12
 - 哔哩漫游版本：1.51
 - 哔哩哔哩版本和版本号：普通版6.49.1
 - 使用的框架和版本：太极 曳影 7.0.0.02111627-6757
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7570051/log.txt)
件

**Comment by yujincheng08** [comment]
太极的问题
