### ISSUE TITLE
哔哩哔哩6.7.0番剧解锁失效

### ISSUE THREAD

**Issue by expliyh** [yujincheng08/BiliRoaming#32]
哔哩哔哩版本：6.7.0
模块版本：1.3.0
哔哩哔哩6.7.0番剧解锁失效（没有token提示）
![Screenshot_2020-08-14-14-13-09-921_tv danmaku bili](https://user-images.githubusercontent.com/54161210/90219410-9191ae80-de38-11ea-839d-63e083f3338a.jpg)
![Screenshot_2020-08-14-14-13-32-743_tv danmaku bili](https://user-images.githubusercontent.com/54161210/90219430-9e160700-de38-11ea-97f8-8b7c6aadd704.jpg)

**Comment by expliyh** [comment]
而且强行结束模块再打开运行环境会变成Xposed/ Exposed（我用的是太极）

**Comment by yujincheng08** [comment]
no log no fix
