### ISSUE TITLE
[Feature]能否禁用小视频模式

### ISSUE THREAD

**Issue by oOtroyOo** [yujincheng08/BiliRoaming#326]
**原因**
一直觉得竖屏小视频模式很烦 ，视频和直播点开都可能会出现这种模式，直播已经可以禁用了，所以视频里面想上划翻评论，结果他翻到另一个人去了。

**功能简述**
希望禁用他，然后以常规视频模式打开视频。

**功能逻辑**
如上

**实现参考**
如果有其他方式，设置或者其他xposed模块，可以分享吗

**Comment by duzhaokun123** [comment]
其实可以直接净化`竖屏视频`
