### ISSUE TITLE
[BUG]视频中不能滑动调整音量

### ISSUE THREAD

**Issue by HortenseP** [yujincheng08/BiliRoaming#329]
**问题描述**
视频中上下滑动不能调整音量 调亮度有效果

**复现步骤**
上下滑动会出现音量变动的动画  但实际没有调整 下次滑动还是从之前的位置开始变动

**环境信息**
 - 安卓版本：9
 - 系统版本：10.3.17
 - 哔哩漫游版本：1.5.1
 - 哔哩哔哩版本和版本号：普通版6.50.0
 - 使用的框架和版本：太极阳8.0.6

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7595561/log.txt)

**Comment by duzhaokun123** [comment]
绝了 和漫游有关吗

**Comment by HortenseP** [comment]
> 

应该有吧  把bilibili从太极里移走  就正常了

**Comment by HortenseP** [comment]
草啊  好像是太极的问题   把漫游停用了也这样

**Comment by HortenseP** [comment]
解决了解决了  原来是很早之前安过一个非系统不能调节音量插件  都忘了   然后把b站加到太极里受那个影响了
