### ISSUE TITLE
[BUG]太极不兼容最新版本的模块

### ISSUE THREAD

**Issue by johnsteveabc** [yujincheng08/BiliRoaming#333]
**问题描述**
刚刚更新最新版本哔哩漫游，太极不兼容最新版本的模块

**复现步骤**
如何复现
1. 打开太极
2. 点击模块管理
3. 长按哔哩漫游
4. 查看支持版本
5. 发现不支持1.5.2版本

**截图**
![WeChat 圖片_20211129113348](https://user-images.githubusercontent.com/54939231/143805052-787e4376-a7c4-4541-b7c7-f0c322fbc5a8.jpg)
![WeChat 圖片_20211129113343](https://user-images.githubusercontent.com/54939231/143805065-57f28a1f-fee5-4ec9-9afc-07e9735acaa6.jpg)
![WeChat 圖片_20211129113335](https://user-images.githubusercontent.com/54939231/143805073-350cf548-d881-41ca-aade-bc2a75a7cae5.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：EMUI 10.0.0
 - 哔哩漫游版本：1.5.2
 - 哔哩哔哩版本和版本号：原版6.50.0
 - 使用的框架和版本：太极 含光8.0.6.10181842-6778
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
我能有什么办法？

**Comment by david082321** [comment]
太极会审核模块，等太极自己审核好就可以用了。
（大概等十天半个月吧，毕竟太极作者沉迷游戏）

**Comment by johnsteveabc** [comment]
现在能用了
