### ISSUE TITLE
[Feature]去除动态长按复制

### ISSUE THREAD

**Issue by V-arc** [yujincheng08/BiliRoaming#339]
**原因**
现在已经有了去除评论长按复制，减少了很大一部分误触的可能。但是动态界面仍然会长按复制。

**功能简述**
去除动态长按复制

**功能逻辑**
与屏蔽评论长按复制相同

**实现参考**

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/ed37f6dce877b4c510bae761bbea8d940a190635
