### ISSUE TITLE
[BUG]哔哩哔哩5.48.3番剧解锁失效

### ISSUE THREAD

**Issue by 10935336** [yujincheng08/BiliRoaming#34]
**问题描述**
在哔哩哔哩5.48.3上使用哔哩漫游1.3.3.2版本，番剧解锁功能失效，其他功能正常。
尝试退回到哔哩漫游1.2.9版本，仍然失效。
不会显示您所在的地区无法观看，但无法成功加载视频。
尝试移动4G与移动Wifi均加载失败。

**复现步骤**
1.打开EdXopsed安装哔哩漫游1.3.3.2
2.激活哔哩漫游并重启手机
3.设置哔哩漫游并重启哔哩哔哩
4.打开哔哩哔哩观看港澳台番剧
5.加载失败

1.卸载哔哩漫游1.3.3.2
2.打开EdXopsed安装哔哩漫游1.2.9
3.激活哔哩漫游并重启手机
4.设置哔哩漫游并重启哔哩哔哩
5.打开哔哩哔哩观看港澳台番剧
6.加载失败

**截图**
![Screenshot_2020-09-14-21-54-47-994_tv danmaku bil](https://user-images.githubusercontent.com/32383605/93094801-f3ae2f80-f6d4-11ea-926e-2b1e4423a3f9.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12 20.9.4 开发版
 - 哔哩漫游版本： 1.3.3.2/1.2.9
 - 哔哩哔哩版本和版本号：普通版 5.48.3 (release-b2766331)
 - 使用的框架和版本：EdXopsed v0.4.6.2 (4259) (YAFHA)
 - 其他：所有港澳台番剧

**日志**
[log1.txt](https://github.com/yujincheng08/BiliRoaming/files/5218886/log1.txt)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5218885/log.txt)

**Comment by yujincheng08** [comment]
最低只能保证5.58解锁功能是兼容的。
