### ISSUE TITLE
[Feature]直播画质直接使用原画

### ISSUE THREAD

**Issue by Edfgdz** [yujincheng08/BiliRoaming#344]
**原因**
每次看直播的时候，画质都不是原画，导致画面有点模糊，需要每次把画质调成原画，太麻烦

**功能简述**
打开直播观看的时候画质直接是原画

**功能逻辑**
在模块里面添加这个设置，打开以后生效

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
让官方去做
