### ISSUE TITLE
[Feature]增加类似视频屏蔽的动态屏蔽

### ISSUE THREAD

**Issue by TobyLi223** [yujincheng08/BiliRoaming#353]
原因
大量的雷同动态影响使用

功能简述
用户可以自己屏蔽用户黑名单中的的动态，也可以添加关键词屏蔽动态，和别人转发的动态。

功能逻辑
类似视频屏蔽

**实现参考**

**Comment by yujincheng08** [comment]
可以取关

**Comment by TobyLi223** [comment]
但是这样会错过up的别的内容啊

**Comment by TobyLi223** [comment]
怎么变成closed了？

**Comment by TobyLi223** [comment]
是技术层面做不到还是心理层面不想做？

**Comment by TobyLi223** [comment]
> 可以取关

你有在听我说吗？但是这样会错过的内容啊！如果实现起来困难的话那就说啊，留下一个有问题的解决方法就关闭提案？就这么不想让别人看到吗？
我很抱歉在T群里闹的不愉快，但是这属于软件提供者的霸道，我期待者像去广告一样开源自由开发者能够理解并且修复这个问题，或者至少和我好好交流完，而不是留下一句取关然后就结束讨论。
至少你赋予了我们不可广告，可以看港澳台的权利，这点我很感激。请给予我们能够选择信息来源的权利吧！

**Comment by KyuubiRan** [comment]
自相矛盾了

**Comment by KyuubiRan** [comment]
只能说 鱼和熊掌不可兼得

**Comment by BraveSail** [comment]
什么魔怔需求

**Comment by 3JoB** [comment]
我只能說笑死
