### ISSUE TITLE
[BUG]自由复制评论失效

### ISSUE THREAD

**Issue by wukibaka** [yujincheng08/BiliRoaming#357]
**问题描述**
自由复制评论失效

**复现步骤**
打开“长按自由复制”
重启b站
再重启b站
随意打开一个视频
复制评论区评论显示 “哔哩漫游：找不到评论内容”

**截图**
![Screenshot_20211215-210824__01](https://user-images.githubusercontent.com/51240031/146192148-b388ab79-6539-4078-bcde-2bced70e4347.jpg)

**环境信息**
 - 安卓版本：安卓Q
 - 系统版本：H2OS 10.0.3
 - 哔哩漫游版本：a9d3ef8d64
 - 哔哩哔哩版本和版本号：play版3.3.0
 - 使用的框架和版本：LSPosed 1.6.5 (6282) - Zygisk
 - 其他：

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/7719573/log.txt)

**Comment by yujincheng08** [comment]
play 3.6.0 测试没问题
