### ISSUE TITLE
功能建议 去首页随机出现的广告

### ISSUE THREAD

**Issue by cmmdwl** [yujincheng08/BiliRoaming#36]
**原因**
为什么想要这个功能
web端可以靠插件去广告
**功能简述**
想要个怎样的功能
去除首页的随机广告
**功能逻辑**
如何互交、如何使用等
删掉广告![Screenshot_2020-10-08-00-36-55-790_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/21263352/95360874-9b96d180-08fe-11eb-9250-30b170616e33.jpg)
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
尝试过，但是效果不好，所以不会做。
