### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lsyeuhai** [yujincheng08/BiliRoaming#360]
**问题描述**
在对漫游设置并重启客户端之后，视频详情页下方不显示推荐视频（设置中的推荐窗口已打开）

**复现步骤**
如何复现
1. 打开哔哩漫游设置，调整部分设置后点击重启客户端
2. 点击推荐一栏的视频进入详情页
3. 出现下方没有推荐视频状况

**截图**
![1640007516510](https://user-images.githubusercontent.com/76641257/146776091-5dd8fb57-b74a-4fd7-b387-7342e99f7b51.jpg)

**环境信息**
 - 安卓版本：Android11
 - 系统版本：MIUI12.5.7.0
 - 哔哩漫游版本：1.5.3
 - 哔哩哔哩版本和版本号：普通版5.58.0
 - 使用的框架和版本：太极8.0.6.10181842-6834
 - 其他：

**日志**
入职文件为0B，打开里面什么页没有，发送时直接显示无效文件

**Comment by yujincheng08** [comment]
5.58 不提供额外支持
