### ISSUE TITLE
[BUG]首页过滤指定uid和用户名还会被刷到

### ISSUE THREAD

**Issue by Enaium** [yujincheng08/BiliRoaming#367]
**问题描述**
首页过滤指定uid和用户名还会被刷到

**复现步骤**
如何复现
1. 打开b站
2. 刷新主页
3. 出现被指定uid和用户名up主发的视频

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：11
 - 哔哩漫游版本：最新
 - 哔哩哔哩版本和版本号：play版3.6
 - 使用的框架和版本：lsposed最新

**日志**
GitHub客户端只能上传图片 所以要把后缀改为zip
![LSPosed_2021-12-25T17_25_25.122.jpg](https://user-images.githubusercontent.com/32991121/147382106-5cd644be-7c1e-4bcc-beae-c5c22198567a.jpg)

**Comment by yujincheng08** [comment]
最新版是什么版本？我没发布过最新版这种版本号。

**Comment by Enaium** [comment]
[![Tdjhy8.png](https://s4.ax1x.com/2021/12/26/Tdjhy8.png)](https://imgtu.com/i/Tdjhy8) latest不是最新的意思吗
