### ISSUE TITLE
[BUG]Xpatch版在魅族15上无法正常运作

### ISSUE THREAD

**Issue by Epifall** [yujincheng08/BiliRoaming#37]
**问题描述**
Xpatch版第一次打开时没问题，但是开启插件功能之后，再次打开会闪退

**环境信息**
 - 安卓版本：7.1.1
 - 系统版本：Flyme 8.0.5A
 - 哔哩漫游版本：1.3.6
 - 哔哩哔哩版本和版本号：6.10.0
 - 使用的框架和版本：Xpatch版
 - 其他：无

**日志**
移动端不方便上传log，使用奶牛快传代替，请谅解
https://cowtransfer.com/s/de426a1aa5da4a
取件码rxvh9g

**Comment by yujincheng08** [comment]
系统或手机兼容问题，和模块无关。用32位屁事没有。

**Comment by yujincheng08** [comment]
sandhook问题。64位下方法太短所以hook失败。在32位下方法够长所以才hook成功。16bytes(64bit)/8bytes(32bit)。安卓8或以上不会有此问题。
