### ISSUE TITLE
[Feature]阻止尝试观看离线缓存时，客户端会优先在线播放的神奇逻辑

### ISSUE THREAD

**Issue by tjsky** [yujincheng08/BiliRoaming#373]
**原因**
两个原因：
1. 手机连着流量或者WIFI，稿件也能在线播放，但是这会儿流量不够或者WIFI不好，我还是想看缓存而不是在线看。
2. 如果是已经被阿B删了的，每次去看离线缓存时，如果手机为联网状态，那么阿B会尝试在线播放，然后因为稿件被删了，就无法播放。

上述问题估计很多人都知道怎么办，
就是在尝试播放离线缓存的第一个视频时，把网断了。
等播放开始后，再把网连上，就好了。
阿B只会在播放第一个稿件时检测一下网络，
只要这个时候没有网，阿B就会老老实实播放缓存内容
不过每次播放前都手动开关一下网络还挺费劲的。
不知道漫游可否让这个过程自动化解决？

**功能简述**

- 阻断播放离线缓存内容时，阿B跳转到在线播放的行为。

**功能逻辑**

- 在尝试播放离线缓存时阻断阿B的联网或让阿B以为没有网络。

**实现参考**

- 我想了三种思路，不知道哪种兼容性会好一点
1. 只对阿B删除的稿件进行阻断：抢在阿B前检测稿件，如果稿件失效再阻断阿B的联网。
2. 在播放前对所有离线缓存稿件阻断：从进入离线缓存页面到第一个视频被成功播放之间，阻断阿B客户端的联网。
3. 最简单粗暴的方式：在进入离线缓存页面，播放离线缓存内容时，一直阻断阿B的联网，离开离线缓存页面再恢复网络。

主要目的就是让阿B的客户端别搞什么播放离线内容时，优先尝试在线播放，我要是随时能联网播放，我还离线他干什么？
虽然也可以用漫游的离线导出功能，导出离线内容后，用其他播放器看，但还是麻烦了点。

**Comment by yujincheng08** [comment]
应该向官方反馈。
