### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by QingXuer** [yujincheng08/BiliRoaming#379]
**问题描述**
泰区番剧无法开启1080p及以上画质，开启则表现为黑屏

**复现步骤**
如何复现
1. 打开泰区番剧
2. 点击清晰度，切换至1080p或1080p60f
3. 出现番剧视频黑屏状况

**截图**
![Screenshot_2022-01-08-02-45-25-166_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/97309254/148591778-d73db13a-8960-4cb6-8e1f-aad0ebc6d132.jpg)![Screenshot_2022-01-08-02-45-17-252_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/97309254/148591799-7f2c72c1-d269-4acf-8b74-96a91a43d644.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.5
 - 哔哩漫游版本：1.5.5
 - 哔哩哔哩版本和版本号：6.55.0
 - 使用的框架和版本：lsp1.6.5
 - 其他：所有的泰区番剧

**日志**
无
个人猜想：服务器登不上账号，无法使用1080p及1080p60f清晰度，导致黑屏，但720p及一下均无此bug

**Comment by david082321** [comment]
泰国(东南亚哔哩哔哩)的用户系统是独立的一套，东南亚会员也是需要额外付费。与主站的登录用户及大会员，皆不相通。

| 可观看最高画质 | 主站   | 东南亚 |
|----------------|--------|--------|
| 未登录         | 720p   | 480p   |
| 登录           | 1080p  | 720p   |
| 付费会员       | 全解锁 | 全解锁 |

如上所示，其实你只能看到东南亚的480p。
你能看到720p，是因为解析服务器帮你了。不然你登录的是主站的号，东南亚哔哩哔哩只会认为你没登录。

ps. 前段时间能看1080p，是因为之前东南亚有活动免费送短期的付费会员，刚好最近都该到期了。
