### ISSUE TITLE
[Feature]屏蔽视频上层投票overlay

### ISSUE THREAD

**Issue by 0x00Finch** [yujincheng08/BiliRoaming#380]
**原因**
只想好好看个视频，非得弹出一个投票，关闭按钮还那么小，而且遮挡视频内容

**功能简述**
最好在插件里加个开关，可以关闭视频播放时候的pop up 投票功能

**功能逻辑**
用开关关闭

**实现参考**
无

**Comment by yujincheng08** [comment]
这个东西在 native 上，xposed 不能搞定。

**Comment by 0x00Finch** [comment]
> 这个东西在 native 上，xposed 不能搞定。

反射不行吗？
