### ISSUE TITLE
[Feature]首页推荐过滤掉关闭评论区或者弹幕的视频

### ISSUE THREAD

**Issue by Enaium** [yujincheng08/BiliRoaming#386]
**原因**
不能发弹幕不能评论，就没看这个视频的意义了

**功能简述**
首页推荐过滤掉关闭评论区或者弹幕的视频

**功能逻辑**
勾选过滤关闭评论区或弹幕的视频选项框

**Comment by JasonKhew96** [comment]
串别人视频底下发评论发弹幕就有意义？
而且底下大部分都是宣传人，对 漫游/解析服务器 没有帮助，反而拖累 解析服务器

**Comment by yujincheng08** [comment]
不会支持。首页视频列表接口没描述视频是否开启评论区或弹幕。手动查询会触发大量请求而导致账号被封。不会支持。
