### ISSUE TITLE
[Feature]能否重新加入默认倍速功能

### ISSUE THREAD

**Issue by watermelonfree** [yujincheng08/BiliRoaming#391]
**原因**
不知道为什么取消这个功能，它真的太好用了，能否重新加入进来。以前有这个功能的版本的漫游没办法适配最新的谷歌版了

**功能简述**
想要个怎样的功能

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
因为无人维护该功能。
