### ISSUE TITLE
更新1.1.15后仍然无法生效

### ISSUE THREAD

**Issue by dv3lood** [yujincheng08/BiliRoaming#4]
k20pro miui开发版3.26
模块中显示已激活，但是应用中并没有启用相应的功能和净化

**Comment by yujincheng08** [comment]
发我adb的logcat？

**Comment by dv3lood** [comment]
> 发我adb的logcat？

怎么输出啊？具体命令是什么求指导。

**Comment by yujincheng08** [comment]
应该已经修复了，试试这个@dv3lood 
[BiliRoaming_1.1.15.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/4442154/BiliRoaming_1.1.15.apk.zip)
