### ISSUE TITLE
[Feature]支持净化首页所有标签

### ISSUE THREAD

**Issue by Edfgdz** [yujincheng08/BiliRoaming#410]
**原因**
净化所有主页标签以后，打开APP能够直接使用搜索功能来搜索想要的内容，不会被任何推荐内容干扰

**功能简述**
如标题所说

**功能逻辑**
支持净化所有标签

![Screenshot_2022-01-28-11-34-06-435_tv danmaku bili](https://user-images.githubusercontent.com/26460124/152150905-ce323387-62c3-4e67-a87f-e4db7771b8d8.jpg)

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
你把首页删了不就好。

**Comment by david082321** [comment]
你是想要开启的时候，自动跳转到搜索页？
[试试点这个？](bilibili://search) `

**Comment by Edfgdz** [comment]
其他三个页面没有搜索框咋办？

![Screenshot_2022-02-02-20-18-15-039_tv danmaku bili](https://user-images.githubusercontent.com/26460124/152152948-8cc4ff54-72d2-4f41-bb31-cef2985ddc22.jpg)

![Screenshot_2022-02-02-20-18-19-620_tv danmaku bili](https://user-images.githubusercontent.com/26460124/152152963-d74ed5fa-3ed9-4b51-bcd2-51b8bf8845c7.jpg)

![IMG_20220202_201854](https://user-images.githubusercontent.com/26460124/152152973-0c311482-a4fc-47e3-8ca2-180d8c823243.png)
