### ISSUE TITLE
[Feature]长按首页推荐视频直接将对应理由添加至过滤器

### ISSUE THREAD

**Issue by greenredstone** [yujincheng08/BiliRoaming#414]
**原因**
为什么想要这个功能
看见一个手动加一个费劲

**功能简述**
想要个怎样的功能
直接将up主、推荐原因（xx点赞、xx投币等）、分区、频道等一键添加到过滤器

**功能逻辑**
如何互交、如何使用等
借助官方长按菜单长按直接添加

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by articuly** [comment]
实现参考
大圣净化中，八戒模块利用无阻碍助手可代替人手多次点击举报或关闭不喜欢的视频、广告。
