### ISSUE TITLE
[Feature]首页关键词过滤相关

### ISSUE THREAD

**Issue by xiaole3349** [yujincheng08/BiliRoaming#419]
**原因**
因为很多想屏蔽的关键词总是能整出些不同的写法导致多了一大堆关键词。当然，正则没尝试（因为不知道能不能使用正则）。

**功能简述**
让首页过滤不区分大小写

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
就是强匹配
