### ISSUE TITLE
开启竖屏视频更改为普通视频这个功能时候闪退[BUG]

### ISSUE THREAD

**Issue by CCNOTXX** [yujincheng08/BiliRoaming#426]
**问题描述**
开启竖屏视频更改为普通视频这个功能时候，打开竖屏视频会卡死然后闪退

**复现步骤**
如何复现
1. 打开替换竖版视频功能重启App
2. 随意点击一个竖屏视频
3. 出现卡死闪退状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：安卓11
 - 系统版本：一加7Pro 的 Flyme 9.21.7.26第三方包
 - 哔哩漫游版本：1.5.6
 - 哔哩哔哩版本和版本号：普通版6.43.0（如概念版6.2.3）
 - 使用的框架和版本：Lsp1.6.5（6272）（如太极6.3.0）
 - 其他：
[比例漫游bug.txt](https://github.com/yujincheng08/BiliRoaming/files/8034364/bug.txt)
（如哪部番、哪个专栏等）

**日志**
已上传Log

**Comment by yujincheng08** [comment]
不支持 6.43.0
