### ISSUE TITLE
[BUG]强制旧版直播间依旧显示新版

### ISSUE THREAD

**Issue by iblade0918** [yujincheng08/BiliRoaming#428]
**问题描述**
【强制旧版直播间样式】选项开启状态下，打开直播间仍然为新版样式

**复现步骤**
如何复现
1. 打开【强制旧版直播间样式】选项
2. 点击任意直播间
3. 出现打开直播间仍然为新版样式状况

**截图**
![S20211-14135804](https://user-images.githubusercontent.com/43067123/153546886-51b1ec79-c12a-468b-8177-1de74bafc675.png)

**环境信息**
 - 安卓版本：11
 - 系统版本：Flyme 9.2.4.2A
 - 哔哩漫游版本：1.5.7
 - 哔哩哔哩版本和版本号：[LSPatch] [1.5.7] [6.59.0] 哔哩哔哩.apk
 - 使用的框架和版本：集成LSPatch框架版
 - 其他：（如哪部番、哪个专栏等）

**日志**
[文本(2017-10-15 073455).txt](https://github.com/yujincheng08/BiliRoaming/files/8046350/2017-10-15.073455.txt)

**Comment by yujincheng08** [comment]
下个版本移除
