### ISSUE TITLE
[BUG]无法替换旧版直播间

### ISSUE THREAD

**Issue by Huaxidesu** [yujincheng08/BiliRoaming#431]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 点击恢复旧版直播间选项
2. 进入直播显示已替换文本提示
3. 出现没有效果状况

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2022-02-12-12-56-55-271_tv danmaku bili](https://user-images.githubusercontent.com/45794248/153697905-490457d9-2961-40ad-acd0-671c3aff3a86.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：10MIUI12
 - 哔哩漫游版本：1.5.7
 - 哔哩哔哩版本和版本号：6.59.0
 - 使用的框架和版本：LSP1.6.5(6272)-riru
 - 其他：直播

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8052827/log.txt)

**Comment by yujincheng08** [comment]
这个功能下个版本就删

**Comment by Huaxidesu** [comment]
> 

新版直播间太折磨人了，真的没办法弄吗

**Comment by Huaxidesu** [comment]
> 这个功能下个版本就删了

新版直播间太折人了，真的没弄吗
