### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TonyYangStark** [yujincheng08/BiliRoaming#434]
**问题描述**
bilibili国际版谷歌下载的，没弄成功过，在APKpure切换了两个旧版本也没成功。概念版和HD版都一次成功

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
![Screenshot_20220217-093221.jpg](https://user-images.githubusercontent.com/60918068/154387405-041d89fc-9566-41af-a06d-37944f6a0845.jpg)

**环境信息**
 - 安卓版本：8.0.0
 - 系统版本：EMUI8.0.0
 - 哔哩漫游版本：1.5.7
 - 哔哩哔哩版本和版本号：国际版3.7.0
 - 使用的框架和版本：太极框架 阴 承影9.0.0.01201725-7189
 - 其他：所有港澳台番剧

**日志**![log.txt](https://github.com/yujincheng08/BiliRoaming/files/8084878/log.txt)

**Comment by yujincheng08** [comment]
试试重新优化 bilibili

**Comment by TonyYangStark** [comment]
> 试试重新优化 bilibili

不行，优化完，进到b站里连漫游的设置都打不开
