### ISSUE TITLE
繁简字幕转化[Feature]

### ISSUE THREAD

**Issue by amronbook** [yujincheng08/BiliRoaming#437]
**原因**
为什么想要这个功能
哔哩漫游的主要目的是看港澳台番剧，而这些番剧的字幕大部分为繁体，而大陆人看简体更为舒服一些

**功能简述**
想要个怎样的功能
可以增加中文(中国)的字幕，就像油猴脚本网页端那样

**功能逻辑**
如何互交、如何使用等
在字幕控制按钮上添加简体中文

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
油猴脚本繁简转换功能

**Comment by david082321** [comment]
> 咋关闭了呢？

漫游： #400 
脚本： https://github.com/ipcjs/bilibili-helper/pull/944

是同一个人写的，如果你要的话，自己编译漫游。
