### ISSUE TITLE
[Feature] 首次进入b站自动假装分享视频获得5经验

### ISSUE THREAD

**Issue by DTpeel** [yujincheng08/BiliRoaming#440]
**原因**
1.打开b站想要获得5经验要手动假装分享，嫌麻烦

**功能简述**
首次进入b站自动假装分享视频至qq获得5经验
![Screenshot_20220223_133356_edit_214107103089991](https://user-images.githubusercontent.com/61195619/155266677-b33e6815-2d50-4517-94b8-1c7af6ae8ba8.jpg)

**功能逻辑**
开启按钮后打开自动进行分享

**Comment by yujincheng08** [comment]
需求太弱，不加。
