### ISSUE TITLE
[BUG] 使用漫游代理关闭版权番剧下载限速时缓存解析错误

### ISSUE THREAD

**Issue by XM631** [yujincheng08/BiliRoaming#441]
**问题描述**
在关闭解除番剧下载限速时 使用系统代理可以正常下载 使用漫游代理提示解析错误 视频可以正常播放

**复现步骤**
如何复现
1. 打开解除番剧下载限速
2. 使用漫游代理
3. 下载番剧提示解析错误

**截图**
![Screenshot_20220223-175739](https://user-images.githubusercontent.com/100275676/155288632-9197716a-e34c-4853-b8e2-52b836f13f40.png)

**环境信息**
 - 安卓版本：Android 10
 - 系统版本： Xperia XZ3 52.1.A.3.92
 - 哔哩漫游版本： 1.5.7
 - 哔哩哔哩版本和版本号：Play版3.8.0
 - 使用的框架和版本：Lsposed-1.7.2(6379)-Zygisk
 - 其他：轻音少女 剧场版

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8123054/log.txt)

**Comment by yujincheng08** [comment]
![Screenshot_2022-03-02-02-57-48-674_com.bilibili.app.in.jpg.png](https://user-images.githubusercontent.com/5022927/156231534-d85f0f15-a31d-45eb-a834-953c0f135644.png) 并没有问题
