### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sandersshine** [yujincheng08/BiliRoaming#445]
**问题描述**
发生了什么情况？有什么现状？
“屏蔽视频下方推荐栏”功能失效。（首页净化是奏效的）但会提示“已清除视频下方推荐”

**截图**
![IMG_20220226_190721](https://user-images.githubusercontent.com/58631015/155841278-64114596-3fbf-406c-9644-7f4be8ab4701.jpg)
![IMG_20220226_190656](https://user-images.githubusercontent.com/58631015/155841282-97444ae1-e2d1-4d35-8756-4f12fc382ea1.jpg)
![Screenshot_2022-02-26-19-06-34-656_com bilibili app blue](https://user-images.githubusercontent.com/58631015/155841288-d0f428c2-78f5-4351-bdef-9668bab9c2de.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：miui12.5.6
 - 哔哩漫游版本：1.5.7
 - 哔哩哔哩版本和版本号：概念版6.50.0
 - 使用的框架和版本：lsposed 1.6.5

 - 其他：（如哪部番、哪个专栏等）

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8146466/log.txt)

**Comment by Sandersshine** [comment]
1

**Comment by david082321** [comment]
正常。
这个功能是屏蔽这个推荐广告
![IMG_20220228_102424_992](https://user-images.githubusercontent.com/7046617/155913964-34bf47d4-d808-4435-bde9-2d037f83afdd.jpg)
