### ISSUE TITLE
[Feature] 净化视频详情页下方的视频推荐

### ISSUE THREAD

**Issue by Sandersshine** [yujincheng08/BiliRoaming#447]
**原因**
同净化首页推荐，防止刷手机时间过长

**功能简述**
去除视频下方的视频推荐
![image](https://user-images.githubusercontent.com/58631015/155866724-2014eedf-9d31-41e4-a611-4e403d51d8d2.png)

**功能逻辑**
同净化首页推荐

**实现参考**
就像这样（这是旧版APP用的已经停更的哔哩布丁，但旧版APP无法显示评论区）
![image](https://user-images.githubusercontent.com/58631015/155866773-27c52125-64d8-4880-8eda-1f4921423f1c.png)

**Comment by yujincheng08** [comment]
Duplicate of #341
