### ISSUE TITLE
6.13不支持吗？总是加载失败是什么鬼？

### ISSUE THREAD

**Issue by freasen** [yujincheng08/BiliRoaming#45]
手机无法上传图片
具体毛病是视频加载失败，找不到播放地址
所有（仅限台湾地区）的视频都无法播放
什么情况呀？
红米note4x，安卓7，MIUI国际版，
因为要用google，所以装的国际版
语言地区没有中国大陆，所以设置香港
不过这个应该没影响吧？
国内网加载失败，科学上网还是加载失败！

**Comment by yujincheng08** [comment]
支持。

**Comment by freasen** [comment]
我不是技术流，你给我发的我也看不懂呀？这个问题是什么情况呀？怎么解决呀？

**Comment by yujincheng08** [comment]
就是你安卓系统版本刚好有bug，不是模块的问题。

我稍微做过兼容的，要多按几下刷新试试。

最好的就是升级系统版本（7.1就行），或者换手机。

**Comment by qingsheng76** [comment]
你自己的问题
