### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Miyagi-jiye** [yujincheng08/BiliRoaming#451]
**问题描述**
哔哩漫游入口被隐藏,无法进入设置

**复现步骤**
如何复现
1. 打开...哔哩漫游设置-自定义我的页面
2. 点击...取消选中（标题项目）推荐服务,（标题项目）更多服务
3. 出现...哔哩漫游入口隐藏,无法进入漫游设置

**截图**
点击文本框下面小长条可以上传文件
![IMG_20220228_143830.jpg](https://user-images.githubusercontent.com/69101424/155936051-b09acbb7-2d56-4cb0-b8f8-e4076fe91166.jpg)
![Screenshot_2022-02-28-14-36-59-677_tv.danmaku.bili.jpg.png](https://user-images.githubusercontent.com/69101424/155936081-c9989021-043a-407f-b15a-a39b5011227e.png)
![Screenshot_2022-02-28-14-37-14-215_tv.danmaku.bili.jpg.png](https://user-images.githubusercontent.com/69101424/155936108-a0077b59-a87e-4253-8501-1cfca2983dca.png)

**环境信息**
 - 安卓版本：12
 - 系统版本：miui13
 - 哔哩漫游版本：[LSPatch] [1.5.7] [6.59.0]

**Comment by david082321** [comment]
保留标题项目的 推荐服务 或 更多服务。

要删除的话，你保留的标题项目，底下的子项目可以删。

**Comment by Miyagi-jiye** [comment]
> 保留标题项目的 推荐服务 或 更多服务。
> 
> 要删除的话，你保留的标题项目，底下的子项目可以删。

所以说可以把父元素〈标题项目〉给固定不让用户取消选中吗？就只留给用户子元素的选择权,不然设置后就只能清空数据重新设置,还挺麻烦的。

**Comment by david082321** [comment]
> > 保留标题项目的 推荐服务 或 更多服务。
> > 要删除的话，你保留的标题项目，底下的子项目可以删。
> 
> 所以说可以把父元素〈标题项目〉给固定不让用户取消选中吗？就只留给用户子元素的选择权,不然设置后就只能清空数据重新设置,还挺麻烦的。

不用清空。
复原步骤：
1. 打开B站，切换到「我的」分页，然后等待大概5~30秒(依照个人网络速度等待)。
2. 打开漫游，点击第二个设置，然后就能进入漫游设置了
