### ISSUE TITLE
[BUG] 部分番剧分享链接为null

### ISSUE THREAD

**Issue by ghost114513** [yujincheng08/BiliRoaming#458]
**问题描述**
部分番剧分享-复制链接没反应 分享更多原本是链接显示null

**复现步骤**
如何复现
1. 打开明日同學的水手服（僅限港澳台地區）
2. 点击分享-复制链接或分享-更多
3. 没正常出现复制链接到剪贴板

**截图**
图1是错误样式 图2是正确样式
![IMG_20220303_211457_988](https://user-images.githubusercontent.com/100826879/156563616-239c3d55-0c98-4bda-a3d4-d9461225b1a4.jpg)
![Screenshot_20220303-212048](https://user-images.githubusercontent.com/100826879/156563735-62d61f12-188c-4385-9992-6aa86dd0231c.png)

**环境信息**
 - 安卓版本：Android 10
 - 系统版本：Xperia H9493 52.1.A.3.92
 - 哔哩漫游版本：db49dde6dd
 - 哔哩哔哩版本和版本号：Play版3.8.0
 - 使用的框架和版本：LSPosed-v1.7.2-6379-zygisk-release
 - 其他：如图 明日同學的水手服（僅限港澳台地區）异常 搖曳露營△ 第二季（僅限港澳台地區）正常

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8177809/log.txt)没抓到的话可以再抓

**Comment by yujincheng08** [comment]
净化分享就是这种功能。

**Comment by ghost114513** [comment]
> 净化分享就是这种功能。

为啥关了净化分享也一样 打开净化分享有的正常有的是Null
