### ISSUE TITLE
直播自动选择 原画 [Feature]

### ISSUE THREAD

**Issue by 954548** [yujincheng08/BiliRoaming#459]
**原因**
为什么想要这个功能
老版直播间没了，切原画容易滑到其他直播间💢
太折磨
**功能简述**
想要个怎样的功能
**功能逻辑**
如何互交、如何使用等
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
play旧版直播默认原画

**Comment by yujincheng08** [comment]
找 b 站加，而不是找我加。
