### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by XingJunior** [yujincheng08/BiliRoaming#469]
**问题描述**
升级1.5.9后模块整个失效

**复现步骤**

**截图**

**环境信息**
 - 安卓版本：12
 - 系统版本：MIUI 13.0.1
 - 哔哩漫游版本：1.5.9
 - 哔哩哔哩版本和版本号：哔哩哔哩6.62
 - 使用的框架和版本：太极9.0.0

**日志**
都没法打开应用内设置了怎么导出日志啊(恼)

**Comment by XingJunior** [comment]
只能说无语了

**Comment by david082321** [comment]
更新前看一下太极适配版本。

太极模块列表，长按漫游，查看支持版本。

确定有了再更新模块。
