### ISSUE TITLE
[BUG]6.63.0自定义底栏与自定义我的页面无法使用

### ISSUE THREAD

**Issue by L-Trump** [yujincheng08/BiliRoaming#479]
**问题描述**
底栏元素屏蔽不生效且无法设置

**复现步骤**
打开bili漫游设置后相应选项点进去为空，之前里面只有两个未知，勾上后也没了。

**截图**
![Screenshot_2022-03-13-10-06-35-91_149003a2d400f6adb210d7e357a3a646](https://xqhma.oss-cn-hangzhou.aliyuncs.com/image/xbtc/Screenshot_2022-03-13-10-06-35-91_149003a2d400f6adb210d7e357a3a646.jpg)

![Screenshot_2022-03-13-10-06-40-08_149003a2d400f6adb210d7e357a3a646](https://xqhma.oss-cn-hangzhou.aliyuncs.com/image/xbtc/Screenshot_2022-03-13-10-06-40-08_149003a2d400f6adb210d7e357a3a646.jpg)

**环境信息**
 - 安卓版本：Android12
 - 哔哩漫游版本：1.5.9
 - 哔哩哔哩版本和版本号：6.63.0
 - 使用的框架和版本：LSP1.7.2(6456)

**日志**

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8238858/log.txt)

**Comment by JasonKhew96** [comment]
**重置**

**Comment by david082321** [comment]
重启客户端。

打开「我的」页面之后，等待大概5~15秒（视您的网络速度而定）。
然后，才能打开漫游设置。

**Comment by L-Trump** [comment]
> 重启客户端。
> 
> 打开「我的」页面之后，等待大概5~15秒（视您的网络速度而定）。 然后，才能打开漫游设置。

没有用 重置也没有用

**Comment by yujincheng08** [comment]
> > 重启客户端。
> > 打开「我的」页面之后，等待大概5~15秒（视您的网络速度而定）。 然后，才能打开漫游设置。
> 
> 没有用 重置也没有用

尝试降级 LSPosed。如果有用，提交问题到 LSPosed 那边我会继续处理。
