### ISSUE TITLE
[Feature]恢复旧版本app按时间排序功能

### ISSUE THREAD

**Issue by SZCDSB** [yujincheng08/BiliRoaming#489]
**原因**
B站关闭了旧版本的app评论使用按时间排序功

**功能简述**
恢复旧版本app评论按时间排序

**功能逻辑**
重新添加原有按钮

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
没精力给旧版本做任何功能和兼容。
