### ISSUE TITLE
视频评论区无法正常显示评论楼层

### ISSUE THREAD

**Issue by ZYT-studio** [yujincheng08/BiliRoaming#49]
**问题描述**
打开显示评论区楼层功能后在视频评论中无法显示楼层

**复现步骤**
如何复现
1. 打开视频
2. 点击评论
3. 出现无法显示楼层的状况

**截图**
![Screenshot_20201121_183541_com huawei himovie](https://user-images.githubusercontent.com/49780662/99875167-74832d80-2c28-11eb-8a09-dc9b2de2d901.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：EMUI10
 - 哔哩漫游版本：1.3.9
 - 哔哩哔哩版本和版本号：官方版本6.13.0
 - 使用的框架和版本：太极6.4.0
 - 其他：

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5577423/log.txt)

**Comment by yujincheng08** [comment]
先不说你config是空的。

太极那边尝试取消bilibili优化。

**Comment by ZYT-studio** [comment]
已尝试取消优化并重启应用，没有效果。
![Screenshot_20201121_185543_tv danmaku bili](https://user-images.githubusercontent.com/64797191/99875539-87e3c800-2c2b-11eb-90ba-fa4991a03f71.jpg)
![Screenshot_20201121_185616_tv danmaku bili](https://user-images.githubusercontent.com/64797191/99875591-d2654480-2c2b-11eb-91f5-905c3eddb6a0.jpg)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5577465/log.txt)

**Comment by yujincheng08** [comment]
那就用Xpatch版

**Comment by ZYT-studio** [comment]
好的，谢谢。我试试。

**Comment by qingsheng76** [comment]
建议弃用太极改用edxp
