### ISSUE TITLE
[BUG]显示账号未登录

### ISSUE THREAD

**Issue by Aleks233** [yujincheng08/BiliRoaming#499]
**问题描述**
1.5.9是正常的
1.6.0显示解析服务器发生错误，账号未登录,切换解析地址，也是这种错误

**复现步骤**
打开港澳台的番剧

**截图**
![Screenshot_20220328-142712](https://user-images.githubusercontent.com/61233076/160339158-64a816c7-ecf7-4389-957c-be400b130e6f.jpg)

**环境信息**
 - 安卓版本：android11
 - 系统版本：HOS11.1.2.2
 - 哔哩漫游版本：1.6.0
 - 哔哩哔哩版本和版本号：6.65.0
 - 使用的框架和版本：LSPosed-Zygisk1.8.0
 - 其他：打开港澳台的番剧

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8360157/log.txt)

**Comment by Aleks233** [comment]
> **问题描述** 1.5.9是正常的 1.6.0显示解析服务器发生错误，账号未登录
> 
> **复现步骤** 打开港澳台的番剧
> 
> **截图** ![Screenshot_20220328-142712](https://user-images.githubusercontent.com/61233076/160339158-64a816c7-ecf7-4389-957c-be400b130e6f.jpg)
> 
> **环境信息**
> 
> * 安卓版本：android11
> * 系统版本：HOS11.1.2.2
> * 哔哩漫游版本：1.6.0
> * 哔哩哔哩版本和版本号：6.65.0
> * 使用的框架和版本：LSPosed-Zygisk1.8.0
> * 其他：
> 
> **日志** [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8360157/log.txt)

**Comment by Aleks233** [comment]
> > **问题描述** 1.5.9是正常的 1.6.0显示解析服务器发生错误，账号未登录，试过将解析服务器换成别的，也是这种
> > **复现步骤** 打开港澳台的番剧
> > **截图** ![Screenshot_20220328-142712](https://user-images.githubusercontent.com/61233076/160339158-64a816c7-ecf7-4389-957c-be400b130e6f.jpg)
> > **环境信息**
> > 
> > * 安卓版本：android11
> > * 系统版本：HOS11.1.2.2
> > * 哔哩漫游版本：1.6.0
> > * 哔哩哔哩版本和版本号：6.65.0
> > * 使用的框架和版本：LSPosed-Zygisk1.8.0
> > * 其他：打开港澳台番剧
> > 
> > **日志** [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8360157/log.txt)

**Comment by yujincheng08** [comment]
addressed by https://github.com/yujincheng08/BiliRoaming/commit/3e2c3f6c5eea56df565a982d96483bda148a19d2
