### ISSUE TITLE
1.15无法生效，附带log

### ISSUE THREAD

**Issue by kcn3388** [yujincheng08/BiliRoaming#5]
log在附件
[2020-04-06-18-26-13.txt](https://github.com/yujincheng08/BiliRoaming/files/4437742/2020-04-06-18-26-13.txt)
[2020-04-06-18-31-08.txt](https://github.com/yujincheng08/BiliRoaming/files/4437743/2020-04-06-18-31-08.txt)

**Comment by yujincheng08** [comment]
没有找到模块相关的log。请重新抓一下

**Comment by kcn3388** [comment]
已经按问题复现步骤抓取log了，不知道为什么抓不出来

**Comment by yujincheng08** [comment]
你没有抓debug信息

**Comment by kcn3388** [comment]
换了个软件重新抓了，看看这样子抓到没有
[Apr 6, 2020 18-50-13.log](https://github.com/yujincheng08/BiliRoaming/files/4437808/Apr.6.2020.18-50-13.log)
[Apr 6, 2020 18-46-49.log](https://github.com/yujincheng08/BiliRoaming/files/4437809/Apr.6.2020.18-46-49.log)

**Comment by yujincheng08** [comment]
没有，你还是没有抓debug信息

**Comment by kcn3388** [comment]
我勾选了debug的了

**Comment by yujincheng08** [comment]
Log里面没有`time D/xxxx`这样的log

**Comment by kcn3388** [comment]
try this.
[Apr 6, 2020 19-21-22.log](https://github.com/yujincheng08/BiliRoaming/files/4438006/Apr.6.2020.19-21-22.log)

**Comment by yujincheng08** [comment]
发现问题了。但是我没办法解决的样子。
原因是在哔哩哔哩的进程里面访问不到biliroaming的设置，导致模块认为自己没有启动。

**Comment by kcn3388** [comment]
更改设置文件存储的位置会不会有帮助
例如：qx和微x的配置文件存放于内置存储目录

**Comment by kcn3388** [comment]
这里是1.12正常生效的log，可以参考一下
[Apr 6, 2020 20-09-39.log](https://github.com/yujincheng08/BiliRoaming/files/4438300/Apr.6.2020.20-09-39.log)
