### ISSUE TITLE
[BUG]净化功能不能生效

### ISSUE THREAD

**Issue by YXlangran** [yujincheng08/BiliRoaming#52]
**问题描述**
净化功能已经打开，但是没有效果，其他功能正常。

**环境信息**
 - 安卓版本：安卓11
 - 系统版本：MIUI12 开发版9.19
 - 哔哩漫游版本：1.4.0
 - 哔哩哔哩版本和版本号：普通版6.14.0
 - 使用的框架和版本：edxp YAHFA0.5.0.6_4576

**日志**
抱歉不知道手机怎么上传日志，所以放在了坚果云
https://www.jianguoyun.com/p/DZWZ3F0QxfqWCBiZus4D

**Comment by yujincheng08** [comment]
未能复现。

**Comment by yujincheng08** [comment]
https://github.com/ElderDrivers/EdXposed/pull/717
