### ISSUE TITLE
[BUG]国际版2.8.0无法显示模块入口

### ISSUE THREAD

**Issue by xushet** [yujincheng08/BiliRoaming#520]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
![Screenshot_20220403-162835_bilibili.png](https://user-images.githubusercontent.com/34502902/161419153-313929da-31d3-4e81-8423-d7b7d4029cfd.png)![Screenshot_20220403-163006_Shady启动器.png](https://user-images.githubusercontent.com/34502902/161419156-7f9dbfa7-1410-4388-8885-1d9a81b9ab67.png)

**Comment by yujincheng08** [comment]
版本太老
