### ISSUE TITLE
[BUG]加载首页后会闪退

### ISSUE THREAD

**Issue by idnimabi** [yujincheng08/BiliRoaming#523]
**问题描述**
打开哔哩哔哩加载首页后会闪退，需要再次打开后才能正常打开，之后大概一小时内关闭再打开不会闪退。
从其他软件跳转到播放页时也会闪退，然后自动重启到首页，保持后台打开情况下，再次从其他软件跳转能够正常播放

**复现步骤**
同描述

**环境信息**
 - 安卓版本：12
 - 系统版本：MIUI 13.0.5
 - 哔哩漫游版本：1.6.1
 - 哔哩哔哩版本和版本号：小米应用商店普通版6.66.0
 - 使用的框架和版本：LSPosed 1.8.0

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8406972/log.txt)

**Comment by duzhaokun123** [comment]
发 log_old.txt
