### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by idnimabi** [yujincheng08/BiliRoaming#524]
**问题描述**
打开哔哩哔哩加载首页后会闪退，需要再次打开才能正常打开，之后一小时再次打开不会有问题。
从其他软件跳转到播放页时也会闪退，然后自动重启到首页，保持后台打开情况下，再次从其他软件跳转能够正常播放

**复现步骤**
同描述

**截图**
无

**环境信息**
 - 安卓版本：12
 - 系统版本：MIUI 13.0.5
 - 哔哩漫游版本：1.6.1
 - 哔哩哔哩版本和版本号：6.66.0
 - 使用的框架和版本：LSPosed 1.8.0

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8406972/log.txt)

**Comment by duzhaokun123** [comment]
发 log_old.txt

**Comment by idnimabi** [comment]
> 发 old_log.txt

这个log就是导出的old_log.txt，只是名字不知道为啥是log.txt

**Comment by duzhaokun123** [comment]
建议都发

**Comment by duzhaokun123** [comment]
> > 发 old_log.txt
> 
> 这个log就是导出的old_log.txt，只是名字不知道为啥是log.txt

因为改名写起来复杂 不想写

**Comment by duzhaokun123** [comment]
而且你是不是又正常启动了一次才发的 olg_log.txt

**Comment by idnimabi** [comment]
> 建议都发

[原本的log.txt](https://github.com/yujincheng08/BiliRoaming/files/8407038/log.txt)

**Comment by idnimabi** [comment]
> 而且你是不是又正常启动了一次才发的 olg_log.txt

是的

**Comment by duzhaokun123** [comment]
> > 而且你是不是又正常启动了一次才发的 olg_log.txt
> 
> 是的

复现崩溃 再发 old log

**Comment by idnimabi** [comment]
> > > 而且你是不是又正常启动了一次才发的 olg_log.txt
> > 
> > 
> > 是的
> 
> 复现崩溃 再发 old log
又闪退了，这次是连续两次打开闪退，第一次加载首页动画完成一半时闪退，第二次直接在欢迎页闪退，这是第二次的log和old_log。第三次打开时启动成功

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8407247/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8407248/old_log.txt)

**Comment by yujincheng08** [comment]
这个好像要看b站自带的崩溃日志
```
crash_dump64: failed to attach to thread 5125, already traced by 6108 (libbili_core_dumper.so)
```

**Comment by idnimabi** [comment]
> 在 /data/data/tv.danmaku.bili 里面找找，大概叫 tomestone 什么的

先关了吧，清除缓存之后两天没有闪退过了，不知道是清除缓存好的还是关闭了HMA的file detections好的

**Comment by yujincheng08** [comment]
HMA 的 file detection 日常导致闪退
