### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bluerabbitsu33** [yujincheng08/BiliRoaming#525]
**问题描述**
港澳台番剧专栏可播放
点进去番剧之后显示资源不存在
哗哩漫游显示己成功获取播放地址

**复现步骤**
如上

**截图**
![Screenshot_20220404-160543](https://user-images.githubusercontent.com/68809667/161503425-5e447ee7-e6ac-472a-8878-67edbea977fc.png)
![Screenshot_20220404-160550](https://user-images.githubusercontent.com/68809667/161503526-219077db-d9e9-4ac1-9219-e3618790ae0c.png)

**环境信息**
 - 安卓版本：7.1
 - 系统版本：U study OS
 - 哔哩漫游版本：1.6.1
 - 哔哩哔哩版本和版本号:play版3.6.1
 - 使用的框架和版本：太极 承影9.0.0
 - 

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8407956/old_log.txt)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8407984/log.txt)

**Comment by yujincheng08** [comment]
old_log 显示你的区域是国际地区
log 却显示你是中国大陆地区

合理怀疑你 vpn 问题。

**Comment by bluerabbitsu33** [comment]
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8409019/old_log.txt)
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8409022/log.txt)

**Comment by bluerabbitsu33** [comment]
vpn关了也一样
