### ISSUE TITLE
[BUG]开机会卡在警告界面

### ISSUE THREAD

**Issue by dytfy666** [yujincheng08/BiliRoaming#53]
**问题描述**
华为Emui9，root使用的是magisk，框架用的edxposed，开机会卡在警告界面，

**复现步骤**
如何复现
1. 安装哔哩哔哩漫游，然后在edxposed中模块选项选择激活，
2. 点击.edxposed的重启，等待重启激活
3. 就会出现卡在开机警告界面的情况

**环境信息**
 - 安卓版本：9
 - 系统版本：Emui9.1.0.340
 - 哔哩漫游版本：1.4.0
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）普通版 6.14.0
 - 使用的框架和版本：（如太极6.3.0）
   Riru(Riru-core) v21.3
   Riru-Edxposed v0.4.6.4(4563)(YAHFA)

   Riru(Riru-core) V19.7
   Riru-EdxposedV0.4.5.5.5(4470)(YAHFA)

   Riru(Riru-core) V19.4
   Riru-EdxposedV0.4.5.1(4463)(YAHFA)(Sandhook)
    都试过,在选择激活，重启，就会卡开机。
 - 其他：（如哪部番、哪个专栏等）无

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[logcat.txt](https://github.com/yujincheng08/BiliRoaming/files/5633369/logcat.txt)
日志，新手一个，百度的抓开机log，adb导出教程，也不知道对不对

**Comment by yujincheng08** [comment]
12-02 22:11:56.120 F/zygote64( 2875): jni_internal.cc:619] JNI FatalError called: (system_server) Not whitelisted : /data/app/me.iacn.biliroaming-LmQ2RxHsEZFGN_2BisV1tA==/base.apk

这跟漫游没啥关系。漫游会在initzygote打开自己的apk以获取resource，而是zygote在fork的时候会检查打开文件白名单。EdXposed理论会吧/data/app的文件加到白名单。所以你应该去找EdXposed反馈而不是来我这里反馈。

**Comment by dytfy666** [comment]
谢谢，已关闭issue




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LoveSy"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 中午12:47
收件人: "yujincheng08/BiliRoaming"<BiliRoaming@noreply.github.com&gt;; 
抄送: "千万千万"<1205096258@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yujincheng08/BiliRoaming] [BUG]开机会卡在警告界面 (#53)





 
12-02 22:11:56.120 F/zygote64( 2875): jni_internal.cc:619] JNI FatalError called: (system_server) Not whitelisted : /data/app/me.iacn.biliroaming-LmQ2RxHsEZFGN_2BisV1tA==/base.apk
 
这跟漫游没啥关系。漫游会在initzygote打开自己的apk以获取resource，而是zygote在fork的时候会检查打开文件白名单。EdXposed理论会吧/data/app的文件加到白名单。所以你应该去找EdXposed反馈而不是来我这里反馈。
