### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gqly** [yujincheng08/BiliRoaming#531]
**问题描述**
除了番剧限制和版权番剧下载外一切功能都能使用，每次刚安装的前十几分钟里可以正常解锁番剧限制，后面便显示加载失败

**复现步骤**
如何复现
1. 打开哔哩哔哩
2. 点击哔哩哔哩番剧
3. 出现页面加载失败请重试

**截图**
![Screenshot_2022-04-08-13-50-20-723_tv danmaku bili](https://user-images.githubusercontent.com/103238722/162372967-9be2a8e1-1468-47cd-846c-4a2ba60912f9.jpg)

**环境信息**
 - 安卓版本：12
 - 系统版本：miui13. 0. 4. 0
 - 哔哩漫游版本：1.6.1
 - 哔哩哔哩版本和版本号：6.67.0
 - 使用的框架和版本：太极承影9.0.0

**日志**
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8448920/old_log.txt)

**Comment by yujincheng08** [comment]
可能是太极在 Android 12 上的缺陷，试试 LSPatch 版本。
