### ISSUE TITLE
[BUG]播放时反复弹出模块信息与定位至上次播放位置

### ISSUE THREAD

**Issue by 1090734668** [yujincheng08/BiliRoaming#534]
**问题描述**
观看任何港澳台番剧时反复弹出模块运行信息与“已为您定位至上一次播放位置”

**截图**
有截图

**环境信息**
 - 安卓版本：安卓10
 - 系统版本：MIUI12.5.2稳定版
 - 哔哩漫游版本：1.6.1
 - 哔哩哔哩版本和版本号：普通版6.66
 - 使用的框架和版本：lspatch6.66模块1.61
 - 其他：任何港澳台番剧

**日志**
有日志
![Screenshot_2022-04-09-12-40-42-530_tv danmaku bili](https://user-images.githubusercontent.com/103300436/162558498-c68282db-18c3-450d-9f4c-6fc98f48f6f1.jpg)

**Comment by 1090734668** [comment]
为什么关闭？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月9日(周六) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yujincheng08/BiliRoaming] [BUG]播放时反复弹出模块信息与定位至上次播放位置 (Issue #534)




 
Closed #534.
 
&mdash;

**Comment by david082321** [comment]
> 为什么关闭？

你没上传日志文件，在网页版点📎，然后选择日志文件
