### ISSUE TITLE
XPatch不正常

### ISSUE THREAD

**Issue by yxfjsksker** [yujincheng08/BiliRoaming#544]
**问题描述**
XPatch版哔哩哔哩打开没有哔哩漫游设置

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：8.0
 - 系统版本：8.0
 - 哔哩漫游版本：Xpatch6.31.0
 

![Screenshot_20220411-040238](https://user-images.githubusercontent.com/103385608/162643585-b9399729-d90a-4518-93a0-14cccd8ba6b3.jpg)

**Comment by david082321** [comment]
客户端6.31.0搭配的漫游版本太低，想自己办法更新漫游版本
建议可以自己打包

[用这里的 xpatch-3.0.jar 打包](https://github.com/yujincheng08/Xpatch/releases/tag/biliroaming)

[打包方法在这里](https://github.com/yujincheng08/Xpatch#xpatch%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

**Comment by yxfjsksker** [comment]
> 客户端6.31.0搭配的漫游版本太低，想自己办法更新漫游版本 建议可以自己打包
> 
> [用这里的 xpatch-3.0.jar 打包](https://github.com/yujincheng08/Xpatch/releases/tag/biliroaming)
> 
> [打包方法在这里](https://github.com/yujincheng08/Xpatch#xpatch%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

方法还得输入指令什么吗？看不太懂😂
