### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Superbia000** [yujincheng08/BiliRoaming#55]
**问题描述**
在bilibili打开漫游设置没反应，解除区域限制无效

**复现步骤**
如何复现
1. 打开bilibili App
2. 点击哔哩漫游设置
3. 没反应
4. 直接进入漫游App调出设置界面
5. 启用功能后重启
6. 进入限制地区的番
7. 非常抱歉，根据版权方要求，您所在地区无法观看本片

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI Global 12.0.7
 - 哔哩漫游版本：1.4.0
 - 哔哩哔哩版本和版本号：Play 2.7.0
 - 使用的框架和版本：太极6.4.0
 - 其他：

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5638018/log.txt)

**Comment by yujincheng08** [comment]
请尝试Xpatch版
