### ISSUE TITLE
[BUG]1.6.2模块版本在6.66官方版app上显示不支持架构 框架

### ISSUE THREAD

**Issue by BestTimerOne** [yujincheng08/BiliRoaming#550]
**问题描述**
1.6.2模块版本在6.66官方版app上显示不支持架构 框架，没有模块设置入口（从哔哩漫游app能进入设置）
以前的1.5.9在6.63正常
不过模块可生效，比如替换竖版视频，av号显示

**复现步骤**
打开app就这样

**截图**
![微信图片_20220417040323](https://user-images.githubusercontent.com/32497282/163689772-99b15d74-f096-402a-b5eb-36af3800ddaa.jpg)

**环境信息**
 - 安卓版本：11
 - 系统版本：MIUI 12.5 21.11.3
 - 哔哩漫游版本：1.6.2
 - 哔哩哔哩版本和版本号：粉色官方版 6.66
 - 使用的框架和版本：EDXP最新
 - 其他：

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8500565/log.txt)

**Comment by yujincheng08** [comment]
换框架即可。没有精力适配所有框架。
