### ISSUE TITLE
[Feature] 动态页分类过滤&正则表达式过滤

### ISSUE THREAD

**Issue by Samachurl** [yujincheng08/BiliRoaming#551]
**原因**

- 很多up会接pdd、tb的动态广告，如
![1](https://user-images.githubusercontent.com/48409650/163710715-642b1aad-efc3-485f-978e-5fc01c84e0cb.jpg)

- 类似视频更新预告预约、直播预约的动态有点混淆视听，经常会误以为更新了视频，如
![2](https://user-images.githubusercontent.com/48409650/163710847-a851571d-9dbb-4bd1-8878-0a4c9bad8f94.jpg)

**功能简述**
动态过滤功能，包括

- 分类过滤（转发、图文、文字、视频、小视频、专栏、音频、番剧、分享、开播记录、自转发等等）
- 自定义关键词和正则表达式过滤

**功能逻辑**
[可参考Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved)
![image](https://user-images.githubusercontent.com/48409650/163711079-25e0fc89-d637-49ed-8d70-8217fb804100.png)

**实现参考**
[Bilibili-Evolved-动态过滤器](https://github.com/the1812/Bilibili-Evolved/blob/master/registry/dist/components/feeds/filter.js)

**Comment by yujincheng08** [comment]
Duplicate of #190
