### ISSUE TITLE
[Feature] CC字幕简繁转换

### ISSUE THREAD

**Issue by Samachurl** [yujincheng08/BiliRoaming#552]
**原因**
太笨了，看繁体字幕有点费劲T_T

**功能简述**
CC字幕简繁转换

**功能逻辑**
提供 CC字幕简繁转换 功能及开关

**实现参考**
[ipcjs/bilibili-helper](https://github.com/ipcjs/bilibili-helper)

**Comment by yujincheng08** [comment]
多看看就懂了。
