### ISSUE TITLE
[BUG]港澳台番剧以及番剧出差主页加载失败

### ISSUE THREAD

**Issue by misaka10843** [yujincheng08/BiliRoaming#553]
**问题描述**
bili港澳台番剧加载失败

并且更换解析服务器也是一样的问题

**复现步骤**
1. 从追番点击进入番剧
2. 出现截图1中的问题

**截图**
![Screenshot_2022-04-17-22-04-20-190_tv danmaku bili](https://user-images.githubusercontent.com/69132853/163717991-09a0e92b-e386-4738-a5c9-b49fb7ca1c1f.jpg)
![Screenshot_2022-04-17-22-04-50-294_tv danmaku bili](https://user-images.githubusercontent.com/69132853/163717993-92d98e91-b13a-4419-8c42-ab623fe74770.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI 12.5.3 Global
 - 哔哩漫游版本： 1.6.2
 - 哔哩哔哩版本和版本号：6.68.0（官版）
 - 使用的框架和版本：LSPosed
 - 其他：全部港澳台及番剧出差

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8501788/log.txt)

**Comment by misaka10843** [comment]
虽然感觉应该不需要，但还是给一下lsposed的信息吧
```

API 版本
93

注入接口
Zygisk

框架版本
1.8.1 (6499)

管理器版本
1.8.1 (6499)

系统版本
10 (API 29)

设备
Xiaomi Redmi 8 

系统架构
arm64-v8a
```

**Comment by KimmyXYC** [comment]
lsposed中重新优化哔哩哔哩客户端试试

**Comment by misaka10843** [comment]
> lsposed中重新优化哔哩哔哩客户端试试

还是不行，但是感觉似乎是lsposed的问题（因为杜比大喇叭也无法运行）但是其他模块却可以照常运行，就挺怪

**Comment by yujincheng08** [comment]
重装 b站客户端 是否能用一段时间？

**Comment by yujincheng08** [comment]
你的 SELinux 是 permissive？

**Comment by misaka10843** [comment]
> 你的 SELinux 是 permissive？

SELinux似乎是关闭的

**Comment by misaka10843** [comment]
> 重装 b站客户端 是否能用一段时间？

能，而且是基于重装后发生的（第一次是像无root版的一个bug一样，就是漫游设置无法在b站里面打开，只能靠漫游跳转打开）
然后重装b站后用了一段时间后就出现了这种问题

**Comment by misaka10843** [comment]
> > 你的 SELinux 是 permissive？
> 
> SELinux似乎是开启的 ![IMG_20220418_094251](https://user-images.githubusercontent.com/69132853/163741612-beced61b-652f-46d2-8833-53de3b7d02a3.jpg)

设置成`permissive`重启后还是无法加载😂

**Comment by misaka10843** [comment]
> > 重装 b站客户端 是否能用一段时间？
> 
> 能，而且是基于重装后发生的（第一次是像无root版的一个bug一样，就是漫游设置无法在b站里面打开，只能靠漫游跳转打开） 然后重装b站后用了一段时间后就出现了这种问题

又出现了无法打开设置的bug

https://user-images.githubusercontent.com/69132853/163744268-cf76f4e9-c5e4-41dd-be02-aa756b0f4360.mp4

**Comment by yujincheng08** [comment]
发一下 /proc/mounts

**Comment by misaka10843** [comment]
> /proc/mounts
proc下没有mounts😂

**Comment by yujincheng08** [comment]
![Screenshot_2022-04-18-12-08-11-847_com mixplorer silver](https://user-images.githubusercontent.com/5022927/163753025-8009579a-af55-4198-80ba-e3860357c698.png)

**Comment by misaka10843** [comment]
> ![Screenshot_2022-04-18-12-08-11-847_com mixplorer silver](https://user-images.githubusercontent.com/5022927/163753025-8009579a-af55-4198-80ba-e3860357c698.png)

https://paste.ubuntu.com/p/zN2RWnvwqC/

**Comment by yujincheng08** [comment]
lsposed 问题
