### ISSUE TITLE
[Feature]希望动态页面可以选择关闭“最常访问”和“频道与话题”

### ISSUE THREAD

**Issue by f59375543** [yujincheng08/BiliRoaming#555]
**原因**
这个实在是太占位置了，而且最常访问的排序还是乱序（有时候排前面的还是我根本没开打过也没看过视频），没有实际使用价值

**功能简述**
关闭“最常访问”和“频道与话题”

**功能逻辑**
修改页面要素

**实现参考**
该模块之前的界面修改

**Comment by david082321** [comment]
#314

**Comment by yujincheng08** [comment]
Duplicate of #314
