### ISSUE TITLE
安卓12好像用不了内置模块的版本[BUG]

### ISSUE THREAD

**Issue by jcmrn1314520** [yujincheng08/BiliRoaming#556]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by david082321** [comment]
只写个标题，里面内容都不写的，要怎么帮你？我又不会算命。

**Comment by jcmrn1314520** [comment]
就是更新了安卓12之后原来的那个ls自带模块的版本用不起了，

**Comment by jcmrn1314520** [comment]
就是更新了安卓12之后原来的那个ls自带模块的版本用不起了，

**Comment by jcmrn1314520** [comment]
下载那个最新版之后进去是普通版本的应用，莫得那个哔哩漫游设置了
