### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jcmrn1314520** [yujincheng08/BiliRoaming#559]
**问题描述**
发生了什么情况？有什么现状？

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：
 - 系统版本：
 - 哔哩漫游版本：
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）
 - 使用的框架和版本：（如太极6.3.0）
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by jcmrn1314520** [comment]
你好就是今天更新了新的系统安卓12之后，自带哔哩漫游的那个软件模块就失效了，打开就是普通的版本了，没有哔哩漫游设置，我的手机是iQOOneo3。

**Comment by david082321** [comment]
> **问题描述** 发生了什么情况？有什么现状？
> 
> **复现步骤** 如何复现
> 
> 1. 打开...
> 2. 点击...
> 3. 出现...状况
> 
> **截图** 点击文本框下面小长条可以上传文件
> 
> **环境信息**
> 
> * 安卓版本：
> * 系统版本：
> * 哔哩漫游版本：
> * 哔哩哔哩版本和版本号：（如概念版6.2.3）
> * 使用的框架和版本：（如太极6.3.0）
> * 其他：（如哪部番、哪个专栏等）
> 
> **日志** 无日志会被直接关闭 点击文本框下面小长条可以上传文件

https://github.com/yujincheng08/BiliRoaming/issues/559#issue-1206755244

选择性忽略内文是吧？

问题描述
发生了什么情况？有什么现状？

复现步骤
如何复现

打开...
点击...
出现...状况
截图
点击文本框下面小长条可以上传文件

环境信息

安卓版本：
系统版本：
哔哩漫游版本：
哔哩哔哩版本和版本号：（如概念版6.2.3）
使用的框架和版本：（如太极6.3.0）
其他：（如哪部番、哪个专栏等）
日志
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by jcmrn1314520** [comment]
新xp版本安卓12没有哔哩设置了
安卓12
系统版本传图
lspatch1.62
![Screenshot_20220418_165950](https://user-images.githubusercontent.com/70710216/163784894-a4df166f-c228-4240-b1b4-5b236276dd5d.jpg)

**Comment by jcmrn1314520** [comment]
使用版本
![Screenshot_20220418_170233](https://user-images.githubusercontent.com/70710216/163785095-f5e6bcf5-cf14-4d54-b9a1-4df24971189e.jpg)
