### ISSUE TITLE
[BUG]自选颜色在客户端重启后失效

### ISSUE THREAD

**Issue by Yanstory** [yujincheng08/BiliRoaming#56]
**问题描述**
自选颜色设定后重启客户端，客户端将只会应用原本的主题设置。重新设置后依旧如此。

**复现步骤**
设置自选颜色→双击back退出→再次进入客户端，bug复现

**截图**
无截图，但设置自选颜色后，退出主题设置界面再重进：
![Screenshot_2020-12-15-12-03-59-600_tv danmaku bili](https://user-images.githubusercontent.com/5153875/102169685-ac9b2a80-3ecd-11eb-84a4-5ed97e4b0bca.jpg)

**环境信息**
 - 安卓版本：7.1.1
 - 系统版本：MIUI 11
 - 哔哩漫游版本：1.4.0
 - 哔哩哔哩版本和版本号：6.14.0
 - 使用的框架和版本：太极6.3.0（太极·阳 128(60)）

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5651073/log.txt)

**Comment by yujincheng08** [comment]
已修复 https://github.com/yujincheng08/BiliRoaming/commit/84bb202b2a9a0052f496429aa987f387c38ffe72 https://github.com/yujincheng08/BiliRoaming/commit/de2c5d12e024ea4e1447d544993fd5fdd1dcd08b
