### ISSUE TITLE
[Feature]希望可以添加取消选择P2P CDN的支持

### ISSUE THREAD

**Issue by long45343** [yujincheng08/BiliRoaming#569]
**原因**
为什么想要这个功能
校园网的P2P性能过于垃圾
**功能简述**
想要个怎样的功能
只从B站的服务器加载视频而不从P2P加载
**功能逻辑**
如何互交、如何使用等
做成开关形式，供用户选择
**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
https://github.com/Richasy/Bili.UWP
该UWP已实现

**Comment by cxw620** [comment]
> **原因** 为什么想要这个功能 校园网的P2P性能过于垃圾 **功能简述** 想要个怎样的功能 只从B站的服务器加载视频而不从P2P加载 **功能逻辑** 如何互交、如何使用等 做成开关形式，供用户选择 **实现参考** （可选）该功能可能的实现方式，或者其他已经实现该功能的应用等 https://github.com/Richasy/Bili.UWP 该UWP已实现

我提pr了, 你想尝鲜可以拉我的[branch](https://github.com/cxw620/BiliRoamingX/tree/break_pcdn)自己编译用用, 我测试效果还行. 我个人是屏蔽掉PCDN, 配合屏蔽掉HTTPDNS, 强制走v6节省v4流量, v6是免费的.
