### ISSUE TITLE
[Feature]希望添加cc字幕繁体转简体功能

### ISSUE THREAD

**Issue by hichengsheng** [yujincheng08/BiliRoaming#571]
**原因**
为什么想要这个功能
繁体大部分都看得懂但还是有部分生僻繁体字理解障碍影响字幕阅读顺畅感

**功能简述**
想要个怎样的功能
cc字幕繁体自动转换为简体

**功能逻辑**
如何互交、如何使用等
做成开关形式，供用户选择

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等
https://greasyfork.org/zh-CN/scripts/431021-bilibili-b%E7%AB%99-%E7%95%AA%E5%89%A7cc%E5%AD%97%E5%B9%95%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2-%E7%BF%BB%E8%AF%91-%E7%B9%81%E4%BD%93%E8%BD%AC%E7%AE%80%E4%BD%93
该功能已在油猴脚本网页端实现

**Comment by david082321** [comment]
As #552

**Comment by QingM0** [comment]
https://github.com/yujincheng08/BiliRoaming/pull/400
