### ISSUE TITLE
[Feature]请求使旧版本app评论区正常显示🙏

### ISSUE THREAD

**Issue by hnzzmyr** [yujincheng08/BiliRoaming#575]
**原因**
从今年二月多开始，5.45等旧版本的视频评论区受到官方限制无法显示

**功能简述**
能够正常显示就可以

**功能逻辑**
能够正常显示

**Comment by duzhaokun123** [comment]
可我们甚至不支持旧版客户端

**Comment by hnzzmyr** [comment]
> 可我们甚至不支持旧版客户端

啊这。。非常感谢你😂
