### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zhangcx1223** [yujincheng08/BiliRoaming#576]
**问题描述**
发生了什么情况？有什么现状？
在哔哩哔哩内无法打开漫游设置界面且功能失效，可以在外部打开。
**复现步骤**

1. 打开哔哩哔哩
2. 点击哔哩哔哩漫游设置
3. 出现点不开状况

**截图**
![46C399A9-83B0-48F2-B48C-D1ACBE927890](https://user-images.githubusercontent.com/94476518/165782674-69630243-ce3f-44bc-b08b-de307623d019.jpeg)
![9C5DCD56-7092-43B4-A42C-FAAE2196D19F](https://user-images.githubusercontent.com/94476518/165782686-c2628db5-5960-4a76-b322-e6337cfe0007.jpeg)

**环境信息**
 - 安卓版本：10
 - 系统版本：MIUI12
 - 哔哩漫游版本：最新ci版以及1.6.2都试过
 - 哔哩哔哩版本和版本号：官方版6.70.0
 - 使用的框架和版本：Lsposed 1.8.1  zygisk
 - 其他：（如哪部番、哪个专栏等）

**日志**

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8583867/log.txt)

无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by yujincheng08** [comment]
Android 10 在 lsposed 1.8.+会有的问题，暂时回退或者用 CI 版

**Comment by Zhangcx1223** [comment]
使用了最新CI版本依旧无效，不过把哔哩哔哩回退到6.66.0解决了这个问题，谢谢。

**Comment by yujincheng08** [comment]
关键是重装一下。你现在装个 6.70 应该也能用了。
