### ISSUE TITLE
[Feature]单独禁止合集和推荐视频自动播放的功能

### ISSUE THREAD

**Issue by Clyde-Li** [yujincheng08/BiliRoaming#579]
**原因**
B站上线了合集功能替代分P功能，但站内目前还存在大量的分P视频。当前的视频自动播放下一个的开关同时对合集和分P都生效。
分P跳转不会切换评论区，而且内容围绕统一标题展开，个人期望自动跳转；合集内视频内容关联小，而且评论区独立，每次正打着字就刷到下个视频了，自动跳转过于痛苦。

**功能简述**
漫游菜单添加合集自动连播和分P自动连播的单独开关。

**功能逻辑**
合集自动连播开，会自动播放合集内下一个视频。
分P自动连播开，会自动播放下一P。
两个开关作用域独立。
（如果开发者愿意的话，也可针对播完暂停、列表循环、单视频循环等完整播放后动作列表进行一个狠狠地切割）

**实现参考**
无

**Comment by yujincheng08** [comment]
应该给官方反馈。网页版是有这个开关的。

**Comment by Clyde-Li** [comment]
> 

实测网页那个开关没有区分合集和分P视频，在合集视频里关了分P视频也会被关闭。
