### ISSUE TITLE
[Feature]可以在play版添加课堂功能吗

### ISSUE THREAD

**Issue by synge0718** [yujincheng08/BiliRoaming#58]
**原因**
购买了沈逸老师的课程，但是play版虽然历史记录里有课堂却不能观看课堂

**功能简述**
在play版“我的”界面中添加课堂按钮

**功能逻辑**
可以尝试伪装成国内版的UA，但是否有效我也不知道

**Comment by yujincheng08** [comment]
这个不打算加了
