### ISSUE TITLE
[Feature]希望在电视盒子/投影仪上看B站港澳台

### ISSUE THREAD

**Issue by lenghonglin** [yujincheng08/BiliRoaming#581]
**原因**

尝试在电视盒子/投影仪上看B站港澳台的一些实践

在路由器上运行 openwrt ，跑一个 v2ray ，然后通过 B 站客户端观看港澳台番剧。这种方法挂在最后一步，B 站有很多安卓版本，但是只有很少的 TV 版本，主要有两个流派。 第一个是官方的云试听小电视，第二个是第三方修改哔哩哔哩 tv 版本。当使用官方版本的时候，搜不出来港澳台的番剧。使用三方修改版本的时候，能搜出番剧并且也能观看，但是由于港澳台的番剧是外挂的字幕，导致三方版不支持该功能。

还有一种方法，使用哔哩哔哩 HD 版本，不过由于我的电视盒跑的安卓 4.4 32bit ，导致很多新版本不能成功安装上。

![image](https://user-images.githubusercontent.com/4686802/166199795-f2a99659-4d2b-4409-9407-8171bec0488b.png)

折腾几天下来的似乎没有好的解决方法，但随着用电视盒 /投影仪的人增多，越来越多的人会有该需求。

跟该https://github.com/yujincheng08/BiliRoaming/issues/24 的需求差不多。

**功能简述**
可以在投影仪/电视盒子上看B站港澳台

**功能逻辑**
哔哩哔哩 v1.1.7.18 智能音箱提取版 可以直接登陆手机版的大会员，在电视上直接播放1080p+及以上的视频，非常的方便。

**实现参考**
可以在https://github.com/yujincheng08/BiliRoaming/issues/529 上添加哔哩漫游的支持。

**Comment by yujincheng08** [comment]
Duplicate of #529

**Comment by duzhaokun123** [comment]
4.4 漫游不支持

**Comment by lenghonglin** [comment]
> 

是的，在投影仪上看B站港澳台， 这个需求会逐渐多起来的

**Comment by lenghonglin** [comment]
> Duplicate of #529

是的， 在投影仪上看B站这个需求会越来越多的。需要做测试的话，可以一起配合。

**Comment by lenghonglin** [comment]
> 4.4 漫游不支持



> 4.4 漫游不支持

https://github.com/duzhaokun123/BilibiliHD2  这个也不支持4.4 = =

**Comment by duzhaokun123** [comment]
> > 4.4 漫游不支持
> 
> > 4.4 漫游不支持
> 
> https://github.com/duzhaokun123/BilibiliHD2 这个也不支持4.4 = =

so?

idk
