### ISSUE TITLE
[Feature]希望可以添加自动简繁转换的字幕

### ISSUE THREAD

**Issue by InoryLwc** [yujincheng08/BiliRoaming#585]
**原因**
推荐给朋友看番时，不太习惯繁体，看起来比较费劲

**功能简述**
简繁体自动转换生成，可以切换

**功能逻辑**
类似于“[解除B站限制](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6)”脚本，自动转换后，可以手动选择

**实现参考**
“[解除B站限制](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6)”脚本

**Comment by david082321** [comment]
#400
