### ISSUE TITLE
你好，我想问个问题

### ISSUE THREAD

**Issue by Ln-G0179** [yujincheng08/BiliRoaming#590]
我记得哔哩漫游和一个脚本有点关系，脚本名叫b站番剧解锁，现在下架了，作者应该是叫墨小呆，本来有群，现在群好像解散了，请问您知道具体情况吗

**Comment by david082321** [comment]
> 我记得哔哩漫游和一个脚本有点关系
应该没有关系吧？

> 脚本名叫b站番剧解锁，现在下架了，作者应该是叫墨小呆
是被人举报下架的，理由好像是抄了 https://greasyfork.org/zh-CN/scripts/25718 的代码

> 本来有群，现在群好像解散了
我看了一下他的电报群还在，加群的方式自己找

**Comment by Ln-G0179** [comment]
非常感谢大佬能够抽空解答

**Comment by Ln-G0179** [comment]
> 我看了一下他的电报群还在，加群的方式自己找
您好，方便说一下他的电报群账号吗，或者名称之类的，我怎么找到那个群呢，非常感谢
