### ISSUE TITLE
[BUG]6.71.0出现开屏广告

### ISSUE THREAD

**Issue by litianyuhehe** [yujincheng08/BiliRoaming#592]
**问题描述**
6.71.0出现开屏广告

**复现步骤**
如何复现
1. 打开哔哩哔哩6.71.0
2. 出现开屏广告，并不是每一次都会出，偶尔会出现

**截图**
![Screenshot_2022-05-06-19-37-12-36_149003a2d400f6adb210d7e357a3a646](https://user-images.githubusercontent.com/29541117/167124282-f0f8a0cf-9000-454c-b5dc-9ff3deed975e.jpg)

**环境信息**
 - 安卓版本：12
 - 系统版本：ColorOS12.1
 - 哔哩漫游版本：31922d9497（ci最新）
 - 哔哩哔哩版本和版本号：6.71.0-b8533838（6710300）正式版
 - 使用的框架和版本：lsposed_1.8.3_6550_zygisk
 - 其他：无

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8639638/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8639640/old_log.txt)

**Comment by Enaium** [comment]
![Screenshot_2022-05-07-07-38-15-968_tv.danmaku.bili.jpg](https://user-images.githubusercontent.com/32991121/167228212-69b22c85-01b8-4d24-ab88-2d16ef57dce8.jpg)
