### ISSUE TITLE
[Feature]底栏按钮修改

### ISSUE THREAD

**Issue by FinaFina233** [yujincheng08/BiliRoaming#593]
**原因**
底栏会员购以及上传键无用

**功能简述**
自由编辑底栏按键

**实现参考**
我记得旧版哔哩漫游是有这个功能的，我还反复看了几分钟才发现没了，是因为新版限制了吗

**Comment by david082321** [comment]
开启隐藏功能。
开启方式自己找，找不到就加一下QQ频道或是TG群

**Comment by FinaFina233** [comment]
好的 谢谢
