### ISSUE TITLE
[BUG] 哔哩哔哩6.71.0竖屏视频解析失败

### ISSUE THREAD

**Issue by EvatsugDnalloR** [yujincheng08/BiliRoaming#595]
**问题描述**
因为6.71.0为竖屏视频引入了新的抖音瀑布流框架，导致之前的竖屏视频解析失效了，希望能有像“直播间使用旧版框架“一样的功能，做到禁用新版恶心的抖音瀑布流框架

**复现步骤**
如何复现
1. 打开最新版6.71.0
2. 进入任意竖屏视频并全屏
3. 显示“解析失败，无法替换竖屏视频”，并处于最新的抖音瀑布流短视频播放框架

**截图**
![Screenshot_20220507-110945](https://user-images.githubusercontent.com/86464406/167247886-8231b823-db83-48a5-891c-1c55ca71e8c9.png)
![Screenshot_20220507-110957](https://user-images.githubusercontent.com/86464406/167247892-a41c4f18-b071-4eb1-9598-2e991d547d9e.png)

**环境信息**
 - 安卓版本：11
 - 系统版本：One UI 3.1
 - 哔哩漫游版本：1.6.2
 - 哔哩哔哩版本和版本号：国内版6.71.0
 - 使用的框架和版本：LSPosed 1.8.2
 - 其他：任意竖屏视频

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8644805/log.txt)

**Comment by duzhaokun123** [comment]
这功能本来就有

**Comment by EvatsugDnalloR** [comment]
> 这功能本来就有 而且没失效的样子

好吧，我看到解析失败还以为是因为用了新架构
不过主要还是解析失败的问题

**Comment by duzhaokun123** [comment]
如果说是灰度
抓一下 app.bilibili.com/x/v2/feed/index 的包

**Comment by EvatsugDnalloR** [comment]
> 如果说是灰度 抓一下 app.bilibili.com/x/v2/feed/index 的包

手机上浏览器打开再复制里面的内容吗？

**Comment by duzhaokun123** [comment]
不是 不会抓算了

**Comment by EvatsugDnalloR** [comment]
> 不是 不会抓算了

好吧确实不会

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/8656557/app-debug.zip)
用这个版本抓个日志

**Comment by EvatsugDnalloR** [comment]
> [app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/8656557/app-debug.zip) 用这个版本抓个日志
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8664354/log.txt)
