### ISSUE TITLE
[BUG]自定义我的页面和修改我的页面样式冲突

### ISSUE THREAD

**Issue by Kulahala** [yujincheng08/BiliRoaming#598]
**问题描述**
自定义我的页面和修改我的页面样式冲突,同时开启会如下且无法变为列表，关闭修改样式也不可逆

**复现步骤**
如何复现
1. 打开自定义我的样式，修改我的页面样式为列表
2. 点击确定并重启客户端
3. 出现自定义我的页面显示未知

![Snipaste_2022-05-08_18-47-37](https://user-images.githubusercontent.com/54696830/167327982-f1fa8679-092c-4299-a1a0-48378931f09c.png)

**环境信息**
 - 安卓版本：12
 - 系统版本：miui13
 - 哔哩漫游版本：1.6.2
 - 哔哩哔哩版本和版本号：6.14
 - 使用的框架和版本：太极 9.0.1
 - 其他：无

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8648333/log.txt)

**Comment by duzhaokun123** [comment]
这两个功能应该不冲突

显示为未知应该是缓存问题

不知道什么原因导致的

**Comment by Kulahala** [comment]
> 

好的

**Comment by david082321** [comment]
是你开启速度太快。
先点漫游设置的重启客户端→点击底栏的“我的”→等待10~30秒(具体时间视你的网络速度)→然后打开漫游设置

**Comment by Kulahala** [comment]
> 是你开启速度太快。 先点漫游设置的重启客户端→点击底栏的“我的”→等待10~30秒(具体时间视你的网络速度)→然后打开漫游设置

阿这，我还重复卸载重装了几次好了
