### ISSUE TITLE
[BUG] 官方版6.72.0开屏净化失效

### ISSUE THREAD

**Issue by vgjjk5** [yujincheng08/BiliRoaming#599]
**问题描述**
无法屏蔽开屏广告

**复现步骤**
如何复现
1. 打开app

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2022-05-10-22-06-49-947_tv danmaku bili](https://user-images.githubusercontent.com/105296008/167648341-bbdd6f51-bd40-4c05-bbd9-9477b91ec517.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：miui 12.5.1 eu
 - 哔哩漫游版本：1.6.2
 - 哔哩哔哩版本和版本号：官方版 6.72.0
 - 使用的框架和版本：lsposed 1.8.3
 - 其他：

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8662208/log.txt)

**Comment by yujincheng08** [comment]
2d33f139c4bbddd6c33141b4373337cf37b9e24f

**Comment by duzhaokun123** [comment]
换 ci 再试
