### ISSUE TITLE
[Feature]恢复评论区按时间或热度排序

### ISSUE THREAD

**Issue by Enaium** [yujincheng08/BiliRoaming#600]
**原因**
有些视频评论区没有按时间排序或热度排序

**功能简述**
视频评论按时间排序或热度排序

**功能逻辑**
和有按时间排序或热度排序的评论区一样

**实现参考**
有按时间排序或热度排序的评论区

**Comment by duzhaokun123** [comment]
接口把这功能屏蔽了

难道全爬下来自己排

**Comment by Enaium** [comment]
> 接口把这功能屏蔽了
> 
> 难道全爬下来自己排

让评论区跳转到页末?

**Comment by duzhaokun123** [comment]
> > 接口把这功能屏蔽了
> > 难道全爬下来自己排
> 
> 让评论区跳转到页末?

你在说什么

我是说 官方在服务端屏蔽了这个功能 要想实现只能全爬下来自己排这么扭曲

**Comment by Enaium** [comment]
> > > 接口把这功能屏蔽了
> > > 难道全爬下来自己排
> > 
> > 让评论区跳转到页末?
> 
> 你在说什么
> 
> 我是说 官方在服务端屏蔽了这个功能 要想实现只能全爬下来自己排这么扭曲

没看懂? 这个接口没了不代表评论都加载不了，往下滑一个距离评论就会再次加载，滑倒最低也就是页末也就是最新的评论
