### ISSUE TITLE
[BUG]港澳台间谍过家家无法观看，其他的港澳台番剧可以观看

### ISSUE THREAD

**Issue by TonyYangStark** [yujincheng08/BiliRoaming#603]
**问题描述**
打开就缓冲，弹幕评论都没有

**复现步骤**
如何复现
1. 打开...
2. 点击...
3. 出现...状况

**截图**
- ![Screenshot_20220515-095631.jpg](https://user-images.githubusercontent.com/60918068/168454013-abf4e24a-03bb-43cb-bb47-955468a3db31.jpg)![Screenshot_20220515-095649.jpg](https://user-images.githubusercontent.com/60918068/168454015-8d1c0e61-71f5-4003-9ffe-ba3e9803c505.jpg)

**环境信息**
 - 安卓版本：8.0.0
 - 系统版本：EMUI8.0.0
 - 哔哩漫游版本：1.5.7
 - 哔哩哔哩版本和版本号：普通版6.59.0
 - 使用的框架和版本：太极阴内核129，承影9.0.0.01201725-7774
 - 其他：间谍过家家

**日志**
![log.txt](https://github.com/yujincheng08/BiliRoaming/files/8694178/log.txt)

**Comment by duzhaokun123** [comment]
不对就版本提供技术支持
