### ISSUE TITLE
[BUG]無法使用UPOS測速, 某些番劇無法觀看

### ISSUE THREAD

**Issue by sugiuraayano12345** [yujincheng08/BiliRoaming#61]
**问题描述**
無法使用UPOS測速, 某些番劇無法觀看

**复现步骤**
如何复现
1. 打开app
2. 点击某部番劇
3. 出现無法獲取視頻位址

1. 打開app
2. 進入嗶哩漫遊設定
3. 選擇UPOS測速
4. 顯示測速失敗

**截图**
![Screenshot_20201228-024425127](https://user-images.githubusercontent.com/76661755/103177582-c4ec4b80-48b6-11eb-915f-184499e11cf9.jpg)
![Screenshot_20201228-024857361](https://user-images.githubusercontent.com/76661755/103177648-4e038280-48b7-11eb-9cf0-4ccb5195c433.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：Custom ROM 
 - 哔哩漫游版本：1.4.0
 - 哔哩哔哩版本和版本号： 6.14.0
 - 使用的框架和版本：xpatch版
 - 其他：Tari tari 魔女之旅

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/5745025/log.txt)

**Comment by yujincheng08** [comment]
自带服务器都停止解析了，要自建服务器
