### ISSUE TITLE
[Feature]建议添加屏蔽三连 投票 评分弹窗 功能

### ISSUE THREAD

**Issue by jiang-yuan** [yujincheng08/BiliRoaming#612]
**原因**
弹窗太烦了

**功能简述**
屏蔽三连 投票 评分弹窗

**功能逻辑**
加个按钮可以勾选

**实现参考**
tg群里有人发了去弹窗的6.6.0 的apk,可以参考下实现

**Comment by jiang-yuan** [comment]
我想说这个功能现在在最新版失效了

**Comment by golezi** [comment]
我翻了下源码 导出配置修改再导入的
play商店最新版 没有再显示三连这些了

jiang-yuan ***@***.***> 于 2023年1月11日周三 19:56写道：

**Comment by jiang-yuan** [comment]
嗯,更新最新版可以了
