### ISSUE TITLE
麻烦修改下wiki里的公共解析服务器

### ISSUE THREAD

**Issue by InternetBugs** [yujincheng08/BiliRoaming#616]
**原因**
为什么想要这个功能

**功能简述**
麻烦在我的解析服务器xn--3dz622b.xn--n4y597a0mfle743a.icu（碧诗.被陈睿送进.icu）上方加个域名
陈睿.我爱你
服务端是同一个 支持全区域解锁

**功能逻辑**
如何互交、如何使用等

**实现参考**
（可选）该功能可能的实现方式，或者其他已经实现该功能的应用等

**Comment by yujincheng08** [comment]
好了
