### ISSUE TITLE
[Feature]将主搜索框与首页分离

### ISSUE THREAD

**Issue by aoout** [yujincheng08/BiliRoaming#625]
**原因**
如果在底栏显示中取消首页就没法进入主搜索框，那么实际上就并不能提供一种有效的避开内容推荐流后仍然能够使应用正常使用的手段。

**功能简述**
提供一个选项，可以将动态页的搜索替换成首页的搜索。

**功能逻辑**
仍然照常使用。

**Comment by yujincheng08** [comment]
脱裤子放屁
