### ISSUE TITLE
[Feature]希望支持切换硬解码

### ISSUE THREAD

**Issue by wan0ge** [yujincheng08/BiliRoaming#627]
原因

从官方版本6.15后叔叔就删除了自由切换解码，后续版本基本上都是强制软解，但硬解在现在优势更大，可中幅减少手机cpu核心占用和优化耗电、发热情况（相较于软解）
![IMG_20220525_233227](https://user-images.githubusercontent.com/82034747/170301444-3e6400d3-9a1c-4132-bfc4-b77d523e803a.jpg)
![2022-5-25_23-31-46](https://user-images.githubusercontent.com/82034747/170301499-63293f66-d6c7-4134-a2de-ad36724eeb40.JPEG)
（测试图上面为软解下面为硬解，机型用的备用机骁龙710所以整体占用会比较大）

功能简述
加个开关就好，重点是能否实现切换硬解码

功能逻辑
开启则强制硬解码，关闭则官方默认（或者关闭则软解）

实现参考
本人不是大佬所以不知道官方6.15后删除的是开关还是具体实现方式，如果只是删了开关那或许可以调用出官方的方案，如果删的比较彻底那可能就需要大佬想想办法了，理论上切换播放视频的解码或许不难？在播放视频前替换解码方式什么的？
ps：有一部分人因为对硬解码的执念至今还留在6.14版本，所以还是有需求的，求求了看看能不能实现

**Comment by wan0ge** [comment]
有同样需求的https://github.com/yujincheng08/BiliRoaming/issues/582#issue-1222656698

**Comment by duzhaokun123** [comment]
有没有可能 新版默认硬解优先

**Comment by wan0ge** [comment]
> 有没有可能 新版默认硬解优先 而你的设备可能不能硬解 hevc

好像…测了下还真是💦 被别人误导忘记测新版了，打扰了💦
