### ISSUE TITLE
哔哩漫游设置的按钮不见了。[BUG]

### ISSUE THREAD

**Issue by whzdl** [yujincheng08/BiliRoaming#628]
**问题描述**
漫游设置的入口在某一次进入软件时不见了，同时“我的”页面增加了游戏中心的相关入口。

**复现步骤**
复现
1. 打开bilibili  lsp版6.74.0
2. 点击“我的”
3. 找不到“哔哩漫游设置”的入口。
4. 取而代之出现，“游戏中心”“我的游戏”〝我的预约”〝找游戏”〝游戏排行榜”入口

**截图**
![Screenshot_20220525_215504_tv danmaku bili_edit_1077181917889278](https://user-images.githubusercontent.com/89906152/170326438-afdf05c5-044d-4175-a158-f348b0fb22d4.jpg)
![Screenshot_20220526_012619](https://user-images.githubusercontent.com/89906152/170326445-8adb4eea-3d3a-4f47-8e1e-82494fa977bb.jpg)

**环境信息**
 - 系统版本：HarmonyOS  2.0.0.230
 - 哔哩漫游版本:
 - 哔哩哔哩版本和版本号:lsp版6.74.0
 - 使用的框架和版本：
 - 其他：

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件

**Comment by david082321** [comment]
1. 打开哔哩哔哩，点击底栏的「我的」，等到30秒
2. 打开哔哩漫游app，然后点第二个设置：「打开模块设置」
3. 打开漫游的「自定义我的页面」→「重置」→「确定并重启客户端」
4. 重新设置的时候，记得保留最后的推荐服务，否则容易出bug
