### ISSUE TITLE
[BUG]play版无法使用1.6.0及之后版本

### ISSUE THREAD

**Issue by Apkeniqo** [yujincheng08/BiliRoaming#630]
**问题描述**
设置按钮消失，通过漫游强行打开设置并配置后不生效

**复现步骤**
如何复现

1. 打开...
2. 点击...
3. 出现...状况

**截图**
![4E097D53705068A089BA3C40A95BB721](https://user-images.githubusercontent.com/90621995/170808451-d17a72fe-4074-4644-8b78-cb7fd7a5fcc6.jpg)
![7B3331B8E6E3954CC8B66188311B7256](https://user-images.githubusercontent.com/90621995/170808452-0b0c189e-0c29-4dcb-979b-20f94ea7f5d3.jpg)
![C13238F779D083CAFB4AB96FFC73276E](https://user-images.githubusercontent.com/90621995/170808454-dd5ca882-6161-488a-aa1a-e2410c38be05.jpg)
![C8483515F986AE420300D050199EB241](https://user-images.githubusercontent.com/90621995/170808455-4e3eb2b2-4422-4f23-8a00-004e3ec77a25.jpg)

**环境信息**
 - 安卓版本：10
 - 系统版本：Harmony OS 2.0.0.232
 - 哔哩漫游版本：1.6.0及之后
 - 哔哩哔哩版本和版本号：play版3.9.1
 - 使用的框架和版本：太极9.0.1
 - 其他：所有港澳台番剧

**日志**
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8790434/log.txt)

**Comment by AisukaYuki** [comment]
05-28 11:08:57.882 30103 30103 D BiliRoaming: BiliRoaming version: 1.5.9(59)   
你更新了个寂寞
