### ISSUE TITLE
[Feature]希望能够增加净化动态页面“校园”标签功能

### ISSUE THREAD

**Issue by TennoujiKud** [yujincheng08/BiliRoaming#638]
**原因**
校园标签之前强推的同城标签类似，碍眼无用。尽管在高版本上可以通过关闭个性化内容推荐的方式关闭，但是关闭后首页推荐视频质量无法令人满意。没有该按钮的低版本应用更是无法关闭该标签。

**功能简述**
增加净化功能，开启净化校园标签后不必关闭个性化内容推荐即可使得校园标签不再出现在动态界面。

**功能逻辑**
类似净化同城标签

**实现参考**
类似净化同城标签

**Comment by zjns** [comment]
没有支持校园标签的账号，不知道对应的id是多少。

**Comment by zjns** [comment]
装下这个调试版的漫游，打开哔哩哔哩。点下动态标签，把日志贴到这，我就能找到校园的标签id。
[app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/8792546/app-debug.apk.zip)

**Comment by TennoujiKud** [comment]
> 装下这个调试版的漫游，打开哔哩哔哩。点下动态标签，把日志贴到这，我就能找到校园的标签id。 [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/8792546/app-debug.apk.zip)

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792646/log.txt)

**Comment by zjns** [comment]
> > 装下这个调试版的漫游，打开哔哩哔哩。点下动态标签，把日志贴到这，我就能找到校园的标签id。 [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/8792546/app-debug.apk.zip)
> 
> [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792646/log.txt)

日志内容不够，看不到，要不你备份下配置，重新安装一遍哔哩哔哩，重新在LSPosed里勾选下模块，然后直接进APP点动态，导出日志，先不恢复配置。

**Comment by zjns** [comment]
> > 装下这个调试版的漫游，打开哔哩哔哩。点下动态标签，把日志贴到这，我就能找到校园的标签id。 [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/8792546/app-debug.apk.zip)
> 
> [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792646/log.txt)

应该还需要先登录下账号，不然可能看不到校园标签

**Comment by TennoujiKud** [comment]
> > > 装下这个调试版的漫游，打开哔哩哔哩。点下动态标签，把日志贴到这，我就能找到校园的标签id。 [app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/8792546/app-debug.apk.zip)
> > 
> > 
> > [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792646/log.txt)
> 
> 应该还需要先登录下账号，不然可能看不到校园标签

更换设备重新抓取了一下，这次应该可以了
[Uploading log.txt…]()

**Comment by TennoujiKud** [comment]
> 
更换设备重新抓取了（刚刚没注意没上传完就发了艹）
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792688/log.txt)

**Comment by zjns** [comment]
> > 
> 
> 更换设备重新抓取了（刚刚没注意没上传完就发了艹） [log.txt](https://github.com/yujincheng08/BiliRoaming/files/8792688/log.txt)

日历里看到校园标签啦
