### ISSUE TITLE
[Server] bili.pch.pub 跑路了

### ISSUE THREAD

**Issue by pchpub** [yujincheng08/BiliRoaming#652]
### 联系方式

https://t.me/chenzerocheng

### 域名

bili.pch.pub

### 支持地区

- [ ] 中国大陆
- [ ] 港澳
- [ ] 台湾
- [ ] 东南亚

### 赞助地址

https://afdian.net/@pinkchen

**Comment by WAZ000** [comment]
这个服务器不能用了吗？显示我的B站ID为不在白名单
