### ISSUE TITLE
[Bug] HD 1.20.0版本"我的"界面侧边栏不显示漫游设置

### ISSUE THREAD

**Issue by Snapmali** [yujincheng08/BiliRoaming#654]
### 问题描述

HD 1.20.0版本对”我的”侧边栏进行改版，导致哔哩漫游设置无法显示。

### 复现步骤

1. 打开HD版本APP进入“我的”页面

### 预期行为

左侧边栏上滑显示哔哩漫游设置

### 实际行为

左侧边栏已改版，上滑不显示哔哩漫游设置

### 截图或录屏

![IMG_20220608_214946](https://user-images.githubusercontent.com/34858368/172634661-c0ac7275-3759-49ce-b2d9-061dcb03c53b.jpg)

### 安卓版本

11

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.20.0

### 使用的框架和版本

LSPosed 1.8.3

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8862193/log.txt)

**Comment by david082321** [comment]
已修复 https://github.com/yujincheng08/BiliRoaming/commit/43ba75450f32c54b832cfdaa602107cc8cc25ffc

你既然是LSPosed，可以改用ci版 https://t.me/biliroaming
