### ISSUE TITLE
[Bug] play 2.10.1和国内6.14.0无法观看解锁番剧

### ISSUE THREAD

**Issue by Flying-dragon-boxing** [yujincheng08/BiliRoaming#655]
### 问题描述

打开任意港澳台，东南亚区番剧，play版显示接口返回失败，国内版在资源不存在和一般的有地区限制画面中显示一个，将play版更新至3.11.0后问题消失

### 复现步骤

打开任意打开任意港澳台，东南亚区番剧

### 预期行为

模块显示运行信息进行解析

### 实际行为

play版显示接口返回失败，国内版在资源不存在和一般的有地区限制画面中随机显示，模块亦不显示运行信息

### 截图或录屏

play版没截到
![Screenshot_2022-06-10-10-32-18-179_tv danmaku bili](https://user-images.githubusercontent.com/60290838/172978964-b33cc471-bd09-4a86-a562-c7132cb8bec4.jpg)
![Screenshot_2022-06-10-10-32-27-186_tv danmaku bili](https://user-images.githubusercontent.com/60290838/172978987-c436f2a7-9a01-4c6e-89af-61b5dcf8f194.jpg)

### 安卓版本

12

### 哔哩漫游版本

普通版在1.5.9-1.6.3各版本，play版仅测试1.6.3

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.14.0

### 使用的框架和版本

太极阴 承影·9.1.0.06062317-7935

### 日志

粉版
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8875375/log.txt)
play版
[log (1).txt](https://github.com/yujincheng08/BiliRoaming/files/8875379/log.1.txt)

**Comment by Flying-dragon-boxing** [comment]
此外这两个版本表现为upos无法测速

**Comment by JasonKhew96** [comment]
@Flying-dragon-boxing 解析服务器 的 问题
