### ISSUE TITLE
【功能请求】去除复制的视频链接的冗余后缀

### ISSUE THREAD

**Issue by ZerOri** [yujincheng08/BiliRoaming#66]
**原因**
用app分享视频网址时av号后面会跟一堆来源跟踪参数，分享出去很不美观

**功能简述**
**功能逻辑**
希望能增加个像Bilibili-Evolved的【网址参数清理】类似的功能，自动删除复制到剪贴板中的链接的多余跟踪参数

**实现参考**
Bilibili-Evolved的【网址参数清理】

**Comment by yujincheng08** [comment]
打开不以小程序分享。。。

**Comment by ZerOri** [comment]
> 打开不以小程序分享。。。

说的是play版，play版本来就不能以小程序分享啊
