### ISSUE TITLE
[Bug] 竖屏转正常视频后无法全屏播放

### ISSUE THREAD

**Issue by mchobbylong** [yujincheng08/BiliRoaming#664]
### 问题描述

启用竖屏转正常视频功能后，全屏视频时会自动重新打开相同的视频（多一层activity）。

### 复现步骤

1. 打开一个竖屏视频
2. 点击右下角的全屏按钮

### 预期行为

竖屏转正常视频后，可以正常全屏播放。

### 实际行为

全屏播放竖屏视频时，会自动重新打开相同的视频。

### 截图或录屏

https://user-images.githubusercontent.com/32614955/173770234-2e97d9f5-fd7c-49f0-bd9c-1d0f5c802638.mp4

### 安卓版本

11

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.77.0

### 使用的框架和版本

LSP 1.8.3

### 日志

[log (1).txt](https://github.com/yujincheng08/BiliRoaming/files/8906983/log.1.txt)

**Comment by yujincheng08** [comment]
在设置里面关闭看一看功能。
