### ISSUE TITLE
[Bug] 在harmonyOS 2.0.0下发生开屏闪退

### ISSUE THREAD

**Issue by WXHNO1** [yujincheng08/BiliRoaming#665]
### 问题描述

使用华为平板matepad11（harmonyOS 2.0.0）浏览LSPatch 1.64版本时，出现开屏闪退

### 复现步骤

1.安装好新应用后，首次打开正常
2.在打开后登录自己账号，并导入漫游配置，根据漫游提示重启
3.重启时，开屏时间变长，但能正常浏览
4.再次重启，开始大概率闪退

### 预期行为

正常使用

### 实际行为

开屏大概率闪退

### 截图或录屏

https://user-images.githubusercontent.com/107706956/174347236-5bdd2335-0f31-4b3f-8b44-17b9234e3118.mp4

### 安卓版本

harmonyOS 2.0.0

### 哔哩漫游版本

1.64

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74 .0

### 使用的框架和版本

LSPatch 1.64

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8929503/log.txt)

**Comment by yujincheng08** [comment]
不支持鸿蒙。

**Comment by cxw620** [comment]
最新的lspatch的版本才出现的闪退问题，上一个版本没有的，临时解决方法是彻底清除后台或者多试几次。可能是鸿蒙的后台保活和lspatch框架运行有冲突
