### ISSUE TITLE
[Bug] 启动时提示崩溃

### ISSUE THREAD

**Issue by BlueDolphin9527** [yujincheng08/BiliRoaming#671]
### 问题描述

Realme GT Neo3，安卓12
1、每次启动时都会提示崩溃，但不影响使用。
2、点击UPOS服务器测速，应用就会直接卡住，切到后台再进就正常了。

另一部一加7T LOS系统在同样的magisk,LSP以及B站版本的环境下正常使用。

### 复现步骤

1、每次启动时
2、每次点击UPOS服务器测速时

### 预期行为

应该可以正常使用或测速

### 实际行为

提示崩溃或者应用卡死

### 截图或录屏

![Screenshot_2022-06-22-13-59-31-95_149003a2d400f6adb210d7e357a3a646](https://user-images.githubusercontent.com/62049321/174955005-1decc7f7-d8b2-4d47-96f8-f8ce32551fc0.jpg)

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本号

LTY 3.0版

### 使用的框架和版本

LSP 1.8.3

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8954825/log.txt)
[old_log.txt](https://github.com/yujincheng08/BiliRoaming/files/8954830/old_log.txt)

**Comment by yujincheng08** [comment]
> 哔哩哔哩版本
> No response

**Comment by duzhaokun123** [comment]
@BlueDolphin9527 

> Bilibili version: tv.danmaku.bili@Luo Tianyi(88888888) (32bit)

停止使用你的奇怪哔哩哔哩版本反馈问题

**Comment by BlueDolphin9527** [comment]
委屈，就不能包容一下优秀的修改版应用吗？

**Comment by yujincheng08** [comment]
为什么不让修改版反过来兼容漫游呢 😄
