### ISSUE TITLE
[Feature] 解除区域外番剧投屏限制

### ISSUE THREAD

**Issue by lxchx** [yujincheng08/BiliRoaming#672]
### 原因

- 在Xpatch/LSPatch 版 1.6.4下，港澳台的番剧是不能投屏的，比如大陆的辉夜可以投屏，港澳台的就不行，显示“抱歉，此视频无法投屏”

### 功能简述

 解除区域外番剧的投屏限制

### 功能逻辑

在哔哩漫游设置中加一个开关即可

**Comment by yujincheng08** [comment]
有没有一种可能，这不是限制。
