### ISSUE TITLE
[Bug] 原生音乐通知样式播放音频无法拖动进度条

### ISSUE THREAD

**Issue by Lightsummer233** [yujincheng08/BiliRoaming#678]
### 问题描述

在哔哩漫游设置中勾选原生音乐通知样式后
播放音频无法在通知栏中拖动进度条
视频却可以

### 复现步骤

见截图或录屏

### 预期行为

播放音频可以拖动进度条

### 实际行为

播放音频不能拖动进度条

### 截图或录屏

因为操作视频过大，用阿里云盘发
https://www.aliyundrive.com/s/XjdWazPUiJH

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.78.0

### 使用的框架和版本

LSPatch 版

### 其他

音频和视频在后台播放是正常的，视频是静音的，就是音频的进度条不能在通知栏拖动。

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/8994001/log.txt)

**Comment by Lightsummer233** [comment]
手机是Redmi K40
系统是MIUI 13 开发版公测 V13.0.6.1.40.DEV
这样的原生音乐通知是安卓12的，理论上和MIUI和机型没关系

**Comment by yujincheng08** [comment]
6.79+1.6.4 k50 13.0.21 无法复现

**Comment by Lightsummer233** [comment]
K50一样有这个bug

**Comment by Lightsummer233** [comment]
这个应该是模块只适配了视频没适配音频吧（没勾选时不管是通知还是小米妙播都没有进度条，视频也一样）
