### ISSUE TITLE
[Feature] 增加文字表情包的渲染

### ISSUE THREAD

**Issue by AS042971** [yujincheng08/BiliRoaming#679]
### 原因

复制并发送评论区带有表情包的评论时，如果发送者没有购买这一表情包，在发送的内容中就会显示成【表情包名】
如果能在客户端中将这一类被转化的表情包还原成原始图片，就可以在一定程度上提升评论区的观感

另一个原因是我做的一个自定义表情包插件
https://www.bilibili.com/read/cv17348244
https://github.com/AS042971/bilibili-bobo
希望能在手机端以某种方式呈现出来

### 功能简述

当在动态和评论区检测到【表情包名】这样的文本时，将其替换为对应的表情包图片

如果可以加入自定义的表情包图片替换规则就更好了

### 功能逻辑

建立一个额外的仓库存储所有表情包名称和 Bilibili 图床 URL 的对应关系
程序启动时从此仓库更新数据
加载动态和评论区时进行匹配和替换

### 实现参考

网页端的自定义表情包插件（基于Tampermonkey）
https://github.com/AS042971/bilibili-bobo/blob/main/bilibili-bobo.js

新的表情包输入面板和动态中的表情包解析采用的都是 XHR 返回值注入的方式
评论可以采用 JQuery 返回值注入，但这里是直接在渲染得到的 dom 上进行修改

不知道手机端的数据通信是不是用了类似的模式

**Comment by yujincheng08** [comment]
没啥意义，不搞
