### ISSUE TITLE
[Bug] 华为mate40pro用太极阴无法使用

### ISSUE THREAD

**Issue by zkh1992** [yujincheng08/BiliRoaming#680]
### 问题描述

华为鸿蒙系统，用太极阴创建应用后，开起模块后进入哔哩哔哩虽然提示已激活，但在“我的”里面没有漫游配置。
且直接进模块apk设置也无用

### 复现步骤

1.使用太极阴创建最新版哔站，目前是6.79
2.根据提示卸载原版程序并成功创建程序
3.安装漫游模块前，并启动
4.重启手机并打开哔站

### 预期行为

提示漫游已激活并且在“我的”里面可以设置

### 实际行为

提示了漫游已激活但是“我的”里面没有设置，且漫游不生效

### 截图或录屏

![Screenshot_20220701_191619](https://user-images.githubusercontent.com/29116860/176884533-009693bb-87ed-43f9-a1c1-2afa1e8fdec8.jpg)

### 安卓版本

鸿蒙应该是安卓10

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.79.0

### 使用的框架和版本

Xpatch

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9028425/log.txt)

**Comment by yujincheng08** [comment]
日志完全没有漫游的东西，怀疑是太极的问题。
