### ISSUE TITLE
[Server]   星瞳.我爱你  地区改为所有

### ISSUE THREAD

**Issue by QingM0** [yujincheng08/BiliRoaming#682]
### 联系方式

https://space.bilibili.com/401315430/

### 域名

星瞳.我爱你

### 支持地区

- [x] 中国大陆
- [x] 港澳
- [x] 台湾
- [x] 东南亚

### 赞助地址

https://afdian.net/@qmswf/

**Comment by yujincheng08** [comment]
好了
