### ISSUE TITLE
[Feature] 评论区解锁

### ISSUE THREAD

**Issue by cxw620** [yujincheng08/BiliRoaming#683]
### 原因

目前发现有评论区也是锁区的，没办法看到评论区。
例如契约之吻（仅限港澳台）。
开启代理后是可以看到评论区的，似乎只有大陆不能看评论区。

### 功能简述

如题，希望评论区和弹幕的API也进行代理解锁

### 功能逻辑

对评论区和弹幕的API进行反代。

**Comment by JasonKhew96** [comment]
修什么呢，都好好的，你的版本问题

**Comment by cxw620** [comment]
> 修什么呢，都好好的，你的版本问题

不过试了好几次只有这一个番出问题，其他都好好的，版本是lspatch的最新版，比较奇怪😔

**Comment by david082321** [comment]
> 出现相同情况，7月新番的评论区都无法查看，4月番倒是可以正常看。可能是解析服务器的小问题吧，但是我换了四五个服务器都不行。😂

与解析服务器无关，没有代理评论区(漫游目前也没有这个功能)，所以这就是原本官方给你的样子。

**Comment by cxw620** [comment]
升级go-server版本一通后现在已经可以了

**Comment by cxw620** [comment]
大概率是嗶哩嗶哩的限制吧, 反正我測試現在都正常了, 之前評論區沒能正常顯示的契約之吻現在評論區也能看到了.
