### ISSUE TITLE
[Bug] 番剧彩蛋失效

### ISSUE THREAD

**Issue by xiaoxiaoxiaoxiaowu** [yujincheng08/BiliRoaming#688]
### 问题描述

当在看《暂停！让我查攻略》的第6话的16:35时应该会出现彩蛋，可是并没有出现

### 复现步骤

看《暂停！让我查攻略》的第6话的16:35

### 预期行为

正常出现结尾的彩蛋

### 实际行为

没有出现对应的彩蛋

### 安卓版本

安卓12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

未使用任何框架

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9076314/log.txt)

**Comment by yujincheng08** [comment]
给张对比图很难？

**Comment by xiaoxiaoxiaoxiaowu** [comment]
很难，要卸载现在的版本然后下原版

**Comment by yujincheng08** [comment]
ok

**Comment by david082321** [comment]
你的问题，我用自己打包的LSPatch版(无内置模块)，就能看到番剧彩蛋。

**Comment by xiaoxiaoxiaoxiaowu** [comment]
> 你的问题，我用自己打包的LSPatch版（无内置模块）+额外安装漫游，就能看到番剧彩蛋。

啊这，我直接下作者提供的就遇到的这个问题

**Comment by xiaoxiaoxiaoxiaowu** [comment]
> 还行



> 你的问题，我用自己打包的LSPatch版（无内置模块）+额外安装漫游，就能看到番剧彩蛋。

![image](https://user-images.githubusercontent.com/87689396/178103676-37666fb8-b2e4-43cf-ad26-f5c82da14a13.png)
