### ISSUE TITLE
[BUG]Edxp打开后仍无法激活

### ISSUE THREAD

**Issue by mdogwoop** [yujincheng08/BiliRoaming#69]
**问题描述**
Edxp无法激活应用

**复现步骤**
激活后重启，无法使用，仍然显示未激活

**截图**
![Screenshot_2021-01-16-19-17-54-406_org meowcat edxposed manager](https://user-images.githubusercontent.com/64186089/104810493-ea260700-582f-11eb-9bd3-34c609987e7e.jpg)
已激活，已重启，但是仍然无法使用

**环境信息**
 - 安卓版本：11
 - 系统版本：乌堆官改，开发版MIUI12.5，21.1.8
 - 哔哩漫游版本：1.4.1
 - 哔哩哔哩版本和版本号：普通版6.17.1
 - 使用的框架和版本：Magisk21.2，Riru版本v23.3，Magisk官方仓库安装，Edxposed Canary YAHFAv0.5.1.4_4668-master
 - 其他：（如哪部番、哪个专栏等）

**日志**
[EdXposed_Verbose_20210116_191525.txt](https://github.com/yujincheng08/BiliRoaming/files/5824292/EdXposed_Verbose_20210116_191525.txt)

**Comment by yujincheng08** [comment]
你的module list是空的
