### ISSUE TITLE
[Feature] 希望可以拥有屏蔽评论区关键词跳转的功能

### ISSUE THREAD

**Issue by tinypie1** [yujincheng08/BiliRoaming#690]
### 原因

在评论区，时不时有会遇到这些有关键词跳转的评论，有时候会误触
![Screenshot_20220712-061947_哔哩哔哩](https://user-images.githubusercontent.com/108934214/178368262-d016a13a-d63e-4938-8498-50d151dde67d.png)
图随手截的

### 功能简述

希望在隐藏功能里推出能屏蔽掉评论区蓝色关键字跳转的功能

### 功能逻辑

在隐藏功能开启

**Comment by oOtroyOo** [comment]
+1.
我连app都没更新，他为什么也会出来，纯属脑残功能。阿姨上阵干的事吗
![](https://user-images.githubusercontent.com/19978148/178391756-47810d2f-66df-4607-9e73-385e4f07b109.jpg)

**Comment by zjns** [comment]
目前这个应该还在灰度阶段，不是所有人都会开启这个，可以先装我这个DEBUG版模块然后抓个日志发出来看看
[BiliRoamingX_1.6.4.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9188371/BiliRoamingX_1.6.4.apk.zip)

**Comment by zjns** [comment]
> 目前这个应该还在灰度阶段，不是所有人都会开启这个，可以先装我这个DEBUG版模块然后抓个日志发出来看看 [BiliRoamingX_1.6.4.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9188371/BiliRoamingX_1.6.4.apk.zip)

上面的模块有问题，换一个，查看一个这种带搜索的评论即可
[app-debug.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9188402/app-debug.apk.zip)

**Comment by david082321** [comment]
@zjns 
文件内搜索 `&keyword=`
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9192283/log.txt)

**Comment by zjns** [comment]
> @zjns 文件内搜索 `&keyword=` [log.txt](https://github.com/yujincheng08/BiliRoaming/files/9192311/log.txt)

试下这个包，隐藏功能里加了个选项
[BiliRoamingX_1.6.4.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9194088/BiliRoamingX_1.6.4.apk.zip)

**Comment by zjns** [comment]
> > @zjns 文件内搜索 `&keyword=` [log.txt](https://github.com/yujincheng08/BiliRoaming/files/9192311/log.txt)
> 
> 试下这个包，隐藏功能里加了个选项 [BiliRoamingX_1.6.4.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9194088/BiliRoamingX_1.6.4.apk.zip)

@tinypie1 @oOtroyOo 用这个包试试能不能屏蔽评论蓝字搜索，隐藏功能最后一个选项

**Comment by oOtroyOo** [comment]
![Screenshot_20220728-032526__01](https://user-images.githubusercontent.com/19978148/181356250-0f63a018-e048-4266-8260-d9375493276a.jpg)
![Screenshot_20220728-032707__01](https://user-images.githubusercontent.com/19978148/181356268-f62ccb66-4789-484e-ba47-8479a9c7afec.jpg)

似乎无效

**Comment by oOtroyOo** [comment]
> 
> 模块激活了吗，我这个模块包名不一样，你要把原版模块关掉，然后勾选我这个哔哩漫游X，重启哔哩哔哩

原版是关了，况且，菜单有这个选项，并且这个是仅限港澳台的番剧的截图

**Comment by zjns** [comment]
> > 模块激活了吗，我这个模块包名不一样，你要把原版模块关掉，然后勾选我这个哔哩漫游X，重启哔哩哔哩
> 
> 原版是关了，况且，菜单有这个选项，并且这个是仅限港澳台的番剧的截图

我用这个模块，换了一个有评论关键字搜索的账号，查看你截图的这条评论，发现是生效的，应该就是模块没生效。你可以发个日志出来看看

**Comment by zjns** [comment]
> > 模块激活了吗，我这个模块包名不一样，你要把原版模块关掉，然后勾选我这个哔哩漫游X，重启哔哩哔哩
> 
> 原版是关了，况且，菜单有这个选项，并且这个是仅限港澳台的番剧的截图

发个日志出来，看看用的哪个版本的哔哩哔哩，有可能是哔哩哔哩版本号不同导致的

**Comment by zjns** [comment]
> > 模块激活了吗，我这个模块包名不一样，你要把原版模块关掉，然后勾选我这个哔哩漫游X，重启哔哩哔哩
> 
> 原版是关了，况且，菜单有这个选项，并且这个是仅限港澳台的番剧的截图

找到问题了，哔哩哔哩老版本数据格式不同的问题，已经修复，可以试试这个包
[BiliRoamingX_1.6.4.apk.zip](https://github.com/yujincheng08/BiliRoaming/files/9205463/BiliRoamingX_1.6.4.apk.zip)

**Comment by oOtroyOo** [comment]
似乎行了👌 我再观察一会有没有出现。等正式版

**Comment by oOtroyOo** [comment]
发现新问题，如果从  我的消息→收到的赞→点任意历史评论。这里也会出现评论搜索。不过呢原视频的底下的同一条评论搜索是确认关闭了，可能是这个评论界面是单独做的。

**Comment by oOtroyOo** [comment]
@zjns

**Comment by zjns** [comment]
> @zjns

已经改了
