### ISSUE TITLE
[Feature] CC字幕繁体转简体

### ISSUE THREAD

**Issue by bobleer** [yujincheng08/BiliRoaming#695]
### 原因

繁体看着太累

### 功能简述

字幕选项中如果有繁体中文的字幕，就新增一个简体中文的选项。

### 功能逻辑

字幕选项中如果有繁体中文的字幕，就新增一个简体中文的选项。

**Comment by JasonKhew96** [comment]
https://github.com/yujincheng08/BiliRoaming/issues/608 https://github.com/yujincheng08/BiliRoaming/issues/585 https://github.com/yujincheng08/BiliRoaming/issues/584 https://github.com/yujincheng08/BiliRoaming/issues/571 https://github.com/yujincheng08/BiliRoaming/issues/552 https://github.com/yujincheng08/BiliRoaming/issues/467 https://github.com/yujincheng08/BiliRoaming/issues/437
