### ISSUE TITLE
[Feature] 增加"移除b站横屏转为竖版视频按钮"功能

### ISSUE THREAD

**Issue by DTpeel** [yujincheng08/BiliRoaming#696]
### 原因

竖版视频不讨喜，不如横版视频好用，保留此按钮令人糟心

### 功能简述

增加移除该按钮功能
![Screenshot_20220718_230744_edit_1113559628606911](https://user-images.githubusercontent.com/61195619/179544181-4705b975-d3e4-4afb-93e7-262cfbed36b8.jpg)

### 功能逻辑

将竖版视频按钮不显示或直接从界面移除

**Comment by KimmyXYC** [comment]
有没有一种可能，哔哩哔哩的设置里面是可以关闭的

**Comment by yujincheng08** [comment]
乐

**Comment by DTpeel** [comment]
> 乐

啊Σ(ŎдŎ|||)ﾉﾉ，没看到，抱歉，抱歉，对您造成不便，谢谢大佬回复
