### ISSUE TITLE
[BUG] 打开“替换竖版视频”功能后，打开全屏的竖版视频会闪退

### ISSUE THREAD

**Issue by pptext** [yujincheng08/BiliRoaming#699]
### 原因

bug反馈太繁琐，所以在这里反馈

### 功能简述

[BUG] 打开“替换竖版视频”功能后，打开全屏的竖版视频会闪退，应该是b站改了

### 功能逻辑

。

### 实现参考

。

**Comment by iamr0s** [comment]
https://github.com/yujincheng08/BiliRoaming/pull/729
