### ISSUE TITLE
[Server] 嘉然批.发超市.icu （所有）

### ISSUE THREAD

**Issue by pchpub** [yujincheng08/BiliRoaming#702]
### 联系方式

https://t.me/chenzerocheng

### 域名

嘉然批.发超市.icu

### 支持地区

- [x] 中国大陆
- [x] 港澳
- [x] 台湾
- [x] 东南亚

### 赞助地址

https://afdian.net/@pinkchen

**Comment by yujincheng08** [comment]
好了
