### ISSUE TITLE
希望移除（屏蔽）评论区搜索功能

### ISSUE THREAD

**Issue by wanwangzi666** [yujincheng08/BiliRoaming#705]
### 原因

评论区搜索太影响观感了

### 功能简述

![IMG_20220724_190139](https://user-images.githubusercontent.com/62100759/180644061-1ddbfdc4-a3bb-4a79-9870-abea072ceeab.jpg)

### 功能逻辑

去除评论区蓝字，和跳转。

**Comment by yujincheng08** [comment]
Duplicate of #690
