### ISSUE TITLE
更新MIUI内测系统后b站就不显示漫游了[Bug] 

### ISSUE THREAD

**Issue by UMRs233** [yujincheng08/BiliRoaming#709]
### 问题描述

更新MIUI内测版后，b站漫游模块就不显示了，每次打开都显示哔哩漫游错误

### 复现步骤

更新的MIUI（22.7.13）内测版，root后用lsp安装了模块1.6.4和哔哩软件6.74.0，但是打开哔哩漫游模块消失了

### 预期行为

![IMG_20220726_094248](https://user-images.githubusercontent.com/105194957/180904665-5e9fbe0f-1e3b-492c-8520-38d65d7de794.jpg)

### 实际行为

![Screenshot_2022-07-26-01-39-07-665_tv danmaku bil](https://user-images.githubusercontent.com/105194957/180904485-3e4c28c8-6e6a-4026-83ea-6ec1116387df.jpg)
![Screenshot_2022-07-26-09-29-29-146_tv danmaku bil](https://user-images.githubusercontent.com/105194957/180904496-22405f26-7e67-4e03-be5a-8aea352950f9.jpg)

### 截图或录屏

![Screenshot_2022-07-26-01-39-07-665_tv danmaku bil](https://user-images.githubusercontent.com/105194957/180903115-54d18fb4-31b6-482f-9a9b-e505d1b871f7.jpg)
![Screenshot_2022-07-26-09-29-29-146_tv danmaku bil](https://user-images.githubusercontent.com/105194957/180903149-de43cf1d-8635-4cdd-9713-5702379a47b2.jpg)

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

LSPosed 1.8.3

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9185891/log.txt)

**Comment by jiasswee** [comment]
我也是这样，请问解决了吗

**Comment by david082321** [comment]
> 我也是这样，请问解决了吗

MIUI 的问题，换其他牌子的手机就可以了。

**Comment by duzhaokun123** [comment]
其实卸载 MIUI 也可以
________________________________

**Comment by yujincheng08** [comment]
试试手动使用最新的 LSPatch 打包试试？我打包时候的 LSPatch 版本比较低可能有点问题。
