### ISSUE TITLE
[Bug] 哔哩哔哩闪退

### ISSUE THREAD

**Issue by aobakaolengmian** [yujincheng08/BiliRoaming#711]
### 问题描述

在太极阴或漫游内打开哔哩哔哩后就会闪退

### 复现步骤

在太极阴或哔哩漫游内启动哔哩哔哩，哔哩哔哩出现闪退

### 预期行为

正常使用

### 实际行为

闪退

### 截图或录屏

Uploading SVID_20220727_141624_1.mp4…

### 安卓版本

10

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.81.0

### 使用的框架和版本

太极9.3.1

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9195579/log.txt)

**Comment by yujincheng08** [comment]
太极的问题。
