### ISSUE TITLE
[Bug] 自定义同时缓存数，无法打开开关，显示客户端不支持

### ISSUE THREAD

**Issue by FairyWorld** [yujincheng08/BiliRoaming#713]
### 问题描述

自定义同时缓存数，无法打开开关，显示客户端不支持。

经过测试6.58是可以的, 6.70和6.83不可以打开，如果先安装6.58打开开关后再覆盖安装到新版本，虽然新版本还是无法打开开关，但是自定义同时缓存数的功能已经打开并且可用。

所以新版本应该是支持的，但是没办法打开开关。

### 复现步骤

6.58版本可以打开"自定义同时缓存数", 6.70和6.83都不行。

### 预期行为

允许设置同时缓存数

### 实际行为

不允许设置同时缓存数

### 安卓版本

12

### 哔哩漫游版本

4e718588da

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.83.0

### 使用的框架和版本

1.8.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9217471/log.txt)

**Comment by yujincheng08** [comment]
不支持就是不支持啊
