### ISSUE TITLE
最新版港澳台区评论区无法显示[Bug] 

### ISSUE THREAD

**Issue by Guimianneko** [yujincheng08/BiliRoaming#714]
### 问题描述

港澳台区番剧评论区无法显示

### 复现步骤

打开评论区即复现

### 预期行为

正常显示评论

### 实际行为

评论区无法显示

### 截图或录屏

![Uploading Screenshot_2022-07-30-06-06-59-184_tv.danmaku.bili.jpg…]()

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.83.0

### 使用的框架和版本

LSPosed1.8.3（6591）

### 其他

所有港澳台区番剧

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9223478/log.txt)

**Comment by yujincheng08** [comment]
我能打开

**Comment by KimmyXYC** [comment]
试试 东南亚/泰国 服务器 留空，然后再试试能否查看评论区

**Comment by Guimianneko** [comment]
解决了！感谢
