### ISSUE TITLE
[Bug] 旧版bilibili打开即报错

### ISSUE THREAD

**Issue by swhoro** [yujincheng08/BiliRoaming#715]
### 问题描述

app打开即报错
MIUI 13.0.8

### 复现步骤

1.安装bilibili
2.打开bilibili

### 预期行为

正常打开

### 实际行为

打开即报错

### 截图或录屏

![1659158449287](https://user-images.githubusercontent.com/34229589/181875984-3bb6801e-6b59-4f9b-a3e9-2737c860d129.jpg)

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

5.58.0

### 使用的框架和版本

1.8.3

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9225346/log.txt)

**Comment by duzhaokun123** [comment]
1.6.4 不支持 5.x

你可以使用旧版哔哩漫游

注意使用旧版意味着放弃技术支持

**Comment by swhoro** [comment]
> 1.6.4 不支持 5.x
> 
> 你可以使用旧版哔哩漫游
> 
> 注意使用旧版意味着放弃技术支持

请问下最新支持的漫游是哪个版本

**Comment by yujincheng08** [comment]
我可没空兼容旧版。
