### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by lrln** [yujincheng08/BiliRoaming#720]
### 原因

阿b的服务器经常抽风，习惯性缓存观看，但是每次点击缓存都很麻烦

### 功能简述

视频右下角三个点，点击时候，也弹出缓存按钮，可以选择清晰度确认下载或者直接下载。按钮位置跟稍后再看一起并排放

### 功能逻辑

动态界面点击视频左上角三个点，点击后，在稍后再看上面有缓存按钮。
搜索界面，点击右下角三个点，除了分享，稍后再看意外，可以点击直接缓存
稍后再看界面，点击右下角三个点，除了删除，还有缓存选项
主页界面，点击右下角三个点，除了反馈，我不想看，添加至稍后再看，还有缓存选项

**Comment by yujincheng08** [comment]
不搞
