### ISSUE TITLE
[Bug] 32位APP提示账号未登录，无法解锁港澳台番剧

### ISSUE THREAD

**Issue by SekiBetu** [yujincheng08/BiliRoaming#721]
### 问题描述

提示账号未登录，无法解锁港澳台番剧

### 复现步骤

1.打开哔哩哔哩
2.打开港澳台动画页面
3.提示账号未登录
4.退出账号，清空APP全部数据和缓存
5.重新打开APP登录并重复1、2步骤仍然无法解锁

### 预期行为

应该能解锁观看

### 实际行为

提示账号未登录

### 截图或录屏

![Screenshot_2022-08-03-13-47-21-741_tv danmaku bili](https://user-images.githubusercontent.com/38283893/182533455-8d42fe23-0886-48c0-b3fe-5e78eaa3b9d8.jpg)

![Screenshot_2022-08-03-13-15-53-062_tv danmaku bili](https://user-images.githubusercontent.com/38283893/182532953-9eac9a1f-0aab-489f-975b-08bb55f4cc08.jpg)

### 安卓版本

12

### 哔哩漫游版本

3b0078eb26

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.83.0

### 使用的框架和版本

LSPosed 1.8.3 6593 zygisk

### 其他

magisk 25.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9248273/log.txt)

**Comment by duzhaokun123** [comment]
看起来 32bit 的坏了

**Comment by SekiBetu** [comment]
习惯用酷安一键更新apk，给我升成32位的了，nnd，换成64位可以了

**Comment by duzhaokun123** [comment]
建议别关 因为 32bit 是坏的

除非他砍 32bit 支持

**Comment by yujincheng08** [comment]
似乎是部分 dex 由于懒加载而还没有被加载，导致部分类没找到。
