### ISSUE TITLE
[Feature] 希望添加可以修改播放器快捷手势的功能

### ISSUE THREAD

**Issue by Mzhuangshao** [yujincheng08/BiliRoaming#722]
### 原因

![S20803-21422555](https://user-images.githubusercontent.com/79238849/182625843-fada7f71-22e7-44fb-a99d-17d2b661714c.png)
长按视频快进功能很容易误触，阿b又不让关闭

### 功能简述

可以屏蔽or强制关闭某个快捷手势

### 功能逻辑

漫游的设置页内可以添加一个选项来强制开关播放器内的快捷手势

**Comment by yujincheng08** [comment]
太复杂不搞，应该直接找叔叔要。
