### ISSUE TITLE
[Feature] 漫游番剧提供中文简体字幕

### ISSUE THREAD

**Issue by Raiden-1** [yujincheng08/BiliRoaming#723]
### 原因

看繁体还是比较累，PC端脚本已经有繁转简中字幕

### 功能简述

底端字幕可以选择简中
![image](https://user-images.githubusercontent.com/75219287/182670610-12f4591a-49d3-4610-9fbe-a45efbc30524.png)

### 功能逻辑

字幕增加中文（中国）选项
![image](https://user-images.githubusercontent.com/75219287/182670714-616cb87f-c278-40b9-a264-173adadc4ca9.png)

### 实现参考

脚本：解除B站区域限制 https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md

**Comment by KimmyXYC** [comment]
#608 #585 #584 #571 #552 #467 #437
