### ISSUE TITLE
[Bug] 哔哩哔哩6.83.0版本强制使用旧版直播间功能失效

### ISSUE THREAD

**Issue by Raiden-1** [yujincheng08/BiliRoaming#724]
### 问题描述

哔哩哔哩6.83.0版本强制使用旧版直播间功能失效

### 复现步骤

哔哩漫游设置选择“强制使用旧版直播间样式”功能选择，哔哩哔哩6.83.0版本下打开直播间无法生效

### 预期行为

强制使用旧版直播间样式

### 实际行为

仍为新版直播间

### 截图或录屏

![1c67b6011f4070e1484fb9260ecd6bc](https://user-images.githubusercontent.com/75219287/182671569-18adf5ef-2736-4582-98f2-0198d7262150.jpg)

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.83.0

### 使用的框架和版本

LSPosed 1.8.3

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9253808/log.txt)

**Comment by yujincheng08** [comment]
无解，旧版直播间的代码已经完全被移除了，不可能加回来了。而且旧版直播间有问题，比如部分直播间不能打 SC 等。这个功能以后会移除或者限制版本。
