### ISSUE TITLE
[Feature] 禁用看一看按钮

### ISSUE THREAD

**Issue by Raiden-1** [yujincheng08/BiliRoaming#725]
### 原因

横屏稿件半屏时显示看一看按钮原来是可以在播放设置里自行关闭的，6.83.0版本不能关闭了。开了替换竖屏视频的情况下，点该按钮页面也会重新加载。该按钮靠近全屏按钮，容易误触。
![image](https://user-images.githubusercontent.com/75219287/182676642-912f8c74-87c7-436e-b9cd-a52ab00e143a.png)
![image](https://user-images.githubusercontent.com/75219287/182675144-ec212fc6-e362-4ef0-b1ec-8885190650a4.png)

### 功能简述

在哔哩漫游设置中加入禁用看一看按钮

### 功能逻辑

开关选择禁用/开启

**Comment by KimmyXYC** [comment]
哔哩哔哩设置里面关闭
