### ISSUE TITLE
[Bug] 64bit无法打开哔哩哔哩番剧出差主页，无法解锁港澳台

### ISSUE THREAD

**Issue by MakesYT** [yujincheng08/BiliRoaming#728]
### 问题描述

无法打开哔哩哔哩番剧出差主页，提示加载出错

### 复现步骤

1.打开哔哩哔哩番剧出差主页

### 预期行为

打开主页

### 实际行为

保存

### 截图或录屏

![Screenshot_20220805_102651_tv danmaku bili](https://user-images.githubusercontent.com/42534870/182988551-a87aadf4-d37f-48fe-8ac4-96127205f1ac.jpg)

### 安卓版本

鸿蒙2

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.84.0

### 使用的框架和版本

太极 承影·9.1.2.07052050-8190

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9264756/log.txt)

**Comment by MakesYT** [comment]
![Screenshot_20220805_103941_tv danmaku bili](https://user-images.githubusercontent.com/42534870/182990060-4ed806b0-935a-4189-9f19-21b7088636a6.png)

**Comment by duzhaokun123** [comment]
日志没啥信息 重新抓

**Comment by MakesYT** [comment]
![log.txt](https://github.com/yujincheng08/BiliRoaming/files/9265058/log.txt)

**Comment by yujincheng08** [comment]
不支持鸿蒙

**Comment by KimmyXYC** [comment]
我建议使用lspatch框架及漫游最新ci试试看
