### ISSUE TITLE
[BUG] CC字幕显示错误

### ISSUE THREAD

**Issue by lrhtony** [yujincheng08/BiliRoaming#73]
**问题描述**
CC字幕显示错误，并出现多语种字幕重合的情况

**复现步骤**
如何复现
1. 打开摇曳百合 夏日时光！+这部番
2. 开启CC字幕并选择简体中文
3. 出现CC字幕错误的情况

**截图**
![Screenshot_2021-01-18-20-15-20-819_tv danmaku bili](https://user-images.githubusercontent.com/54092711/104915066-b3e2a780-5955-11eb-87ba-3903739f8026.jpg)
![Screenshot_2021-01-18-20-18-18-816_tv danmaku bili](https://user-images.githubusercontent.com/54092711/104915072-b6dd9800-5955-11eb-8b4c-2b4ceef29151.jpg)

**环境信息**
 - 安卓版本：安卓10
 - 系统版本：MIUI 12.0.11.0
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号：原版6.17.1 国际版2.10.1 
 - 使用的框架和版本：EdXposed v0.4.6.4(4563)(YAHFA)
 - 其他：摇曳百合 夏日时光！+（泰国的）<https://bangumi.bilibili.com/anime/37265>

**日志**
[EdXposed_Modules_20210118_203011.txt](https://github.com/yujincheng08/BiliRoaming/files/5830166/EdXposed_Modules_20210118_203011.txt)
[EdXposed_Verbose_20210118_203031.txt](https://github.com/yujincheng08/BiliRoaming/files/5830168/EdXposed_Verbose_20210118_203031.txt)

**Comment by yujincheng08** [comment]
这能和我有什么关系呢
