### ISSUE TITLE
[Bug] 自签发证书不支持

### ISSUE THREAD

**Issue by PikuZheng** [yujincheng08/BiliRoaming#731]
### 问题描述

自建服务器并使用自签发证书。自签发CA已添加至 安全-加密与凭据-用户凭据。
使用手机浏览器打开自建服务器地址，显示连接是安全的。

bili漫游提示“服务器不可用”

日志
```
BiliRoaming: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

### 复现步骤

1. 使用nginx自建服务器
2. 使用easy-rsa或其他方式生成rootCA，并将其添加至 安全-加密与凭据-用户凭据
3. 使用easy-rsa或其他方式生成服务器证书，并配置nginx使用该证书
4. 配置bili漫游使用此服务器

### 预期行为

正常代理

### 实际行为

服务器不可用

### 安卓版本

9

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.82.0

### 使用的框架和版本

EdXposed v93.0

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9274393/log.txt)

**Comment by yujincheng08** [comment]
预期行为

**Comment by machine-doll** [comment]
要么转成系统证书，要么用插件干掉bilibili客户端的ssl pinning
