### ISSUE TITLE
[Feature] 添加32位版本

### ISSUE THREAD

**Issue by Kuddray** [yujincheng08/BiliRoaming#732]
### 原因

我的设备是32位系统，下载连接中的1.19 HD版 装不了

### 功能简述

请问可以添加一个32位的LSPatch版[1.6.4] [1.19.0] 哔哩哔哩 HD.apk吗？

谢谢

### 功能逻辑

.

**Comment by duzhaokun123** [comment]
不可能 因为官方就没有

**Comment by Kuddray** [comment]
> 不可能 因为官方就没有

你好如果你说的是32位的1.19 HD版，这个是吗？我的设备能安装起来

**Comment by Kuddray** [comment]
https://www.apkmirror.com/apk/bilibili/%e5%93%94%e5%93%a9%e5%93%94%e5%93%a9hd-2/%e5%93%94%e5%93%a9%e5%93%94%e5%93%a9hd-2-1-19-0-release/%e5%93%94%e5%93%a9%e5%93%94%e5%93%a9hd-1-19-0-android-apk-download/

**Comment by duzhaokun123** [comment]
哦 怎么 1.19 也有 32 的

算了不重要 lspatch 的自己打包就有了

**Comment by yujincheng08** [comment]
自己打包
