### ISSUE TITLE
[Server] 嘉然批.发超市.icu  和 万人骑.pch.pub 捐赠地址更改(避免典)

### ISSUE THREAD

**Issue by pchpub** [yujincheng08/BiliRoaming#735]
### 联系方式

https://t.me/chenzerocheng

### 域名

嘉然批.发超市.icu

### 支持地区

- [x] 中国大陆
- [x] 港澳
- [x] 台湾
- [x] 东南亚

### 赞助地址

嘉然批.发超市.icu/donate

**Comment by yujincheng08** [comment]
o了
