### ISSUE TITLE
[Bug] 修改后功能缺失

### ISSUE THREAD

**Issue by Kihara777** [yujincheng08/BiliRoaming#736]
### 问题描述

装扮系统下线
搜索结果为空
底栏内容消失
我的页面残废

### 复现步骤

不需要。

### 预期行为

什么都不会发生。

### 实际行为

装扮系统消失，找不到入口且装扮不会生效。

使用自带的搜索时返回空结果，但由漫游创建的（如其他地区番剧搜索）则不受影响。

底栏内容只剩下三个（首页 动态 会员购）

我的页面中的推荐内容只剩下四个图标（直播中心，免流量服务，会员购中心，我的钱包），其他设置仅剩下三个（联系客服，哔哩漫游设置，设置）。同时可能伴有 修改我的页面样式 失效。

注：以上问题均出现于 **默认不修改任何设置** 且 **不启用隐藏功能** 的情况下。

### 截图或录屏

首次启动时：
![photo_2022-08-12_14-21-39](https://user-images.githubusercontent.com/24633616/184293390-fb4ea654-9525-4adc-a227-5f67f4b051c7.jpg)
第二次启动时：
![photo_2022-08-12_14-14-08](https://user-images.githubusercontent.com/24633616/184293371-81395fe5-a621-45b8-9c03-6f5b2dae0434.jpg)

### 安卓版本

12 (SDK31)

### 哔哩漫游版本

8eca4a0c9f

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

tv.danmaku.bili >= 6.70.0

### 使用的框架和版本

LSPatch 0.3.1 (manager)

### 其他

我的页面消失后的临时解决方案：
安装漫游APK
从漫游应用进入漫游菜单
开启 移动我的页面到侧边栏 并重启哔哩哔哩。

### 日志

已开启可调试，log文件为漫游导出。
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9314052/log.txt)

**Comment by yujincheng08** [comment]
`Bilibili version: tv.danmaku.bili@6.70.0(1)`

版本号是 1，功能怎么可能正常。
