### ISSUE TITLE
[Server] 伊蕾娜.我爱你 请求更换捐赠地址（捐赠地址可正常解析）

### ISSUE THREAD

**Issue by azurstar** [yujincheng08/BiliRoaming#737]
### 联系方式

https://t.me/AzurStar

### 域名

伊蕾娜.我爱你

### 支持地区

- [x] 中国大陆
- [x] 港澳
- [x] 台湾
- [x] 东南亚

### 赞助地址

伊蕾娜.我爱你/donate

**Comment by yujincheng08** [comment]
好了
