### ISSUE TITLE
统一两个界面下的自由复制UI

### ISSUE THREAD

**Issue by Miuzarte** [yujincheng08/BiliRoaming#741]
### 原因

正常浏览和稍后在看的评论区长按复制所弹出的窗口UI样式不统一，太怪了

### 功能简述

统一这两个界面的按钮排布
![Screenshot_20220813-203915_哔哩哔哩](https://user-images.githubusercontent.com/66856838/184494555-546608ca-a168-4afd-be6c-4b9191f42f97.png)
![Screenshot_20220813-203945_哔哩哔哩](https://user-images.githubusercontent.com/66856838/184494558-431d2c0b-07d8-4183-8535-637362882220.png)

### 功能逻辑

统一这两个界面的按钮排布

**Comment by duzhaokun123** [comment]
dialog 相关代码只有 https://github.com/yujincheng08/BiliRoaming/blob/02baaa238613162bcb0eff4f45fa41d1f933538b/app/src/main/java/me/iacn/biliroaming/hook/CopyHook.kt#L69-L92

样式不统一可能是别的问题
