### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiaoxiaoxiaoxiaowu** [yujincheng08/BiliRoaming#743]
### 问题描述

竖屏视频替换之后无法开启全屏

### 复现步骤

1.在漫游中设置替换竖屏视频
2.找到一个竖屏视频
3.点击全屏的位置

### 预期行为

视频处于全屏状态并继续播放

### 实际行为

视频没有开启全屏，并且重新回到原来的视频界面

### 截图或录屏

Uploading Screenrecorder-2022-08-14-02-03-39-188(0).mp4…

### 安卓版本

安卓12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

未使用任何框架

### 其他

av298947648

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9331981/log.txt)

**Comment by xiaoxiaoxiaoxiaowu** [comment]
https://user-images.githubusercontent.com/87689396/184506340-d67acee7-d693-4910-91d4-2404d7cf87c1.mp4

视频没上传上来，就再发一下

**Comment by yujincheng08** [comment]
关掉看一看功能

**Comment by xiaoxiaoxiaoxiaowu** [comment]
> 关掉看一看功能

关闭替换竖屏视频？对吗？
