### ISSUE TITLE
[Feature] 去除up设置的广告

### ISSUE THREAD

**Issue by Miuzarte** [yujincheng08/BiliRoaming#748]
### 原因

这个广告会导致下面的标题、关注按钮等控件都下移一段距离，每次点进视频界面习惯性马上点开简介会导致点到关注
虽然我怎么记得好像之前的版本有过这个功能？最近更新了一下哔哩哔哩就又开始出现了  不太确定

### 功能简述

去除`up主推荐广告`
![Screenshot_20220815-010743_哔哩哔哩~2](https://user-images.githubusercontent.com/66856838/184547716-192a31e1-1baa-461f-822a-b55ecb2dba6d.png)

### 功能逻辑

去除`up主推荐广告`

**Comment by KimmyXYC** [comment]
有这个功能的

**Comment by Miuzarte** [comment]
> 有这个功能的，需要动脑筋找一找

能不能劳您大驾动动聪明的脑袋瓜帮我想一想
