### ISSUE TITLE
[Feature] 评论区楼层显示

### ISSUE THREAD

**Issue by hui-shao** [yujincheng08/BiliRoaming#752]
### 原因

无他，想看看小破站删评是多离谱：
通过楼层数可以看出总评论数，然后结合对比下现存评论数……

以前好像是因为api失效所以下架了。
我也是看到了近期有人实现，所以过来请开发团队评估一下。

（如果有其它方法看到总评论数也行？）

### 功能简述

在评论区的回复内额外显示楼层信息。
（就按照以前那样就行啦）

### 功能逻辑

有两种方案：

方案一【api调用量最大】：
在设置中添加开关，开启后，显示所有评论的楼层信息。

方案二【api调用量中等】
1. 在设置中添加“总开关”，开启后，在 `视频的菜单` 添加“显示视频评论区楼层”按钮。（添加在楼层右侧三个点的菜单里）
2. 点击这个“显示视频评论区楼层”的按钮后，再显示所有评论的楼层（或者做成`lazyload`的样式？滑动到可视区域再去获取）

方案三【api调用量最少】：
1. 在设置中添加“总开关”，开启后，在 `视频评论区具体的楼层内` 添加“显示当前评论楼层”按钮。（添加在楼层右侧三个点的菜单里）
2. 点击这个“显示当前评论楼层”的按钮后，再去获取楼层。

### 实现参考

https://greasyfork.org/zh-CN/scripts/443543
链接是最近看到的一个 PC 版油猴脚本的实现。

大致流程是：
1. 先通过 `//api.bilibili.com/x/v2/reply/main` 获取整体的评论信息。
2. 接下来根据 `//api.bilibili.com/x/v2/reply/info` 获取某条评论具体的信息，服务器返回的数据里包含了楼层信息。

附件是完整的 js 实现（备份）
[哔哩哔哩（B站）评论区显示楼层v1.8.6.user.js.txt](https://github.com/yujincheng08/BiliRoaming/files/9386553/B.v1.8.6.user.js.txt)

**Comment by cxw620** [comment]
越看越生气的玩意儿, 反正是那种简短的容易留下(例如"统一!"), 敏感一点的视频长评必被夹

**Comment by yu22c** [comment]
旧版本现在只能点开楼中楼看楼层了

**Comment by yujincheng08** [comment]
很难保证 `//api.bilibili.com/x/v2/reply/info` 不会在未来砍掉楼层信息，所以并不打算做。
