### ISSUE TITLE
[Bug]网页端番剧《在地下城尋求邂逅是否搞錯了什麼 第四季》拉取失败

### ISSUE THREAD

**Issue by SDB-dier** [yujincheng08/BiliRoaming#756]
### 问题描述

进入番剧界面后视频显示无法播放的16秒视频，弹框中出现“拉取视频失败，原因账号未登录”。本人已登录但非大会员

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss42271#634348
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"尚电部的蒂尔电教","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=42271
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=779640202&qn=80&type=&otype=json&fourk=1&bvid=BV1ye4y197u5&ep_id=634345&fnver=0&fnval=80&session=f9c42129d73001ce96f311161f09d2ca&module=bangumi&area=&access_key={{access_key}}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=779640202&qn=80&type=&otype=json&fourk=1&bvid=BV1ye4y197u5&ep_id=634345&fnver=0&fnval=80&session=f9c42129d73001ce96f311161f09d2ca&module=bangumi&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=779640202&bvid=BV1ye4y197u5&qn=80&type=&otype=json&ep_id=634345&fourk=1&fnver=0&fnval=80&session=ce31e67609b12d4550e498074bb130cb&module=bangumi&balh_ajax=1&area=&access_key=38b99ad7f5f59695159a01b65e798051
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=779640202&bvid=BV1ye4y197u5&qn=80&type=&otype=json&ep_id=634345&fourk=1&fnver=0&fnval=80&session=ce31e67609b12d4550e498074bb130cb&module=bangumi&balh_ajax=1&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: /x/web-interface/nav {"uname":"尚电部的蒂尔电教","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep634346 true
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=786580967&bvid=BV1Kd4y1U747&qn=80&type=&otype=json&ep_id=634346&fourk=1&fnver=0&fnval=80&session=66c19dabd168c81e5d418014f387e6bb&module=bangumi&balh_ajax=1&area=&access_key=38b99ad7f5f59695159a01b65e798051
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=786580967&bvid=BV1Kd4y1U747&qn=80&type=&otype=json&ep_id=634346&fourk=1&fnver=0&fnval=80&session=66c19dabd168c81e5d418014f387e6bb&module=bangumi&balh_ajax=1&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54

### 复现步骤

1.打开自己的VPN，选择香港地区加速
2.打开哔哩哔哩出差的主页，找到《在地下城尋求邂逅是否搞錯了什麼 第四季》并打开
3.跳转后显示16秒无法播放的视频
4.关闭自己的VPN，刷新界面，任然弹出16秒无法播放的视频

### 预期行为

跳转后正常播放视频（有几率弹出拉取视频失败，但原因为空）

### 实际行为

弹出“拉取视频失败，原因账号未登录”的弹窗

### 截图或录屏

![QQ截图20220821182208](https://user-images.githubusercontent.com/111683786/185786551-f4c5353d-07fe-46ea-a359-37c472b1a9ff.png)

### 安卓版本

网页端

### 哔哩漫游版本

网页端

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

网页端

### 使用的框架和版本

解除B站区域限制 8.2.26

### 其他

番剧《在地下城尋求邂逅是否搞錯了什麼 第四季》

### 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss42271#634348
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"尚电部的蒂尔电教","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=42271
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=779640202&qn=80&type=&otype=json&fourk=1&bvid=BV1ye4y197u5&ep_id=634345&fnver=0&fnval=80&session=f9c42129d73001ce96f311161f09d2ca&module=bangumi&area=&access_key={{access_key}}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=779640202&qn=80&type=&otype=json&fourk=1&bvid=BV1ye4y197u5&ep_id=634345&fnver=0&fnval=80&session=f9c42129d73001ce96f311161f09d2ca&module=bangumi&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=779640202&bvid=BV1ye4y197u5&qn=80&type=&otype=json&ep_id=634345&fourk=1&fnver=0&fnval=80&session=ce31e67609b12d4550e498074bb130cb&module=bangumi&balh_ajax=1&area=&access_key=38b99ad7f5f59695159a01b65e798051
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=779640202&bvid=BV1ye4y197u5&qn=80&type=&otype=json&ep_id=634345&fourk=1&fnver=0&fnval=80&session=ce31e67609b12d4550e498074bb130cb&module=bangumi&balh_ajax=1&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: /x/web-interface/nav {"uname":"尚电部的蒂尔电教","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep634346 true
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=786580967&bvid=BV1Kd4y1U747&qn=80&type=&otype=json&ep_id=634346&fourk=1&fnver=0&fnval=80&session=66c19dabd168c81e5d418014f387e6bb&module=bangumi&balh_ajax=1&area=&access_key=38b99ad7f5f59695159a01b65e798051
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=786580967&bvid=BV1Kd4y1U747&qn=80&type=&otype=json&ep_id=634346&fourk=1&fnver=0&fnval=80&session=66c19dabd168c81e5d418014f387e6bb&module=bangumi&balh_ajax=1&area=tw&access_key=38b99ad7f5f59695159a01b65e798051
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54

**Comment by yujincheng08** [comment]
关我屁事

**Comment by SDB-dier** [comment]
啊？

**Comment by SDB-dier** [comment]
这玩意不是你写的吗？我有问题就来反馈啊，什么叫关你屁事

**Comment by yujincheng08** [comment]
网页版就不是我写的，当然不关我事

**Comment by david082321** [comment]
> 这玩意不是你写的吗？我有问题就来反馈啊，什么叫关你屁事

看来你还是搞不懂啊，网页脚本的作者明明是这个
https://github.com/ipcjs/bilibili-helper
