### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 666Zoe666** [yujincheng08/BiliRoaming#757]
### 问题描述

之前用都没事，最近突然看视频老是看着看着就黑屏，然后又自己重新加载播放，看得我贼难受，看非国区的番只能看一会就看不了了，进度条也拖不动。卸载重装也没用
手机是redmi note 11t Pro，版本是1.6.4

### 复现步骤

打开视频
突然黑屏
过几秒后会回到前几秒继续播放
过了一会又会这样

打开非国区番剧
突然停止，进度条也无法拖动

### 预期行为

视频正常播放

### 实际行为

视频总是莫名其妙的停止

### 截图或录屏

链接：https://pan.baidu.com/s/1U7UcrtAR8xhbxJgpsCMvUA?pwd=1234 
提取码：1234 
--来自百度网盘超级会员V1的分享   这个是番剧的录屏

链接：https://pan.baidu.com/s/1DRu79aCtK0omjROpphLXAg?pwd=1234 
提取码：1234 
--来自百度网盘超级会员V1的分享   这个是普通视频的录屏，大约在中间和偏后面一点的地方各有一次

### 安卓版本

12

### 哔哩漫游版本

1.6.4

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

LS patch 1.6.4

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9391186/log.txt)

**Comment by yujincheng08** [comment]
普通视频也有问题那就是客户端本身的 bug。跟模块没啥关系。

**Comment by 666Zoe666** [comment]
> 跟模块普通视频也有那是啥本质关系的问题。

可以解释一下吗，我有点看不懂，谢谢
