### ISSUE TITLE
[Bug] 开启其他地区番剧搜索失败

### ISSUE THREAD

**Issue by EvatsugDnalloR** [yujincheng08/BiliRoaming#759]
### 问题描述

再打开 “开启其他地区番剧搜索” 功能的情况下搜索页面没有港澳台泰的选项

### 复现步骤

1. 开启 “其他地区番剧搜索” 功能并随便搜索一个番剧
2. 可以看到没有港澳台泰等地区的选项

### 预期行为

有其他地区的番剧搜索出现

### 实际行为

港澳台泰等其他地区的番剧搜索不出现

### 截图或录屏

![Screenshot_20220822-140708](https://user-images.githubusercontent.com/86464406/185917962-05b57ebf-246a-4787-be44-97b04d96000c.png)

### 安卓版本

12.0

### 哔哩漫游版本

6624cbcdb3

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.86.0

### 使用的框架和版本

Lsposed 1.84 (6552)

### 其他

Magisk版本25.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9394176/log.txt)

**Comment by JasonKhew96** [comment]
6.86.0 亲测没问题

**Comment by yujincheng08** [comment]
6.86.0 亲测没问题
