### ISSUE TITLE
[Bug] 模拟器解析服务器失败

### ISSUE THREAD

**Issue by jackwd387** [yujincheng08/BiliRoaming#762]
### 问题描述

在模拟器安装了哔哩漫游
使用了api.qiu.moe 哔哩.plus 哔哩.icu等代理服务器均无法使用

显示：‘请求服务器发生错误：啥都木有’

### 复现步骤

打开哔哩哔哩
点击番剧
出现请求错误

### 预期行为

正常使用代理服务器看番剧

### 实际行为

显示：‘请求服务器发生错误：啥都木有’

### 截图或录屏

![Uploading Screenshot_20220823-182625.png…]()

### 安卓版本

9

### 哔哩漫游版本

eaaccc18e9

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.55

### 使用的框架和版本

LSPoesd 1.8.3

### 其他

Msgisk delta v25.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9401760/log.txt)

**Comment by JasonKhew96** [comment]
没看出问题，怕是版本太老

**Comment by yujincheng08** [comment]
```
08-23 18:30:48.791 32204 32504 D BiliRoaming: getContent url: https://哔哩.icu/intl/gateway/v2/ogv/view/app/season
08-23 18:30:48.791 32204 32504 D BiliRoaming: getContent result: {"code":-404,"message":"啥都木有","ttl":1}
```

被当成泰区了。先尝试升级版本。
