### ISSUE TITLE
[Bug] 在动态中进入竖屏视频默认为抖音瀑布流

### ISSUE THREAD

**Issue by EvatsugDnalloR** [yujincheng08/BiliRoaming#763]
### 问题描述

在动态中进入竖屏视频默认为直接播放的抖音瀑布流而非正常视频，但从个人主页进入还是正常竖屏视频

### 复现步骤

1. 在动态中点击进入一个竖屏视频
2. 进入后默认显示为抖音瀑布流
3. 从个人主页进入则为正常竖屏视频

### 预期行为

从动态中点击进入竖屏视频也像从个人主页中进入动态视频一样显示为正常竖屏视频而非默认为抖音瀑布流

### 实际行为

从动态中点击进入竖屏视频就会默认进入自动播放的抖音瀑布流，但从个人主页进入同样的视频却不会

### 截图或录屏

![Screenshot_20220823-165657](https://user-images.githubusercontent.com/86464406/186192854-d101da9d-3895-4390-ac77-29f8abb08cee.png)

### 安卓版本

12.0

### 哔哩漫游版本

eaaccc18e9

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.86.0

### 使用的框架和版本

Lsposed 1.84 (6552)

### 其他

Magisk版本：25.2

截图中的视频为爱修汇的竖屏视频

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9403744/log.txt)

**Comment by EvatsugDnalloR** [comment]
还有一点从热门板块进入的竖屏视频也是正常的，就只有动态会直接进瀑布流

**Comment by yujincheng08** [comment]
https://user-images.githubusercontent.com/5022927/186352996-f653729f-635d-4389-93d2-6f9571ac289b.mp4

**Comment by EvatsugDnalloR** [comment]
> 
> https://user-images.githubusercontent.com/5022927/186352996-f653729f-635d-4389-93d2-6f9571ac289b.mp4
> 
> 

https://user-images.githubusercontent.com/86464406/186353952-9af09f39-af61-4ef2-a647-d2e1f0bff8f1.mp4

**Comment by zjns** [comment]
新的替换竖屏视频hook针对新版B已经完全无效，就没走hook的方法，新版B投稿竖屏视频竖屏模式入口设置里单独给了开关（这一块最近版本一直在变，恶心人），但这个开关不针对这一类“动态视频”（不属于投稿视频，投稿列表不会有）。
