### ISSUE TITLE
[Feature]  添加禁用新版（6.87.0）的“大家都在搜”功能

### ISSUE THREAD

**Issue by bobsword** [yujincheng08/BiliRoaming#764]
### 原因

看起来不爽

### 功能简述

隐藏新版app（6.87.0）退出视频到推荐页后的“大家都在看”
如图

![IMG_20220824_220324](https://user-images.githubusercontent.com/64725315/186440220-992783ab-9fa0-443c-98af-ac9c324132b3.jpg)

### 功能逻辑

在选项中开启，直接隐藏即可

### 实现参考

隐藏相关的按钮和文字，如果这样做不到无缝，也许可以拦截显示“大家都在搜”的代码（本人不是很了解，还得大佬指点）

**Comment by cxw620** [comment]
感觉B的产品经理没活了可以咬打火机

**Comment by david082321** [comment]
你会经常显示这个吗？
我待会发一个版本给你试试

**Comment by bobsword** [comment]
@david082321 

在普通版bili（tv.danmaku.bili）6.87.0
play版bili(com.bilibili.app.in) 3.13.0
可以触发，触发方式：
在首页推荐视频随意点进一个，浏览数秒后回到首页，有一定概率触发。
您可以把包发给我，我尝试复现。

**Comment by david082321** [comment]
@bobsword 
开启「隐藏功能」

开启方式加TG频道，然后再从频道加群，接着看验证机器人的欢迎提示。（或者自己找开启方法）

**Comment by bobsword** [comment]
> 「净化首页推荐内容」设置里面，多了四个选项，每次勾选其中一个，然后重启客户端测试。我觉得比较有可能的是 

> `rcmd`，但是我不敢肯定。

全部无效，
 以下为一次触发“大家都在搜”时的日志。大约在12:49:43出现。我不知道能不能帮助你排查

https://1drv.ms/t/s!AuIKvf55F0jtjjsNUI0SvqkMLHU-

**Comment by david082321** [comment]
> 全部无效， 以下为一次触发“大家都在搜”时的日志。大约在12:49:43出现。我不知道能不能帮助你排查

用这个，再抓一次日志
https://github.com/david082321/BiliRoaming/suites/7994353571/artifacts/342445371

**Comment by bobsword** [comment]
> 你试着用[这个](https://github.com/david082321/BiliRoaming/suites/7995694721/artifacts/342535375)，再抓一次日志

大约22:18:43

https://1drv.ms/t/s!AuIKvf55F0jtjj7cWmw9H5ZFI-nd

**Comment by david082321** [comment]
@bobsword 

抱歉，日志没找到特别的东西。

等其他人来做吧，我放弃了。

**Comment by yujincheng08** [comment]
没有见到过，怀疑小范围恢测后砍掉了。
