### ISSUE TITLE
[Bug] 无法搜索其它地区番剧

### ISSUE THREAD

**Issue by cicur** [yujincheng08/BiliRoaming#766]
### 问题描述

开启其它地区番剧搜索后搜索页面没有港澳台泰的选项
已尝试更新漫游和哔哩哔哩，以及重新开启该选项，均无效

### 复现步骤

1. 打开“开启其它地区番剧搜索”
2. 在搜索栏内搜索任意内容
3. 未出现港澳台泰等选项

### 预期行为

在搜索栏下方出现港澳台泰等选项

### 实际行为

搜索栏下方未出现港澳台泰等选项

### 截图或录屏

![Screenshot_2022-08-26-19-59-31-335_tv danmaku bili](https://user-images.githubusercontent.com/88472780/186907737-cbba41b7-e5f5-4c69-a7d5-cfa13ebd439a.jpg)
![IMG_20220826_204722](https://user-images.githubusercontent.com/88472780/186907763-25895e1e-cb10-4e5c-8532-b9ebe1c1031f.jpg)

### 安卓版本

12

### 哔哩漫游版本

d3c7464f5a

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.87.0

### 使用的框架和版本

LSPosed 1.8.3

### 其他

Magisk 25.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9433299/log.txt)

**Comment by zjns** [comment]
不太好修，新版搜索已经在灰度grpc了，那几个分类标签倒好说，关键是如何把拿到的json数据组装成pb数据或者是相应的实体。

**Comment by machine-doll** [comment]
我也遇到了同样的问题
目前只能通过港澳台的页面来看其他地区的视频了
