### ISSUE TITLE
[Feature] 把投稿界面被隐藏的添加分p按钮加回来

### ISSUE THREAD

**Issue by AmasakiKiha** [yujincheng08/BiliRoaming#775]
### 原因

投稿工具使用体验极差，完全过时，其它投稿分p功能已被封锁，作为一个老用户非常难过。如果真的能考虑，感激不尽

### 功能简述

如果投稿添加分p按钮真的只是被隐藏了的话，请问有时间会考虑一下做，把投稿界面被隐藏的添加分p按钮加回来吗。似乎电磁力够高的话手机端还是可以分p的，但是大家并不是都能做到，有许多人都发现没有添加视频按钮，许只能卸载回退老版本。如果能帮大家强制调出该按钮（指稿件编辑页面的添加视频按钮），应该会有许多老用户受益。

### 功能逻辑

在投稿界面，有一小部分人有一个添加视频的按钮，但是大多数人没有，如果能强制调出就好了。
![1661763364802](https://user-images.githubusercontent.com/65280447/187164031-b2c84e31-f7ec-4e98-8eb4-d9c34feefc65.png)

**Comment by yujincheng08** [comment]
不考虑。鼠鼠执意砍的东西加回来也不长远，跟评论区楼层一样。
