### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by RizukiJI** [yujincheng08/BiliRoaming#780]
### 问题描述

华为鸿蒙系统，分享视频或者直播间到qq微信时，一直显示分享失败

### 复现步骤

1.打开视频或者直播间
2.分享到qq或者微信
3.分享失败

### 预期行为

跳转到qq或者微信里确认分享，然后显示分享成功

### 实际行为

直接显示分享失败

### 截图或录屏

-

### 安卓版本

10

### 哔哩漫游版本

1.6.5

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.68.0

### 使用的框架和版本

1.8.5

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9453779/log.txt)

**Comment by cxw620** [comment]
哔哩哔哩的签名和官方包不一样, 微信/QQ会不阻止分享, 所以分享失败.

**Comment by yujincheng08** [comment]
不用漫游就行
