### ISSUE TITLE
[Bug] 未显示模块开启界面，但显示已激活

### ISSUE THREAD

**Issue by lingtian152** [yujincheng08/BiliRoaming#786]
### 问题描述

没有模块界面，但提示已激活，并且功能无效

### 复现步骤

未知，突然就无法使用了

### 预期行为

应该显示模块界面

### 实际行为

无模块界面，但已经显示已激活

### 截图或录屏

https://user-images.githubusercontent.com/49418651/188287182-3b75da8e-b45d-432c-87f7-83750892a57b.mp4

### 安卓版本

12

### 哔哩漫游版本

1.6.5

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.88.0

### 使用的框架和版本

太极 青钢影·10.0.5.08291252-8376

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9483357/log.txt)

**Comment by yujincheng08** [comment]
太极里面重新优化一下

**Comment by lingtian152** [comment]
> 太极里面重新优化一下

不行，刚刚试了，还是没显示

**Comment by yujincheng08** [comment]
反正肯定是太极问题，这里没法解决。你试试重装太极优化过的客户端。
