### ISSUE TITLE
[Bug] 应用重启闪退

### ISSUE THREAD

**Issue by ling-yu-ling** [yujincheng08/BiliRoaming#798]
### 问题描述

应用停止或者第二天重启的时候会卡在logo界面，然后闪退

### 复现步骤

1打开哔哩哔哩概念版
2卡在logo界面
3发生闪退，手机界面卡主5-10s无法操作

### 预期行为

logo界面以后出现开屏画面，之后进入主页显示模块运行信息

### 实际行为

卡在logo界面然后闪退

### 安卓版本

10

### 哔哩漫游版本

1.6.5

### 哔哩哔哩版本

概念版

### 哔哩哔哩版本号

6.81.0

### 使用的框架和版本

LSPatch0.3.1(308) 框架版本1.8.3(6563)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9571929/log.txt)

**Comment by yujincheng08** [comment]
鸿蒙的问题，修不了。

**Comment by cxw620** [comment]
升级HarmonyOS 3.0版本有改观
