### ISSUE TITLE
首次开启时闪退[Bug] 

### ISSUE THREAD

**Issue by NewJediOrder** [yujincheng08/BiliRoaming#802]
### 问题描述

首次开启应用时会闪退，并且会出现3～4次

### 复现步骤

打开应用
进入加载界面
进入首页（或进入自定义启动图）
（打开首页推荐视频）
闪退

### 预期行为

正常来说应该一次就能进入应用

### 实际行为

实际上频繁闪退，会持续3～4次，最多时5次

### 安卓版本

HarmonyOS 2.0.0（AOSP 10.0）

### 哔哩漫游版本

1.6.5

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.87.0

### 使用的框架和版本

LSPatch

### 日志

--------- beginning of main
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   (no managed stack frames)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] 
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] "main" prio=5 tid=1 Native
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | group="" sCount=1 dsCount=0 flags=1 obj=0x73042540 self=0x7921a10800
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | sysTid=12452 nice=0 cgrp=default sched=0/0 handle=0x79a88970d0
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | state=S schedstat=( 6012094781 2447459909 2470 ) utm=567 stm=33 core=3 HZ=100
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | stack=0x7ffe7f7000-0x7ffe7f9000 stackSize=8192KB
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | held mutexes=
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   kernel: (couldn't read /proc/self/task/12452/stack)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #00 pc 00000000000bae08  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #01 pc 0000000000017b60  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #02 pc 0000000000017a30  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+56)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #03 pc 0000000000185e54  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at android.os.MessageQueue.nativePollOnce(Native method)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at android.os.MessageQueue.next(MessageQueue.java:363)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at android.os.Looper.loop(Looper.java:176)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at android.app.ActivityThread.main(ActivityThread.java:8668)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.reflect.Method.invoke(Native method)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] 
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] "HeapTaskDaemon" prio=5 tid=4 WaitingForTaskProcessor
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | group="" sCount=1 dsCount=0 flags=1 obj=0x144819f8 self=0x7921a71800
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | sysTid=12473 nice=4 cgrp=default sched=0/0 handle=0x7915d65d50
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | state=S schedstat=( 232944796 531005724 235 ) utm=19 stm=3 core=5 HZ=100
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | stack=0x7915c63000-0x7915c65000 stackSize=1039KB
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | held mutexes=
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   kernel: (couldn't read /proc/self/task/12473/stack)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #00 pc 000000000006cbc0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #01 pc 000000000015c6e0  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 158000) (art::ConditionVariable::TimedWait(art::Thread*, long, int)+176)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #02 pc 00000000002a79a4  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 17f000) (art::gc::TaskProcessor::GetTask(art::Thread*)+524)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #03 pc 00000000002a824c  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 17f000) (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+92)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at dalvik.system.VMRuntime.runHeapTasks(Native method)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:523)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Daemons$Daemon.run(Daemons.java:137)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Thread.run(Thread.java:929)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] 
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] "FinalizerDaemon" prio=5 tid=6 Waiting
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | group="" sCount=1 dsCount=0 flags=1 obj=0x144814e0 self=0x7910614000
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | sysTid=12476 nice=4 cgrp=default sched=0/0 handle=0x7915b53d50
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | state=S schedstat=( 3158852 9765105 11 ) utm=0 stm=0 core=2 HZ=100
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | stack=0x7915a51000-0x7915a53000 stackSize=1039KB
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | held mutexes=
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   kernel: (couldn't read /proc/self/task/12476/stack)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #00 pc 000000000006cbbc  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #01 pc 000000000015c2a0  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 158000) (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+156)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #02 pc 00000000004292e4  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 366000) (art::Monitor::Wait(art::Thread*, long, int, bool, art::ThreadState)+660)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #03 pc 000000000042af90  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 366000) (art::Monitor::Wait(art::Thread*, art::ObjPtr<art::mirror::Object>, long, int, bool, art::ThreadState)+284)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Object.wait(Native method)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   - waiting on <0x028d3e09> (a java.lang.Object)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Object.wait(Object.java:442)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   - locked <0x028d3e09> (a java.lang.Object)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Daemons$Daemon.run(Daemons.java:137)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Thread.run(Thread.java:929)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] 
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668] "FinalizerWatchdogDaemon" prio=5 tid=7 Sleeping
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | group="" sCount=1 dsCount=0 flags=1 obj=0x14481558 self=0x791061f000
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | sysTid=12477 nice=4 cgrp=default sched=0/0 handle=0x7915a4ad50
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | state=S schedstat=( 645833 17005209 8 ) utm=0 stm=0 core=2 HZ=100
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | stack=0x7915948000-0x791594a000 stackSize=1039KB
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   | held mutexes=
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   kernel: (couldn't read /proc/self/task/12477/stack)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #00 pc 000000000006cbc0  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #01 pc 000000000015c6e0  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 158000) (art::ConditionVariable::TimedWait(art::Thread*, long, int)+176)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #02 pc 0000000000429304  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 366000) (art::Monitor::Wait(art::Thread*, long, int, bool, art::ThreadState)+692)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   native: #03 pc 000000000042af90  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 366000) (art::Monitor::Wait(art::Thread*, art::ObjPtr<art::mirror::Object>, long, int, bool, art::ThreadState)+284)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Thread.sleep(Native method)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   - sleeping on <0x0300580e> (a java.lang.Object)
09-18 22:51:10.241 12452 12472 F ili:pushservic: runtime.cc:668]   at java.lang.Thread.sleep(Thread.java:443)
09-18 22:51:10.241 12452 12472 F ili:pushservic:

**Comment by yujincheng08** [comment]
鸿蒙的问题，不关漫游事

**Comment by NewJediOrder** [comment]
所以能针对鸿蒙做一下优化嘛

**Comment by yujincheng08** [comment]
这是鸿蒙的 bug，我这边修不了。

**Comment by yujincheng08** [comment]
据说鸿蒙 3.0 修好了

**Comment by NewJediOrder** [comment]
3.0普通版还是不行，自从6.74.0开始我这就一直这样

**Comment by yujincheng08** [comment]
那没办法，换手机吧。安卓反正没问题。

**Comment by cxw620** [comment]
只有全新安装的首次启动才会, 后面就很少了
