### ISSUE TITLE
[Feature] 热门视频屏蔽相关

### ISSUE THREAD

**Issue by RizukiJI** [yujincheng08/BiliRoaming#806]
### 原因

就……我明明不看这种短视频，但是b站一直给我推，低创的同时时长低，浪费时间

### 功能简述

类似于首页视频屏蔽的功能

### 功能逻辑

参考“首页视频屏蔽”

**Comment by cxw620** [comment]
已经有这feature了, 自己设置, (推低创也是b站大环境使然)
![Screenshot_20220923_224220_tv danmaku bili](https://user-images.githubusercontent.com/70561268/191987221-30eb352b-a704-4d7d-9e85-cfbe556c26db.jpg)
