### ISSUE TITLE
隐藏视频下方推荐视频

### ISSUE THREAD

**Issue by metaltube** [yujincheng08/BiliRoaming#808]
### 原因

视频下方推荐的其他视频有时不符合自己的需求，容易被这些视频分心。希望可以点开一个视频，下方不会有其他视频。

### 功能简述

一键开启/隐藏下方的视频

### 功能逻辑

在隐藏功能里面，可选择开启

**Comment by axixa1234** [comment]
确实有这个需求

**Comment by axixa1234** [comment]
希望都跟央视账号发的视频一样
