### ISSUE TITLE
[BUG]Xpatch版花式闪退

### ISSUE THREAD

**Issue by Undefined-User** [yujincheng08/BiliRoaming#81]
**问题描述**
发生了什么情况？有什么现状？
Xpatch版花样随机闪退

**复现步骤**
如何复现
1. 打开
2. 使用正常功能（比如全屏看直播/看视频）或打开一个应用内网页
3. 过一会闪退/Webview页面闪退（对于Webview闪退，再次打开就不会闪退了）

**截图**
闪退了哪来的截图，辣鸡bot

**环境信息**
 - 安卓版本：Q(10.0)
 - 系统版本：One UI 2.5
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号：Play 2.7.0（有直播）
 - 使用的框架和版本：Xpatch
 - 其他：没有

**日志**
[adb.log](https://github.com/yujincheng08/BiliRoaming/files/5913068/adb.log)

**Comment by yujincheng08** [comment]
应该是 sandhook 框架的问题。为了阻止 inline 把 profile 干了，然后现在 crash 在 `art::ProfileSaver::FetchAndCacheResolvedClassesAndMethods` 了。你应该去 sandhook 那边反馈一下。这与模块无关。

或者可以尝试其他版本，play 版好像自带 profile 所以容易出问题。

**Comment by Undefined-User** [comment]
> 应该是 sandhook 框架的问题。为了阻止 inline 把 profile 干了，然后现在 crash 在 `art::ProfileSaver::FetchAndCacheResolvedClassesAndMethods` 了。你应该去 sandhook 那边反馈一下。这与模块无关。
> 
> 或者可以尝试其他版本，play 版好像自带 profile 所以容易出问题。

刚才又获取到一个比较典型的崩溃：打开软件后过几秒就闪退，请问是同样的问题嘛？
[adb2.log](https://github.com/yujincheng08/BiliRoaming/files/5915887/adb2.log)
