### ISSUE TITLE
隐藏评论区[Feature] 

### ISSUE THREAD

**Issue by outsidesilence** [yujincheng08/BiliRoaming#817]
### 原因

有些视频评论区乌烟瘴气带节奏，小破站还拉偏架，评论仅自己可见，还不如不看了，眼不见心不烦。希望作者大大在设置里加入隐藏评论区开关。

### 功能简述

在设置里加入隐藏评论区开关。

### 功能逻辑

在设置里加入隐藏评论区开关，评论区页面空白或者评论区这个标签直接不显示

**Comment by bilibili2233a** [comment]
正确的解决方法:![Screenshot_20221002_172930_com.huawei.android.launcher_edit_2253445313197.jpg](https://user-images.githubusercontent.com/99982054/193447550-52d127c3-6310-4c57-9816-c31b6372b14d.jpg)

**Comment by ianchb** [comment]
正确的解决方法：![Screenshot_2022-10-02-17-36-41-804_com.miui.home-edit.jpg](https://user-images.githubusercontent.com/45872450/193447778-dad0db87-7fcb-4666-95b9-8f64b696e9f0.jpg)

**Comment by outsidesilence** [comment]
😂😂😂😂😂😂😂😂😂😂我关注了一些up，看还是要看的。就是不想看到评论区而已（特别是手机圈、汽车圈太乱了），只想静静看视频。我觉得作者大大现在连评论区修改显示多少行都已经做出来了，那隐藏一个tab标签，应该挺容易实现的。希望大大考虑下i🤣

**Comment by bilibili2233a** [comment]
只看视频那用这个:
https://github.com/10miaomiao/bilimiao2
![Screenshot_20221002_182718.jpg](https://user-images.githubusercontent.com/99982054/193449538-0fc4da12-ef52-49db-b98a-37f33b9f313f.jpg)
