### ISSUE TITLE
[Bug] 首选视频标签bug

### ISSUE THREAD

**Issue by SkeStars** [yujincheng08/BiliRoaming#820]
### 问题描述

开启 动态净化-首选视频标签 选项后，点击底栏的 动态 按钮不能返回顶部并刷新

### 复现步骤

1.  开启 动态净化-首选视频标签 选项
2. 点击底栏的 动态 按钮
3. 不能返回顶部并刷新

### 预期行为

返回顶部并刷新

### 实际行为

没有反应

### 安卓版本

12

### 哔哩漫游版本

1.6.6

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.0.0

### 使用的框架和版本

LSPosed 1.8.4(6609)

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9714117/log.txt)

**Comment by yujincheng08** [comment]
首选视频标签仅仅是把 b 站 API 返回的 tab 改成视频：

https://github.com/yujincheng08/BiliRoaming/blob/master/app/src/main/java/me/iacn/biliroaming/hook/DynamicHook.kt#L79

这个问题是 b 站实现问题，不是我们的 bug，所以我们也不会给它兜底。
