### ISSUE TITLE
[Server] 申请添加公共服务器

### ISSUE THREAD

**Issue by hanasaki-misaki** [yujincheng08/BiliRoaming#823]
### 联系方式

https://lolicon.team/about/

### 域名

api.lolicon.team

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 赞助地址

https://afdian.net/a/miraipip

**Comment by yujincheng08** [comment]
加上了，但是这个赞助地址似乎不对
