### ISSUE TITLE
[Bug] 官方版v6.69+漫游v1.6.5/1.6.6无法下载版权番剧

### ISSUE THREAD

**Issue by Yuanlailai** [yujincheng08/BiliRoaming#830]
### 问题描述

[Bug] v6.69+v1.6.5/1.6.6无法下载版权番剧，太极阴10.0.5，v129，红米k50
按照记忆中该版本配合1.6.4是可以下载过。
另外小bug，1.6.6的在漫游设置里查看版本的时候还是1.6.5

### 复现步骤

下载版权番剧按钮灰色

### 预期行为

可以下载

### 实际行为

下载版权番剧按钮灰色

### 安卓版本

12

### 哔哩漫游版本

1.6.6

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.69.0

### 使用的框架和版本

太极阴10.0.5 v129

### 其他

测试番剧 莉可丽丝

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9835724/log.txt)

**Comment by yujincheng08** [comment]
太极的问题
