### ISSUE TITLE
[Bug] play版3.14.0登录后依然无法解锁番剧

### ISSUE THREAD

**Issue by kljjh** [yujincheng08/BiliRoaming#834]
### 问题描述

play版3.14.0 登录帐号后提示解析错误：账号未登录 同一账号同一解析服务器在原版和概念版均没有此问题

### 复现步骤

1.安装play版3.14.0
2.设置解析服务器后 选择任一外区番剧 提示账号未登录

### 预期行为

正常解析

### 实际行为

提示账号未登录

### 截图或录屏

![Screenshot_20221024-154456](https://user-images.githubusercontent.com/29812342/197474610-2e41590f-dd86-4435-acfa-05b2e3c7a8a6.jpg)

### 安卓版本

11

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

play 版

### 哔哩哔哩版本号

3.14.0

### 使用的框架和版本

lspatch 0.5（349）

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9849781/log.txt)

**Comment by yujincheng08** [comment]
安装包发一下

**Comment by kljjh** [comment]
> 安装包发一下

https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=3994380&key=6434618ff69bdf6d54bea6cdbdbf3965e56eb180
