### ISSUE TITLE
[Bug] 1.6.7 模块的禁止上下滑动切换直播间不好用

### ISSUE THREAD

**Issue by Tyanyie** [yujincheng08/BiliRoaming#839]
### 问题描述

上下滑动还是会切换直播间

### 复现步骤

1. 更新模块，重启了两次应用
2. 重启了一次手机
3. 还是不好使

### 预期行为

预期 禁止上下滑动切换直播间

### 实际行为

上下滑动切换还是能直播间

### 安卓版本

11

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.33.0

### 使用的框架和版本

LSposed 1.8.4

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9892729/log.txt)

**Comment by zjns** [comment]
不向后兼容老版本

**Comment by Tyanyie** [comment]
> 不向后兼容老版本

不兼容谁的版本？ bilibili吗？
