### ISSUE TITLE
[Feature] 添加合集关闭自动连播功能

### ISSUE THREAD

**Issue by HS7097** [yujincheng08/BiliRoaming#841]
### 原因

有些up上传视频后会自动加入到合集，视频播完后会自动播放下一个

### 功能简述

允许关闭视频合集自动连播

### 功能逻辑

在框架设置页面添加一个自动关闭联播选项，默认关闭

### 实现参考

如其他功能一样整合至框架设置页面

**Comment by yujincheng08** [comment]
![Screenshot_2022-11-15-03-02-40-028_tv danmaku bili](https://user-images.githubusercontent.com/5022927/201743989-1c9623a7-e97c-4ffa-849d-35c1564b5631.jpg)
设置播放完暂停即可。
