### ISSUE TITLE
[Server] 请求添加公共服务器

### ISSUE THREAD

**Issue by boysimple** [yujincheng08/BiliRoaming#847]
### 联系方式

https://t.me/daluoda

### 域名

姬坂乃爱.我爱你

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by boysimple** [comment]
另外请给一下公共黑名单的地址，我添加一下

**Comment by david082321** [comment]
> 另外请给一下公共黑名单的地址，我添加一下

加TG群，at一下这个管理：Js0n

**Comment by yujincheng08** [comment]
Done.
