### ISSUE TITLE
显示点踩数 [ Return Bilibili Dislike ]

### ISSUE THREAD

**Issue by razilong** [yujincheng08/BiliRoaming#849]
### 原因

有效**回避劣质内容**(营销号、标题党、低质内容、水军、引战)，**避免浪费时间**

**查看视频赞踩权重**

**显示自己稿件的赞踩数量**

### 功能简述

在哔哩视频页面显示点踩数
![2022_11_11_14_36_44_871](https://user-images.githubusercontent.com/97635957/201278693-5d392b46-8987-48ae-9e49-6379292fe417.jpeg)

### 功能逻辑

     ㅤ

### 实现参考

 [Return YouTube Dislike油管显示点踩数](http://github.com/Anarios/return-youtube-dislike)
在YouTube vanced和Revanced的应用上以及网页端扩展的实现

**Comment by KimmyXYC** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/status_number.md

哔哩哔哩对于 dislike参数 的返回恒为0 除非有其他接口可以获取 dislike参数 否则不可能实现

**Comment by david082321** [comment]
Return YouTube Dislike 原本是利用API获取，在API也失效后，现在改成他们自己搞个服务器来提供。
等于是只有安装插件的人能点踩，请求会发送到他们的服务器，然后也只有安装插件的人才能看到。
