### ISSUE TITLE
[Bug] 为了使用繁化姬功能升级了内置LSPatch模块，但是无法与自定义字幕功能同时使用

### ISSUE THREAD

**Issue by y9918995** [yujincheng08/BiliRoaming#850]
### 问题描述

为了使用繁化姬功能升级了内置LSPatch模块，但是无法与自定义字幕功能同时使用
表现为简中字幕功能以及字幕拖拽功能都失效
拖拽功能无所谓，但是想请作者大大修复一下简中字幕功能，谢谢您！

### 复现步骤

B站版本6.50.0（使用旧版是因为为了使用自定义字幕功能）
模块版本1.6.7
打开自定义字幕功能，字号200，打开修复换行（字号确实大，个人习惯）
打开简中字幕转换

### 预期行为

显示简体字幕
字幕可以拖拽更改位置

### 实际行为

仍然显示繁体字幕
拖拽更改无所谓反正字体调大了不太需要它

### 截图或录屏

![B站版本](https://user-images.githubusercontent.com/57078593/201458392-212ab51b-0367-44f3-8c66-57fdd1bfb757.jpg)
![漫游版本](https://user-images.githubusercontent.com/57078593/201458982-9e018dfe-d4a2-46ba-9279-849b5ae61dfb.jpg)
![简中字幕](https://user-images.githubusercontent.com/57078593/201458489-69593f4d-4ede-4b20-8fbe-9dfa76e69314.jpg)
![字母拖拽](https://user-images.githubusercontent.com/57078593/201458490-20456ea4-e51a-4ec3-9428-0a1db1bdb4d0.jpg)

### 安卓版本

12（鸿蒙3.0）

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.50.0（最后一版支持自定义字幕的版本）

### 使用的框架和版本

 LSPosed 1.8.5

### 其他

在电脑上跟着教程用java生成的内置LSPatch的安装包，cmd输入
java -jar lspatch.jar bilibili6500.apk -m BiliRoaming_1.6.7.apk -l 2
然后其余功能都依然正常，但是字幕未能改成简体字
哪部番貌似都一样的
用的不是漫游的接口，是自己的香港节点

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9994220/log.txt)

**Comment by yujincheng08** [comment]
旧版不管

**Comment by y9918995** [comment]
你直接用新版的就行了，现在新版的可以用字幕了。我删过了。你可以从豌豆荚或者是 Apk pure上面找这个版本。发自我的手机-------- 原始邮件 --------发件人： Cm037 ***@***.***>日期： 2023年2月7日周二 凌晨2:10收件人： yujincheng08/BiliRoaming ***@***.***>抄送： y9918995 ***@***.***>, Author ***@***.***>主    题： Re: [yujincheng08/BiliRoaming] [Bug] 为了使用繁化姬功能升级了内置LSPatch模块，但是无法与自定义字幕功能同时使用 (Issue #850)

这个哔哩哔哩能不能给一下
