### ISSUE TITLE
[Bug] 最新版 [LSPatch] [1.6.7] [1.29.1] 哔哩哔哩 HD.apk的自定义CC字幕功能失效

### ISSUE THREAD

**Issue by y9918995** [yujincheng08/BiliRoaming#851]
### 问题描述

自定义cc字幕功能开启，字号调大为200，没有起作用

### 复现步骤

自定义cc字幕功能开启，字号调大为200，没有起作用

### 预期行为

cc字幕字号增大

### 实际行为

未起效

### 截图或录屏

我知道我刚刚被关闭了上一个提交，但是我只是想提醒一下，hd版的该功能同样失效且功能入口未关闭
如果能修复当然更好了，作者大大辛苦啦！
（平板上的cc字幕字号真的很小）

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.29.1

### 使用的框架和版本

打包好的[LSPatch] [1.6.7] [1.29.1] 哔哩哔哩 HD.apk

### 其他

任意带cc字幕视频

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/9994529/log.txt)

**Comment by yujincheng08** [comment]
https://github.com/yujincheng08/BiliRoaming/commit/922c2f6a085d75d7abe520ab3fff95e62d742b22
