### ISSUE TITLE
[Feature] 电视上之前用的第三方哔哩哔哩客户端被限制清晰度了，希望破解一下

### ISSUE THREAD

**Issue by lon91ong** [yujincheng08/BiliRoaming#854]
### 原因

老旧的智能电视(小米4，4G存储版，没多少应用空间了)
用如下图所示的这个第三方客户端好长时间了，最近突然被限制清晰度360P，糊的没眼看，之前最高能看1080p的
![哔哩哔哩v1.6.6去广告大会员盒子版](https://user-images.githubusercontent.com/16462258/202169151-8bd16e86-05b3-4bf7-8952-9d3629282b9d.png)
试着装了一下官方新出的电视客户端，花里胡哨的不习惯，还需要删除其它一些APP才能挤出空间

### 功能简述

希望能通过LSPatch将此插件集成的该第三方电视客户端，实现破解清晰度限制的目标

软件下载地址：
https://myqqjd.com/18072.html

### 功能逻辑

破解清晰度限制，修改UA数据或直接改请求字段数据，伪装成正版客户端

**Comment by yujincheng08** [comment]
非官方客户端不会兼容。

**Comment by david082321** [comment]
> 非官方客户端不会兼容。

应用签名可以证明是由官方签名的

![Screenshot_20221117_002525](https://user-images.githubusercontent.com/7046617/202236966-27df7157-9628-498b-aade-5d4b23e367e3.png)
![Screenshot_20221117-002328_MT Manager](https://user-images.githubusercontent.com/7046617/202236974-19f67aba-b4c7-4c4d-b848-a90088df0e49.png)

**Comment by david082321** [comment]
该app请求playurl如下：

https://app.bilibili.com/v2/playurl?buvid=略&npcybs=0&mid=0&platform=android_tv&build=1606&expire=0&track_path=0&appkey=iVGUTjsxvpLeuDCf&otype=json&avid=略&qn=64&device=android&cid=略&sign=略


1. 强行将 platform 改成 android → 无效，还是360p
2. appkey 和 sign 就不会改了

**Comment by david082321** [comment]
附上 playurl 返回内容

![Screenshot_20221117-003724_HttpCanary_Mosaic_0_37_28](https://user-images.githubusercontent.com/7046617/202240100-e80df6b3-0135-4f0b-986a-d60a40a9c4bd.png)
