### ISSUE TITLE
屏蔽视频下方的相关视频推荐

### ISSUE THREAD

**Issue by jdhdhsbjd6454543** [yujincheng08/BiliRoaming#858]
### 原因

如果不屏蔽视频下方的相关视频推荐，人们就会从一个视频点到另一视频，从另一个视频再点到下一个视频，慢慢就变成“抖音快手式"的内容，这很不“b站”，另外从戒手机的角度考虑也应该做这个功能，而且哔哩漫游本身就有同类的功能，比如屏蔽推荐内容、自定义底部栏、自定义首页标签，所以也应该加上这个功能。

### 功能简述

屏蔽视频下方的相关视频推荐

### 功能逻辑

点击哔哩漫游，多次点击版本号开启隐藏功能，在隐藏功能部分下滑，可以看到一个选项“屏蔽视频下方的相关视频推荐”，点击即可开启

### 实现参考

b站自身的某些视频自带这种效果，比如首页->新征程，里的视频。

**Comment by yujincheng08** [comment]
Duplicate of #808
