### ISSUE TITLE
[Bug] 原声音乐通知失效

### ISSUE THREAD

**Issue by Oosl** [yujincheng08/BiliRoaming#859]
### 问题描述

哔哩哔哩版本：国内版7.6.0
漫游版本：1.6.7
正确激活漫游后，开启了功能项：原声音乐通知样式
但是重启哔哩哔哩后，此功能不生效，哔哩哔哩的播放通知依旧是哔哩哔哩自己的，不是原生样式

### 复现步骤

1，打开原声音乐通知样式
2，确定并重启哔哩哔哩
3，播放一个视频然后返回桌面，通知栏出现哔哩哔哩的媒体播放通知
4，通知样式为哔哩哔哩自己的，非原生样式

### 预期行为

媒体播放通知样式为原生样式

### 实际行为

媒体播放通知为哔哩哔哩自己的样式

### 安卓版本

13

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.6.0

### 使用的框架和版本

LSPosed 1.8.5

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10046809/log.txt)

**Comment by yujincheng08** [comment]
无法复现，怀疑是云控，你看看退出登录后是否还是这样？

**Comment by Oosl** [comment]
刚又多次尝试了下，有下述结论：  
- 账户无论是否登录，都不影响此问题，都无法按预期工作。  
- 模块“原声音乐通知样式”功能的开关与否，确实会影响到哔哩哔哩的通知样式，截图如下（截图中均为未登录状态，登录后也一样）。
  
  
**关闭模块原生音乐通知时**  
![Screenshot_20221119-202052_Nameless_Launcher.png](https://user-images.githubusercontent.com/27420243/202850796-6125f1cb-8a16-468f-9ef9-e55f135094e3.png)  
![Screenshot_20221119-202057_Nameless_Launcher.png](https://user-images.githubusercontent.com/27420243/202850802-e5866748-0036-4912-bfb4-7e30c0dcd506.png)  
  
**开启模块原生音乐通知时**  
![Screenshot_20221119-202131_Nameless_Launcher.png](https://user-images.githubusercontent.com/27420243/202850821-db56b29b-f4e0-4327-9adc-707603d37e5c.png)  
![Screenshot_20221119-202126_Nameless_Launcher.png](https://user-images.githubusercontent.com/27420243/202850823-4e416fac-647b-4a50-9dc3-b7193693bae0.png)

**Comment by yujincheng08** [comment]
有没有可能，这个就是原生样式？

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047028/app-debug.zip)
用这个版本复现然后提取日志看看

**Comment by Oosl** [comment]
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10047040/log.txt)

**Comment by yujincheng08** [comment]
日志上看确实 hook 上了，样式也改了，怀疑是 Android 13 上有新通知 API？你有 12 机子可以测试一下吗？

**Comment by duzhaokun123** [comment]
@yujincheng08 这个功能在 7.0.0 上是正常的

**Comment by yujincheng08** [comment]
我在 7.6.0 也正常。

**Comment by duzhaokun123** [comment]
> 我在 7.6.0 也正常。

不开漫游的功能是不是也是原生样式

**Comment by yujincheng08** [comment]
是的

**Comment by Oosl** [comment]
我去试试7.0.0

**Comment by duzhaokun123** [comment]
> 是的

@yujincheng08 问一下你手机型号什么的

**Comment by yujincheng08** [comment]
米米 k50

**Comment by yujincheng08** [comment]
用 aosp Android 13 一样还是不能复现，不过确实不需要打开开关

**Comment by Oosl** [comment]
感觉你们是云控账户？我即使用7.0.0也必须要打开开关才能有原生音乐通知。

**Comment by yujincheng08** [comment]
云控用户竟是我自己

**Comment by Oosl** [comment]
叔叔可真是太坏了
（话说你aosp上测试也登了账号？

**Comment by yujincheng08** [comment]
没登

**Comment by yujincheng08** [comment]
确实开不开开关都是那个样式了。~~看来可以不维护这个功能了~~

**Comment by duzhaokun123** [comment]
所以这是地区云控吗

**Comment by Oosl** [comment]
> 确实开不开开关都是那个样式了。~~看来可以不维护这个功能了~~

暴风哭泣

**Comment by Oosl** [comment]
> 所以这是地区云控吗

所以我是广东，你们是哪？

**Comment by yujincheng08** [comment]
我广东。

我先研究一下云控开关在哪，然后看看能不能强制打开算了。

**Comment by Oosl** [comment]
好（大声
等你好消息

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047190/app-debug.zip)
先用这个抓个日志看看

**Comment by yujincheng08** [comment]
问题知道了。

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047223/app-debug.zip)
日志

**Comment by Oosl** [comment]
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10047232/log.txt)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047314/app-debug.zip)
日志

**Comment by Oosl** [comment]
[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10047336/log.txt)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047453/app-debug.zip)
应该能用了

**Comment by Oosl** [comment]
去掉应该，能用了。
C大师牛逼，啥时候请你吃饭！

**Comment by yujincheng08** [comment]
再确认一下这个能不能用（7.0.0 和 7.6.0 都测一下）

[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047465/app-debug.zip)

**Comment by yujincheng08** [comment]
[app-debug.zip](https://github.com/yujincheng08/BiliRoaming/files/10047487/app-debug.zip)
这个呢？

**Comment by Oosl** [comment]
这个700和760都正常

**Comment by yujincheng08** [comment]
你这个问题应该说是进度条消失。一开始误导了我

**Comment by Oosl** [comment]
啊，但是咋一看确实像是失效了一样，只能说我也被误导了😂

**Comment by Oosl** [comment]
现在用的play最新版本+最新版漫游，似乎又有类似的问题了。
系统是cos14，自己做了个垃圾媒体控制卡片。
1、bilibili正常播放视频，快捷面板没有任何媒体通知（bilibili自己的以及系统的媒体卡片都没反应）
2、bilibili听剧模式，系统媒体卡片可以正常看到bilibili的播放状态。
3、正常观看视频时，切换到其他应用，偶尔会触发截图里的bilibili自己的媒体通知（类似此issue原始问题现象）
![Screenshot_2024-01-20-12-53-31-72_948cd9899890cbd5c2798760b2b95377.jpg](https://github.com/yujincheng08/BiliRoaming/assets/27420243/37d3f51f-c2a0-4e06-b54b-8f706b95b6ae)
