### ISSUE TITLE
[Bug] 自由复制失效

### ISSUE THREAD

**Issue by 0XPYEX0** [yujincheng08/BiliRoaming#870]
### 问题描述

评论区“去除长按复制”与“长按自由复制”无效

### 复现步骤

正常打开视频评论区，长按一条评论，全部复制而无弹窗

### 预期行为

弹出文本窗口

### 实际行为

全部文本都被复制

### 截图或录屏

https://user-images.githubusercontent.com/50171612/203904366-6bff8c31-be83-4972-aaf3-2de83b4a30e6.mp4

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.4.0 (release-b10365484)

### 使用的框架和版本

Taichi-10.2.0.11231740-8706

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10088739/log.txt)

**Comment by yujincheng08** [comment]
我这边测试 7.8.0 都没问题。怀疑是太极的问题。

**Comment by 0XPYEX0** [comment]
最新版太极已修复该Bug
