### ISSUE TITLE
既然能净化动态，可以让不想要看到的的东西屏蔽掉，那能不能弄个只想要看到某些东西啊（）？

### ISSUE THREAD

**Issue by XiaoFuOS** [yujincheng08/BiliRoaming#872]
### 原因

既然能净化动态，可以让不想要看到的的东西屏蔽掉，那能不能弄个只想要看到某些东西啊（）？

### 功能简述

1

### 功能逻辑

1

**Comment by XiaoFuOS** [comment]
> 安装CI版本，勾选正则模式，填入以下正则即可
> 
> ```
> ^(?!.*(你想看到的内容填这里))
> ```

CI版本在哪

**Comment by XiaoFuOS** [comment]
> > > 安装CI版本，勾选正则模式，填入以下正则即可
> > > ```
> > > ^(?!.*(你想看到的内容填这里))
> > > ```
> > 
> > 
> > CI版本在哪
> 
> 这个: [Android CI](https://github.com/yujincheng08/BiliRoaming/actions/runs/3573874968)

太极框架进不去，用的内置框架LSPatch版本的，里面的净化动态不支持正则吧，想不到啥办法了
![Screenshot_2022-12-02-17-26-55-961-edit_tv danmaku bili](https://user-images.githubusercontent.com/103229747/205261182-45957deb-1e52-495a-bca1-1eec93b7e469.jpg)

**Comment by david082321** [comment]
@XiaoFuOS 
https://t.me/biliroaming_lspatch2/181

**Comment by XiaoFuOS** [comment]
> @XiaoFuOS https://t.me/biliroaming_lspatch2/181

有了，非常感谢
