### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Mttronger** [yujincheng08/BiliRoaming#873]
### 问题描述

自定义底栏功能失效

### 复现步骤

1.打开自定义底栏功能
2.只勾选我的和首页
3.重启两次

### 预期行为

动态图标消失

### 实际行为

底栏无反应

### 截图或录屏

Uploading Screenrecorder-2022-11-26-16-09-41-119.mp4…

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.29.1

### 使用的框架和版本

LSPosed 内置版

### 日志

[1_log.txt](https://github.com/yujincheng08/BiliRoaming/files/10095901/1_log.txt)

**Comment by Mttronger** [comment]
是无法复原导致issue关闭的吗？我试了五个平板都是这样诶....

**Comment by Mttronger** [comment]
请问是因为日志的问题导致无法确定问题才关闭issue的吗？

**Comment by david082321** [comment]
> 请问是因为日志的问题导致无法确定问题才关闭issue的吗？

无效是因为HD版的底栏不会云控，目前代码是修改云控返回内容来达到屏蔽目的，所以得针对HD版重写（问题是没人来写）
