### ISSUE TITLE
[Bug] 净化首页标签功能失灵

### ISSUE THREAD

**Issue by Mttronger** [yujincheng08/BiliRoaming#875]
### 问题描述

净化首页标签功能失灵

### 复现步骤

1.打开净化首页标签功能
2.勾选推荐
3.重启两次

### 预期行为

首页推荐标签消失

### 实际行为

首页推荐标签无变化

### 截图或录屏

Uploading Screenrecorder-2022-11-26-16-48-28-352.mp4…

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.29.1

### 使用的框架和版本

LSPosed内置版

### 日志

[1_2_log.txt](https://github.com/yujincheng08/BiliRoaming/files/10095923/1_2_log.txt)

**Comment by yujincheng08** [comment]
HD 版本不支持该功能。
