### ISSUE TITLE
[Server] bili.takami.ink 域名&联系方式&捐赠地址变更

### ISSUE THREAD

**Issue by tkmssb** [yujincheng08/BiliRoaming#876]
### 联系方式

https://t.me/+14704079183

### 域名

bili.ayaka.ink

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

bili.ayaka.ink/donate

**Comment by yujincheng08** [comment]
Done.
