### ISSUE TITLE
[Bug] 更改主题颜色不全面

### ISSUE THREAD

**Issue by RagueI** [yujincheng08/BiliRoaming#878]
### 问题描述

悼念归悼念，应该给用户正常显示颜色的权力

### 复现步骤

1. 打开app
2. 直接就是黑白滤镜了

### 预期行为

应该该彩色就彩色，如果用户设置了的话，而不是被官方远控

### 实际行为

实际打开应用就变黑白

### 截图或录屏

![Screenshot_2022-12-01-08-32-30-353_tv danmaku bili](https://user-images.githubusercontent.com/82907020/204945554-ba44a5d3-111f-42c9-a561-0b8c2a4cdf58.png)

### 安卓版本

11

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.6.0

### 使用的框架和版本

LSposed 1.8.5 RIRU

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10128565/log.txt)

**Comment by RagueI** [comment]
@yujincheng08  为什么close了？ 原因都不给？

**Comment by yujincheng08** [comment]
closed this as not planned

**Comment by RagueI** [comment]
> closed this as not planned

how about adding a feature?

**Comment by yujincheng08** [comment]
not planned
