### ISSUE TITLE
[Feature] 禁止下载App基础组件库

### ISSUE THREAD

**Issue by My-Responsitories** [yujincheng08/BiliRoaming#880]
### 原因

这个组件库是app体积膨胀的罪魁祸首, 通过抓包软件阻止请求后之后体积立即减少700多mb, 且屏蔽后视频, 直播, 专栏等不受影响, 似乎上传视频会受影响

### 功能简述

禁止下载App基础组件库(设置 > 清理存储空间 > App基础组件库)

### 功能逻辑

添加阻止基础组件库的检测与下载开关. 检测组件库地址: app.bilibili.com/bilibili.app.resource.v1.Module/List

**Comment by david082321** [comment]
抓包只找到这个
grpc.biliapi.net/bilibili.app.resource.v1.Module/List
