### ISSUE TITLE
[Bug] 插件无法正常加载

### ISSUE THREAD

**Issue by NanZhuChan** [yujincheng08/BiliRoaming#881]
### 问题描述

插件打开后提示“不支持当前框架”，但本人使用的是较为流行的LSPosed，且在哔哩漫游本体页面显示已激活（Xposed）。

### 复现步骤

1.打开哔哩哔哩

### 预期行为

哔哩漫游正常工作

### 实际行为

提示不支持当前框架

### 安卓版本

10

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.8.2

### 使用的框架和版本

Lsposed 1.3.7

### 日志

在开启漫游自带的导出日志后，仍无日志生成

**Comment by NanZhuChan** [comment]
> logcat 都没有是吧

是的，内容为空

**Comment by yujincheng08** [comment]
1.3.7😅
