### ISSUE TITLE
[Bug] 无法下载番剧

### ISSUE THREAD

**Issue by Tim-Paik** [yujincheng08/BiliRoaming#884]
### 问题描述

进入番剧页面后，没有提示解锁，并且下载按钮是灰的

### 复现步骤

打开番剧页面（比如间谍过家家）

### 预期行为

可以正常下载番剧

### 实际行为

点击显示版权原因无法下载

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.8.2

### 使用的框架和版本

LSPosed 1.8.5

### 其他

Magisk 25.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10167915/log.txt)

**Comment by yujincheng08** [comment]
LSPosed 页面重新优化b站试试。

**Comment by Tim-Paik** [comment]
> LSPosed 页面重新优化b站试试。

貌似没什么变化，问题依旧

**Comment by yujincheng08** [comment]
无法复现。

**Comment by Tim-Paik** [comment]
问题貌似找到了，有两个问题，其中一个是因为LSP框架的版本和zagisk导致的崩溃，另一个是因为解析服务器无法链接（被openwrt的dns当成广告拦截了）

谢谢您的耐心解答。
