### ISSUE TITLE
[Server] 

### ISSUE THREAD

**Issue by boysimple** [yujincheng08/BiliRoaming#887]
### 联系方式

https://t.me/daluoda

### 域名

姬坂乃爱.我爱你

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by boysimple** [comment]
升级了一下，现在港澳台，大陆，东南亚应该都可以解析了，麻烦帮忙改一下解锁区域为所有

**Comment by yujincheng08** [comment]
好力
