### ISSUE TITLE
[Feature] 建议增加导出配置文件功能

### ISSUE THREAD

**Issue by HanHan233** [yujincheng08/BiliRoaming#89]
**原因**
本人有时候会卸载哔哩哔哩并重新安装，这时会丢失所有数据，重新设置挺麻烦

**功能简述**
方便地进行配置备份，还原等

**功能逻辑**
哔哩哔哩数据清空后biliroaming仍能保持清空数据前的工作状态。

**实现参考**
把配置文件保存在biliroaming应用内，并提供导入/导出配置文件选项，或者直接导出到Download目录内。

**Comment by yujincheng08** [comment]
已有
