### ISSUE TITLE
lsp模块正常工作，提示帐号未登录

### ISSUE THREAD

**Issue by 0316ng** [yujincheng08/BiliRoaming#894]
### 问题描述

lsp模块正常工作，提示帐号未登录
bilibili play版3.16.0 
哔哩漫游 1.6.7

### 复现步骤

观看港澳台番剧提示帐号未登录

### 预期行为

正常工作

### 实际行为

提示帐号未登录

### 截图或录屏

![Screenshot_20221217-004837](https://user-images.githubusercontent.com/61930381/208149268-cfb04bb6-a352-4080-aca1-beb6d63aca1e.jpg)

### 安卓版本

10

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

3.16.0

### 使用的框架和版本

1.8.5

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10247601/log.txt)

**Comment by cxw620** [comment]
粉版3.16.0?太老了是play版吧,解析服务器不支持
