### ISSUE TITLE
[Bug] Play版Bilibili「生成简中字幕」选项失效

### ISSUE THREAD

**Issue by HyperCherry** [yujincheng08/BiliRoaming#895]
### 问题描述

在Play版Bilibili 3.16.0版（12月8日最新版）中，「生成简中字幕」选项失效。字幕无法被正常转换为简体中文。将Bilibili客户端降级至上版本（3.15.1）可解决问题。

### 复现步骤

1.勾选「生成简中字幕选项」
2.打开任意繁体字幕番剧

### 预期行为

产生简体字幕

### 实际行为

仍然为繁体字幕

### 截图或录屏

![Screenshot_20221218-000213_bilibili](https://user-images.githubusercontent.com/20416586/208251705-930e26a7-b038-4962-a9ed-2087f1becbca.png)
![Screenshot_20221218-000410_bilibili](https://user-images.githubusercontent.com/20416586/208251710-80334cf0-22f5-48f1-98a9-70a70465ea59.png)

### 安卓版本

12

### 哔哩漫游版本

1.6.7

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

3.16.0

### 使用的框架和版本

LSPosed 1.8.5(6649)-Zygisk

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10252139/log.txt)

**Comment by HyperCherry** [comment]
版本选错了，是play版bilibili（

**Comment by yujincheng08** [comment]
@zjns
