### ISSUE TITLE
[Feature] 将b23.tv分享链接转换为b23.wtf分享链接

### ISSUE THREAD

**Issue by poly000** [yujincheng08/BiliRoaming#90]
**原因**
b23.tv 有 tracing 行为

**功能简述**
如题
**功能逻辑**
在bilibili生成转发链接时修改分享内容

**实现参考**
将tv改为wtf即可

**Comment by poly000** [comment]
…… 说起来可以直接把分享链接改为到bilibili.com的链接呢

**Comment by yujincheng08** [comment]
我模块已经弄成 b23.tv/video/av170001 这样了也有 tracing？

**Comment by poly000** [comment]
> 我模块已经弄成 b23.tv/video/av170001 这样了也有 tracing？

没仔细看设置。。
