### ISSUE TITLE
[Feature] 希望可以去除评论区关键词搜索放大镜

### ISSUE THREAD

**Issue by Moisss** [yujincheng08/BiliRoaming#906]
### 原因

非常影响评论区观看体验，正常的一段话就因为关键词被标蓝还多了放大镜的空格导致很难看，且容易不小心点击导致进入搜索
![IMG_20221228_151021](https://user-images.githubusercontent.com/91914216/209773697-63195c6e-48cf-4f1c-bf34-af8da5755257.jpg)

### 功能简述

希望能像旧版（6.65及之前）评论区一样没有这个蓝字放大镜，希望能增加一个开关控制

### 功能逻辑

在选项中开启，开启后自动屏蔽或去除蓝字放大镜

### 实现参考

本人不太了解，或许能参考旧版评论区？

**Comment by cxw620** [comment]
早就有了

**Comment by Moisss** [comment]
> 

是新版漫游吗，1.6.8没找到

**Comment by Moisss** [comment]
> 早就有了, 屏蔽评论关键词搜索功能

请问是在哪里呢，刚刚找了一下没有这个功能

**Comment by yujincheng08** [comment]
已经有了

**Comment by Moisss** [comment]
> 已经有了

抱歉我没有找到具体在哪里……是新版本的吗

**Comment by yujincheng08** [comment]
有反正肯定有，找不到就跟我们没关系了。

https://github.com/yujincheng08/BiliRoaming/blob/f8361861810f425be59eedf12ae70564d0780742/app/src/main/res/values/strings.xml#L214-L215
