### ISSUE TITLE
[Bug] 使用后App无法启动

### ISSUE THREAD

**Issue by peasoft** [yujincheng08/BiliRoaming#908]
### 问题描述

使用此模块后，哔哩哔哩App异常退出。有时App没有退出但提示程序出错（见下方图片）。点击“清除缓存”后哔哩哔哩App能够启动，但多启动几次后又无法启动。（并且程序数据似乎全部丢失了？）

### 复现步骤

1. 确保模块已启用
2. 打开哔哩哔哩
3. App异常退出

### 预期行为

App正常启动

### 实际行为

App异常退出

### 截图或录屏

![Screenshot_2023-01-01-17-52-59-33](https://user-images.githubusercontent.com/55051861/210167230-db58a8f8-a56a-41d7-82aa-132f7b9185ea.jpg)

### 安卓版本

10

### 哔哩漫游版本

Snapshot f836186181

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.12.0

### 使用的框架和版本

LSPosed 1.8.5 (6649) - Zygisk

### 其他

Magisk 25.2 (25200) with Zygisk

### 日志

adb logcat: [log.log](https://github.com/yujincheng08/BiliRoaming/files/10328607/log.log)

**Comment by yujincheng08** [comment]
不兼容鸿蒙

**Comment by peasoft** [comment]
这就是ColorOS 7……
不过现在我自行排查发现可能是LSPosed的问题，因为那时候LSPosed Manager都打不开了。现在把LSPosed升级到Snapshot暂时没出现问题。
