### ISSUE TITLE
[Feature] 能否干掉“上下滑动控制音量”的功能？

### ISSUE THREAD

**Issue by 1913618332** [yujincheng08/BiliRoaming#909]
### 原因

横屏看视频不小心上滑，音量直接拉满，能自己给自己吓死。

### 功能简述

加开关，可以选择是否屏蔽“上下滑动滑动控制音量”的功能。

### 功能逻辑

同上

**Comment by yujincheng08** [comment]
不能。

**Comment by guosic** [comment]
可以关掉“媒体音量控制”这个权限，我MIUI13安卓12是有的，其他系统不知道
