### ISSUE TITLE
[BUG]填写解析服务器设置时不显示填空栏

### ISSUE THREAD

**Issue by biqiguhexuenai** [yujincheng08/BiliRoaming#91]
**问题描述**
发生了什么情况？有什么现状？
如题
**复现步骤**
如何复现
1. 打开b站（旧版），长按设置，出现漫游设置页面
2. 点击解析服务器设置
3. 出现如题状况

**截图**
点击文本框下面小长条可以上传文件
![Screenshot_2021-02-08-19-08-55-77](https://user-images.githubusercontent.com/63104635/107214243-3dbee700-69cf-11eb-94c6-991044b265a0.png)

**环境信息**
 - 安卓版本：5.1.1
 - 系统版本：OPPOR9PlusmA_11_A.29_190904
 - 哔哩漫游版本：1.4.2
 - 哔哩哔哩版本和版本号:国内 非概念版 5.58.0
 - 使用的框架和版本：太极6.4.0
 - 其他：无

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
无法上传，是空的

**Comment by yujincheng08** [comment]
旧版的问题不会修复

**Comment by biqiguhexuenai** [comment]
我又试了太极可以适应的最高版本，也是这种状况，是否可以修复

**Comment by yujincheng08** [comment]
emmmm 试试 xpatch 版

**Comment by biqiguhexuenai** [comment]
emmm，就是用不了xp版才用插件的，手机不兼容

**Comment by yujincheng08** [comment]
哦，5.1.1 好家伙

**Comment by biqiguhexuenai** [comment]
好家伙，我真是买了个好手机

**Comment by biqiguhexuenai** [comment]
我明天换部手机试试，可以的话就是换个手机的问题了
