### ISSUE TITLE
[Feature] 大会员到期后之前缓存的部分视频无法播放,希望可以取消这个限制

### ISSUE THREAD

**Issue by gyhmz** [yujincheng08/BiliRoaming#914]
### 原因

![Screenshot_20230110-092005](https://user-images.githubusercontent.com/95202722/211440331-33cd5460-42d6-40c8-8606-1759dc4dc9e8.jpg)

![Screenshot_20230110-092054](https://user-images.githubusercontent.com/95202722/211440412-052748f8-89cd-49c3-bffd-c8b8d827c1a8.jpg)

### 功能简述

如图

### 功能逻辑

大会员到期后之前缓存的视频无法播放

**Comment by yujincheng08** [comment]
预期行为
