### ISSUE TITLE
[Feature] 去除视频截屏左下角的水印

### ISSUE THREAD

**Issue by a3087814532** [yujincheng08/BiliRoaming#917]
### 原因

一个好的画面全被水印毁了。

### 功能简述

去除截屏时左下角的水印。

### 功能逻辑

![IMG_20230111_231057](https://user-images.githubusercontent.com/77884486/211842300-a914416e-3497-472f-b674-99b6d97d772a.jpg)

**Comment by david082321** [comment]
用Android系统自带的截图，具体按钮自行搜索「你的手机厂商名称+截图」
