### ISSUE TITLE
[Feature] 自定义播放速度&设置默认播放速度

### ISSUE THREAD

**Issue by rhjdvsgsgks** [yujincheng08/BiliRoaming#92]
**原因**
老版其实是支持最高到3.5倍速的，只是ui只显示到了2

**功能简述**
自定义播放速度&设置默认播放速度
也可以使弹幕速度不随视频速度变化

**功能逻辑**
使用自定义数值替换掉原有速度档位

**实现参考**
已经写好了，但目前是写死的，稍微改改加个ui就pr上来

**Comment by yujincheng08** [comment]
自定义播放速度我之前都写好了，但是群里说没用我以我就懒得搞了。。实际上任何速度都可以，我试过 0.01 和 10 都能用。

**Comment by rhjdvsgsgks** [comment]
可能是我用的b站的 ijkplayer 版本比较老，或是手机性能太差了，速度虽然可以设上去，但实际视频的速度好像并没有比 3.5 快多少

**Comment by rhjdvsgsgks** [comment]
那这个功能你还打算写吗，如果不的话我就pr了，如果觉得这个功能不需要的话我就不pr了

**Comment by yujincheng08** [comment]
你写吧，最近我再搞 LSPosed 不想搞 b 站。

**Comment by rhjdvsgsgks** [comment]
我来整理下思路，版本是 play 2.4.2 ，播放速度列表以及默认播放速度这边，首先 `tv.danmaku.biliplayer.demand.g.onPrepared` 会以 `PlayerOptionsPanelHolder` 中的第二项为备用速度，向 `tv.danmaku.biliplayer.basic.context.c` 中的 bundle 获取 `bundle_key_playback_speed` 的值，这个值最终会传到 `tv.danmaku.ijk.media.player.IjkMediaPlayer` 的 `setSpeed` 处。 `tv.danmaku.biliplayer.basic.context.c` 中的 bundle 中 `bundle_key_playback_speed` 的值是由 `tv.danmaku.bili.ui.video.creator.a` 的 `c` 设置的，而这个值是写死的。所以在 `tv.danmaku.biliplayer.basic.context.c` 处阻止 `tv.danmaku.bili.ui.video.creator.a` 向 bundle 中写入 `bundle_key_playback_speed` 即可让 `tv.danmaku.biliplayer.demand.g.onPrepared` 在设置速度时使用备用值（即自定义的速度）。而在新版中有一个专门用来获取速度的方法，直接 hook 下就好了。

再来说说弹幕的速度，与播放速度类似，在 `tv.danmaku.biliplayer.features.danmaku.g.onPrepared` 处初始化弹幕速度，但与手动切换速度时（也就是 `onEvent`）不同，速度是直接从 preference 里读的，不会与播放速度进行计算，所以会造成设置默认播放速度后弹幕速度并不会变，需要手动切换下速度才能正常，而解决方法也很简单，用 `DemandPlayerEventRequestPlaybackSpeed` 和默认播放速度 call 下 `onEvent` 即可。

弹幕速度随播放速度变化也是在这附近实现的， `tv.danmaku.biliplayer.features.danmaku.g` 的 `a` 会向 `b.icr`(EventCenter) 注册一堆 listener ，其中就包括 `DemandPlayerEventRequestPlaybackSpeed` ，之后就是 `tv.danmaku.biliplayer.features.danmaku.g` 的 `onEvent` 根据播放速度设置弹幕速度了。

根据播放速度设置弹幕的 view 是在 `tv.danmaku.biliplayer.features.danmaku.view.h$2` 的 `a(tv.danmaku.biliplayer.features.danmaku.view.u, Int, String, Float` 处，本来是想在开启 “独立弹幕速度” 后直接用滑杆的值不经过播放速度的计算直接设弹幕速度的，但这滑杆精度太低了只有四个档位，而且都是在一个方法里不好改，只好加了个设置弹幕速度的页面

**Comment by rhjdvsgsgks** [comment]
另外，自定义播放速度列表中的速度数量是可以超过原有数量的，虽然显示不出来，但可以通过双指横划来切换到上/下一个速度
