### ISSUE TITLE
[Server] hk.biliroaming.bili33.top

### ISSUE THREAD

**Issue by GamerNoTitle** [yujincheng08/BiliRoaming#923]
### 联系方式

https://github.com/GamerNoTitle

### 域名

https://hk.biliroaming.bili33.top

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [ ] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://bili33.top/sponsors/

**Comment by yujincheng08** [comment]
Done
