### ISSUE TITLE
[Feature] 希望恢复相簿和分区频道功能

### ISSUE THREAD

**Issue by TobyLi223** [yujincheng08/BiliRoaming#926]
### 原因

因为许多人更习惯旧版界面，我也希望能这新版本收藏动态图片

### 功能简述

分区功能被挪到了首页的角落，频道变成了话题，自定义链接按钮我不会用，希望加一个便捷开关
相簿可以看看旧版代码，旧版可以收藏不能取消，但也够用了，可能复杂些

### 功能逻辑

同简述

**Comment by yujincheng08** [comment]
砍掉的功能很容易以后连 API 都删掉，不会做。
