### ISSUE TITLE
[Server] cc.hmountainln.cn

### ISSUE THREAD

**Issue by JSTks24** [yujincheng08/BiliRoaming#929]
### 联系方式

https://t.me/JSTks24

### 域名

https://cc.hmountainln.cn

### 支持地区

- [X] 中国大陆
- [x] 港澳
- [ ] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/blroaming

**Comment by yujincheng08** [comment]
好了。
