### ISSUE TITLE
[Server] bilibili.com.co（麻烦加到陈睿.我爱你下边，然后把捐赠地址全部修改一下）

### ISSUE THREAD

**Issue by InternetBugs** [yujincheng08/BiliRoaming#933]
### 联系方式

https://t.me/internetbugs

### 域名

bilibili.com.co

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://bilibili.com.co/donate

**Comment by yujincheng08** [comment]
Done
