### ISSUE TITLE
[Feature] 直播真原画链接设置

### ISSUE THREAD

**Issue by Haocen2004** [yujincheng08/BiliRoaming#936]
### 原因

直播二压原画1080p大果粒 但开播前一小会能获取到真原画流（有效期1h）

### 功能简述

网页端已有脚本可以重写直播流的地址 希望手机端也能加点类似功能

### 功能逻辑

有几个设想 互相独立
1.进入直播间时从某个设置的网站尝试请求原画流
2.添加按钮手动输入原画流
直播流信息中有个deadline时间戳为过期时间 超时后回落到b站官方接口返回的流

### 实现参考

参考api：https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo
网页端参考油猴脚本：https://greasyfork.org/zh-CN/scripts/453967-bilibili%E7%9B%B4%E6%92%AD%E8%87%AA%E5%8A%A8%E8%BF%BD%E5%B8%A7/code

**Comment by zjns** [comment]
作用不大，就一些小 up 主直播能拿到 “真原画”。

**Comment by yujincheng08** [comment]
O得K

**Comment by kurikomoe** [comment]
> 作用不大，就一些小 up 主直播能拿到 “真原画”。

还是有用的，即使是大主播，开播的前几分钟也能抓到真实直播源（有效期 1h）。配合自己的 bot 推送 tg。

只要建立好连接，即使有效期 1h 也能一直拿到流内容直到下播。
