### ISSUE TITLE
[Server] 添加新Server请求

### ISSUE THREAD

**Issue by lhf277** [yujincheng08/BiliRoaming#938]
### 联系方式

t.me/liangburs

### 域名

cherry.icu.cnmobile.link

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/LiangBurs

**Comment by yujincheng08** [comment]
都加上了。
