### ISSUE TITLE
[Feature] 希望增加分屏时强制全屏功能

### ISSUE THREAD

**Issue by TKgbUssr** [yujincheng08/BiliRoaming#946]
### 原因

哔哩哔哩运行在
【①"Windows Subsystem for Android“
（https://baike.baidu.com/item/Windows%20Subsystem%20for%20Android/61938077?fr=aladdin）
②各手机厂家分屏模式
③支持多任务窗口的安卓x86_64电脑】时，无论何种方式，都提示”分屏状态下暂不支持全屏播放"
已经尝试多个哔哩哔哩版本，均无果
哔哩哔哩自带的”进入详情页自动全屏“无效
本人无此方面技术，故前来向您询问该功能是否可行。
![ot](https://user-images.githubusercontent.com/102952455/216275236-5d97977c-74e4-4d1d-b1dc-d4120c7b6366.jpg)

 

### 功能简述

欺骗客户端，强制允许全屏，展示包含画质选项等功能的全屏页面
亦或是点入视频后直接进入全屏

### 功能逻辑

如上

**Comment by yujincheng08** [comment]
Duplicate of #805
