### ISSUE TITLE
[Bug] 关于大会员限制问题

### ISSUE THREAD

**Issue by JSTks24** [yujincheng08/BiliRoaming#948]
### 问题描述

观看 别酱了 最新一集出现hk大会员限制错误。
服务器是我个人的，别的番剧或者是别酱了其他的几集需要大会员的集数，点开也可以正常观看。网页端油猴插件账号授权之后，我这里也可以正常观看最新一集。
服务器部署的是BilibiliRoaming-PHP的脚本，并且Mysql缓存被我打开了，不是很确定和这个有没有关系，而且我在哔哩漫游中导出的日志中具体时间和我操作时候的时间差了大约半个小时。

### 复现步骤

1.打开哔哩哔哩
2.进入别酱了
3.点开最新一集

### 预期行为

正常播放

### 实际行为

提示hk授权错误

### 截图或录屏

注：此处前面几集以及别的番剧会员专属都可以看，网页油猴脚本账号授权后本集可看。
![4](https://user-images.githubusercontent.com/62133008/216759681-97e676dc-e969-44b3-bf18-06a4d87d9341.jpg)

### 安卓版本

HarmonyOS 3.0.0

### 哔哩漫游版本

1.6.8

### 哔哩哔哩版本

HD版

### 哔哩哔哩版本号

1.36.0

### 使用的框架和版本

LSPatch

### 其他

别当哥哥了 

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10608313/log.txt)

**Comment by JasonKhew96** [comment]
后端问题，你可以把缓存关掉看看问题有没有消失
如果自己一个人用，缓存没必要开

**Comment by JSTks24** [comment]
> 后端问题，你可以把缓存关掉看看问题有没有消失 如果自己一个人用，缓存没必要开

服务器之前被我issue共享到公共解析服务器列表里了，并非一个人用，所以把缓存打开了。我将缓存关掉试试吧，看看会不会有改善。
