### ISSUE TITLE
[Server] Server信息修改(cherry.icu.cnmobile.link)(麻烦您把 联系方式 支持地区 修改一下)

### ISSUE THREAD

**Issue by lhf277** [yujincheng08/BiliRoaming#950]
### 联系方式

https://t.me/LiangBurs_ServerLogs

### 域名

cherry.icu.cnmobile.link

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/LiangBurs

**Comment by yujincheng08** [comment]
好力
