### ISSUE TITLE
[Feature] 屏蔽掉直播间购买装扮小黄车

### ISSUE THREAD

**Issue by junbluedd** [yujincheng08/BiliRoaming#951]
### 原因

以前是没有这个弹窗的，只有个小黄车在跳动，有一天大概手贱更新到了7.15.0，现在不光有小黄车还有个弹窗，每次都要手动关闭
![Screenshot_2023-02-05-21-47-56-865_tv danmaku bili](https://user-images.githubusercontent.com/69491742/216823421-74716314-1251-4990-9f04-b1d41f0d7df9.png)

### 功能简述

直接添加去掉直播间小黄车以及弹窗功能

### 功能逻辑

直接添加去掉直播间小黄车以及弹窗功能

**Comment by yujincheng08** [comment]
#867 #868
