### ISSUE TITLE
[Server] 请求添加解析服务器

### ISSUE THREAD

**Issue by xifeng0** [yujincheng08/BiliRoaming#953]
### 联系方式

t.me/xifeng040

### 域名

hk.xifeng.cf

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/a/xifeng04

**Comment by yujincheng08** [comment]
好了。
