### ISSUE TITLE
[Bug] 净化搜索功能失效

### ISSUE THREAD

**Issue by korin5** [yujincheng08/BiliRoaming#956]
### 问题描述

净化搜索功能失效

### 复现步骤

净化搜索功能失效

### 预期行为

净化搜索

### 实际行为

净化搜索功能失效

### 安卓版本

11

### 哔哩漫游版本

1.6.9

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.5.0

### 使用的框架和版本

太极-10.0.5

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10708775/log.txt)

**Comment by yujincheng08** [comment]
无法复现，怀疑是太极问题。
