### ISSUE TITLE
[Bug]请适配梦境框架Dreamland

### ISSUE THREAD

**Issue by momo54181** [yujincheng08/BiliRoaming#959]
### 问题描述

使用梦境框架激活提示不支持此框架.
框架地址：https://github.com/canyie/Dreamland

### 复现步骤

wu

### 预期行为

在菜单“我的”里面会有“哔哩漫游设置”

### 实际行为

在菜单“我的”里面没有“哔哩漫游设置”

### 安卓版本

7.0

### 哔哩漫游版本

1.6.9

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.2.0

### 使用的框架和版本

Dreamland 2.1（2101）

### 其他

Magisk 24.1

### 日志

noto

**Comment by yujincheng08** [comment]
系统太老，没时间兼容
