### ISSUE TITLE
[Server] api.mahiron.moe

### ISSUE THREAD

**Issue by KimmyXYC** [yujincheng08/BiliRoaming#961]
### 联系方式

https://t.me/Kimmy_XYC

### 域名

api.mahiron.moe

### 支持地区

- [X] 中国大陆
- [X] 港澳
- [X] 台湾
- [X] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

### 赞助地址

https://afdian.net/@KimmyXYC

**Comment by KimmyXYC** [comment]
麻烦加在 `哔哩.plus` 下面，谢谢

**Comment by yujincheng08** [comment]
好力
