### ISSUE TITLE
[Server] 

### ISSUE THREAD

**Issue by Respawn-ID** [yujincheng08/BiliRoaming#966]
### 联系方式

@Artemis_Fowl1 telegram

### 域名

lushx.top

### 支持地区

- [ ] 中国大陆
- [X] 港澳
- [X] 台湾
- [ ] 东南亚

### 带会员专享

- [ ] 服务器只有带会员用户能解析

**Comment by yujincheng08** [comment]
好了。

**Comment by Respawn-ID** [comment]
> 好了。

泰区评论会寄.lushx.top
换成子域名了刚才

**Comment by yujincheng08** [comment]
好了。但你的解析服务器不是不支持泰区吗（

**Comment by Respawn-ID** [comment]
> 好了。但你的解析服务器不是不支持泰区吗（

只能说是肺腑之言了（
-来自刚从小黑屋出来的人
