### ISSUE TITLE
[Feature] 评论区过滤

### ISSUE THREAD

**Issue by GentsunCheng** [yujincheng08/BiliRoaming#967]
### 原因

越来越多水军小号之类的了，不知道这种功能有没有好的实现方式

### 功能简述

评论区过滤，如通过等级，关键词正则等方式过滤

### 功能逻辑

设置中添加一个选项，可设定评论区过滤，如按照等级过滤，只显示设定等级以上的评论

**Comment by yujincheng08** [comment]
不好实现
