### ISSUE TITLE
[BUG]最近ci闪退

### ISSUE THREAD

**Issue by BoBppy** [yujincheng08/BiliRoaming#97]
**问题描述**
发生了什么情况？有什么现状？

批站fc

**复现步骤**

尝试点击模块设置页，引发fc

**截图**
点击文本框下面小长条可以上传文件

**环境信息**
 - 安卓版本：11
 - 系统版本：dotOS5
 - 哔哩漫游版本：最新ci....
 - 哔哩哔哩版本和版本号：（如概念版6.2.3）6.18.2
 - 使用的框架和版本：（如太极6.3.0）LSPosed 5175
 - 其他：（如哪部番、哪个专栏等）

**日志**
无日志会被直接关闭
点击文本框下面小长条可以上传文件
log地址
https://del.dog/pelogrosux

刚刷完机，没装什么东西
疑似最新commit所致

**Comment by yujincheng08** [comment]
试试上个版本的 ci 呢

**Comment by BoBppy** [comment]
@yujincheng08 安装了9e30e6e496。正常打开模块设置页，未触发fc

**Comment by yujincheng08** [comment]
试试 a2d3d1c0a

**Comment by BoBppy** [comment]
@yujincheng08 正常

**Comment by yujincheng08** [comment]
@duzhaokun123 来背锅

**Comment by duzhaokun123** [comment]
发现问题由 minify 导致...

**Comment by yujincheng08** [comment]
@duzhaokun123 等你 pr 哦 😆

**Comment by yujincheng08** [comment]
Revert 了，应该好了

**Comment by duzhaokun123** [comment]
**环境信息**
 - 安卓版本：10
 - 系统版本：LineageOS 
 - 哔哩漫游版本：同此次CI
 - 哔哩哔哩版本和版本号：6.18.2
 - 使用的框架和版本：lsp 5175

尝试点击模块设置页，未引发fc

推测与 Android 版本有关，等我回去找个旧手机装 Android 11 再试

> 发现问题由 minify 导致...

应该不是，这只导致 Debug 构建出现错误

**Comment by duzhaokun123** [comment]
确认fc由本次提交修改德`SettingDialog.kt`导致

**Comment by duzhaokun123** [comment]
只在干净安装后会出现

**Comment by duzhaokun123** [comment]
@yujincheng08  问题找到了
https://github.com/yujincheng08/BiliRoaming/pull/96/files#diff-462affdd6ff87629b6aff2c8bc69f846db462f4e931d8f20549d444b3429bf25#60L
空指针

**Comment by yujincheng08** [comment]
❓
