### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chenqian3788** [yujincheng08/BiliRoaming#970]
### 问题描述

集成到一起的LSPatch版，能不能卑微请求大佬解决一下分享到微信时显示签名不一致的问题，另外叔叔家的客户端越来越卡顿，开启速度也越来越慢了。如有一个速度快一点的lite版推荐，不胜感激

### 复现步骤

其实并不影响使用

### 预期行为

感谢大佬开发辛苦了

### 实际行为

谢谢

### 安卓版本

10

### 哔哩漫游版本

1.62

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

6.74.0

### 使用的框架和版本

1.8.2

### 日志

如有回复，不胜感激涕零

**Comment by yujincheng08** [comment]
> 解决一下分享到微信时显示签名不一致的问题

这个只能嵌入 B 站突破重重防御然后偷取签名。
