### ISSUE TITLE
[Feature] 强开4k和杜比，增加更多倍速选项

### ISSUE THREAD

**Issue by razilong** [yujincheng08/BiliRoaming#973]
### 原因

让非大会员、非4k机型 能强开4k、1080P60帧，杜比音效

增加更多倍速选项，0.75x, 1.25x, 1.75x, 2.5x, 3x, 4x,

### 功能简述

.

### 功能逻辑

.

### 实现参考

更多倍速，Xposed模块
https://wwye.lanzouy.com/iVOfh0o5wdvg 密码1ntr
作者:酷安@dadaewq

**Comment by yujincheng08** [comment]
跟大会员有关的功能不会添加
