### ISSUE TITLE
[Bug] 最新版本无法保存评论笔记中的图片

### ISSUE THREAD

**Issue by kistin233** [yujincheng08/BiliRoaming#974]
### 问题描述

无法保存笔记中的图片

### 复现步骤

1.长按笔记中的图片

### 预期行为

保存图片

### 实际行为

未保存图片

### 截图或录屏

https://user-images.githubusercontent.com/63286728/223121976-dd958d67-eb58-44b3-97f5-23a40203ac47.mp4

### 安卓版本

13

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.18.0

### 使用的框架和版本

LSPosed1.18.2

### 日志

[log.txt](https://github.com/yujincheng08/BiliRoaming/files/10898596/log.txt)

**Comment by yujincheng08** [comment]
@zjns

**Comment by zjns** [comment]
前端的懂哥来修吧，我搞不定。

**Comment by yujincheng08** [comment]
ok，我有空看看。

**Comment by kistin233** [comment]
目前测试来看，在评论区中可以长按保存预览的图片，但是点击展开笔记就不能保存图片；
