### ISSUE TITLE
[Feature] 恢复旧版本中的按弹幕等级屏蔽弹幕

### ISSUE THREAD

**Issue by funnycups** [yujincheng08/BiliRoaming#981]
### 原因

新版本中，弹幕精选功能作用微乎其微，在弹幕很多的情况下，经常出现开了和没开一个样的现象。使用旧版本的1-10等级屏蔽可以很好地控制弹幕数量

### 功能简述

通过多个等级划分来过滤弹幕
目前已知在国际版3.8.0中仍然有原先的弹幕等级屏蔽功能

### 功能逻辑

与现在的弹幕精选类似，但可以选择更多的屏蔽等级。

**Comment by yujincheng08** [comment]
啊B把API砍掉就失效了。所以没计划实现。
