### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lsxuan12138** [yujincheng08/BiliRoaming#984]
### 问题描述

华为手机报毒：a.gray.PiggyGoldcoin

### 复现步骤

安装就报毒
测试集成LSpatch版本 最新版和前一个版本都报毒
<img width="846" alt="Snipaste_2023-03-16_10-05-32" src="https://user-images.githubusercontent.com/74349318/225491160-66a81d96-0643-48b6-aac8-ddc77e2f4874.png">
系统信息mate40pro 鸿蒙3的最新版本3.0.0.206（勉强算是安卓12？

### 预期行为

正常

### 实际行为

报毒
![Screenshot_20230316_100843](https://user-images.githubusercontent.com/74349318/225491513-a9a13731-d65f-427f-9d3a-bc5b95ad00c5.jpg)

### 安卓版本

12

### 哔哩漫游版本

1.6.10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.18.0

### 使用的框架和版本

使用集成LsPatch版本

### 其他

无

### 日志

无，

**Comment by yujincheng08** [comment]
那你自己打包。
