### ISSUE TITLE
[Feature] 希望支持评论时自动取消勾选 分享至动态 

### ISSUE THREAD

**Issue by limbia** [yujincheng08/BiliRoaming#996]
### 原因

很烦评论过的东西自动被放到动态 他那个按钮贼小 而且只要一用截图评论或传图评论都会自动勾选上分享到动态 我又懒得去那里一个个删或者每次想评论时老是去取消勾选 求大佬整一个^_^

### 功能简述

想要能自动取消勾选这个 能直接隐藏掉这个功能更好 不喜欢这个功能233

### 功能逻辑

在杂项里加上 评论时自动取消勾选分享至动态 和 评论时隐藏分享至动态 这两项设置就行emm..

### 实现参考

就俩开关吧emm

**Comment by zjns** [comment]
没想到这一块儿是用 Jetpack Compose 写的。
